### ISSUE TITLE
Make `app_name` translatable again

### ISSUE THREAD

**Issue by pejakm** [iNPUTmice/Conversations#1063]
This is a request to partially revert commit #821. Some languages are using Cyrillic script (like Serbian) so if an app name is not localized, translation is considered incomplete.

**Comment by SamWhited** [comment]
> translation is considered incomplete

Considered incomplete by what? Transifex, Android Studio, the linter?

**Comment by pejakm** [comment]
By people: users and translation community.

**Comment by plsng** [comment]
@pejakm has a point, although I think it would be best to just manually add a localised name if the language uses a different script.

**Comment by strb** [comment]
This is also a potential branding issue, so @iNPUTmice might want to have a single, unique, identifiable name for the app. But I don't know what the landscape looks like over there. Do other apps/service (Facebook, WhatsApp, Instagram, ...) localize themselves in that way?

**Comment by pejakm** [comment]
Facebook -> Фејсбук ("Fejsbuk" in Latin)
Firefox -> Фајерфокс ("Fajerfoks" in Latin)

but, for example, where a name is not a trademark, translators have free will to either translate or transliterate the name (based on what "sounds" best):

IceWeasel -> Ледоласица ("Ledolasica" in Latin, basically means "ice weasel")

"Conversations" is a convenient name, I translated it like "Конверзација" ("Konverzacija"), which is similar, sounds like and have exactly the same meaning as "conversations".

**Comment by pejakm** [comment]
Other examples (Android apps):

OpenKeychain -> Отворени кључарник (translated)
K-9 Mail -> К-9 Пошта (translated)
Cache Cleaner -> Чистач кеша (translated)
Flym -> Флим (transliterated)
Lightning -> Муња (translated)
Quick Lyric -> Квик лирик (transliterated)

**Comment by ElectronicWar** [comment]
I for my part hate it when Apps are translated into my native language (German), it's hard to find on the app store and sometimes just stupid. I do understand the need tho for languages with other scripts for easier input/search.

**Comment by Lesik** [comment]
In the case of German, I'd definitely prefer "Conversations" over "Konversationen" or "Gespräche", but transcribing the latin name into cyrillic does make sense for cyrillic languages.

**Comment by pejakm** [comment]
Any news regarding this?

**Comment by licaon-kter** [comment]
> I for my part hate it when Apps are translated into my native language (German), it's hard to find on the app store and sometimes just stupid. I do understand the need tho for languages with other scripts for easier input/search.

I agree with this.
