### ISSUE TITLE
Feature request: Share location via PEP/PubSub

### ISSUE THREAD

**Issue by ivucica** [iNPUTmice/Conversations#1069]
When I saw the [new plugin for sharing location](https://github.com/siacs/ShareLocationPlugin), I found it useful and a nice way to contribute to the project. I also found the reasoning "main app should request minimum permissions" very reassuring. Thank you!

[XEP-0080](http://xmpp.org/extensions/xep-0080.html) defines a way to publish user's location with PEP and PubSub. It would be nice to be able to share my current location (being able to specify a certain granularity, of course). 

My familiarity with [0163 - PEP](http://xmpp.org/extensions/xep-0163.html) and [0060 - PubSub](http://xmpp.org/extensions/xep-0060.html) is limited, but it seems like, in the interests of privacy, 0060 might be a better choice.

Why 0060? My specific use case is writing a bot that would fetch the location, and update the Conversations status remotely (meaning it depends on #1068) based on my location. So I'm actually interested primarily in sharing my very precise location with my bot -- and not quite so much with other users.

**Comment by TameOfGroans** [comment]
I, too, had hoped the plug-in would provide an option to update PEP [and interval]

For those not fond of G "free" services search f-droid for: nlp

**Comment by TameOfGroans** [comment]
I would love mobile UI for Privacy Lists!

**Comment by SamWhited** [comment]
> I would love mobile UI for Privacy Lists!

Conversations supports the [XEP-0191](https://xmpp.org/extensions/xep-0191.html) (Blocking Command) which is effectively a light weight sub-set of privacy lists. However, I fail to see what this has to do with PEP location sharing. Let's try to keep things on topic.

**Comment by TameOfGroans** [comment]
https://github.com/siacs/ShareLocationPlugin

**Comment by TameOfGroans** [comment]
^ oops. Ignore that

**Comment by miighty** [comment]
Has anyone progressed on this, I have just started my implementation

**Comment by Natureshadow** [comment]
@miighty, any news :)?

**Comment by mcepl** [comment]
> For those not fond of G "free" services search f-droid for: nlp

yes, but do these work with Conversations?

**Comment by phrokton** [comment]
> but do these work with Conversations?

@mcepl If conversations would show in the **Share** options for apps like [waze ](https://m.waze.com/)or [glympse](http://glympse.com/about).  That afaik is up to conversations.

(glympse does _not_ require any phone number inanity very unlike waze for sharing location [follow me, or meet up])

**Comment by dbielz** [comment]
Yeah, that's one thing I am looking for already quite a time. One implementation I already found in http://www.tigase.net/content/tigase-messenger-android , which works quite well with prosody as well. On status updates, my location is part of my status, and I can see it in the status in gajim on my desktop.
Unfortunately, Tigase on android apparently has stalled development now for 2-3 years (last version, that is), and, of course, I prefer Conversations much more. And, of course, having two or more Jabber clients on one device, well, ....  
So I really would love to see this functionality in Conversations somehow, maybe with some improvements:
Tigase for now only allows sharing location generally to all with one granularity, which you can set to: country / city / street / exact coordinates, or completely off. Here it would be very nice, to be able to say for example: 
- Certain Groups (e.g. "family" and "friends") and / or contacts can see my exact coordinates
- Other Groups ("collegues") and / or contacts  can see city where I am
- All registered buddies can see country
- Unknown people can't see my location at all.

All of that could be visible in the status of a contact (buddy), in form of a symbol if location status is available. Hitting this symbol could open a map, showing the current (resp. last submitted) location.
Alternatively, Conversations could have a special roaster (is that the right terminus?), showing a map with all location stats available in my buddy list, fitting to the zoomed area of the map.

I know, there are solutions for track sharing, track recording, (like Traccar, opentrack) etc., but all what I am looking for is the option to answer questions like "Is my buddy in the neighbourhood, so I'll ask him to go for a beer", or "Yes, I'm on my way, but here's a lot of traffic, so please stop asking every 5 minutes when I will be home", or "My kids are quite late; did they forgot the time at their friends, or are they already on their way home?", or "Where ary my holiday buddies around in this foreign region?" 
So all I want to be able to see and to tell, is the current status, whithout having to send it manually or to ask for it every time.

And, of course, last but not least, a "On/Off" switch without having to setup details every time again would be essentially :-)

Yeah, I know, "I have a dream ..."
But maybe someone else finds this usefull as well and knows how to make it.

**Comment by unicorntaco** [comment]
> Conversations supports the XEP-0191 (Blocking Command) which is effectively a light weight sub-set of privacy lists. However, I fail to see what this has to do with PEP location sharing

Perhaps the intersection is Conversations privacy settings [defaults] with a grouping management.

Could roster wield a simple binary grouping:  high trust, trust.  Or whatever label you please.  High trust receives all social/presence informatics, whereas trust receives a subset.

**Comment by unicorntaco** [comment]
> Certain Groups

Seems like an extension or application of Privacy Lists XEP ;)
