### ISSUE TITLE
Display address instead of map with position of other user

### ISSUE THREAD

**Issue by karlkarpfen** [iNPUTmice/Conversations#1144]
When one user submits its position to an other one, the recipient gets a button "Location". When this button is pressed, a map opens showing the current position of this user. This map has two major problems:
- downloading the tiles causes network traffic which is quite expensive in some countries
- detecting the position of the user is complicated, one have to check the (very small printed) street names close to the location

OpenStreetMap offers a service called "Nominatim" that returns the region/city/street for a given geoposition. It would be much better to (optionally) display just this address as text instead of showing this complicated to use map.

**Comment by jkufner** [comment]
If recipient use Osmand, he has map already downloaded, so there is no
cost of displaying the map. Also current street name is displayed in
titlebar, and it is easy to zoom in to get names of neighbour streets.

Simple sollution is to use better map application ;)

Automatic street name look up leaks private data to 3rd party web
service, which is not very nice.

**Comment by karlkarpfen** [comment]
2015-04-21 16:10 GMT+02:00 Josef Kufner <notifications@github.com>:

> If recipient use Osmand, he has map already downloaded, so there is no
> cost of displaying the map.


To be honest: the quality of OSMAND is quite poor, so I have doubts very
much people are using it.


> Automatic street name look up leaks private data to 3rd party web
> service, which is not very nice.
>

This can be an option, so only these people can enable this function that
do not suffer from this leak. On the other hand: the recipient is
retrieving the senders position data, so when NSA or other guys that
"protect" us, assign this position information to the recipient, they
assign the wrong position to the wrong person :-D
