### ISSUE TITLE
please enhance location feature

### ISSUE THREAD

**Issue by emdete** [iNPUTmice/Conversations#1205]
it would be cool if the location feature would be enhanced by
- showing the jid and name on the map as well
- allow "moving" positions of friend on the map

**Comment by emdete** [comment]
i am writing a map application and this is how it would look like:

![screenshot_2015-05-17-22-49-43](https://cloud.githubusercontent.com/assets/3251523/7672114/34ebbe6a-fce7-11e4-8e4f-14d81b571499.png)

**Comment by jkufner** [comment]
From Conversations point of view, this feature requires:

  - Let Conversations broadcast GPS position - to specified contact or MUC; explicit permission by user must be required; one-time send or continuous updates.
  - Gather positions from other users - a small local database. Optionally record GPX file with all known positions (one track per user, including local user). Map app will connect here.
  - Provide gathered data to other apps - explicit permission by user must be required per app.

I've seen some discussions on this topic recently, so explore existing issues.

**Comment by jkufner** [comment]
Also consider if your use-case could not be handled using [Osmand](http://osmand.net/) or some small extension for it.

**Comment by emdete** [comment]
no, all this is not required. the current design is to have a plugin. my app already implements the API for this plugin but the intent does neither contain the jid nor the real name. the "movement" of the position is a bit more complicated but also achievable. you just see the "share location" as a "start sharing" and add a "stop sharing location". either conversations polls the location from the plugin or the plugin sends the location continusly.
osmand has no de-centralized communication with my friends, how would that fit? 
my idea is even to have chatroom where you have all participant on a map, maybe even with their avatar moving around accordingly...

**Comment by jkufner** [comment]
Ah, it looks like that the plugin is already implemented... didn't notice that :)

> osmand has no de-centralized communication with my friends, how would that fit? 

Osmand as a map app, not for communication. Osmand is advanced, fully featured map & navigation open-source app. It is worth a look.

> my idea is even to have chatroom where you have all participant on a map, maybe even with their avatar moving around accordingly...

Yes, that matches my expectation.

**Comment by emdete** [comment]
yes, there is even an official conversation plugin which shows the location via google api. my app is just starting to implement it and there  may be more.

so why look at osmand if the same problem persists: the communication? i know osmand and use it alot but it's a different thing: it's a navigation app, not something where you want to watch tracks, pois and persons moving around you. it may be a candidate if you want to navigate to a  persion known in conversations but that is not my usecase. it must be implemented in osmand and the necesary part in conversations for that usecase is already there.

my intention is more outdoor sports where you need to know where people are around you when in the wilderness where navigation won't work anyway.

**Comment by jkufner** [comment]
Osmand is not navigation only - the navigation is just one feature of many. Actually, there is similar plugin to what you are doing, but it uses proprietary service - [Osmo plugin](http://osmand.net/help/osmo-plugin.html). It would be nice to have open-source alternative to that. I see an opportunity in combining Osmand's Osmo plugin with Conversation's ShareLocation plugin.

**Comment by emdete** [comment]
osmo is why i said "de-centralized" in the beginning. that's why i don't use this feature. track support in osmand is poor as well in my opinion. there may be many features in osmand which are near to unusable so for me it boils down to navigation.

(btw: the last update looks increadible good and i have to check about the features again)

**Comment by jkufner** [comment]
Yes, Osmo plugin's communication part is ugly, but that is the part you want to replace with Conversation's ShareLocation plugin. Everything else should be fine (or at least good enough for a start; I haven't seen its code tho).

**Comment by emdete** [comment]
no, i do not want to replace anything in osmand, i develop a different map app. ;) i ask for improvement of conversations to allow better usecases.

**Comment by jkufner** [comment]
I'm talking about forking and reusing relevant part of Osmand's Osmo plugin, and connecting it to Conversations (instead to proprietary service), so you don't have to write entire map app. But if you want to write it... ok :)

**Comment by emdete** [comment]
as i said: i already have. it's a fork of RMaps which seemed to be abandoned. you can see the screenshot... so forking osmand isn't my business but feel free...

**Comment by TameOfGroans** [comment]
I similar mature service is

http://glympse.com

I refer to this category as Social GPS  (as GNSS is not a term many would use. Both GPS and GLONASS are GNS Systems)

Glympse does not require the receiving party to have an app (or plugin)

**Comment by TameOfGroans** [comment]
@emdete 

Is the location available from PEP to contacts in my roster? 

Also please employ the 
Open Source Location API

https://github.com/microg/android_packages_apps_UnifiedNlp/issues/36#issuecomment-86744484

and not the proprietary Play Services Location API.

**Comment by emdete** [comment]
@TameOfGroans : i do not understand both of your points. 

the roaster is not part of the idea, and the PEP about the location is a nightmare (it doesn not allow encryption). i like Conversations aproach better here. the enhancement just asks for steady updates of my location to a friend i am chatting with.

which geo location provider is used in android is not the decision of an app but of the one installing (or deinstalling) apps on his device (and yes, i do NOT use any gapps on my phone and it works fine so far).

**Comment by miighty** [comment]
@Emdete are you sure there is no way the pep messages can be encrypted?

**Comment by phrokton** [comment]
@emdete @miighty Are not PEP entries stanzas?  Does not OTR/OMEMO encrypt stanzas?

**Comment by PanderMusubi** [comment]
What is the status related to https://bitbucket.org/SamWhited/opensharelocationplugin/src ?

**Comment by SamWhited** [comment]
> What is the status related to https://bitbucket.org/SamWhited/opensharelocationplugin/src ?

This is just a fun little thing I built; feel free to use it (or not); it still has only the data Conversations sends to it, so it's not likely to get either of the requested features soon.
