### ISSUE TITLE
Feature: Render locations as an image instead of a button

### ISSUE THREAD

**Issue by sesceu** [iNPUTmice/Conversations#1228]
I like the location sharing solution and I really like, the plugin solution, so that conversations doesn't need the right to access the location. But the "Show location" button that is shown when you send or receive a location is just ugly.

From what I understood by looking at the source, is that the message contains a geo-url, that is rendered as a button by conversations. Is that right?

I don't know if it is technically possible, but instead of rendering a button, couldn't we just request an image from the location sharing plugin (via a different intent?), and render this into the conversation view? An make this image clickable to open the plugin view, the same way as it opens now when you click the button?

**Comment by TameOfGroans** [comment]
generate screencapture? or save thumbnail view of map from plugin? 

would it be more aesthetic to allow the inline image to be zoomed or panned rather than spawning a new window?  (allowing for spawning by long click or double tap)

**Comment by jkufner** [comment]
The image could be 3x times bigger (one extra screen to each side), so
it can be scrolled a little, but still be a static image.

But much better sollution would be to embed real map view into
conversations. Google maps are used this way all the time so it must be
somehow possible. However, Osmand maps should be used instead of Google,
because Osmand is offline so it won't leak location anywhere.

**Comment by sesceu** [comment]
I don't really need it to be scrollable or anything. It would just need to be an image with a reasonable zoom. Whenever I wild life to zoom in closer or scroll, it would be fine for me to simply tab the image an have the location share plugin opened.

**Comment by jkufner** [comment]
Question is, what reasonable zoom is.

**Comment by sesceu** [comment]
How about the zoom level, that is selected by the sending user? Does the geo-url allow for defining a zoom level? If so, the sender could just transmit the zoom level. 

Another way could be, that the sender generates the image according to his zoom level and transmits that image together with the geo-url. 

Other than that, we could have an option in the settings which sets the default zoom level for all incoming messages. If in some cases the level does not fit, the user can always click the image to open the plug-in.

**Comment by SamWhited** [comment]
Zoom is simple enough to do (you can include it in the geo URI, or just pick a reasonable zoom level based on their locality). The problem with this is where image rendering is done. You either have to include a mapping library in Conversations, which means that that map may look different than the plugin (eg. if you're using my Mapnick/OSM plugin and Conversations uses Google Maps you'll see a Google Map and then click on it and see an OSM map, or visa versa which makes for a poor UX). You could send the image via file transfer, but that's slow and error prone, and a waste of time when you have all the information you need to generate one off the bat.

The most likely way I can see to do this is two fold: If you're the one sending a location, just return the bitmap you want in the bundle (this is easy enough to do). If you're the one receiving the location, however, you can't do this. Instead, you'd have to build a "map generation service" into the location plugin. Conversations could then send an intent to this plugin which would generate the map, and return the image. Doing this without a UI means that you'd have to run as a background service, create a view, load the images, and somehow obtain a bitmap representation of the view (rendering to an internal canvas and not to the screen buffer) to return. I'm not sure if Android provides API's for doing this sort of thing or not.

**Comment by bonsaithis** [comment]
I would prefer plugin use the open source location api and not the proprietary google api. 

without zoom or pan would sending a static bitmap with coordinates require changes on the recipient end?

**Comment by SamWhited** [comment]
> I would prefer plugin use the open source location api and not the proprietary google api.

I have made a similar plugin which uses Open Street Map data and Mapnick Maps (via the OSMDroid library). Feel free to [download it](https://github.com/SamWhited/OpenShareLocationPlugin/releases) and give it a whirl. It's also available from the Play Store. If you have questions about it you can contact me directly or flie an issue on its issue tracker (not here).

**Comment by iNPUTmice** [comment]
writing a service that creates bitmaps will be extremely complicated and not worth the effort. those bitmaps will be too large to send as a result intent so you would have to use pipes to transfer the image.

if this feature is something that is really desired the best solution is just to use the Google maps api. (Maybe as a seperate build for the playstore version)

Using OSM isn't a good alternative either because OSM will still leak your information to a third party.

**Comment by sesceu** [comment]
For the creation of the images in a service as part of the plugin, I have to check.

However, there is already the feature that if a link to an image is sent, this image is downloaded and displayed. I don't know how these images are returned to the conversation view once they are downloaded (can y, but couldn't we use the same mechanism here (providing we already know how to create these images)?

**Comment by licaon-kter** [comment]
@alexara it renders the map on the developer server....sa you give them your IP and your location...

**Comment by ildar** [comment]
But it doesn't mean it can't be rendered from the app.
True? want to reopen?

**Comment by licaon-kter** [comment]
@ildar I guess, sounds nice but a PR sounds nicer :)

**Comment by licaon-kter** [comment]
Blabber now allows server owners to host their own preview scripts 👍 
https://codeberg.org/kriztan/blabber.im/commit/8287e3e39e9aac7de28aebb00b93459057289f0b
