### ISSUE TITLE
accept file transfer automatically when connected via wifi

### ISSUE THREAD

**Issue by Sohalt** [iNPUTmice/Conversations#1311]
The current options only permits to enable automatic file transfers for files under a certain size. Since this feature predominantly serves to save data on mobile connections with volume limited plans I would suggest to expand the options with the ability to enable automatic file transfers when connected to a WiFi network since those are rarely volume capped.

**Comment by strb** [comment]
You might still not want to automatically accept/download 10GB transfers though...

**Comment by Sohalt** [comment]
Of course not. But WiFi and file size are not two exclusionary features to determine whether to download something automatically. A suggestion for an UI would be two separate (number) inputs, one for mobile and one for WiFi size limits.

**Comment by JensKorte** [comment]
I've got a feature request: The Acceptable attachments size should be different for mobile/paid connections and unpaid network connections. Licaon_Kter‎ wrote in the conversation chat: "yeah, this a nice thing that I keep postponing to borrow from Pix-Art :)" If the code is good enough there it could be copied.

**Comment by licaon-kter** [comment]
Yup, still want this...

**Comment by iNPUTmice** [comment]
In the interest of keeping Conversations (relatively) maintainable I think it's better not to introduce more settings at this point.
