### ISSUE TITLE
Sharing via HTTP upload should preserve original filename

### ISSUE THREAD

**Issue by jkufner** [iNPUTmice/Conversations#1494]
See https://github.com/processone/ejabberd-contrib/issues/128

When sharing a photo via http upload, a link like this is created:

```
https://example.com/upload/RANDOM-STUFF/ANOTHER-RANDOM-STUFF.jpg
```

So later, when file is downloaded, user ends up with file `ANOTHER-RANDOM-STUFF.jpg`. It would be much better if original filename is preserverd, so link would look like this:

```
https://example.com/upload/RANDOM-STUFF/original_name.jpg
```

Then downloaded file would be named `original_name.jpg`, which looks much better.

Is there a reason for throwing away the original filename and replacing it with random stuff?

**Comment by jkufner** [comment]
This happens only when sending photos, not when sending files. When file is sent, filename is preserved as expected.

I guess the random filename is generated because image is resized, but if this is the reason, it would be better to insert a note before extension of the file like this: `original_name.resized-RANDOM_STUFF.jpg`

**Comment by samweisgamdschie** [comment]
In this case an option to switch between resizing and sending original filesize would be nice.

**Comment by deoren** [comment]
@samweisgamdschie  +1, that would be great. As it is now I do my best to remember to send everything directly from within the Conversations UI as a File instead of an image. That way I can work around the image quality reduction that is the norm now.

**Comment by samweisgamdschie** [comment]
Ah perfect thx!
