### ISSUE TITLE
request: eta + transfer speed for file transfers

### ISSUE THREAD

**Issue by telegenesis** [iNPUTmice/Conversations#1505]
When sending a file, its filesize and the percentage file transfer is being shown.
However, adding some information like transfer speed or estimated time of the transfer would be neat.
What do you think?

**Comment by thundergreen** [comment]
I like this idea!

**Comment by srguglielmo** [comment]
This should probably only be displayed for files larger than X size. It would be almost useless to show this for tiny transfers.

**Comment by SafwatHalaby** [comment]
"Tiny" is subjective, it's relative to the internet connection speed. A better approach would be showing those extra details once the elapsed file transfer time exceeds some small predefined number of seconds.
