### ISSUE TITLE
[Feature Request] Better handling of history

### ISSUE THREAD

**Issue by axelsimon** [iNPUTmice/Conversations#1506]
Hi,
I see there are other similar isuses opened (#1473, #703), I hope this one won't be (too?) redundant with these.

When using Conversations for a while, quite a bit of useful information gets stored in the conversations we have with our contacts.

Unfortunately, it's currently hard or impossible to :
- scroll back in any useful way in the message history
  - here, at least at slider to fast-scroll the entire history, rather than having to endlessly swipe up and down the screen would be a very good start
- delete useless messages (OTR or gajim's E2E encryption error messages, duplicate messages)
- jump to a date (that's #703)
- export history (in plain text? in html?)

I submit these all to your consideration, I hope they can be implemented as I think they'd really make the experience of using Conversations even better.

In any case, thanks for a really nice XMPP app on Android (and I've used a lot ;)).

**Comment by bastlwasti** [comment]
the export to plain-text works

**Comment by monojp** [comment]
Hi, sorry for bumping this old issue, but I also thought that an export / import history feature would be nice. Or is technically not possible / insecure if using OMEMO?  This is currently not existing but directly possible via database I guess? Or what did you mean by export to plain-text works?

**Comment by iNPUTmice** [comment]
Under Settings / Expert Settings there is a button that exports all logs in plain text to the SD card. (You can't re-import that though. Just archive it on your PC or something)

If you want to switch devices or reinstall your current device please follow the the backup instructions in the readme.

**Comment by monojp** [comment]
I see, thank you very much for your fast response Daniel! And sorry that I oversaw that and bumped this old issue again.
