### ISSUE TITLE
XEP-0202: Entity Time

### ISSUE THREAD

**Issue by tbeitter** [iNPUTmice/Conversations#1538]
It would be nice if Conversations could use xep-0202 to publish an entity time other clients could work with. (And add it to Conversations If the contacts time differs from the own timezone and there is a nice way to embed this into the UI.)

**Comment by Natureshadow** [comment]
Yeah, that would work around the issue with German E-Plus customers being 40 minutes off several times a week :D!

**Comment by iNPUTmice** [comment]
Conversations responds to entity time requests since 1.13.6 or so. I'm still thinking about a good way to visualize this in the UI (and also avoid generating too much traffic by requesting it all the time)

**Comment by thundergreen** [comment]
@iNPUTmice it might be a good solution to request those times only on chatstate change.

**Comment by Echolon** [comment]
May refusing to make those request by a time limit would be helpful?
