### ISSUE TITLE
When several notifications, show the roster

### ISSUE THREAD

**Issue by moshpirit** [iNPUTmice/Conversations#1552]
_That's probably an intended behaviour and I couldn't find any issue about it (sorry if it's a duplicate)._

I see that when I get several notifications from several chats, Conversations open the last message instead of showing the roster and let me decide which message I'd like to see first.

This is important because maybe I don't want to see this last message now (e.g: it can be a reminder) but I want to see the other (a random message from another user that can be important).

**Comment by d9h02f** [comment]
I can agree with this, although eg on a tablet (or maybe in landscape mode on a phone as well, haven't checked), both the roster and the chat are shown at the same time, so if you would only want to show the roster, there would be a lot of empty space on the screen.

**Comment by moshpirit** [comment]
Well, for now it could be the exception. I mean: Conversations, in my opinion, should show the roster unless you're using a tablet or the landscape mode.
