### ISSUE TITLE
Stop outputing Jabber ID in logcat

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#1588]
A crash in another app will yield a Google Feedback dialog where you can attach a system log.
That system log ( taken as root by the Google Feedback agent? ) has everything in it ( like Wi-Fi SSIDs from around the device which are a privacy bomb on their own anyway ) and unfortunately Conversation outputs connection errors, ping and all in there by mentioning the account in full.

Either stop that all together or (for debugging) let the user give a different alias for accounts and not output Jabber ID directly.

/LE: All these `Log.d(Config.LOGTAG, account.getJid().toBareJid().toString() +` need to be redesigned.

**Comment by mimi89999** [comment]
JIDs could be logged like this: Instead of username@example.com --> u*******@e******.com (same number of '*' as of replaced chars...)

**Comment by licaon-kter** [comment]
I'd go with a fixed number of `*` just to make things *random* a bit.

**Comment by mimi89999** [comment]
@licaon-kter It is still useful for the person debugging to know to what contact is an issue related...

**Comment by mimi89999** [comment]
@iNPUTmice What do you think?

**Comment by gerg5c42g542g2c54g52c** [comment]
I'd replace each JID with a random string generated every time new JID, XMPP server or username is found in the log.

Fe. user@xmppserver would become c43hn78@32n4c8. That's even more useful to the dev, because u*******@e******.com is not unique.

Or use hashes.

**Comment by licaon-kter** [comment]
There need to be easily identified by the user, so s/he can provide if needed more info like server name and such, not sure how your idea can be implemented, the * method sound easier.

**Comment by gerg5c42g542g2c54g52c** [comment]
dukgo.com will still be a constant here, just a random string, same with username, so it would be clear if a specific server or account is making problems.

You just parse the log and replace every unique JID (or separately username and server) with stuff from /dev/urandom.

For hashes, you just hash the JIDs and they are constants too, just not random.

**Comment by licaon-kter** [comment]
Again not sure abut implementation, as this log is generated continuously during app usage.

**Comment by cijo7** [comment]
`Log.d(Config.LOGTAG, account.getJid().toBareJid().toString() )` could be made to `Log.d(Config.LOGTAG, account.getJid().hashCode() )`
I think we could get some unique number representing the Account.
But replacing it everywhere in Log seems tedious. Any other suggestions?

**Comment by daivat15** [comment]
@licaon-kter I think your idea of using * seems the most appropriate. That way the user will know which account the app is referring to and the log will still be discreet enough. We can also add a unique tag along with the JID so that the developers can identify the account easily.  What do you say?
