### ISSUE TITLE
Support for Remote Roster Management (XEP-0321)

### ISSUE THREAD

**Issue by mcepl** [iNPUTmice/Conversations#1627]
(This is related to #913 but I think it is even more urgent than that, because this makes life miserable even when the transport is configured via another client)

When using Facebook (and other) transports actual JID is usually something horrible (e.g., 59326548@domainoftransport.net). Most transport servers (e.g., [spectrum](http://spectrum.im)) support for this reason Remote Roster Management, so instead of plain JID they push to the client’s roster complete contact with alias filed with the actual human name of the friend. Without that I am getting in my roster through Conversations weird numerical-only JIDs.

**Comment by singpolyma** [comment]
If transport is configured by another client, and that client supports 0321, then shouldn't your roster have the names in it and thus conversations will see them?

**Comment by mcepl** [comment]
That's correct for already received contacts, but not for contacts acquired when only Conservations is running.
