### ISSUE TITLE
Timestamp for "has read up to this point"

### ISSUE THREAD

**Issue by darix** [iNPUTmice/Conversations#1639]
as the subject says ... this line lacks a timestamp and i find that information useful.

**Comment by lovetox** [comment]
i know, its problematic though from a privacy point of view.

if there is a timestamp delivered with that, users should be able to dont send this information. even the "has read up to this point" should be optional.

whatsapp was going through these motions already.

**Comment by darix** [comment]
you can already turn off sending those notifications

**Comment by lovetox** [comment]
ha, ok sorry didnt know that, ignore what i said :/

**Comment by singpolyma** [comment]
Yes.  Displaying the time we received that state would be useful

**Comment by tmolitor-stud-tu** [comment]
Indeed. +1

**Comment by darix** [comment]
That stale bot has no mercy.
