### ISSUE TITLE
XEP-0060: Publish-Subscribe

### ISSUE THREAD

**Issue by Trowic** [iNPUTmice/Conversations#1642]
Is it possible to add PubSub support to Conversations ?

It's a great way to receive news from the server (apps can publish updates to a node, can add a bot to publish rss updates, ...).

**Comment by singpolyma** [comment]
just receiving should already work if the message contains a body, I think

**Comment by Trowic** [comment]
How would you subscribe to a node?
I am mainly interested in receiving. Getting messages in a dummy conversation is really fine with me, if the body is printed in a bubble message.

**Comment by singpolyma** [comment]
@Trowic for now, could sub from another client, no?

**Comment by Trowic** [comment]
Oh ok. Thats what you meant by "just recieving". 
I did it and tried to publish a test message from a python bot but didn't get the notification.
Maybe i did not format the message correctly : 
```
Published item bc862ae6-f748-4984-98b0-4fce35d4500b to test:
<test xmlns="test"><body> Hello world !</body></test>
```
where can i find documentation with examples ?

**Comment by singpolyma** [comment]
Did you maybe subscribe to a full JID (instead of bare) with a different resource that Conversations is using?

**Comment by Trowic** [comment]
I susbscribe with Gajim to a node on my server. Is there other ways ? Better clients than gajim ?

**Comment by akrus** [comment]
+1

**Comment by ariep** [comment]
@singpolyma I tried this as well, and when a new item is published, I don't see any notification in Conversations. Another client (Gajim) pops up a window with the new item.
My subscription uses a bare jid (I checked by asking the list of subscribers from the server).

**Comment by KillyMXI** [comment]
XEP-0060 and XEP-0163 should allow to make use of movim.eu services (blogging).
That's really sad there is no other client so far (besides their own) supporting this features.
