### ISSUE TITLE
[MUC] reconnect is not working

### ISSUE THREAD

**Issue by sokai** [iNPUTmice/Conversations#1671]
Hi! – Today I investigated a little mystery (for me), that exists for a while …

**Mystery**
If I stay in a MUC/chat-room and the server (for the domain where the MUC is running) becomes n/a (for example becaus the sever restarts) I will never automatically reconnected to the MUC. I only have the option to leave the MUC.

**Expectations/Wish**
I wish that Conversations polls the MUC-server for (re-)availability (after the mostly very short off-time, caused by the restart).
_Or:_ Conversations gives me the option to retry to connect (instead only offering the leaving).

As far as I got the information from the Prosody help chat there are no specifications for MUCs in XMPP, where a standardised reconnect behaviour is defined. So the client has to poll the MUC server to get information about the (re-)availability of a MUC.

Thanks and best regards!

**Comment by sokai** [comment]
Thanks @iNPUTmice for making a first step (with commit a3e1141) for fixing this issue! :-)
But may it possible automatically retrying to connect to the muc instead of showing an error message? (I think it would be more comfortable...) *thx*

**Comment by vanitasvitae** [comment]
I encounter the exact same issue (I guess). Sometimes I wonder, why MUC messages appear on my desktop client, but not in conversations. If I reconnect to my account from "Manage Accounts", the messages do arrive. It would be nice if Conversations reconnects automatically. Sometimes even the status indicator is green when in fact the chat is not connected, which is really annoying.

**Comment by sokai** [comment]
@iNPUTmice: May there any updates to this _problem_? (I'm sry if I annoy you …!)

**Comment by stevenroose** [comment]
Seems like this could have a quite easy fix. I think simply doing an exponential backoff'ed retry for all disconnected MUCs would be sufficient..

**Comment by sokai** [comment]
Thanks @stevenroose!
I enabled the Prosody module "muc_ping" on my server but that doesn't solve my issue. – Has XEP-0410 become implemented in Conversations?

**Comment by contrapunctus-1** [comment]
Bump? This is causing issues for all fledgeling XMPP communities - users get disconnected, effectively getting silently dropped out of the chat. Non-geek users don't even know something has happened, let alone what or how to fix it.

**Comment by licaon-kter** [comment]
I keeep seeing these too (even made https://github.com/siacs/Conversations/issues/3397 to explain)

**Comment by sbrl** [comment]
I've got a device with a reconnect issue, and it's not limited to reconnecting to MUCs - its the main connection to the server.

1. Ensure conversations is connected & the persistent notification is active
2. Close conversations, and note that the notification shows that it's still connected
3. Switch from WiFi to mobile data or vice versa
4. See that conversations is now disconnected via the notification
5. Notice that conversations won't reconnect again until you open the app itself again

Would this be a new issue, or related to this one?

Ping @licaon-kter

**Comment by licaon-kter** [comment]
@sbrl Device? Android version? App source? Version 2.5.3? Battery optimizations ignored?

**Comment by iNPUTmice** [comment]
@sbrl this has nothing to do with the issue at hand. This issue is specifically about MUC. I encourage you to ask in the Conversations channel. This is most likely a device issue instead of a Conversations issue. (In that there is nothing Conversations could do about it.) Or you are just too impatient. After switching networks it might take a moment for the reconnect to happen.

As an update to this issue. This is nothing Conversations can fix on it's own. On the contrary this issue could even be solved completely on the server side which is what Prosody currently attempts to do (since 0.11). However e467fe341e6f10566a6aee42cc582573ce2d7cbb implements another approach (not the one the Prosody is doing) that might be a bit less resource consuming for the server but also requires server support which currently no server has.

**Comment by sbrl** [comment]
Ah, I see @iNPUTmice. Not sure what you mean by "the conversations channel". Is that a MUC?

@licaon-kter Ah, yes. I was in such a hurry to ask about the issue that I forgot essential details :P

The device isn't actually mine, but it belongs to a family member.

 - Battery optimisations are disabled for Conversations
 - Keep WiFi on during sleep is turned on
 - Device model: Samsung Galaxy J5 (2016) (SM-J510FN)
 - Android Version: 7.1.1

I guess I should open a new issue?

**Comment by licaon-kter** [comment]
@sbrl yes muc `xmpp:conversations@conference.siacs.eu?join`

Where is the app from? If F-Droid is expert settings->Foreground service on?

**Comment by sbrl** [comment]
@licaon-kter: Ah, I see. I can certainly join that chat when I get a moment.

It's the official paid-for version from the Google Play Store, and the persistent notification ("keep service in foreground") is enabled.

**Comment by licaon-kter** [comment]
I actually disconnect before a restart, then reconnect hours later. Else rooms get stuck and multiple swipe offs and rejoins don't help. :(

**Comment by mdosch** [comment]
I know you consider it a terrible hack but would you consider the already mentioned [XEP-0410](https://xmpp.org/extensions/xep-0410.html)?
If not, at least a visual hint in the chat list that a manual action (open the chat, press reconnect) is required would already help as sometimes I don't realize for days that conversations fell out of the MUC until I open it because I want to write something.

**Comment by contrapunctus-1** [comment]
I'm afraid this is still an issue affecting user experience in v2.10.2+fcr. MUC server restarts, Conversations doesn't know it's disconnected from the MUC, and shows no indication (avatars are visible, send button is green) that one needs to rejoin.

**Comment by mwild1** [comment]
I consider this to be a server-side issue. XEP-0410 is a hack that will patch over the real issue at the cost of bandwidth and battery life.

The fact that no implementation/XEP currently solves this server-side is unfortunate, but I think that's where the bug reports and pestering should be directed to.

**Comment by mwild1** [comment]
@licaon-kter it's not even clear that a XEP is needed. There are multiple possible server-side solutions - including the server simply pinging the MUC on the client's behalf. If a ping fails, the server can notify the client that they are no longer in the room via standard XEP-0045 methods. No protocol changes are needed for such a solution.

**Comment by licaon-kter** [comment]
@mwild1 Which solution does ~~Prosody~~Snikket use now?

**Comment by mdosch** [comment]
Prosody trunk can now detect broken s2s to MUCs with the module [ping_muc](https://modules.prosody.im/mod_ping_muc.html) which will send a [status change](https://xmpp.org/extensions/xep-0045.html#service-error-kick) to the client if it drops out of the MUC.
Would it be feasible for Conversations to react to those, e.g. by waiting for some time and automatically try to rejoin?

**Comment by Zash** [comment]
I started on [mod_ping_muc](https://modules.prosody.im/mod_ping_muc.html), a server-side [XEP-0410](https://xmpp.org/extensions/xep-0410.html) implementation. If/when a server-to-server link goes away, it sends a ping to see if you are still in the MUC. If not, it [sends a notice](https://xmpp.org/extensions/xep-0045.html#service-error-kick). Conversations shows this as a 'You have been kicked' if you go into the chat, but no notification. Better than silently dropping out and thinking you're still in the chat, but not perfect.

![image](https://user-images.githubusercontent.com/197474/147406131-2eeef2ce-f063-422e-a5c8-b76715a8b514.png)

**Comment by Menelmacar** [comment]
Isn't https://modules.prosody.im/mod_s2s_smacks_timeout.html and https://modules.prosody.im/mod_ping_muc.html enough on the sever side to inform the client, solving it on the server side? It seems conversations now knows when it is not connected any longer, it shows me an option to rejoin.
If it would just rejoin itself instead,  that would solve it for good for me I think, or am I missing something? I have no developer xep experience...
