### ISSUE TITLE
[Enhancement] auto download in anonymous rooms

### ISSUE THREAD

**Issue by thundergreen** [iNPUTmice/Conversations#1679]
It's boring in rooms like friends and family to longpress and download pics. I know it's for security reasons but it would be great anyway to have advanced meeting to activate automatic downloads in muc. This option of course would be off standardly and maybe with a security hint if turning it on

**Comment by thundergreen** [comment]
Meeting=settings

**Comment by d9h02f** [comment]
> It's boring in rooms like friends and family to longpress and download pics

But this is exactly the kind of group chats that aren't anonymous.

**Comment by thundergreen** [comment]
I would just like having the possibility to decide whether I wanna download
automatically or manually in every kind of mucs

Thorsten Fröhlich
Am 02.02.2016 20:38 schrieb "d9h02f" <notifications@github.com>:

**Comment by d9h02f** [comment]
But then you would have to provide an example of a case where this would be useful without compromising security. Giving users any kind of option to make their actions less secure is generally not a good thing.

**Comment by thundergreen** [comment]
One example is wa group chat via transport ... I can't see the pic right
away in these rooms and must download them each time manually

Thorsten Fröhlich
Am 02.02.2016 21:38 schrieb "d9h02f" <notifications@github.com>:
