### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by elcuco** [iNPUTmice/Conversations#1688]
As the app is translated to Arabic and Hebrew we need to add RTL support for all layouts.

Android studio has support for doing this automagially, and it does work (tested on Android 6, did not verify all UIs but it seems OK). I looked at the diff - and it seems the tool just replaces all "left" with "start" and "right" with "end". This works on Android 4.3 and above. 

Theoretically, android 4.2/4.1 does support this feature - but from my experience 4.2 ignores it and breake the UI, and some 4.1.2 Samsung's tablets completely fail while loading (see https://code.google.com/p/android/issues/detail?id=60055 - only workaround is doing this in code). 

I am unsure if we should keep the "left"/"right" paddings,margins for older Android support. I assume that Android studio does remove them in purpose.. does anyone have an older phone to test..?

**Comment by iNPUTmice** [comment]
I have no idea how RTL is supposed to look exactly. But I'm more than willing to merge a PR if it is tested carefully and works on Android 4.0+

**Comment by petmue** [comment]
@iNPUTmice RTL means Right-To-Left; Android natively supports layout mirroring when changing the system language: http://android-developers.blogspot.de/2013/03/native-rtl-support-in-android-42.html

**Comment by iNPUTmice** [comment]
Yeah I'm aware what it means and that it has support. But I don't know what
that works in detail. Meaning if you mirror the entire ui or just certain
elements. For example if the buttons in the conference details or account
details move to the left. Or just stiff like the timestamp in the overview.

**Comment by elcuco** [comment]
What is exactly the problem?

1) RLT UI layout is handled by Qt5, if your konversation is translated into 
your language.
2) Each individual line inside the ... "chat window" is RTL'ed, direction is 
detected by an internal algorithm.
3) Input line direction is again - detected by an internal algorithm.
4) We do not use QString::isRightToLeft(), since I felt that it will produce 
too much false positives - all IRC names start with LTR letter. Instead I 
count the numbers of RTL/LTR letters and then decide the best direction of the 
"paragraph"
5) GMail uses the same algorithm

Daniel, Thanks for bringing me, in.
