### ISSUE TITLE
XEP-0257

### ISSUE THREAD

**Issue by ghost** [iNPUTmice/Conversations#1694]
plz add support for
XEP-0257: Client Certificate Management for SASL EXTERNAL
https://xmpp.org/extensions/xep-0257.html

thx

**Comment by d9h02f** [comment]
> Status:	Deferred
> Last Updated:	2012-07-18

**Comment by Flowdalic** [comment]
@d9h02f So you are saying it should not be implemented because the XEP is deferred because no one implemented it? I detect a cycle.

**Comment by iNPUTmice** [comment]
I think the current approach of the XEP doesn’t bring any additional value to Conversations.
