### ISSUE TITLE
add MIX (XEP-0369)

### ISSUE THREAD

**Issue by suchatorg** [iNPUTmice/Conversations#1764]
add MIX (XEP-0369)

**Comment by thundergreen** [comment]
I thought Mix is not finished yet?

**Comment by suchatorg** [comment]
It is experimental, the MIX module will be included in the next version of ejabberd.

**Comment by thundergreen** [comment]
Hope so;)

Thorsten Fröhlich
Am 17.03.2016 11:14 schrieb "Carlos" <notifications@github.com>:

**Comment by petmue** [comment]
> add MIX (XEP-0369)

It might happen this summer: http://wiki.xmpp.org/web/Summer_of_Code_2016#Implement_client-side_MIX_in_Conversations :-)

**Comment by stevenroose** [comment]
Why is this closed?

**Comment by NoelChew** [comment]
any updates on this?

**Comment by devurandom** [comment]
Is anyone working on this? From their commit messages, I understand that [Swift](http://swift.im/) implements this already. So there would be a second client to test this with.

**Comment by selurvedu** [comment]
Bump

**Comment by iNPUTmice** [comment]
The fate of MIX is not decided on this issue. If MIX becomes a thing in the ecosystem I don’t need an issue to notify me of that. So I’m closing this issues are currently pointless as there is nothing actionable here.

**Comment by stevenroose** [comment]
I'd consider a tracking issue valuable as people can subscribe to the issue to follow progress. Isn't that a valuable aspect of feature request issues?
