### ISSUE TITLE
Messages recieved but not showing up in conversation view

### ISSUE THREAD

**Issue by Semperverus** [iNPUTmice/Conversations#1774]
I have several clients who are complaining about getting a notification in their drawer with the full text of the message, but when they click it to see the conversation, it doesn't show up in the conversation at all.

No OMEMO, no GPG, no OTR. I do have MAM enabled. I also haven't changed my configuration in quite some time.

An update to ejabberd seemed to "fix" it for a little while, but it has since begun reoccurring.

**Comment by adoa** [comment]
Now that I think about it, also in my issue #2145 , I sometimes noticed notifications from Conversations but no messages appearing. I am not sure whether this happened all the times.

**Comment by lemmatum** [comment]
I may have had this issue as well, or at least a similar one. I'll get the push notification with a snippet of the message, but then when I click on it and open conversations, the message is not there!

**Comment by licaon-kter** [comment]
Conversations version? Device? Android version? Server?

**Comment by lemmatum** [comment]
conversations version: 2.1.0
device: OnePlus One
Android version: 7.1.2
OS: LineageOS 14.1-20171225-NIGHTLY-bacon
server: ejabberd 18.03 running on freedombox (Debian testing - Buster)

As a note, this problem may be related to another issue I'm having, which is my contacts occasionally see my messages timestamped to a date before I sent them (like a few weeks to a month). And vice-versa for contacts that are using my server.
