### ISSUE TITLE
[Feature Request] Ability to edit profile

### ISSUE THREAD

**Issue by ezraimanuel** [iNPUTmice/Conversations#1779]
Would be nice if we can have ability to edit our own profile/details from account page. :)

**Comment by thundergreen** [comment]
+1

**Comment by benjaminbischoff** [comment]
Yes, it would be really great (and its requested from a few friends) to edit the own nickname within conversations. They do not want to install Gajim on Windows, just to change their nickname ....

**Comment by stevenroose** [comment]
At minimum a name field that is shown on first start and ideally in the change-avatar screen too.

**Comment by johnnybubonic** [comment]
this is still desired

**Comment by stevenroose** [comment]
I agree that it still is.
