### ISSUE TITLE
Colorized status indication on Send button not color-blind friendly

### ISSUE THREAD

**Issue by da2x** [iNPUTmice/Conversations#1806]
Colorized buttons don’t mean anything when you can’t easily tell the colors apart. Should also use different icons, text, or another way to communicate the same thing. The green, orange, red, black Send arrow could contain another smaller symbol inside communicate the statuses. For example, use another small Play-triangle inside the first for available, a circle for busy/away, and a square for offline. Not hyper intuitive but it’s a distinct difference between the states that can be seen by all users. Triangle, circle, squares have been used in other desktop chat applications to solved this exact problem.

**Comment by licaon-kter** [comment]
Aren't the colour-blind colour correction options available since Android 5 just for this?

**Comment by Mikaela** [comment]
Can reproduce setting the screen as grayscale.

* https://gogray.today/android

**Comment by iNPUTmice** [comment]
TBH I currently don’t see myself designing different buttons for all possible status and quick action combinations.
Plus I still consider status a non essential information.
