### ISSUE TITLE
No indicator of new messages in other conversations

### ISSUE THREAD

**Issue by da2x** [iNPUTmice/Conversations#1807]
1. Receive a message from Contact A and expand that conversation to read it
2. While you’re in that conversation, receive another message from Contact B

Problem: No notification of the new message without going back to the conversation list, but there is no prompt for going back. New messages received in other conversations while you’re immersed in another conversation need to provide a visual prompt in the UI telling users to go back to the conversations list to see their new messages.

Some ideas:
- Make the back button in the top left corner pulsate when there are new messages that have arrived since you opened the current conversation
- Display the number of new unread messages in other conversations instead of or next to the back button

**Comment by iNPUTmice** [comment]
That triggers a notification for me

**Comment by Aeyoun** [comment]
Leave your phone on the table with an expanded conversation for a second. Now look at me. Now look back at your phone. Did you miss that notification with a new message from Rebeca? There is no way to tell if you did miss it. [I’m on a horse.](https://www.youtube.com/watch?v=owGykVbfgUE&t=0m10s)

Anyway, I don’t always see the notifications when the app is in the foreground. (Not sure why?) I do get the sound, though but my phone bleeps and peeps 24/7 so it’s not easy to tell what sounds means what. Could just be that I look away when the notification arrive and don’t see it.

**Comment by tmolitor-stud-tu** [comment]
This seems to happen for me, too. Not always but sometimes.
In my opinion the idea of changing the back button (pulsate or display number of unread messages) is very good and helpful, even if notifications are correctly triggered.
