### ISSUE TITLE
the "offline dont show" option does not triggered correctly

### ISSUE THREAD

**Issue by vasisualiy** [iNPUTmice/Conversations#1858]
- **Conversations source: F-Droid

Sometimes I must to recheck the Option "offline dont show" to reach the contact, that I need. With other words, the offline contacts are not shown, and at the same time this options are unchecked.

**Comment by iNPUTmice** [comment]
Can you provide steps to reproduce?

**Comment by vasisualiy** [comment]
By me is it so, that when I start Conversationst the checkbox is already unchecked, doesn't mean if it was checked before. But there are shown only contacts, that are online. I need do check the option, and then unckeck it again to see offline contacts.
