### ISSUE TITLE
add an option to share contact from the attachment dropdown

### ISSUE THREAD

**Issue by pravi** [iNPUTmice/Conversations#1917]
#### General information
- **Version:** 1.13.0
- **Device:** Yu Yuphoria
- **Android Version:** Cyanogenmod
- **Server name:** poddery.com
- **Server software:** prosody 0.10 (if known)
- **Installed server modules:** all modules conversations checks
- **Conversations source:** F-Droid
#### Steps to reproduce
1. … start chatting with a contact
2. … click on attachment icon
#### Expected result

What is the expected output? 

Option to share a contact as vcard or text (like in Signal, Kontalk etc)

What do you see instead?

No option to choose a contact. So we have to go to contacts app and choose share and select conversations.
#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

```
adb logcat -s conversations
```

**Comment by therob84** [comment]
Although this feature is realle "Nice to have", one thing is even worse at the moment:
I did not found any possibility to "**copy and paste**" a contacts **jabber-ID** within Conversations for sending it manually to other contacts...

If I go to "contact details" it is not possible for me to select the jabber-ID.
...which of course would not be neccassary, if a real "send JID to contact XY" would exists....

**Comment by sedrubal** [comment]
I'd prefer the feater to send contacts from android address book as vcard. They include the JID when you link your conversation contacts to your android address book. Conversation could recognize when it receives a vcard and could offer to add the contact to the address book.

**Comment by stopANALytics** [comment]
> when you link your conversation contacts to your android address book.

which everyone ought do.  It makes the conversation of others from zero-presence costly sms texting to jabber texting easier
