### ISSUE TITLE
Missing notification about new message during client os down time

### ISSUE THREAD

**Issue by keynlotepan** [iNPUTmice/Conversations#1929]
#### General information
- **Version:** 1.13.2
- **Device:** Samsung S3
- **Android Version:** latest CM11
- **Server name:** conversations.im (both sides)
- **Server software:** conversations.im's today state
- **Installed server modules:** conversations.im's today state
- **Conversations source:** F-Droid
#### Steps to reproduce
1. Switch off mobile A
2. Send msg from mobile B to mobile A (both accounts on conversations.im)
3. Boot mobile A
#### Expected result

Message from B present AND notification in A's Android status bar
#### Actual result

Message from B present, no notification

**Comment by iNPUTmice** [comment]
Is the message marked as unread in Conversations?

**Comment by keynlotepan** [comment]
I tried to reproduce the error to see whether the message was marked as unread according to your question (I suppose you mean whether my client shows it in bold letters and you do not mean that sender is notified that message was read by me?).
But the error could not be reproduced. Maybe it is a race condition issue. My suspicion has the following reason: This time my WiFi router was turned on. And if WiFi is turned on, internet connection is established much earlier (before SIM unlock) as in the case when there is only a mobile data connection (after SIM unlock). When I initially wrote the bug I did not have WiFi available. I am going to try the  case with mobile only later.

**Comment by keynlotepan** [comment]
While using Conversations for some weeks I experienced cases when there was a notification and message was unread and other cases where message was listed as read and no notification. I will go on observing whether there are any patterns for the occurence of the error.
In my opinion this is no minor error because users who switch off their devices have to poll for new news manually on restart.

**Comment by keynlotepan** [comment]
Yesterday I experienced that two contacts wrote messages during os down time. While os was booting and obtaining wifi connection I heard Coversations' notification sound (before sim card pin entry). In Conversations' contact list only one user was shown bold indicating a new message. The other was not shown bold although there was a new message.

Version 1.15.2 from F-Droid on CM 11 Android 4.4.4 without Gapps on Samsung S3

**Comment by keynlotepan** [comment]
Yesterday this error occurred in a different situation (in which it can be reproduced simply). My phone was in airplane mode while my ocnversations.im account received a message. After switching back to standard mode there was a very short led flash and a very short vibration notification. But the new message was indicated as read and there was no textual notification message in the message bar.

Hope this helps to find the origin and this very annoying bug (which forces me to poll the messenger every morning and after every airplane mode usage) can be fixed.     

Version 1.17.0 from F-Droid on CM 11 Android 4.4.4 without Gapps on Samsung S3

**Comment by iNPUTmice** [comment]
Please provide the adb logcat for that.

**Comment by keynlotepan** [comment]
Today I tried to reproduce and to log the error. But It did not succeed. It seems to be fixed meanwhile in 1.19.4. I tried to catch it with reboots and with airplane mode, both methods failed. I used the same providers (sender and receiver) according to my observation of the bug in the past.

In my opinion the bug report can be closed.

**Comment by keynlotepan** [comment]
The day before yesterday it occurred again. I will go on trying to reproduce it manually applying logcat. 
Maybe it only occurs when other applications are sending notification during obtaining network access again. Maybe it is even an OS issue.

**Comment by keynlotepan** [comment]
- Issue also occurs on a friend's LG H815 G4 with stock Android 5.1 and an account on conversations.im
- Missing notifications can never be observed on my mentioned S3/CM11 from other notifying applications (K9, Signal, ...)
