### ISSUE TITLE
OMEMO communication when fingerprint verification is partially disabled

### ISSUE THREAD

**Issue by hermann-san** [iNPUTmice/Conversations#1955]
#### General information
- **Version:** 1.13.3
- **Device:**  Samsung S4
- **Android Version:**  SlimRom 4.4.4
- **Server name:**  conversations.im
- **Conversations source:**  F-Droid
#### Steps to reproduce
1. OMEMO configured between 2 devices
2. One device (device B) fingerprint verification has become disable for device A for some, unknown reason. 
3. Device A can still  send encrypted messages to device  B but device B can't send any messages anymore at all to device A .  OMEMO encryption is still enabled on both devices. 
   no error message shows up on device B (the one which can't send messages). The message written simply gets in the message history as if it was send to device A but it actually was not send.
#### Expected result
- device B should get an error message that the fingerprint is not verified for device A, hence no encrypted communication can take place. 
  In such a situation , at the moment one doesn't know that the message wasn't delivered to device A
- when device B  fingerprint verification has become disable for device A for some reason, then the OMEMO option should be grayed out in a conversation with device A . At the moment I can see OMEMO is possible from device A to device B (it's not grayed out) , but in practice it can't work.
#### Debug output

I can probably do this if it's really needed. I've not used adb so far. Pls. let me know.

**Comment by iNPUTmice** [comment]
> One device (device B) fingerprint verification has become disable for device A

what does this mean? Can you explain what you see on device B? Or provide a screenshot?

**Comment by hermann-san** [comment]
I made some blue arrows and text below.

![Image of Yaktocat](http://imagizer.imageshack.com/img921/5995/yAGtPx.png)

**Comment by iNPUTmice** [comment]
Is devices A fingerprint disabled (grayed out) or untrusted (slider left but not grayed out)?

And does device B have other fingerprints for that contact that aren't untrusted?

**Comment by hermann-san** [comment]
hm, I don't have device A here to check, but If I remember correctly it was trusted. I haven't changed anything on device a with regards to the fingerprint. So it must have been trusted because after I put dev A on dev B in a trusted state, communication was possible right away. 

dev B has has 2 fingerprints for dev A ( one was trusted , the other one disabled).

Ahhh, now I think I got it. Last week I replaced an older device with Dev A  and I have probably not explicitly verified the new device. 
OK, but then on dev B, when I send the first message to dev A, there should have been a window asking me whether I want to trust the new dev A or not. This did not happen automatically. 
I can verify this behaviour later in the evening today to see if it is reproducible.

**Comment by microwavesafe** [comment]
I'm suffering a similar problem. I recently changed my phone, my my old phone broke. This obviously created a new fingerprint.
When one of my previous contacts sent me a message using OMEMO it showed as sent on his device, but I never received it. This obviously caused confusion for both parties. Am I right in think my contacts device should have prompted him to accept the new fingerprint?

**Comment by iNPUTmice** [comment]
> This obviously caused confusion for both parties. Am I right in think my contacts device should have prompted him to accept the new fingerprint?

yes. However the default is not to trust the new device. So if your contact just ignored the prompt and hit 'OK' instead it doesn't trust the new device.

You can partially circumvent that by selecting 'clear devices' on your new device. This will invalidate the old device and forcing your contact to make a decision about the new device as then the choice is between trusting the device and not sending the message at all.

**Comment by hermann-san** [comment]
I just tried it again with Titanium. On the receivers  end (say device B) I restored Conversations with Titanium on a different device. The contacts, fingerprints and data where also restored. OMEMO was automatically set as the default encryption method (as it was on the old receivers device). I (device A) did send a message to dev B and the message went into my message history but was never received on dev B. The same happend on dev B when a message was send to dev A. There was no indication that something went wrong and messages where not delivered and no prompt to trust the new device either (neither on dev A nor on dev B).  Only when I changed to unencrypted messages, then it work again.
I don't know if you can reproduce this scenario, but if yes, it would be nice if Conversations could better handle such situations and give both users at least a warning message that there is something wrong with device trusts. 
I know that it's logical that if I restore Conversations  (app and data) on a different device then I also have to setup the trusts again, but if you restore  many apps on a different device then one may forget this kind of thing easily.

**Comment by buddabrod** [comment]
I encountered roughly the same yesterday.

I backed up my system using TWRP, played around with roms a little bit and restored the backup. Ever since neither my contacts nor I receive any omemo messages. Removing other devices and untrusting does not help. The messages are not shown and no error message appears.

**Comment by buddabrod** [comment]
I forgot to add that I use conversations 1.14.3 on CM13.

**Comment by hermann-san** [comment]
@buddabrod  this sounds like a different issue to me because you're restoring Conversations to the same device and that shouldn't be a problem. 
I've restored it to a different device which has a different device-ID. Thats why it needs fingerprint verification again.
I dunno why restoring to the same device didn't work for you. To my unterstanding it should work.

**Comment by therob84** [comment]
I stumbled over tha same problem with Conversations 1.21.0 and LineagOS14.1 (coming from Android 5.1) and using TitaniumBackup to restore App & data.
Any solution? As I have root, It would also bepossible to change/delete/empty any files in the filesystem - if I had been known which one.
Seems similar/duplicate to issue #2038

**Comment by licaon-kter** [comment]
As the readme says, 'adb backup' works. 

With root in theory it should work, but be careful to restore permissions and owner (app id no).

**Comment by therob84** [comment]
_for the record:_ only AFTER having this problem, I read the comment in the [ReadMe of Conversations](https://github.com/siacs/Conversations), clearly stating: 
>  **"How do I backup / move Conversations to a new device?"** 
> "[...] It is important that you **deactivate** your account before backup and activate it only after a successful restore, otherwise OMEMO might not work afterwards. Also, remember that you can only transfer the backup to either the same version of Android or to a newer one "

But still I find it is quite hard for users to need to take account for this, and if not - running in the problem OMEMO will not work anymore. Only solution in this case is - and was also for me - to "Regenerate the OMEMO Identity" which I had to to (fiinally with success). All contacts have to re-trust the new OMEMO key, what is not nice, but OK.

**Comment by licaon-kter** [comment]
Advanced users that have root should at least read the readme. :)

**Comment by therob84** [comment]
@licaon-kter: in theory yes. But do you really read ALL ReadMes of ALL Apps you have installed before doing an OS ugrade (Also of using it for years now)? I guess it would be about 20 for my case, which I think is not much, but already takes much time.... I tried to just trust the programmers of apps and backup apps to catch this error...but obviously I is not possible for all caes, I see...
