### ISSUE TITLE
Different notification sound for each contact

### ISSUE THREAD

**Issue by akanouras** [iNPUTmice/Conversations#2002]
- **Version:** 1.13.9
- **Conversations source:** F-Droid

Hello,
it would be nice if I could set a different or no sound per contact. I'm receiving notifications from a Network Monitoring System via XMPP, and it would be very convenient to be able to distinguish them from normal messages without looking at the phone's screen.

Thank you for your work!

**Comment by krushmp** [comment]
If not via conversations then "more something" to allow Light Flow Pro to manage it for us.  The more would need be answered by Andrew, the developer.

**Comment by daivat15** [comment]
I think it is also appropriate if we add options for custom notification lights and vibration patterns. The vibration patterns are supported from API 26 onwards according to my knowledge.

**Comment by SoyaLeaf** [comment]
@daivat15  
Hi, I think most devices do not work with API 26，maybe we can discuss this issue later. :)

**Comment by daivat15** [comment]
@SoyaLeaf The notification lights feature can be implemented. It is appropriate for earlier API versions too.
Regarding the vibration patterns, I just thought it is best if the app stayed upto date with the newest APIs. :)

**Comment by TntDestroyer** [comment]
Could conversations read a particular extended field for the contact (from android's contact provider)?  A literal pointer to an indexed notification sound?

there are two ways the sound is referenced,  i learned in a discussion about _LightFlow_, the app above suggested to manage this.  

An index number assigned to the sound whicg can change as new soundfiles are added and indexed

Or a filepath

Happy Friday the 13th

I have licensed LightFlow on ALL my devices.  It is that awesome.

**Comment by TntDestroyer** [comment]
i have also donated play store price for each install of conversations from fdroid

**Comment by ramack** [comment]
I was about to create a feature request but stumbled over this one here.

I'd propose to use different Notification Channels for the contacts, then the notifications would be easily customizable. Maybe it can be an option to configure at the contact whether a dedicated channel shall be used or even use the same notification channel for a "group" of contacts.

This seems to be quite similar to #2549 and  #2148.

**Comment by Dartan** [comment]
I was also going to make a request for this. Every other messaging app I use offers this and I would love to have this ability in Conversations as well.

**Comment by luke-jr** [comment]
Do the thumbs-down reactions to stalebot count?

**Comment by zelleb** [comment]
Any news on this one? That would be a really cool feature!

**Comment by tve** [comment]
I would really appreciate this feature. Dunno what closing this issue means. No time to implement? Not a desirable feature? Will not be added even if there's a PR?

**Comment by licaon-kter** [comment]
blabber.im (former Pix-Art) has this now...hard to backport?
