### ISSUE TITLE
Feature request: Bookmark messages

### ISSUE THREAD

**Issue by Lykos153** [iNPUTmice/Conversations#2033]
Another request inspired from somewhere else: I would be glad to be able to store specific messages without having to screenshot them. WhatsApp allows you to 'star' a message so it can be quickly found again. It's very useful if someone sends you a piece of information like an address or thelike or if you just want to remember a well said sentence.

I'm afraid this can only be done locally. I don't know enough of XMPP yet, so I can only guess that _XEP-0049: Private XML Storage_ or _XEP-0223: Persistent Storage of Private Data_ via PubSub could help to make it available on multiple devices.

I can imagine this sort of feature in a way that only one Stanza is stored somewhere but I tend to prefer a pointer to a specific time. Combined with MAM this would allow to precisely scroll back to a specific point of the conversation.

**Comment by Natureshadow** [comment]
Somehow, this seems to be an addition to MAM and MAM should probably support adding tags or something to entries in the future, or a new XEP that allows linking of private XML data to MAM entries.

**Comment by jkufner** [comment]
Many Jabber clients have this feature. I'm not sure how exactly it is implemented (and can't check it now), but it certainly uses some server-side storage. If I remember correctly, Tkabber, Gajim(?) and Psi can place bookmarks into chats. So the best way is to take a look how they do it and do the same.

23. září 2016 15:10:19 CEST, Dominik George <notifications@github.com> napsal:

**Comment by Lykos153** [comment]
I couldn't find the feature in neither Gajim nor Psi. Tkabber has it, but only locally. Of course, this is better than nothing, however having it synced across devices would be very nice.

**Comment by d9h02f** [comment]
Isn't this precisely what you use a note taking application for?

**Comment by knoy** [comment]
I think applying this to server-side storage is going to be really messy. Probably the best way is to just have this all done within Conversations locally that way there is no extra protocol or XEP required.

**Comment by aslmx** [comment]
+1  👍 really would appreciate this feature! Any chance this will be implemented soon?
