### ISSUE TITLE
Only partial history shown when offline

### ISSUE THREAD

**Issue by bastlwasti** [iNPUTmice/Conversations#2044]
#### General information
- **Version:** eg 1.14.1
- **Device:** Wiko Highway
- **Android Version:** Android 4.4
- **Server name:** self hosted
- **Server software:** prosody 0.10 (if known)
- **Installed server modules:** Stream Managment, CSI, MAM
- **Conversations source:**  F-Droid
#### Steps to reproduce

If I go in airplane mode, or anything else that I don't have any network connection.
But want to read a conversation with a friend.
#### Expected result

When I scroll up the history, I can only scroll the recent history, but not the full history
I
It seems to me that the history is in the database, but due to offline mode, it rejects to show me my chat history :-(

**Comment by licaon-kter** [comment]
So, being online:
* you can scroll up several days
* then scroll down to the current day

Then you switch to airplane and you can't scroll up anymore?

**Comment by bastlwasti** [comment]
exactly, licaon-kter!

**Comment by bastlwasti** [comment]
no, the data is always there.... but is not shown , probably because it things it needs to go online to check if there is more, even though everything there.
