### ISSUE TITLE
Change some wordings of Conversations' GUI

### ISSUE THREAD

**Issue by STPKITT** [iNPUTmice/Conversations#2052]
#### General information
- **Version:** 1.14.4
- **Device:** Samsung Galaxy S III mini
- **Android Version:** Android 5.1.1 Cyanogenmod
- **Server name:** jabber.at

To me some wordings could be improved to make things clearer for the end user (I tested this with my 56 year old mother).
I' using the German version of Conversations so I give the German words:
When setting up a newly installed Conversations there is the wording "Konto erstellen", but as that does, at least currently, only offer to create a new account on conversations.im I propose to change "Konto erstellen" to "Konto erstellen auf dem conversations.im-Server".

In Conversations' settings there is the option "Dateien annehmen". Better would be "Dateien automatisch annehmen".

Then there is the option "Bilder komprimieren" and one of the values is "Automatisch". This should somehow be explained to clear up what that value exactly does. I saw that question also coming up in conversations@conference.siacs.eu at least once.

When trying to register a new account on any XMPP-server, that doesn't support creating a new account via a client, the message to the user will be "Der Server unterstützt keine Rrgistrierung". It would be much better to give a clearer message for users who lack experience with XMPP/Jabber. My proposal is to show "Der Server unterstützt keine Registrierung aus einem Client heraus. Besuchen Sie die Website des Servers, um ein Konto zu erstellen." and if technically possible to also show the direct link to the servers' registration page, so it would look like this:
"Der Server unterstützt keine Registrierung aus einem Client heraus. Besuchen Sie die Website des Servers (https://jabber.at/account/register/), um ein Konto zu erstellen.".

**Comment by licaon-kter** [comment]
Go to https://www.transifex.com/projects/p/conversations/

Login with GitHub, join the team, fix it! :)

/close this

**Comment by iNPUTmice** [comment]
> Login with GitHub, join the team, fix it! :)

those strings shouldn't just be changed in one translation though.
I'm going to think about it and if I decide to change them I'm going to change them in the original first.

**Comment by licaon-kter** [comment]
Since this in german you might know better how to edit it, in my translations I kinda adapt strings to better explain stuff rather than just plain (only) translate them.

**Comment by iNPUTmice** [comment]
@licaon-kter I don't think this issue is about unclear wording but about completely different meaning of some strings. (Although I admit that the title is misleading but when you read the suggested changes it becomes clear that it is different)

**Comment by STPKITT** [comment]
The first two is just about adding a word or two.
The latter two would need additional work, but it's clearly not about completely different meaning.
I did wordings multiple times for other software before (German and English) and would like to do this. As I'm subscribed to this issue I'll wait until iNPUTmice gives me the green light.

**Comment by erwin68** [comment]
At first startup present 2 options: "Jabber-Konto erstellen" "Vorhandenes Jabber-Konto benutzen"

If server doesn't support In-Band registration: "Der Server $server unterstützt keine Kontoerstellung per Jabber.  Versuchen Sie das Konto über die Webseite des Anbieters zu erstellen."

Großartiges Projekt. Danke.

**Comment by STPKITT** [comment]
Any news on this? Especially the change from "Dateien annehmen" to "Dateien automatisch annehmen" would bes a big gain in UX and fast to implement.

**Comment by licaon-kter** [comment]
Did you follow my advice in my first comment? It easier to fix it than to re/post here.

**Comment by STPKITT** [comment]
I did not, because iNPUTmice wasn't giving the green light in his first comment.

**Comment by contrapunctus-1** [comment]
I strongly agree with STPKITT. I have seen _way_ too many cases of people accidentally creating conversations.im accounts simply because "Create account" is colored more strongly and is clearer - sounds like less work - than "Use my own provider".
