### ISSUE TITLE
Change colors for individual contacts

### ISSUE THREAD

**Issue by slizzered** [iNPUTmice/Conversations#2065]
Currently, texts received from all contacts have the same color (green/gray).
For users with auto-generated first-letter avatars, the message could be the same as the avatar color.
This makes messages in conference chats much easier to distinguish.

Furthermore, it would be nice to have custom colors for each contact.
Signal does this by provding a small set of fixed colors, which is good enough.
Through custom colors, it is also possible to recreate the current color scheme if desired.

**Comment by knoy** [comment]
I was having a similar idea to this recently about the chat bubbles and avatar colour. I was thinking users with custom avatars could have colours automatically generated based on the color palette of the image (or just have a random colour picked)

**Comment by Jazcafe** [comment]
Maybe use the colour/picture from your phone book avatar (where there is a match) or just manually select a colour for each contact,

**Comment by gwasher** [comment]
Is not this functionality provider by roster _groups_?

**Comment by stopANALytics** [comment]
An expert mode allows you to see contact grouping.

**Comment by immanuelfodor** [comment]
Not that the current green doesn't work well but it's also an option to set alternative colors for contacts or the whole app in other messaging services and apps. It would be great to have predefined/custom colors available to customize the experience in Conversations, too.
