### ISSUE TITLE
OMEMO verification method: Question & Answer (SMP)

### ISSUE THREAD

**Issue by knoy** [iNPUTmice/Conversations#2097]
Similar to https://github.com/siacs/Conversations/issues/2084 , OMEMO should at least be able to support what OTR is capable of doing. One of OTR's major selling points has been in it's ease in verifying keys, especially with Socialist Millionaire Protocol. An OMEMO-SMP implementation should be added to OMEMO to help verify contacts who are geographically separated and don't have a pre-arranged alternative method of contact.

**Comment by knoy** [comment]
The one major objection I can see to this would be that SMP has to be synchronous. But I don't see this as a huge obstacle, if the contact is offline SMP shouldn't allowed. Seeing as most people are online when you're talking to them and especially when you're starting a conversation, this should still be pretty effective in practice

**Comment by bleedingcrow** [comment]
@iNPUTmice
