### ISSUE TITLE
Feature request: Display in notifications (No name or message)

### ISSUE THREAD

**Issue by th3m** [iNPUTmice/Conversations#2103]
An option to hide the name and message from the notifications would be great for privacy.

* **Version:** 1.14.8
* **Conversations source:**  F-Droid

**Comment by vestpucci** [comment]
expanding:

filter notifications to alert differently for contact or content.

**Comment by gwasher** [comment]
> filter notifications to alert differently for contact or content. 

Light Flow Pro [app] allows for this on android 5+.  As I still use 4.4.4 I would greatly appreciate this.
