### ISSUE TITLE
Background picture for chats

### ISSUE THREAD

**Issue by rugk** [iNPUTmice/Conversations#2110]
It would be nice if one could set a background picture for all chats (or even better: for individual chats - in addition to a global background picture).

This would allow the customisation of the whole application making it more personal/individual for the user.

**Comment by MontyJam** [comment]
This seems needlessly distracting.

**Comment by tmolitor-stud-tu** [comment]
well, but it would be cool as this is a feature people know already from whatsapp and havin such a feature too would possibly attract some more people to use xmpp and conversations rather than whatsapp...

but that's definitely some very low priority task...

**Comment by alexara** [comment]
I actually would welcome it as customizing is fun and I and probably many others don't like the boring white or black background.
@MontyJam  rethorical question: Did you set an individual desktop wallpaper or would it distract you? ;-)

Maby this task could be one for GSOC!

**Comment by harshitbansal05** [comment]
I would try to work on this issue..

**Comment by rugk** [comment]
This issue has manually been given 6 upvotes, because of user wishes. I will continue commenting here if further bots annoy me. Thank you for nothing, bot.

This issue is relevant. #badbot :no_bell::robot::no_bell:

**Comment by iNPUTmice** [comment]
I’m counting this as feature creep and not as something Conversations needs right now.

**Comment by licaon-kter** [comment]
Really? Feature creep? https://www.theverge.com/2020/12/1/21754853/whatsapp-custom-chat-wallpapers-sticker-search

We could have won... :(((
