### ISSUE TITLE
Feature request: Telegram-like stickers

### ISSUE THREAD

**Issue by Piruzzolo** [iNPUTmice/Conversations#2122]
It would be cool to have stickers and sticker packs as in Telegram. Its [source ](https://github.com/DrKLO/Telegram/tree/master/TMessagesProj/src/main/java/org/telegram/ui/Components) for it may help.

And of course, thank you guys, keep up the good XMPP!

**Comment by jkufner** [comment]
"Stickers" are not supported by any other client, so it makes no sense to support them :)

**Comment by BlauerHunger** [comment]
It might be helpful to consider stickers as images from libraries. Maybe a someone could draft a XEP which defines a standard to discover these sticker-libraries (like ACI MetaDiscovery), so that they can be embedded as easily selectable and importable to XMPP clients and if the receiver's client doesn't support stickers, they can be sent as a link to the library.

**Comment by tonghuix** [comment]
How about convert a sticker to exist emoji if that client does not support sticker?

But some old-style PC client (without plugin) or command line client (like irssi or mcabber) does not support emoji either, so sad...

**Comment by Hund** [comment]
Why not use Telegram if you want "stickers"?

I've been using Jabber for a long time now, and the thing I like about it and its clients, besides being open source and decentralized, is that it's all about communication via text - good old plain text. There's no bullshit like stickers, audio or emojis.

I really don't get it way most people today feel they need stickers and what not? It doesn't add anything of value to the conversation.

Well, sorry for the rant. I guess I'm getting old and grumpy. ;)

**Comment by Piruzzolo** [comment]
IMHO such features are needed for a client to spread: security should be taken for granted - and it definitely is with Conversations - with little or no effort from the user. But usability is also important. If Conversations was a 100-lines of code, IRC-style plain text client, it wouldn't be so great at all. Stickers are just an extra you could use or not, of course, but I find them to be within the minimum a modern (nerdy) client should give

**Comment by BlauerHunger** [comment]
Especially students like those fancy features. Many people said to me "Hey, take a look at Telegram! You're going to love these stickers!" or things like this about other messengers. This means: If Conversations is meant to be used by young people, it needs to support some of these fancy stuff to show young people who don't mind about security or openness: Conversations is better!

**Comment by andypl** [comment]
There is a XEP for that :)
http://xmpp.org/extensions/xep-0231.html

**Comment by edhelas** [comment]
Movim actually implement the XEP-0231 to exchange stickers. The main issue here is that the "picture" will have to be transfered in a XHTML-IM body, something that Conversations doesn't support. In Movim XHTML-IM has been disabled with the exception of images tag with cid links (that are used for Stickers).

/my2cents

**Comment by Sirove** [comment]
As a non-techie who doesn't understand the technical details I'd like to know if stickers will be implemented in the future? My friends and I really loved them in Telegram, so it's very disappointing Conversations doesn't have them.

**Comment by conrad-heimbold** [comment]
@Sirove : as you can see from the long list of issues (currently more than 200 ) , there are more urgent issues to solve. So for the near future: I'm sorry, probably no.

**Comment by mimi89999** [comment]
Zom (an XMPP client) supports stickers.

**Comment by gjedeer** [comment]
Why not just use the file transfer capabilities Converstaions already has?

**Comment by BlauerHunger** [comment]
@gjedeer When transferring stickers as images you generate unnecessary traffic. Stickers can be cached or preloaded because they won't change once they are added to a pack.

**Comment by gjedeer** [comment]
@blauerhunger then it's going to be hard to make it work across clients. I don't think you can get developers of Xabber or Psi, who are known for preferring lightweight solutions, to ship a sticker pack. And if you standarize the stickers they will get boring quickly.

So I guess a centralized solution like giphy is the only one that would save transfer. Or mod_stickers for Prosody, lol.

**Comment by jkufner** [comment]
We already have standardized stickers. They are called emoji. What about simple `<big>`😂`</big>` ?

**Comment by d9h02f** [comment]
Zom has stickers, by the way: https://github.com/zom/Zom-Android

If you can wait just a little bit longer, it will have OMEMO, and then you can start suggesting it to any sticker lovers you want to convert to XMPP.

**Comment by uchchishta** [comment]
@d9h02f I want to use Conversations, not Zom; I want stickers too. What's a modern IM client that does not have stickers. 
Even an app like Slack [has](https://slack.com/apps/A0HS6S0BG-imoji) its [share](https://slack.com/apps/A0V1S12HJ-stickzilla)


AFAIK the new [XEP-0385](https://xmpp.org/extensions/xep-0385.html) can be used for sticker caching :)

**Comment by Hund** [comment]
Slack is just another stupidly bloated application, and I wouldn't be surprised if it could make your toast for breakfast as well.

I'm trying my hardest here, but I can't put words on how stupid this is without offending anyone. :) If you really care for stickers that much, you should just switch to the "modern" Slack.

**Comment by uchchishta** [comment]
@Hund why are you using Android or Conversations anyway. Stick with _your_ shitty Console™ Client.
If you call extensions/addons bloated, you may very well stop using XMPP or any apps like browsers.

**Comment by Hund** [comment]
My apologies if I offended you. But stickers is still stupid no matter how much butter you put on it. :)

**Comment by uchchishta** [comment]
░░░░░▄▄▄▀▀▀▀▀▀▀▀▀▄▄▄░░░░░░░░░
░░░▄▀░░░░░░░░░░░░░░░▀▀▄▄░░░░░ 
░░▄▀░░░░░░░░░░░░░░░░░░░░▀▄░░░ 
░▄▀░░░░░░░░░░░░░░░░░░░░░░░█░░ 
░█░░░░░░░░░░░░░░░░░░░░░░░░░█░ 
▐░░░░░░░░░░░░░░░░░░░░░░░░░░░█ 
█░░░░▀▀█▄▄▄░░░▄▌░░░░░░░░░░░░▐ 
▌░░░░░▌░██▀█▀▀░░░▄▄▄▄▄░░░░▌░▐ 
▌░░░░░▀▄▄▄▀░░░░░░▌░▀███▄▄▀░░▐ 
▌░░░░░░░░░░░░░░░░░▀▄▄▄▄▀░░░▄▌ 
▐░░░░▐▀░░░░░░░░░░░░░░░░░░░▄▀░ 
░█░░░▌░░▄▀▀▀▄▄▄░░░░░░░░░░▄▀░░ 
░░█░░▀░░░░▄▄▄▄░▀▀▌░░▌░░░█░░░░ 
░░░▀▄░░░░░░░░░▀░░░▄▀░░▄▀░░░░░ 
░░░░░▀▄▄▄░░░░░░░░░▄▄▀▀░░░░░░░ 
░░░░░░░░▐▀▀▀▀▀▀▀▀▀░░░░░░░░░░░ 
░░░░░░░░█░░░░░░░░░░░░░░░░░░░░ 
█▀▀█ █▀▀█ █▀▀ 　 █░░█ █▀▀█ █░░█ 
█▄▄█ █▄▄▀ █▀▀ 　 █▄▄█ █░░█ █░░█ 
▀░░▀ ▀░▀▀ ▀▀▀ 　 ▄▄▄█ ▀▀▀▀ ░▀▀▀ 
▒█░▄▀ ▀█▀ ▒█▀▀▄ ▒█▀▀▄ ▀█▀ ▒█▄░▒█ ▒█▀▀█ 
▒█▀▄░ ▒█░ ▒█░▒█ ▒█░▒█ ▒█░ ▒█▒█▒█ ▒█░▄▄ 
▒█░▒█ ▄█▄ ▒█▄▄▀ ▒█▄▄▀ ▄█▄ ▒█░░▀█ ▒█▄▄█ 
▒█▀▄▀█ ▒█▀▀▀ ▀█ 
▒█▒█▒█ ▒█▀▀▀ █▀ 
▒█░░▒█ ▒█▄▄▄ ▄░

**Comment by thundergreen** [comment]
I vote for stickers

**Comment by albjeremias** [comment]
pasting link to relevant information on how pidgin dealt with XEP 0231 

https://developer.pidgin.im/ticket/5627

**Comment by Mikaela** [comment]
In case this happens, please don't make stickers animated (like Riot.im did) and if you do, **please** add option to not autoplay or even disable autoplay for them.

Autoplay is accessibility issue and very distracting to some user groups and I am not able to read Riot properly when the room has moving sticker visible.
