### ISSUE TITLE
[Feature Request]: Allow for dedicated notification tone for a contact

### ISSUE THREAD

**Issue by OswaldBoelcke** [iNPUTmice/Conversations#2148]
#### General information

* **Version:** 1.14.9
* **Device:** Samsung GT-i9305
* **Android Version:** Resurrection Remix M v5.7.4 Sammy-version & Resurrection Remix® N v5.8.0
* **Server name:** jabber.de
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce
n/a

#### Expected result

Provision to assign dedicated notification tones to contacts to be used when a message/calls from this contact arrives instead of the standard notification.

#### Debug output

n/a

**Comment by mimi89999** [comment]
Version 1.18.2?

**Comment by noc-jfcbs** [comment]
Thanks for the hint! Typo. Version is 1.14.9

**Comment by singpolyma** [comment]
Also, for those of us who don't use sounds, a different vibrate pattern based on the contact. Very useful!

**Comment by singpolyma** [comment]
Dupe of #2002

**Comment by licaon-kter** [comment]
@iNPUTmice Do close this

**Comment by spaetz** [comment]
Specifically, the option to mute notifications for specific contacts would be terrific. I don't want a notification when my weather bot delivers the weather forecast,  but I want one when my wife sends an urgent shopping list :-)
