### ISSUE TITLE
Feature Request: Hide conversations of disabled accounts

### ISSUE THREAD

**Issue by ghost** [iNPUTmice/Conversations#2168]
Similar to "Hide offline contacts" toggle option, but in conversations list and with disabled accounts.

Useful for a user who has more than 1 account and many conversations. For example, one account for family and friends, another for work. On vacation, he disabled the work account and he wants to move between conversations easily, without having to delete the history of the work conversations.

Currently, the user can select easily between contacts in the contact list (given that the contacts associated with the disabled account aren't show). But it doesn't work with conversations with people not in roster. Besides, switching between conversations is faster than switching between contacts.

**Comment by iNPUTmice** [comment]
I actually like the functionality of going into the conversation of a disabled account and using the snackbar to enable it again.
