### ISSUE TITLE
UI: context menu on contact longpress in conversations view (to open contact details)

### ISSUE THREAD

**Issue by rigid** [iNPUTmice/Conversations#2180]
It would be awesome if the "Contact details" view could be opened from the Conversations overview (e.g. to block the contact).
Currently, one has to open a message or have the contact in the roster.

The background is that people "learned" from various iPhone/WhatsApp DoS attacks, to not open messages from unknown contacts (like spammers/attackers). In Conversations they fail to block the contact since they never open the message or add the contact.

While I find it arguable that not-opening is a good strategy or that blocking helps anything in such cases, I still think that a quicker way of getting contact details, would be a feature worth having.

* **Version:** 1.15.0
* **Device:** Galaxy S3
* **Android Version:** CM13
* **Server name:** self hosted
* **Server software:** ejabberd 16.08
* **Installed server modules:** come on
* **Conversations source:** f-droid

**Comment by licaon-kter** [comment]
For now you can go to Contacts and long press there.
