### ISSUE TITLE
[Feature Request] Standard proxy configurations

### ISSUE THREAD

**Issue by AnonX99** [iNPUTmice/Conversations#2190]
A standard configuration for HTTP & SOCKS proxy is something better to consider.
There are bunch of open-source libraries for both of them.
Even the Orbot app could simply run on another local address. Not going to mention I2P for Android or rather any other proxy servers.

**Comment by stopANALytics** [comment]
AFwall+
TorGuard (not tor)

allow only on vpn

:)
