### ISSUE TITLE
XEP-0374: OpenPGP for XMPP Instant Messaging

### ISSUE THREAD

**Issue by devurandom** [iNPUTmice/Conversations#2196]
[XEP-0374: OpenPGP for XMPP Instant Messaging](http://xmpp.org/extensions/xep-0374.html) is supposed to supersede [XEP-0027: Current Jabber OpenPGP Usage](http://xmpp.org/extensions/xep-0027.html), which appears to be currently used by Conversations (e.g. mentioned in #1584). This would bring compatibility with [Kontalk](https://kontalk.org/), if they indeed choose to use PGP for encryption (kontalk/androidclient#633), instead of  OMEMO (kontalk/specs#16).

**Comment by ArchangeGabriel** [comment]
You know, you can edit issue rather than deleting it…

**Comment by iNPUTmice** [comment]
Implementing this would not bring compatibility with Kontalk since Kontalk doesn't support this standard either.

**Comment by devurandom** [comment]
From kontalk/androidclient#633 and https://github.com/kontalk/specs/blob/master/encryption.md it seemed that they are already working on supporting it.

**Comment by stopANALytics** [comment]
@ArchangeGabriel perhaps you have not experienced github on certain mobile interweb apps;  There is no visible post edit ui element.

**Comment by ArchangeGabriel** [comment]
@stopANALytics Didn’t know about this. I only use the web UI from my desktop, so… By the way, I never found how to delete an issue, even in my own project with my own issues, so I guess this is a feature from some client allowing deletion but not edition, which just looks odd. But heh.

**Comment by devurandom** [comment]
#1698 is a yet incomplete implementation of this.

**Comment by physkets** [comment]
Will [XEP-0373](https://xmpp.org/extensions/xep-0373.html) also have to be implemented, or is that optional? - It defines discovery & retrieval of public keys, as well as synchronising keys across devices.

**Comment by devurandom** [comment]
@physkets : XEP-0374's abstract says "Specifies a OpenPGP for XMPP (XEP-0373) profile for the Instant Messaging (IM) use case." Chapter 1 starts with "This XMPP extension protocol specifies a profile of OpenPGP for XMPP (XEP-0373) for OpenPGP secured Instant Messaging (IM)." Chapter 2.2 says "This specification does not restrict the mechanism of key discovery and retrieval, but compliant clients MUST support the public key announcement as described in XEP-0373."
