### ISSUE TITLE
some messages in (MAM)-MUC are missing / lost

### ISSUE THREAD

**Issue by silberzwiebel** [iNPUTmice/Conversations#2197]
#### General information

* **Version:** 1.15.0
* **Device:** Motorola Defy+ & Samsung Galaxy Tab 2
* **Android Version:** Android 4.4 Cyanogenmod
* **Server name:** self hosted
* **Server software:** prosody 0.10 nightly
* **Installed server modules:** Stream Managment, CSI, MAM, ...
* **Conversations source:** F-Droid

#### Steps to reproduce

1. create a MUC, do not enable OMEMO
2. use Conversations and gajim for several days / weeks with two devices (phone and tablet)
3. (since I do not use mobile internet neither on the phone nor on the tablet, I turned the WIFI for several days on)
4. check back if you got new messages, especially in the MUC, every once in a while

#### Expected result

I'd expect to see the same messages on the phone and on the tablet as I see in gajim.
However, I noticed that on both the phone and the tablet some messages in the MUC were missing. Moreover, I got complaints from non-techy people using my server with the exact same issue and I think this bug is possibly related to #2145 and #2192. However, this issue is not about OMEMO which is not active in the MUC.

I do have the impression that this has something to do with the resumption of the stream and / or re-connecting. I had WIFI enabled all the time, but it automatically disables after a while to save power. 
My idea, how this might happen is:
If some messages in the MUC were not delivered, but newer messages were delivered (maybe because they are written "live" and delivered instantaneously), the older messages never appear again (maybe conversations does not check for older messages, if there are already newer messages received?)

#### Debug output

You will find a rather long logcat (covering days) from the phone (I do not have admin access on the tablet, so it's rather tedious to get the log there but I observed the bug on tablet too -- with different missing MUC messages) and the prosody debug logs ~[under this link]()~ for the next 30 days. (I did not censor names, domains or messages, this is why I do not want this to be longer accessible than necessary. Please, download the logs and tell me -- then I'll disable the access.)
I waited until some messages were not delivered and this happened on the morning of Dec 20.
There were 11 messages (two in the early morning, nine around 21/22 o'clock) on Dec 19 in the MUC [please-ask]@conference... and none of them appeared ever in Conversations on the phone (but all appeared on two separate instances of gaim running on two PCs which is why I suppose it is not a server issue).

Please, let me know, if I can provide any more information.

**Comment by srgcdev** [comment]
Same problem here.

**Comment by licaon-kter** [comment]
@srgcdev Do add your details: app version, app source, server, server modules, device, android version, etc.

**Comment by JackMauro** [comment]
Same problem here, using ejabber 16.09 as server.
As additional data, i can say my test result:
When **A** sends a message to a MUC, **B** is online ad receive it;
1) if **C** is **_online_**, he receives the message too, and the notification appears with sound.
2) if **C** is **_offline_**, he will download the message though MAM, and the notification will NOT appears and no sound will play.
3) if **C** has **_poor connection_** and the server is waiting for resumption of the stream, the message will be lost: Conversations will not receive the message and will not download it though MAM.

When A sends a direct message to C (no MUC), everything works as expected.

My tests were made using different phones and versions of conversations

**Comment by srgcdev** [comment]
In my case, the server is prosody 0.10 nightly, and it has happened always with different versions of conversations and mobiles (nexus 5x, xiaomi, motorola moto g...)

The thing is I think the problem is when there is poor connection and then they receive a message, mam doesn't load older messages.

**Comment by srgcdev** [comment]
I can reproduce the error:

1. **A** lose connection (plane mode on)
2. **B** sends a message in the MUC where **A** is a member and was online
3. **A** recovers the connection (planes mode off)
4. **B** send immediately a message in the MUC
5. **A** receives las message from B but not the previous message

Sometimes, the problem can be reproduced without step 4, but I don't know under what circumstances.

**Comment by mimi89999** [comment]
@srgcdev Only enabling the MAM_MUC module might not be enough. You might need to force logging to MAM in conferences.
Try setting this on the server:

`muc_log_by_default = true;`
`muc_log_all_rooms = true;`

Also, did you set the storage? https://prosody.im/doc/storage 
MAM_MUC needs something else than `internal` 
Try:
`storage = {     muc_log = "xmlarchive"; } `
SQL storage should also work for MAM_MUC.

**Comment by srgcdev** [comment]
@mimi89999 I have enabled muc_log:
{code}
modules_enabled = { "mam_muc"}
storage = { muc_log = "sql"; -- Requires 0.10 or later }
{code}
I can see that is enabled because I see it in the detail of the muc in Conversations.

**Comment by mimi89999** [comment]
@srgcdev 
> I can see that is enabled because I see it in the detail of the muc in Conversations.

AFAIK it means, that it is available and not enabled or disables...

**Comment by srgcdev** [comment]
The problem was that the module Stream management was not working since my last update of prosody. I updated the module and is working now. With sm I can't reproduce the error in the scenario described before but I know some times we missed message in muc's.
I'll keep trying to reproduce the error.

**Comment by srgcdev** [comment]
I can reproduce the error following these steps:

Server: ejabberd from conversations.im
Modules: MAM, MAM_MUC, Stream Management, CSI...
Conversations 1.15.3

1. **A** loses connection (switching off 4G connection)
2. **B** sends a message in the MUC with MAM where **A** is a member and was online
3. After 5 - 6 minutes, server close the session for **A** in server, and then **A** recovers the connection switching on 4G connection
4. **B** sends immediately a message in the MUC (while **A** was reconnecting)
5. **A** doesn't receive last message neither previous message

Can anyone reproduce the same scenario?

**Comment by srgcdev** [comment]
Since 15.4 I can't reproduce the problem describe above.

Thanks.

**Comment by silberzwiebel** [comment]
I payed attention to missing messages as described in my first post and had this problem once again some days ago: one message in a MUC was missing in Conversations but appeared on several other clients, 2x gajim, 2x dino and a different Conversations instance.
My Conversation is now at 1.17.0 and prosody nightly 0.10 up-to-date.

**Comment by rojoweko** [comment]
Any news on this issue? I experienced the loss of some messages, too, while others received them. We used Conversations version 1.18.x at that time. The server was Prosody 0.9 Stable (with MAM for MUC disabled). Unfortunately most of my contacts switched back to WhatsApp because of that... :-(

**Comment by silberzwiebel** [comment]
didn't had this issue since some months, always keeping server and client up-to-date. but I do not know if I'm only lucky or if the issue was fixed by accidence.

**Comment by mimi89999** [comment]
After https://prosody.im/issues/issue/903 got fixed, I don't have any issues with MAM and no messages get lost (or at least I am aware of it).

**Comment by rojoweko** [comment]
I still lose messages in MUCs with the current version of Conversations (1.19.5). The server doesn't offer MAM in MUCs though. Is this considered a different issue from your point of view?

**Comment by silberzwiebel** [comment]
I think this is another issue then. This one is (or was?) in particular
about MAM messages not being retrieved by Conversations while already
received by other clients.
