### ISSUE TITLE
Feature Request: option to remove avatar

### ISSUE THREAD

**Issue by eku** [iNPUTmice/Conversations#2235]
#### General information

* **Version:** eg 1.15.2
* **Device:** any
* **Conversations source:** F-Droid

There's  no way to remove/reset an avartar for an account to the default. Please implement such an option.

**Comment by conrad-heimbold** [comment]
As a workaround: Just upload a newer, empty picture.

**Comment by eku** [comment]
@conrad-heimbold this won't bring back the upercase letter.

**Comment by stopANALytics** [comment]
@eku upload a title case image in a font you prefer?

**Comment by iNPUTmice** [comment]
Currently not possible to implement due to the caching Conversations is doing.

**Comment by licaon-kter** [comment]
Fixed in https://github.com/iNPUTmice/Conversations/commit/e439c223ee07e8ee10394db601cad43320c000e9
