### ISSUE TITLE
Add support for DANE

### ISSUE THREAD

**Issue by Flowdalic** [iNPUTmice/Conversations#2247]
Depends on #2246. MiniDNS 0.2 includes a DaneVerifier. While the code in MiniDNS is well tested, this should possibly be marked as experimental feature which is disabled by default.

**Comment by github-k8n** [comment]
Any plans/timeline for verifying TLSA records (DANE)?
DNSSEC is already being used for verifying the hostname, so verifying and using the TLSA records to check the certificate should be feasible, right?

**Comment by github-k8n** [comment]
Any plans regarding this?
MiniDNS is on 0.3.3 and should support this, right?
So might it be possible to add a "DANE" checkbox that validates the certificate according to the usage field in the TLSA records?
