### ISSUE TITLE
Add quick response (acknowledge/reject) buttons

### ISSUE THREAD

**Issue by jplitza** [iNPUTmice/Conversations#2248]
I must admit, the idea is shamelessly learned from Threema by watching: I think tt would be great to simply acknowledge or reject something with one touch. When I get a message "Are you coming to the meeting?", "Will you join us for lunch?" or "Is Paul near you?", it's usually unnecessarily complicated to unlock my phone just to answer "yes" or "no", especially when something else has my attention.

In Threema, there are two buttons in the expanded notifications to simply acknowledge or decline a message. While it has integrated support for display these answers to the correspondent, in XMPP I basically see options for doing something similar: Propose an XEP that never gets implemented by many clients, or simply send some fixed messages for both of these buttons.

The precise fixed messages are yet to find. I'm thinking about fitting emojis, like 👍 and 👎 or ✔️️ and ❌, because words like "yes" and "no" might not always be fit as an answer and cannot be adapted to the language of the chat partner. But such a feature in general would be great!

(If it has potential to get merged, I might even try to implement it, though I'm no good with Java and Android.)

**Comment by andersruneson** [comment]
Maybe it could help to have a screenshot or two of how this looks in "Threema"?

**Comment by jplitza** [comment]
Here you go (sorry for the German language, hope that isn't a problem).

![notification](https://cloud.githubusercontent.com/assets/3628012/22164242/b62fd490-df56-11e6-919e-99fab8390b44.png)
![chat](https://cloud.githubusercontent.com/assets/3628012/22164241/b62def2c-df56-11e6-8196-4db51981fc58.png)

**Comment by gelft** [comment]
how would one tag an outgoing message as a vote request?

**Comment by jplitza** [comment]
You don't, all messages are assumed to be "votable" (or acknowledgeable). Basically, this is a form of "quick response". If the thumbs up/down doesn't make sense for a message, the receiver can simply not use the buttons.

**Comment by uchchishta** [comment]
So like imessage's quick reactions/tapbacks but on lockscreen
![tapbacks](https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=http%3A%2F%2Fmedia.idownloadblog.com%2Fwp-content%2Fuploads%2F2016%2F09%2FiMessage-Reactions-Demo.png&sp=8a42947582f15814b7b37ff083ae5a00)

**Comment by BlauerHunger** [comment]
I think a quick response feature would have more use cases, especially when users can define their own answers.

**Comment by griffindoors** [comment]
🔻👎
😦

Using my bigboy words:

No!   This is intellectually offensive.  Please do not implement this farce.

**Comment by fti7** [comment]
What about how its implemented in Signal?
There are 2 Buttons under the Notification
Read | Answer

Read = Sets the Message to the "read" state and removes the Notification
Answer = Opens a small Textbox to quickly Reponse (Via Text)

I really like that and miss it in Conversations.

**Comment by jplitza** [comment]
@fti7 Actually, exactly that is what I'm seeing with current Conversations on Android 7.

**Comment by fti7** [comment]
Oh gosh, i should update the app before asking such a question :-) Thx!

**Comment by licaon-kter** [comment]
On Android 5&6 use the QuickReply app ;)

**Comment by adnidor** [comment]
[XEP-0333: Chat Markers](https://xmpp.org/extensions/xep-0333.html) has support for acknowledgements, and is already supported by Conversations. 
It would probably take not that much to add support for the acknowledgement feature, rejecting is going to be harder since I don't see an XEP supporting it.
I'm not familiar with the processes of the XMPP foundation, maybe it is possible to amend XEP-0333 to include a "rejected " marker?

**Comment by adnidor** [comment]
@jplitza You are correct, I misunderstood the standard

**Comment by genofire** [comment]
Herefore exists a XEP in Draft: https://xmpp.org/extensions/inbox/reactions.html

Movim implemented it: https://github.com/movim/movim/commit/24e4d5d18b36940f853a2fc18f316cb3c83f12a4
(over multiple version, for a year)

**Comment by xundeenergie** [comment]
Oh yes!!!
Reactions would be great stuff!!!
