### ISSUE TITLE
Pin certificate and still use system CAs

### ISSUE THREAD

**Issue by mimi89999** [iNPUTmice/Conversations#2266]
**Pin XMPP certificate and still use system CAs for HTTPS (for HTTP upload files from other servers.)**

I am using my own XMPP server in Conversations. Because of that, I would prefer to manually verify my server's certificate than rely on system CAs.
I can check my server's certificate by choosing to distrust system CAs in Conversations advanced settings.
The problem is that if I choose that option, every time somebody on a different server will send my a HTTP upload file, I will be asked to confirm the server certificate. Since I can't really manually check the cert, I can:
1. Blindly trust it.
Or
2. Open the URL in a browser, see if the cert is trusted and compare it. (or directly download the file using the browser, but won't work for AES encrypted files...)

Option 1 is very bad and option 2 is time consuming.

I suggest to implement a way of pinning a server's certificate while still using CAs for other servers instead of the "distrust system CAs" option.

**Comment by moparisthebest** [comment]
What about just implementing HPKP?

https://tools.ietf.org/html/rfc7469

**Comment by SamWhited** [comment]
Please don't give this advice to people. HPKP is a good way to accidentally break your server. Most developers should not be doing this for personal machines unless they can afford a large build / testing / automation / alerting infrastructure.

**Comment by moparisthebest** [comment]
I meant implementing HPKP in Conversation's HTTP code.

But the dangers you speak of is what the Public-Key-Pins-Report-Only header is for, just because some otherwise smart developer *cough* broke their server with HPKP doesn't mean it's a problem. :)

**Comment by mimi89999** [comment]
How will just implementing HPKP solve that?

**Comment by moparisthebest** [comment]
You would set up HPKP on your server and then you could be confident when conversations connects to your server it would only ever be connecting to your server.  No more manually verifying certificate fingerprints that change often, and it's up to you when if ever you change the key.

**Comment by mimi89999** [comment]
But HPKP is a HTTP thing. We don't have that for XMPP.

**Comment by moparisthebest** [comment]
In the issue weren't you just talking about HTTP upload?  Yes HPKP would just be for that.

On another note I have seen an experimental XEP floating around that is not yet submitted that would do the same thing for XMPP, but that's further off down the road.

**Comment by mimi89999** [comment]
No, please re-read what I wrote and if it isn't clear, I will explain it.

**Comment by ArchangeGabriel** [comment]
DANE (+DNSSEC) is a superior solution, especially in this case. ;)

**Comment by moparisthebest** [comment]
> No, please re-read what I wrote and if it isn't clear, I will explain it.
You are saying you like to manually approve your XMPP server certificate and do not like doing this for random HTTP servers, HPKP would help you there.
> DANE (+DNSSEC) is a superior solution, especially in this case. ;)
100% agreed, for both XMPP and HTTP servers, HPKP would also be useful for HTTP servers on domains that don't support DNSSEC.

**Comment by mimi89999** [comment]
I am OK with CA checking random HTTPS servers but that's impossible.

**Comment by ArchangeGabriel** [comment]
@moparisthebest HPKP wouldn’t help because it would be required for *every* HTTP server used, which can’t be all of them. HPKP is not scalable, and thus dying, read https://blog.qualys.com/ssllabs/2016/09/06/is-http-public-key-pinning-dead for instance.

However, being able to pin it’s XMPP certificate but still rely on CA for everything else would work.

Using DANE too, because then only @mimi89999 would have to enable it on his XMPP server to benefit from this.

**Comment by mimi89999** [comment]
> However, being able to pin it’s XMPP certificate but still rely on CA for everything else would work.

That is exactly what I want and what thus issue is about.

**Comment by moparisthebest** [comment]
@ArchangeGabriel HPKP would only be enforced on the servers that chose to implement it, same as DANE, how is it different at all in that way?

**Comment by ArchangeGabriel** [comment]
@moparisthebest @mimi89999 doesn’t care about HTTPS servers. He is fine relying on CA for this. What he cares about is XMPP, for which HPKP can’t do anything.

**Comment by moparisthebest** [comment]
That's not what the title is, maybe it should be edited to say 'Pin XMPP server certificate but use system CAs for HTTPS servers' ?

And I'm not positive how conversations works right now, but it should not be pinning the *certificate*, it should be pinning the *public key*.
