### ISSUE TITLE
XEP-0301: In-Band Real Time Text

### ISSUE THREAD

**Issue by stopANALytics** [iNPUTmice/Conversations#2307]
Will this be possible in conversation's future?

**Comment by dholl** [comment]
This would be awesome.  I miss the old days of ytalk with cross-domain unix talk daemons, and the instant as-you-type conversations with friends...

**Comment by Echolon** [comment]
I think if I gets implemented, it should be opt-in and not a default!

**Comment by dholl** [comment]
Ooh... Existing code?!  👍
@iNPUTmice, Any idea about where #2492 stands?  (over a year ago)  May I/we lend a hand with it?  :)
