### ISSUE TITLE
Differentiate between sending Received- und Read-Confirmation

### ISSUE THREAD

**Issue by meisterlampe** [iNPUTmice/Conversations#2320]
Received-Confirmations are working very well for me. I can easily see, if my contact has received the message. 
However I don't want to share, if I have already read the messages, because that's a much more sensible information. Unfortunately I can only enable both -Received- and Read-Confirmations- at once.

If this two  confirmation-types aren't tied together in XMPP:
Would it be possible to split this option into two?

Thank you very much for this great app!

**Comment by griffindoors** [comment]
If you don't want read notifications stop reading messages

or wait for xep0016

**Comment by meisterlampe** [comment]
Using this argument, we could also remove the option to disable receive- and read-notifications at all. ;)

Prosody's website states, that support for xep-0016 is deprecated in favor of xep-0191 ([link](https://modules.prosody.im/mod_privacy_lists.html)). But generally it would be possible to block just the read-confirmations? 
However to my mind, not sending the data at all is better, than blocking it in later steps.

**Comment by salmonellad** [comment]
> If you don't want read notifications stop reading messages

llol true

> Prosody's website states, that support for xep-0016 is deprecated in favor of xep-0191

Pandering is never prudent 

> I don't want to share

That seems antirhetical to conversing
