### ISSUE TITLE
Add a splash screen carousel for displaying salient features

### ISSUE THREAD

**Issue by badarsh2** [iNPUTmice/Conversations#2340]
We can have a carousel before the login screen to show the essential features of the app. Probably a carousel containing 3 viewpager fragments, 

- One for saying that Conversations.im is the most popular XMPP Android Client
- One or two for mentioning essential features like ability to add encryptions, multidevice syncig etc

**Comment by philpsst** [comment]
Instead of xmpp: Jabber texting

**Comment by uchchishta** [comment]
Also TapTargetViews for feature discovery and interactive how-tos

**Comment by badarsh2** [comment]
@iNPUTmice What is your opinion on this? This is just a UI implementation, but still, can I make a preliminary approach?

**Comment by licaon-kter** [comment]
Pix-Art added some....
* 9 slides on first start
* 3 after add account
* 3 when joining a MUC
* 2 when chatting with a contact
* some more at random

...terrible :(
