### ISSUE TITLE
Improve loading more [messages UI]

### ISSUE THREAD

**Issue by atefhares** [iNPUTmice/Conversations#2346]
When loading more messages [old messages],  instead of showing a Toast telling the user that the data is being fetched, Don't you think that it is better to see a loading progress bar [circle one]?
the bar should appear when loading and disappear when done!

**Comment by rom1dep** [comment]
I'm not sure it's possible to use a progress bar there, because you don't know beforehand how many messages will be retrieved, so there is no unit of completion.

But I'm in favour of a loading animation instead of a toast.

**Comment by hareshkh** [comment]
This is a good suggestion. I want to work on this. @iNPUTmice, should I proceed with this?

**Comment by atefhares** [comment]
@hareshkh I am already working on that.

**Comment by tmolitor-stud-tu** [comment]
The toast disappears before the loading is finished and there is no indication that it is still loading.

A proper load indicator (circle etc.) that is removed once the download of the messages is finished would be better, indeed.
