### ISSUE TITLE
Secondary text in settings for theme,ringtone,accept files,etc. to be changed

### ISSUE THREAD

**Issue by pratikmjoshi** [iNPUTmice/Conversations#2361]
According to guidelines for making an effective settings page, the secondary text for fields such as theme, shouldn't show an explanation. Rather it should show the current selected choice. For example, in the ringtone settings,it would be better if the secondary text showed the selected ringtone, not "Play sound when a new message arrives". 

I would like to work on changing the secondary texts for these fields to show the value currently chosen. 

Reminder: This is only for the settings which are ListPreferences. CheckPreferences can remain the way they are.
Some examples are battery in settings(sec. text shows balanced, power saver,etc.), or location as shown below.
![image](https://cloud.githubusercontent.com/assets/19923446/23716448/5d5448ae-0456-11e7-8f9d-5aa8b60b179f.png)

**Comment by iNPUTmice** [comment]
Sure go ahead. Some settings might then need better wording in the title though if the information from the description is 'lost'.

**Comment by pratikmjoshi** [comment]
@iNPUTmice  I've finished the work on most of the fields, except XMPP Resource field and Grace Period field. I think they are a bit difficult to fit in the title, do you have any better wordings for their titles. Otherwise, they can be left as is
