### ISSUE TITLE
Feature request: tweak "stranger" definition

### ISSUE THREAD

**Issue by klement** [iNPUTmice/Conversations#2392]
Thanks a lot for the "Notifications from strangers" option. This really improved the usability.

I would like to be able to tweak the stranger definition from "not in roster" to "not in roster and different domain". This way, I would get notifications for messages from people in the same company (== same domain as account), who are not part of my roster. Adding thousands of people to my roster is not feasible in this case...

**Comment by wetubeyou** [comment]
Should be "not in roster". +1.
