### ISSUE TITLE
duplicate unread message notification for each thread

### ISSUE THREAD

**Issue by chaseadam** [iNPUTmice/Conversations#2450]
#### General information

* **Version:** 1.18.0
* **Device:** Google Nexus 5X
* **Android Version:** Android 7.1.2 Copperhead OS
* **Server name:** slack XMPP gateway
* **Server software:** ?
* **Installed server modules:** ?
* **Conversations source:** F-Droid

#### Steps to reproduce

1. receive message from one contact
2. receive message from different contact
3. bring conversations to foreground by tapping on app (not selecting notification)

#### Expected result

Each new message triggers a notification which other services can listen for (i.e. gadgetbridge).

Conversations appears to aggressively re-send android notifications for every unread message . I was unable to see any android notification system details in the output of "adb -d logcat -v time -s conversations"

My gadgetbridge log indicated that it received multiple repeat notifications from "eu.siacs.conversations" several of which were for repeat notifications.

Logs below show receiving 2 messages, but gadgetbridge receives 4 notifications in two pulses including the new message and the newest unread messages from a different unread thread.

[conversations.txt](https://github.com/siacs/Conversations/files/931653/conversations.txt)

````

**Comment by licaon-kter** [comment]
Not related to #1970 ?

**Comment by chaseadam** [comment]
It might be related based on some new behavior I am seeing. The thread in Conversations doesn't indicate another message was sent, but maybe #1970 is filtering it out, but still causes an android notification broadcast. Is there a way to turn up log verbosity?

**Comment by iNPUTmice** [comment]
It doesn't resend the notification it only updates them. It also doesn't set a notification sound or a vibration when these updates occur. gadgetbridge should probably able to figure this out and somehow deal with updates differently then with new notifications.
If they want me to set an extra flag or something I can probably arrange that. But in principle i don't see anything wrong with updating notifications when something changes.
