### ISSUE TITLE
Can not reply to messages in Android Auto

### ISSUE THREAD

**Issue by koejok** [iNPUTmice/Conversations#2457]
#### General information

* **Conversation Version:** 1.18.2
* **Device:** Huawei Mate 9, Honor 8
* **Android Version:** Android 7.0 Stock
* **Conversations source:** PlayStore

* **Android Auto Version:** 2.2.710804-release

I have tested this new feature and find this is a very useful thing. Thanks morgenroth!
Unfortunately, it is not possible for me to speak an answer. I receive new messages, and I can also press the pre-prepared posting "I'm driving", which is then also successfully sent.
After reading out the message, AA prompts me to press the microphone key to answer. After pressing the button and the prompt "Answer" says AA "Chat app not installed or needs an update."
I've tested this with two phones but the same behaviour.

As comparison Viber. (In Viber I couldn’t receive messages. This will not display in AA screen ;-) haha ) but I can write messages. After pressing the microphone button and give the command "send Message to" AA asks me which app I would like to use. SMS or viber. 
As a conclusion conversations isn’t listed or know to AA.

I have the same issue in native AA app in my car also in this standalone app.

**Comment by iNPUTmice** [comment]
Mentioning @morgenroth

**Comment by morgenroth** [comment]
I will dig into that. If there are more devices with that issue, it would be good to know what they have in common. So please add yourself if you have the same problem.

**Comment by morgenroth** [comment]
@koejok can you support me investigating and test again with AA developer mode enabled?

> On the mobile device, enable Android Auto developer mode by starting the Android Auto companion app and then tapping the Android Auto toolbar title 10 times. This step is only required the first time you run the companion app.

**Comment by morgenroth** [comment]
I have checked the Play Store version on another phone (Nexus 5) and Android Auto didn't even showed any notification.

@iNPUTmice Did you followed the publishing guide for Android Auto?
https://developer.android.com/distribute/best-practices/launch/distribute-auto.html

The most important part seams to be accepting the terms.
![image](https://cloud.githubusercontent.com/assets/454499/25553652/f54d6b06-2cb8-11e7-8308-923a3a58ead6.png)

**Comment by magoralczyk** [comment]
Since this issue is open for 2,5 years and I cannot get conversations to work within Android Auto: Is this feature only possible, if I am installing conversations through the google play store, or should this also work in the fdroid version? Is there anything else to do, to get this working? Telegram works out of the box...

**Comment by licaon-kter** [comment]
@magoralczyk Telegram from F-Droid or Google Play store?

**Comment by iNPUTmice** [comment]
> Since this issue is open for 2,5 years and I cannot get conversations to work within Android Auto: Is this feature only possible, if I am installing conversations through the google play store,

I know that the Android Auto app has a hidden setting to allow App from third parties ( = not Google Play.) Your car might either have a similar setting or rely on the Android Auto app setting (do you even need the app? Probably not?!)

Now that Conversations has backup import / export it doesn’t hurt to at least try with the Play version I reckon.
And do report back if it works; maybe I can add it to the FAQ in case it only works with Play.

**Comment by magoralczyk** [comment]
First of all: @iNPUTmice, you were right. You have to set the android auto phone app into developer mode. Therefore you have to open options and click a few times on the version info. A dialogue comes up and asks, if you want to switch to developer mode, so you have to confirm that. Then conversations messages will be indicated on the phone and in the car. 

I got messages fom different people and muc chats. The bubble shows the first few words, so android auto has to have the message text (at least these first words)  but in all cases I could't get it to read the message. Google assistant always responds after a few seconds with a variant of "sorry, something went wrong". This behavior is the same on the phone and  in the car. I think displaying the whole message is not a wanted function af Android Auto, so the assistant reading it seems to be the only option.
Telegram (from the play store) works like a charm, so I would try conversations from the play store (having not too much hope, that this will help), but before I do that, I have a question: How should I manage that without loosing my omemo chats?
My plan:
- upgrade f-droid version to current play store version.
- make a backup with the conversations backup function.
- deinstall fdroid version
- install play store version
- install backup

Will this work?
