### ISSUE TITLE
TCP socket not properly shut down after HTTP upload

### ISSUE THREAD

**Issue by ValdikSS** [iNPUTmice/Conversations#2469]
#### General information

* **Version:** 1.18.0
* **Device:** Blackberry Q10
* **Android Version:** Android 4.3 compatibility layer
* **Server name:** Self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** http_upload
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Watch for number of opened TCP sockets on the server side: ss -t | grep 5281 | wc -l
2. Upload any file via http_upload using Conversations
3. Watch for number of opened TCP sockets again

#### Expected result

Expected result: socket get closed after uploading file or after some short time.
Actual result: socket is in ESTABLISHED state and not closed.

-----

It seems that Conversations does not shutdown HTTP Upload TCP socket (send RST) after file uploading.

**Comment by iNPUTmice** [comment]
> It seems that Conversations does not shutdown HTTP Upload TCP socket (send RST) after file uploading.

Is this a bad thing? The Android / Java HTTP client will keep connections open to reuse them later.

**Comment by ValdikSS** [comment]
But they are not reused. New connection opens for every new file upload.

**Comment by iNPUTmice** [comment]
I'm unable to reproduce this by the way. Might be something with your Android stack.

**Comment by lieff** [comment]
It reproduced only with prosody server (which not closes connection too).

**Comment by iNPUTmice** [comment]
> And Conversations must download file, not upload.

That's true for download. I'm about to push a fix for that.

**Comment by Kemopan** [comment]
>2. Upload any file via http_upload using Conversations
I'd say download any file uploaded by http_upload using conversation. 

I've been able to reproduce that issue on Debian Stretch clean installation and prosody 0.9.12 and 0.10 from official prosody repo.
On 0.9.12 its possible to open endless numbers of established connections which becomes sort of DoS.
On 0.10 it seems that you can open 3 established connections max from single IP and then cannot upload or download files till these connections get dropped. (6 hours)
