### ISSUE TITLE
"Verify OMEMO keys" dialog not shown when adding a new contact

### ISSUE THREAD

**Issue by pgerber** [iNPUTmice/Conversations#2496]
#### General information

* **Version:** 1.18.5
* **Device:** N/A
* **Android Version:** N/A
* **Server name:** N/A
* **Server software:** N/A
* **Installed server modules:** N/A
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Click on a link containing a XMMP URI schema that contains OTR or OMEMO keys. The user MUST NOT be in your contact list.
    Example link: `xmpp:peter@example.com?omemo-sid-1319103411=3345DF536C7F147C2C9780B11C9F3CC95A860007354B6BBB5AFD4945A8954D2A;otr-fingerprint=C5107394FDDADB7D01D3BA4AAD2EF52774AC772D`
2. Click on Create in the Create Contact window.

#### Actual result

Keys are added to the newly created contact and considered verified. The user is not informed that keys have been added.

#### Expected result

When the contact is already in the contact list, a message is shown, saying: "You are about to verify the OMEMO keys of peter@example.com after clicking a link. …". This warning should be shown for new contacts too. (Btw, the message mentions OMEMO keys only even if indeed OTR keys are added.)

**Comment by pgerber** [comment]
Just realized that the verification dialog isn't shown when scanning QR codes, even if the contact is already in the contact list. It would probably be best to show a similar dialog in such a case. A user might scan the code from an unsafe source without realizing that it might contain keys.

**Comment by licaon-kter** [comment]
See the posts here too: https://github.com/siacs/Conversations/issues/2627#issuecomment-328351465
