### ISSUE TITLE
VIP contacts

### ISSUE THREAD

**Issue by jplitza** [iNPUTmice/Conversations#2549]
Since Android has the concept of a DND mode where text messages and calls are only accepted from VIP contacts, it would be great if Conversations did also offer this possibility. Ideally, it could use the very same VIP flag that Android uses, but a separate setting inside Conversations would do as well.

**Comment by WarrenBKN** [comment]
See also: Dynamic Tags

And it would be great to assign the group (tags) different LED color

since some newer unroot samsung phones don't play nicely with Light Flow PRO
https://play.google.com/store/apps/details?id=com.rageconsulting.android.lightflow

😬

**Comment by WarrenBKN** [comment]
https://github.com/siacs/Conversations/issues/2550
