### ISSUE TITLE
[feature] store contacts' (OMEMO) keys (incl. trust) globally, not per account

### ISSUE THREAD

**Issue by azrdev** [iNPUTmice/Conversations#2552]
As it seems, when I have multiple accounts using omemo, which all know some contact $Bob, his key will be stored independently for each of my accounts. This means I have to trust Bobs key once for each of my accounts, which is quite cumbersome (and multiplies if Bob is also using multiple accounts with me).

_I therefore suggest storing contact's OMEMO keys independently of local accounts._

-----

FTR, here the same request for gajim: <https://dev.gajim.org/gajim/gajim-plugins/issues/217>

In the conversations MUC I got these opinions:
~~~
A: the somewhat technical answer is that it makes the most sense from a complexity standpoint to do it this way, because we need to be able to for example remove them when the associated account is removed by the user
[…]
azrdev‎: A: and can you elaborate […]? i think you could still remove omemo keys of $bob when you don't have that contact any more in any of the rosters
A: it's really just a complexity thing. it's just all a bit more difficult to do correctly with "global" trust
‎A: basically nobody has cared enough to do it this way so far. and as always there are UX considerations when increasing the amount of "magic"
‎A: people get very confused when automatisms don't do exactly what they'd expect them to
‎A: so it's usually easier to just not automate things you don't have a good reason to
azrdev‎: A: generally agreed. however, do you really consider it automagic if keys of one of my buddies are trusted in the whole app after I verified them, instread of me having to verify them once for each of my accoutns?
‎‎azrdev‎: I don't
A: not necessarily, i'm more referring to subtleties in the removal use-case
‎A: disclaimer: i haven't really thought this through, mostly just shooting from the hip here
‎azrdev‎: re:removal -- true, true
‎A: it just feels like theres some danger of confusion somewhere in there
‎A: but to be completely honest, it's mostly this way because it's the most obvious/simple way to do things and the multi-account-single-contact use-case wasn't ever really considered
I: azrdev: like A using multiple accounts with the same contact is not supported and wont be in the near future 
I: So unless you plan on coding that yourself... 
azrdev‎: I: what do you mean with "supported"? it's simply a matter of adding contacts to the roster
I: Supported as in providing means to make it easier to use 
~~~

**Comment by knoy** [comment]
I think this is a great idea and increases security (having verified contacts) while improving user experience (having to verify a contact repeatedly). The interface for multiple accounts, especially multiple accounts with shared contacts is quite poor and this would be a good feature to encourage security-conscious power users.

I can't think of any possible security repercussions that could happen trust-wise as it's assumedly the same user behind the same accounts on a single phone.

**Comment by annafallasktick** [comment]
UUencode in contact notes field, or UTF  IM:CustomLabel 

OMEMO_1: UTF8 text 
OMEMO_N: UTF8 text 

Both ios and android have IM:Jabber

**Comment by selurvedu** [comment]
I'd like to see this feature implemented as well.

**Comment by iNPUTmice** [comment]
The community has been discussing ways of doing that. However this is not something actionable that Conversations could implement right now.
