### ISSUE TITLE
OMEMO fingerprint verification via XMPP URI does not work with multiple accounts

### ISSUE THREAD

**Issue by vanitasvitae** [iNPUTmice/Conversations#2586]
- ####

 General information

* **Version:** 1.19.5
* **Device:** Google Nexus 6p
* **Android Version:** CopperheadOS 7.1.2
* **Server name:** self hosted
* **Server software:** ejabberd 16.09
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Have multiple accounts (alice@a.org, alice@b.org) and add bob on both accounts as a contact (bob@c.org).
2. Click xmpp:uri of bob which contains his OMEMO fingerprints
3. Conversations presents a list with both bob enties. Select one of them (lets say the one with alice@a.org).

#### Expected result
The fingerprints should now appear verified in bobs contact overview.

#### Actual result
alice@a.org's conversation with bob opens, but fingerprints are still not verified.

Ideally conversations should not even ask me which contact I want to verify, since the fingerprints are the same for both entries. Instead conversations should just verify the fingerprints on both accounts.

**Comment by vanitasvitae** [comment]
@licaon-kter while this issue is related to that request, it is not about the same topic. #2552 wants to change conversations' behaviour, so that verifying keys becomes *easier*, while this issue is clearly about a bug in conversations.

**Comment by licaon-kter** [comment]
That issue and this one is about "supporting one contact on multiple accounts" and Conversations does not do that (for now). Did I understand wrong?

**Comment by vanitasvitae** [comment]
No, #2552 is requesting to store the OMEMO fingerprints of a contact on a per-contact basis instead of per account, so that you'd have to trust a contacts fingerprint only once instead of once per account. There is no buggy behaviour described in that issue.

This issue on the other hand describes a buggy behaviour (fingerprints are not verified when using multiple accounts). Apart from this bug, conversations deals well with multiple accounts :)

**Comment by d9h20f** [comment]
Still sounds like the same issue to me, fingerprints are not verified when using multiple accounts because they are tied to the account and not to the contact. What's different?

**Comment by vanitasvitae** [comment]
#2552 does not mention that fingerprints aren't verifying. I'm okay with closing this, when the fact that fingerprint verification is broken gets added to #2552, but I still think it is a completely different issue.

**Comment by Millesimus** [comment]
Bumping this, since I experienced the same today (4.5 years later).
