### ISSUE TITLE
Discussion: moving icons from titlebar to message bar

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#2598]
Just mock-ups:

![1](https://i.imgur.com/BLkbuK6.png)

![2](https://i.imgur.com/BKQbDW5.png)

Some notes:
* will free titlebar space so the whole MUC address can be shown
* moves the encryption pop-up behind a long press on send-arrow (the suggestion text could be modified to "Send unencrypted message (long press to encrypt)"

Another idea:
* leave the lock (when unlocked, aka unencrypted) in place BUT after enabling encryption move it to the burger menu (eg. How many times does one **change** encryption mode?).

**Comment by horazont** [comment]
> "Send unencrypted message (long press to encrypt)"

"long press to encrypt" will rarely be visible on phones whose font size is set to normal or larger.
