### ISSUE TITLE
Feature Request: Assignable names for OMEMO-fingerprints

### ISSUE THREAD

**Issue by STPKITT** [iNPUTmice/Conversations#2603]
When using multiple devices a user will have multiple OMEMO-fingerprints showing up under his account in Conversations. Without looking up every fingerprint on it's originating device/client-software the user can't tell which fingerprint listed under "Other devices" (assuming that's how it's called in English, in German it's "Andere Geräte") belongs to which device/client-software.
So my feature request is to make the user able to give every fingerprint listed under "Other devices" a name to be able to easily distinguish all the fingerprints.

**Comment by alexara** [comment]
https://github.com/siacs/Conversations/issues/1830

**Comment by ShallNotInfringe** [comment]
Amen

**Comment by ShallNotInfringe** [comment]
Amen to labels

**Comment by laclaro** [comment]
Labels would make it so much easier. One key advantage of jabber is the flexibility in terms of clients. I have now five listed fingerprints of my own and also multiple fingerprints for each contact. It would be great to store additional info like client program or creation time to distinguish and properly expire/delete them if not needed anymore.

I strongly oppose @iNPUTmice in #1830 in that sense, we don't want to substitute the fingerprint as identifier, we just want to organise them properly.

Best,

Henning

**Comment by Perelandra0x309** [comment]
I would also like to see some feature to be able to determine which keys are old.  At the very least, a timestamp can be displayed within each client which shows the first date the key was added locally, and the last date the device was active.  This would not require any protocol changes, all this information would be local to the client on each device.

I also test many messaging application and am cycling out devices frequently for my testing setup and also change my primary phone ROM a few times per year.  Right now on my tablet which is never flashed I have 6 inactive fingerprints but I do not know which ones are from old devices.

I just tried using the "Clear Devices" button at the bottom of the "Other devices" list and it only cleared the devices which are not greyed out.  At which point the Clear devices option disappeared.  The only option left is to distrust each one.

**Comment by trwnh** [comment]
I can't even keep track of my own OMEMO keys easily because I have so many devices and I frequently install/uninstall/reinstall clients. Being able to add a simple text label would help greatly in that regard.

**Comment by STPKITT** [comment]
That stale bot is a joke. What's the benefit from closing issues without resolving them?
I also can't find any way to re-open this issue.
