### ISSUE TITLE
Text mark problems

### ISSUE THREAD

**Issue by ghost** [iNPUTmice/Conversations#2624]
#### General information

* **Version:** 1.20.1
* **Device:** Google Nexus 5, Nexus 7
* **Android Version:** Android 7.1.2 LineageOS
* **Server name:** trashserver.net
* **Conversations source:** F-Droid

#### Steps to reproduce

1. get a message
2. hold on the message
2. tap "mark text"

#### Expected result

The text should be marked

#### Debug output

App jumps back nothing is marked, I'm in the conversation.
It's in 8/10

**Comment by licaon-kter** [comment]
If someone posts while you try this it will jump back.

You should get a normal Android pop-up with copy/paste/etc

**Comment by Dionis0s** [comment]
No, this happened also if i get no message.

**Comment by licaon-kter** [comment]
Can you recod this in a clip?

**Comment by mimi89999** [comment]
I also feel like there is an issue with text selection. See the screen recording: https://lebihan.pl/files/conversations_2624.mp4

**Comment by licaon-kter** [comment]
@mimi89999: I feel that's just Android clumsiness in your video, I find selection painfull in other apps too.

**Comment by mimi89999** [comment]
>  I'm seeing an issue with they keyboard. In my case Gboard. Basically if the keyboard is not open it works ok.
But, when the keyboard is opened, it will select the text (and show selection controls), pop open the numbers row, deselect the text, so you need to longpress the chat bubble again.

@licaon-kter Same for me also on AOSP keyboard. I can add a recording for that...

> I feel that's just Android clumsiness in your video, I find selection painfull in other apps too.

For me it works great in most apps, but a small number of apps has indeed issues with it...

**Comment by Dionis0s** [comment]
I already use the AOSP keyboard. 
Eventually the problem comes if I answer and then, i want to mark for a second answer. Not my own text.

**Comment by LegacyTextingCosts** [comment]
workaround:

Instead select share from the context menu.  Install a clipboard management app.  I preferentially share to Clip Stack instead of fiddling with selection.

**Comment by steffanson** [comment]
Is the option `mark text` still available in Conversations? In Conversations 1.22.0 (F-Droid) and LineageOs 14.1 20171020 I only can choose between `Share, Copy to Clipboard and quote`.

**Comment by mimi89999** [comment]
@steffanson You need to double tap on the text to select. See the changelog.

**Comment by therob84** [comment]
I can also confirm both behaviour on LineageOS14.1 / 1.22.0 (F-Droid) / FP2:

- if double tapped on a text, the dialogue and selection menu is displayed, BUT mostly at least for the first try it also auto closes instantly within half a second. After trying it twice or a third time, it then works as expected (markers and context menu stay open).
- if only long pressed a message I only see `Share | Copy to Clipboard | Quote.`

**Comment by iNPUTmice** [comment]
If we ever do a rewrite it will be fixed automatically due to the use of the framework libraries. But implementing this in the current code is not possible.
