### ISSUE TITLE
On contact add, check remote server

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#2631]
Now you can add a contact, start a chat, write something and ONLY then you will see it fail with `remote server not found`

Maybe the app can check, when the user tries to add a contact, if the server responds and if not, maybe, show a warning `o hay, remote server not found, maybe server address or id is wrong?! CANCEL/CONTINUEANYWAY.`

**Comment by whitetornado** [comment]
yes, if you made a mistake when add a new contact you can wait forever before you get a reply back. It will be nice, when you add a new contact that he checks the server if the contact exist..

**Comment by iNPUTmice** [comment]
This would prevent you from adding contacts while momentarily offline.
