### ISSUE TITLE
Can't connect to server without custom hostname (resolving problem)

### ISSUE THREAD

**Issue by imShara** [iNPUTmice/Conversations#2632]
#### General information

* **Version:** 1.20.1
* **Device:** Xiaomi Redmi Note 3 Pro SE
* **Android Version:** Miui 8.1.3.0, Android 6.0.1
* **Server name:** valdikss.org.ru
* **Server software:** Prosody
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Trying to connect with JID only. E.g shara@valdikss.org.ru
2. Trying to connect with custom host `xmpp.valdikss.org.ru`

#### Expected result

Can't connect with JID only (like on Xabber and other Jabber clients), but custom hostname with prefix xmpp solves problem.

##### Only JID setted
````
conversations: shara@valdikss.org.ru: connecting
conversations: Resolver: [Result{ip='5.45.183.10', hostame='valdikss.org.ru', port=5222, directTls=false, authenticated=false, priority=0}, Result{ip='null', hostame='valdikss.org.ru', port=5222, directTls=false, authenticated=false, priority=0}]
conversations: shara@valdikss.org.ru: using values from dns valdikss.org.ru/5.45.183.10:5222 tls: false
conversations: shara@valdikss.org.ru: failed to connect to /5.45.183.10 (port 5222) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)(java.net.ConnectException)
conversations: shara@valdikss.org.ru: using values from dns valdikss.org.ru:5222 tls: false
conversations: shara@valdikss.org.ru: failed to connect to valdikss.org.ru/5.45.183.10 (port 5222) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)(java.net.ConnectException)
conversations: shara@valdikss.org.ru: error connecting account. try again in 32s for the 2 time. lowPingTimeout=false
conversations: shara@valdikss.org.ru: socket was null during force close
````

##### Hostname xmpp.valdikss.org.ru setted
````
> adb logcat -s conversations
conversations: shara@valdikss.org.ru: connecting
conversations: shara@valdikss.org.ru: TLS connection established
conversations: shara@valdikss.org.ru/phone: Authenticating with SCRAM-SHA-1
conversations: shara@valdikss.org.ru: logged in
````

**Comment by licaon-kter** [comment]
SRV records are ok? 

http://prosody.im/doc/dns#srv_records

**Comment by imShara** [comment]
@licaon-kter 

### Client records for valdikss.org.ru
XMPP clients will use these when logging in.

Target | Port | Priority | Weight
-- | -- | -- | --
xmpp.valdikss.org.ru | 5222 | 5 | 1

### Server records for valdikss.org.ru
Other XMPP servers will use these when peering with this domain.

Target | Port | Priority | Weight
-- | -- | -- | --
xmpp.valdikss.org.ru | 5269 | 5 | 1

https://kingant.net/check_xmpp_dns/?h=valdikss.org.ru

**Comment by ShallNotInfringe** [comment]
why same priority and weight?

**Comment by imShara** [comment]
@ShallNotInfringe , no matter if single record exists.

**Comment by traumal** [comment]
I occasionally resolve resolution problems by specifying the SRV FQDN as conversations custom host.

**Comment by sbernard31** [comment]
I'm unable to connect to several xmpp server (jabber.lqdn.fr, movim.eu) using JID.
Does it exist a work arround ? How can I use custom host ?

**Comment by licaon-kter** [comment]
Did you enable advanced server settings? What's the issue exactly? Logcat ?

**Comment by sbernard31** [comment]
I tested it with 1.20.1 version and 1.22 version.
I not sure to know what is "advanced server settings" but I enable the possibility to enter host and port instead of JID.
I can not connect to those 2 server anymore with this method too.

The issue is "Impossible de trouver le serveur" (unable to find server ?).
I haven't any easy way to use adb, so no logcat for now :/.
I will see if I can find time.

**Comment by licaon-kter** [comment]
What device? What Android version? (encryption protocols support depends on version)

The servers are ok in the tests?
See both c2s and s2s tests here: https://check.messaging.one

**Comment by sbernard31** [comment]
Nesus S/Android 4.4.2 (slim rom)
I was able to use conversation before with this ROM. It just doesn't work since my last update, but I have no way to get the version number I used before :/.

**Comment by sbernard31** [comment]
forgot all my previous comments ... my company blocks recently the xmpp port on its network and I was not aware about that ... sry :/

**Comment by brighterness** [comment]
I suffer this with free public server:

https://blabber.im

I must provide  one of the round robin servers specified in SRV via extended hostname feature.

Differently SRV problematic is Fysh.in
