### ISSUE TITLE
Support of initial messages using Google Assistant / Android Auto

### ISSUE THREAD

**Issue by morgenroth** [iNPUTmice/Conversations#2655]
This is a feature request and if I find some time, I'll start to work on it.

Since my last contribution, I'm able to respond to messages using Android Auto. Still a missing feature is sending an initial message by saying _"ok, Google... send a message to John Doe with Conversation"_. Unfortunately, there is no official documentation on how to implement that. But somehow WhatsApp has added such a feature to its messenger.

So I searched for a decompiled [AndroidManifest.xml](https://github.com/GigaDroid/Decompiled-Whatsapp/blob/master/AndroidManifest.xml) of WhatsApp and found a non-documented intent action.

```
        <activity android:name="com.whatsapp.VoiceMessagingActivity">
            <intent-filter>
                <action android:name="com.google.android.voicesearch.SEND_MESSAGE_TO_CONTACTS" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/plain" />
            </intent-filter>
        </activity>
```

Maybe it is the missing part for being recognized by Google Assistent.

**Comment by ivucica** [comment]
See also [ACTION_VOICE_SEND_MESSAGE_TO_CONTACTS_](https://developer.android.com/reference/android/provider/ContactsContract.Intents.html#ACTION_VOICE_SEND_MESSAGE_TO_CONTACTS) which has the possibly relevant value `android.provider.action.VOICE_SEND_MESSAGE_TO_CONTACTS`.
