### ISSUE TITLE
[UX] It's too easy to cancel presence updates

### ISSUE THREAD

**Issue by marmistrz** [iNPUTmice/Conversations#2673]
When entering the contact details, there's a field named "receive presence updates". If you accidentally click it, you need to ask the other party to explicitly give consent for presence notifications back again. 

It's too easy to resign from the presence updates, especially that this can be even triggered by using the phone in the rain (just a feature of capacitive screens). There should at least be a confirmation dialog.

**Comment by contrapunctus-1** [comment]
I think explicit control over presence updates should be moved to a plugin - if two people are in each others' rosters, they should automatically have mutual presence subscriptions. (I'm not sure if it's relevant, but [PARS](https://xmpp.org/extensions/xep-0379.html) was brought up when this was discussed.)

**Comment by donnovannie** [comment]
The defaults for features should be changed to all-in-sharing:

do **confirm messages**
do send **typing notifications**
do **broadcast last interaction**
do **allow message correction**
do set **Away when screen is off**
do **request message receipts**

and the settings marked for 'privacy' should not be labeled privacy as it actively discourages the NAIVE to  disable them (after the client is setup for them)

![sharing-is-caring](https://user-images.githubusercontent.com/34976385/34459705-c2466680-edac-11e7-8e2c-3aa261622d81.jpg)

**Comment by marmistrz** [comment]
I really don't understand why message receipts are turned off by default. When I set up the client for my friends, I always turn on the options mentioned above and turn off blind-trust-before-verify.

**Comment by licaon-kter** [comment]
> I really don't understand why message receipts are turned off by default.

It might be a privacy problem.

> and turn off blind-trust-before-verify.

Let's hope you are around in person when they change their device or reinstall Conversations, right?

**Comment by marmistrz** [comment]
>>  I really don't understand why message receipts are turned off by default.
> It might be a privacy problem.
If I'm requesting delivery receipts, that's in no way a privacy problem for me.
It might be a privacy problem.

>>  and turn off blind-trust-before-verify.
> Let's hope you are around in person when they change their device or reinstall Conversations, right?
That's needed anyway because of the usual combination of *I won't pay for an IM if I have a free Facebook Messenger* and *you should install the F-what? Please do that for me, I can't*
Alternatively, I just send them a manual if they're tech-savvy enough.

**Comment by TntDestroyer** [comment]
Presence is the HEART of xmpp.  Not only is it inappropriate to move this to a plug-in but the default "privacy" settings need be relabeled in encouraging social words, and enabled by default.  And yes, confirmation for disable with the explanation the other party will have to confirm would be excellent

**Comment by TntDestroyer** [comment]
default
first four under privacy

(yes, i see there are only 3 privacy settings)

Send indicates status

expert settings
blind trust 
allow message correction
away when screen off
dnd in silent mode
request message receipts 


this is a bidirectional communication tool not a stealthy interweb posting tool

**Comment by marmistrz** [comment]
This is still an issue

**Comment by contrapunctus-1** [comment]
Still an issue

**Comment by iNPUTmice** [comment]
> Still an issue

Unfortunately nobody has been interested in working on that in three years. So it's fair to assume that this is not going to happen any time soon.
