### ISSUE TITLE
Conversations re-shows notification for old messages, i.e., notifications that I have already previously clicked on

### ISSUE THREAD

**Issue by ericbodden** [iNPUTmice/Conversations#2706]
#### General information

* **Version:** current Play Store version
* **Device:** Samsung S6
* **Server name:** self josted jabber
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Run app for a while, use for chatting, let go to background
2. Occasionally, notifications will pop up again for long-ago conversations

#### Expected result

Never show again notifications that have already been clicked on.

#### Actual result

Notifications re-appear for long ago conversations that I have already clicked on.

**Comment by therob84** [comment]
I can confirm this behaviour on FP2 / LineageOS14.1 / Conversations 1.22.0-F-Droid.
But with the constraint, that I only see this behaviour sometimes after a complete device restart or a complete kill of the app (and then also not always!)

**Comment by licaon-kter** [comment]
Seen this after a reboot too, but not as the OP says, during normal usage.

**Comment by carlosladsal** [comment]
It happened to me once using prosody because i was using the wrong MAM module. I do not know if that is your case. I hope it helps.

**Comment by licaon-kter** [comment]
Seeing this too in 1.23.7/8 in the main Conversations MUC.

On reconnect there's a 50% chance to get a notification from 12h ago of a certain post.

Eg. Today is from one user. But yesterday was from another one.

**Comment by Dehumanizer77** [comment]
I have this problem too and it's really annoying, it happens upon reconnect. I wonder if noone else is experincing this. The issue is 2 years old and nobody responded yet...

**Comment by licaon-kter** [comment]
@Dehumanizer77 you're seeing this with 2.3.10?

**Comment by Dehumanizer77** [comment]
@licaon-kter yes, I have tried 2.3.8 , 2.3.9 and 2.3.10 and it behaves the same... 
I have also tried to experiment with message archive settings on my server (Openfire) but it didn't help at all.

**Comment by Dehumanizer77** [comment]
The problem still persists in 2.3.12...

**Comment by Dehumanizer77** [comment]
And it's still the same with 2.4.3

**Comment by ReyKoxha** [comment]
@Dehumanizer77 what device do you have?
How about your Android version?

**Comment by Dehumanizer77** [comment]
@ReyKoxha currently Android 9 (Xiaomi Pocophone F1), but it's also doing the same on my wife's Android 8

**Comment by Dehumanizer77** [comment]
And it usually pops up the notification about old messages when it switches from wifi to LTE when I'm leaving home...

**Comment by licaon-kter** [comment]
@Dehumanizer77 Any tests on ejabberd or prosody servers?

**Comment by Dehumanizer77** [comment]
@licaon-kter unfortunatelly I don't have the opportunity to test other servers right now...

**Comment by licaon-kter** [comment]
@Dehumanizer77 eh, opportunity sounds awful: https://compliance.conversations.im

**Comment by Dehumanizer77** [comment]
@licaon-kter 
![Screenshot at 2019-05-14 16-04-12](https://user-images.githubusercontent.com/1876451/57704578-7e56c880-7662-11e9-927b-e7d0dac0b6fa.png)

This is a result for my server, I suppose XEP-0313 (MAM) is what's causing a problem here and it seems the server is compliant with that XEP... If I understand it correctly.

**Comment by licaon-kter** [comment]
@Dehumanizer77 Well, it doesn't hurt to get your server into shape first ;)

I linked to the tester so you can maybe find some public ejabberd or prosody server that you can register 2 accounts on and chat a bit between them so you can repro (or not) the issue.

**Comment by Dehumanizer77** [comment]
The problem is I don't really know how to reproduce the issue. It's really intermittent, sometimes it doesn't happen for a week and sometimes it does it several times in a row. I can try though.

**Comment by Dehumanizer77** [comment]
Just a note that I didn't notice the problem for a long time now, so I suppose it was fixed somehow in some of the recent versions.
