### ISSUE TITLE
Make README.md uniformally formatted

### ISSUE THREAD

**Issue by Rushi98** [iNPUTmice/Conversations#2711]
#### General information
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce
1. View the `README.md` file in any decent text viewer.

#### Expected result
A file with uniform formatting.

#### Actual result
A file with not uniform formatting.
1. Lines are not wrapped uniformally.
2. Initial paragraphs of the file can be converted to markdown. (With exception of center align, which I don't know how to make totally markdown and Google didn't gave any results).

#### Debug output
Not Applicable

This helps in improving project/code quality. And also good first issue for me to work on :smile:

**Comment by iNPUTmice** [comment]
Knock yourself out.

**Comment by Rushi98** [comment]
Does that mean go ahead?

**Comment by daivat15** [comment]
I think you mean 'uniformly' 😆
