### ISSUE TITLE
Wrong order of messages of messages sent as soon as network is available

### ISSUE THREAD

**Issue by allo-** [iNPUTmice/Conversations#2745]
#### General information

* **Version:** 1.3.3
* **Device:** Samsung Note 10.1
* **Android Version:** Android 4.4 LineageOS
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** CSI, MAM, (some probably not relevant ones)
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Write a message when no network is available
2. Receive a message while there is no network. 
3. Have another client receiving it and the server storing it in the archive
4. Go online

#### Expected result

Correct message history

#### Actual result

The own message is sent, then the received message is added below.

#### Debug output

History as seen in gajim, which is online the whole time:

```
‎‎[22:55:50] contact: aaa #(conversations offline)
‎[22:56:06] me: bbb #(conversations offline)
‎[22:56:42] me: ccc #(conversations connecting. possibly already online)
```

History as seen in conversations:
```
me: bbb
contact: aaa
me: ccc
```

In this example I am not 100% sure if inaccurate clocks may be part of the problem. Both devices should use NTP, but the tablet may have some seconds as it were disconnected before. But as it only were disconnected for a few minutes there should probably be no big deviation.

Is there some option to get the full timestamps in conversations?

**Comment by allo-** [comment]
Is this fixed?

**Comment by iNPUTmice** [comment]
I have actually never been able to reproduce this.
