### ISSUE TITLE
Feature request: Add UI emoji button

### ISSUE THREAD

**Issue by wurstsalat3000** [iNPUTmice/Conversations#2759]
Right now, you can choose between the Enter button and the emoji button being displayed (in expert settings).
Is there a way to show them both?

An alternative to the emoji button in the lower right of the keyboard would be an additional button somewhere in the message typing area (e.g. the left of the text input field). This way, both buttons could be displayed at the same time.

**Comment by licaon-kter** [comment]
It's a keyboard feature mostly. Try another keyboard. Eg. Gboard

**Comment by wurstsalat3000** [comment]
Wouldn't it be best if it works with the standard Android AOSP keyboard?

Chatting via several IM clients (Telegram, WhatsApp, Signal), Conversation is the only one lacking this feature.

**Comment by licaon-kter** [comment]
Adding another button to the Conversations app has nothing to do with what buttons your favourite keyboard shows (that's what my comment refers to).

Eg. Gboard has such an option, to show both ENTER and emoji, IIRC.

Do edit your title accordingly, _"add UI emoji button"_ or something.

**Comment by Echolon** [comment]
I support @wurstsalat3000's idea, because most standard user will **never ever** install another keyboard. And I experienced several time that they hate the standard smileys or the missing emoji-button somehow. 

So, offering this would make their _Conversations-experience_ more satisfying.

**Comment by allo-** [comment]
I think it is useful for two reasons:

- Keyboard emojis are more cumbersome. First touch the input field, then wait for the keyboard to open, then long-press the emoji button (depends on keyboard), then select the emoji, then switch back to keyboard mode.
- (Some) Keyboards show the system emoji set, while Conversations has an own one. Some smileys are quite different there. For example the eyes emoji is sexy eyes in stock android and curious eyes in Conversations.

**Comment by wurstsalat3000** [comment]
To summarize this: Emojis should be a keyboard task, otherwise every app would have to implement their own solution, which would never satisfy everyone. https://github.com/siacs/Conversations/pull/2907#issuecomment-443517889 gives some hints on why this would *much* extra work for developers.

Hint for LineageOS users or any user of Android Open Source Project's (AOSP) keyboard: In Conversations expert settings, set 'Replace Emoji button with Enter'. This way, you can long-press Enter to reach Emojis.
