### ISSUE TITLE
[Feature request] Different notification sound for MUC messages than private/mention

### ISSUE THREAD

**Issue by Mikaela** [iNPUTmice/Conversations#2806]
#### General information

* **Version:** 1.23.6
* **Device:** OnePlus 3
* **Android Version:** Android 8.0 OxygenOS
* **Server name:** blesmrt.net
* **Server software:** unknown
* **Installed server modules:** partial PEP, everything else available
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

Open Conversations settings of Android notification settings for Conversations and see that there are notification settings only for everything.

#### Expected result

I would like to have seen option for setting different notification sound for messages coming to MUC that aren't mentioning me, so I don't have to open screen to see have I gotten a private message or something in a MUC.

#### Actual result

I saw only option for global ringtone which applies to private chats, MUC messages and MUC pings/mentions.

#### Debug output

N/A

**Comment by Mikaela** [comment]
@licaon-kter I don't see that issue mentioning MUCs or group chats at all?

**Comment by licaon-kter** [comment]
Indeed, but still a duplicate.
:)

**Comment by d9h20f** [comment]
Not really, the issue you mentioned is asking for a way to give each contact a different sound, this one is only asking for differentiating between private and group messages. That said, I would simply change the notifications for the group chats you're in to only notify on mention.

**Comment by Mikaela** [comment]
There is no notification class for MUCs that I can see, only Calls, Messages and Status Information.

**Comment by Mikaela** [comment]
This would still be helpful for me
