### ISSUE TITLE
notificactions history keeps sensible information

### ISSUE THREAD

**Issue by linuxnow** [iNPUTmice/Conversations#2868]
#### General information

* **Version:** 2.0.0.0-beta2
* **Device:** Google Nexus 5x
* **Android Version:** LienageOS 15.1 (Android 8.1.0)
* **Server name:** all
* **Server software:** all
* **Installed server modules:** does not matter
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. …enable notifications
2. …check notification history

#### Expected result

What is the expected output? 
Whatever you send to a notification gets logged and kept in the notifications history.

#### Actual result
Notification history keeps messages and metadata for a long time, creating a privacy problem.

### Proposal
It would be nice to have a configuration option. like Signal, to control what goes to notifications:
-name and message
-name
-just an app notification without name or message

**Comment by licaon-kter** [comment]
Is notification history a LOS thing and not a standard Android feature, right? It does not have any settings, blacklists?

**Comment by linuxnow** [comment]
It's a standard feature and the only thing you can configure is to enable or disable notifications for an app.
If you disable them you have to open the app to check the activity.
