### ISSUE TITLE
Idea: Shortcut for QR-Code scanning 

### ISSUE THREAD

**Issue by Echolon** [iNPUTmice/Conversations#2896]
**Version:** 1.23.8 and 2.0.0
**Device:** Samsung S3 and OnePlus 2
**Android Version:** LineageOS
**Conversations source:** PlayStore, F-Droid

#### Issue

It's pretty hard and obstacle-like way to find the QR-Code via the Share-Button. Most people probably guess to only share their ID from there. Today me and a friend (and we are both engineers ;) ) couldn't find the QR-Code for verification (before asking in the group chat). 
To kind of hide it there makes it even more hard for most people to "easy & voluntary" verify their fingerprints. We both discussed my idea to improve here, thus I like to present it to you.

#### Idea

I wonder this did came up earlier. Anyway, we would like to suggest to just put a shortcut on each fingerprint field, as the screen-shots below show:

#### _Previous layout_ 
(Sry it's a screen still from 1.23.8)
![qr1](https://user-images.githubusercontent.com/29168011/37867649-e8a27540-2f9b-11e8-8678-3abbcfd03e29.jpg)

#### _Our idea:_
![qr2](https://user-images.githubusercontent.com/29168011/37867652-ebd2a2d0-2f9b-11e8-98ef-244ab900803d.jpg)

If the copy-button is in the way, it probably should be dropped or hidden in the previous method by long-pressing the field. I'm questioning: How often do you copy this in comparison to the number of 0 verification your intend to do?

Hope you agree that this is a more intuitive method. A small "Verify"-text below this button may provide additional help understanding.

Kind regards, feel free to vote!

**Comment by licaon-kter** [comment]
Why not me the Share icon from the titlebar right there, and drop copy indeed.

**Comment by Echolon** [comment]
Hi,

me again. I just saw that Conversations already has a solution for this - maybe came with C2.0 once I updated. Unfortunately, this is only usable for fingerprints I like to scan, not for those to show from my side. I'm talking about this from a contact's profile:

![screenshot_20180327-175556](https://user-images.githubusercontent.com/29168011/37983938-2a6ed4e0-31f5-11e8-9788-ddd8aa8be8ef.png)

Would be great to see this my own fingerprints, too. Still, I think the QR-Code-Symbol is more intuitive, but okay.

Cheers

**Comment by allo-** [comment]
On the qr-code scanning page could be a shortcut at top or bottom, which opens an account chooser menu (or just displays the code when there is only one account).

**Comment by RalfJung** [comment]
This is still a problem in the current version -- I just literally could not figure out how to show my barcode; I had to use google. Long-pressing my own profile picture in the conversation is an extremely well-hidden place to put this menu item.

**Comment by licaon-kter** [comment]
Account - Share - Barcode is hidden?

**Comment by allo-** [comment]
> Account - Share - Barcode is hidden?

You probably sound a bit snarkier than you intended, but please consider that you have three users who came here to report a usability problem finding the function. So I would say it is too hidden to find it intuitively.  For usability issues it isn't helpful to say "You're not looking close enough it is not that hidden" when people face the issue that it wasn't easy to find for them.

As adding people by barcode is a convenience feature making it as easy as possible to add other users, it is probably the best when it is as easy to find as possible in prominent and logical places. It may be worth to have a look at which places similar apps make the feature accessible.

**Comment by licaon-kter** [comment]
Adding peoplo by barcode adds some security safety features users might regret having later on when changing devices.

So, snarky or not, I want users to be aware of this more than to be slowed down by 2 more touches.

**Comment by RalfJung** [comment]
> Account - Share - Barcode is hidden?

Yes, it is. "Share" is usually associated with sending some kind of message to someone. I would never have expected "show barcode" there.

> Adding people by barcode adds some security safety features users might regret having later on when changing devices.

That's fair, but I don't see how hiding the feature communicates this fact.

**Comment by allo-** [comment]
>     Adding people by barcode adds some security safety features users might regret having later on when changing devices.

I think this is a separate issue and can probably be improved. You're right. Using this feature makes it harder to change devices for a reason. But this is not communicated in a good way. Still, in particular, one should be able to improve the opportunistic BTBV security using the barcode to transfer key fingerprints for the current installation and still allow changing devices by not necessarily disabling BTBV forever. The features are currently combined (enable secure mode and add keys) but don't have to be connected. You could have "enable secure mode (requires transferring the fingerprints)" and "improve security (transfer fingerprints, but do not enable secure mode)".
