### ISSUE TITLE
HTTP link page with more privacy

### ISSUE THREAD

**Issue by allo-** [iNPUTmice/Conversations#2913]
A possible improvement for more privacy could be to put the private information in an anchor, i.e. https://conversations.im/i/#user@host and generate the page with javascript.
Of course this would on the other hand not work for people blocking javascript, so there is some tradeoff there.

Another possible solution may be to create the page on the own server via HTTP upload, but I am not sure if this would be possible.

**Comment by SkewedZeppelin** [comment]
It actually used to be that way, not too sure why it changed

**Comment by BlauerHunger** [comment]
https://github.com/ge0rg/easy-xmpp-invitation works like this, conversations.im sends the xmpp uri to the server

**Comment by TntDestroyer** [comment]
> on the own server via HTTP upload

In a cloud agnostic way where users (JID) could provide credentials?

**Comment by licaon-kter** [comment]
In the invitation site path regulated by a standard or something so it can be detected? @ge0rg 

@iNPUTmice I'd like to have Conversations generate the link to `https://myserver.tld/i/#myjid@myselver.tld` and not `conversations.im/invite/...` if it detects that I have the invite landing page/path setup.

**Comment by licaon-kter** [comment]
Still want this though.

**Comment by iNPUTmice** [comment]
Maybe for someone else to setup and host a privacy friendly version of this. Once it exists and has been established we can revisit.

**Comment by ge0rg** [comment]
Like the one hosted on https://join.jabber.network/#conversations@conference.siacs.eu?join maybe? ;)

Disclaimer: I'm the one running it, but feel free to catch the URL right in conversations and to use it.
