### ISSUE TITLE
Black screen for barcode scanner on Replicant

### ISSUE THREAD

**Issue by doak** [iNPUTmice/Conversations#2973]
#### General information

* **Version:** 2.1.0
* **Device:** Samsung Galaxy S3 
* **Android Version:** Replicant 6.0 0003 
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Click on any 'Scan Barcode' button

#### Expected result

Current live image of camera to target barcode.

#### Actual result

Black screen. Back button cancels scanning and returns to previous view.
Perhaps it is related to #2787.

#### Debug output

(Let me know if needed...)

**Comment by licaon-kter** [comment]
Did it ask and did you give it "Camera" permission?

**Comment by iNPUTmice** [comment]
> (Let me know if needed...)

Yes.

**Comment by doak** [comment]
Thank you for your response:

@licaon-kter, I think it already had. At least it has permissons now. Privacy is set to 'always ask', but interestingly is states "never used".

@iNPUTmice, ok.

**Comment by doak** [comment]
There is the anonymised `logcat` output of a whole Conversation run. The last few lines happened when hitting the scan button and pressing back after a few seconds:

        --------- beginning of system
        --------- beginning of main
        04-20 23:33:07.805  3480  3480 D conversations: initializing database...
        04-20 23:33:07.805  3480  3480 D conversations: restoring accounts...
        04-20 23:33:07.945  3480  3480 D conversations: restoring conversations...
        04-20 23:33:07.965  3480  3480 D conversations: finished restoring conversations in 22ms
        04-20 23:33:07.980  3480  3524 D conversations: restoring roster...
        04-20 23:33:08.030  3480  3480 D conversations: stopped foreground service
        04-20 23:33:08.030  3480  3480 D conversations: update unread count to 0
        04-20 23:33:09.950  3480  3524 D conversations: restoring messages...
        04-20 23:33:09.970  3480  3521 D conversations: start merging phone contacts with roster
        04-20 23:33:09.970  3480  3521 D conversations: finished merging phone contacts
        04-20 23:33:13.145  3480  3524 D conversations: finished restoring messages in 3198ms
        04-20 23:33:24.415  3480  3480 D conversations: resetting all attempt counts
        04-20 23:33:24.635  3480  3866 D conversations: JID1@SERVER1: socket was null during force close
        04-20 23:33:24.650  3480  3866 D conversations: JID1@SERVER1: connecting
        04-20 23:33:26.365  3480  3866 D conversations: Resolver: [Result{ip='IPv4A', hostame='jabberd.SERVER1', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='IPv6B', hostame='jabberd.SERVER1', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='IPv4A', hostame='jabberd.SERVER1', port=80, directTls=false, authenticated=false, priority=20}, Result{ip='IPv6B', hostame='jabberd.SERVER1', port=80, directTls=false, authenticated=false, priority=20}, Result{ip='IPv6B', hostame='jabberd-ipv6.SERVER1', port=5222, directTls=false, authenticated=false, priority=30}, Result{ip='null', hostame='jabberd-ipv6.SERVER1', port=5222, directTls=false, authenticated=false, priority=30}, Result{ip='IPv4A', hostame='jabberd-ipv4.SERVER1', port=5222, directTls=false, authenticated=false, priority=31}]
        04-20 23:33:26.375  3480  3866 D conversations: JID1@SERVER1: using values from dns jabberd.SERVER1/IPv4A:5222 tls: false
        04-20 23:33:26.885  3480  3866 D conversations: JID1@SERVER1: TLS connection established
        04-20 23:33:26.930  3480  3866 D conversations: JID1@SERVER1/resource1: Authenticating with SCRAM-SHA-1
        04-20 23:33:27.515  3480  3866 D conversations: JID1@SERVER1: logged in
        04-20 23:33:27.630  3480  3866 D conversations: JID1@SERVER1: not counting stanza(IqPacket). Not in smacks session.
        04-20 23:33:27.645  3480  3866 D conversations: JID1@SERVER1: starting service discovery
        04-20 23:33:27.660  3480  3866 D conversations: JID1@SERVER1: server caps came from cache
        04-20 23:33:27.685  3480  3866 D conversations: JID1@SERVER1: stream management(3) enabled (resumable)
        04-20 23:33:27.730  3480  3866 D conversations: JID1@SERVER1: Requesting block list
        04-20 23:33:27.895  3480  3866 D conversations: JID1@SERVER1: successfully enabled carbons
        04-20 23:33:27.895  3480  3866 D conversations: Received blocklist update from server
        04-20 23:33:28.365  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Bundle 1866407781 in PEP was current
        04-20 23:33:28.365  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Announcing device 1866407781
        04-20 23:33:28.380  3480  3866 D conversations: JID1@SERVER1: online with resource resource1
        04-20 23:33:28.380  3480  3866 D conversations: JID1@SERVER1: fetching roster
        04-20 23:33:28.390  3480  3866 D conversations: JID1@SERVER1: running mam query with=*, end=2018-04-20T21:33:27.672Z, order=NORMAL, after=1524244354217721, catchup=true
        04-20 23:33:28.390  3480  3866 D conversations: JID1@SERVER1 sending csi//inactive
        04-20 23:33:28.920  3480  3866 D conversations: JID1@SERVER1: retrieved own device list: [1891143678, 1866407781]
        04-20 23:33:28.980  3480  3866 D conversations: JID1@SERVER1: added own device 05e3297f64bf9b269b0e7eb60770220503ed42a3bfc5c1c638d7e73aa7b90d7e6c to list of expired devices. Last message received 168 hours ago
        04-20 23:33:28.980  3480  3866 D conversations: AxolotlService (JID1@SERVER1): publishing own device ids
        04-20 23:33:28.980  3480  3866 W conversations: AxolotlService (JID1@SERVER1): Own device list empty, attempting to publish (try 1)
        04-20 23:33:29.235  3480  3866 D conversations: JID1@SERVER1: successfully purged offline messages
        04-20 23:33:29.280  3480  3866 D conversations: JID1@SERVER1: finished mam after 2(0) messages. messages left=true count=302
        04-20 23:33:29.280  3480  3866 D conversations: JID1@SERVER1: found 0 pending receipt requests
        04-20 23:33:29.280  3480  3866 D conversations: JID1@SERVER1: joining conversation ROOM1@conference.SERVER1/resource2
        04-20 23:33:29.290  3480  3866 D conversations: JID1@SERVER1: running mam query to=ROOM1@conference.SERVER1, start=2018-03-19T09:57:27.134Z, end=2018-04-15T21:33:29.294Z, order=REVERSE, catchup=false
        04-20 23:33:29.290  3480  3866 D conversations: JID1@SERVER1: running mam query to=ROOM1@conference.SERVER1, start=2018-04-15T21:33:29.294Z, end=2018-04-20T21:33:29.294Z, order=NORMAL, catchup=true
        04-20 23:33:29.290  3480  3866 D conversations: JID1@SERVER1: fetching members for ROOM1
        04-20 23:33:29.290  3480  3866 D conversations: JID1@SERVER1: joining conversation ROOM2@conference.SERVER1/resource2
        04-20 23:33:29.305  3480  3866 D conversations: JID1@SERVER1: running mam query to=ROOM2@conference.SERVER1, start=2017-12-09T10:57:14.425Z, end=2018-04-15T21:33:29.309Z, order=REVERSE, catchup=false
        04-20 23:33:29.305  3480  3866 D conversations: JID1@SERVER1: running mam query to=ROOM2@conference.SERVER1, start=2018-04-15T21:33:29.309Z, end=2018-04-20T21:33:29.309Z, order=NORMAL, catchup=true
        04-20 23:33:29.305  3480  3866 D conversations: JID1@SERVER1: fetching members for ROOM2
        04-20 23:33:29.445  3480  3915 D conversations: JID1@SERVER1: persisted roster in 209ms
        04-20 23:33:31.705  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Received PEP device list [1866407781] update from JID1@SERVER1, processing... 
        04-20 23:33:32.305  3480  3866 D conversations: JID1@SERVER1: finished mam after 0(0) messages. messages left=false count=0
        04-20 23:33:32.305  3480  3866 D conversations: JID1@SERVER1: found 0 pending receipt requests
        04-20 23:33:32.305  3480  3866 D conversations: JID1@SERVER1: finished mam after 0(0) messages. messages left=true count=0
        04-20 23:33:32.305  3480  3866 D conversations: JID1@SERVER1: found 0 pending receipt requests
        04-20 23:33:32.330  3480  3866 D conversations: JID1@SERVER1: retrieved members for ROOM1@conference.SERVER1: []
        04-20 23:33:32.330  3480  3866 D conversations: JID1@SERVER1: finished mam after 0(0) messages. messages left=false count=0
        04-20 23:33:32.330  3480  3866 D conversations: JID1@SERVER1: found 0 pending receipt requests
        04-20 23:33:32.330  3480  3866 D conversations: JID1@SERVER1: finished mam after 0(0) messages. messages left=true count=0
        04-20 23:33:32.330  3480  3866 D conversations: JID1@SERVER1: found 0 pending receipt requests
        04-20 23:33:32.335  3480  3866 D conversations: JID1@SERVER1: retrieved members for ROOM2@conference.SERVER1: []
        04-20 23:35:34.970  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Received PEP device list [1492839573] update from JID5@SERVER1, processing... 
        04-20 23:36:45.510  3480  3480 D conversations: onCreateView
        04-20 23:36:45.585  3480  3480 D conversations: ConversationsOverviewFragment.onStart()
        04-20 23:36:45.585  3480  3480 D conversations: ConversationsOverviewFragment.onResume()
        04-20 23:36:45.625  3480  3480 D conversations: JID1@SERVER1 send ping (action=ui,lowTimeout=false)
        04-20 23:36:45.720  3480  3480 D conversations: app switched into foreground
        04-20 23:36:45.830  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Received PEP device list [274451254] update from JID3@SERVER1, processing... 
        04-20 23:36:45.840  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Received PEP device list [441684066] update from JID2@SERVER1, processing... 
        04-20 23:36:45.855  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Received PEP device list [15804675] update from JID1@jabber.org, processing... 
        04-20 23:36:45.920  3480  3866 D conversations: JID1@SERVER1: OpenKeychain error 'Encountered an error reading input data!' code=0
        04-20 23:36:45.920  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Received PEP device list [390479008] update from JID4@SERVER2, processing... 
        04-20 23:36:45.925  3480  3866 D conversations: AxolotlService (JID1@SERVER1): Received PEP device list [1866407781] update from JID1@SERVER1, processing... 
        04-20 23:36:45.930  3480  3866 D conversations: JID1@SERVER1: ignoring duplicate own device id list
        04-20 23:36:56.555  3480  3480 D conversations: ConversationsOverviewFragment.onPause()
        04-20 23:36:56.780  3480  3480 D conversations: app switched into background
        04-20 23:37:09.895  3480  3480 D conversations: ConversationsOverviewFragment.onStart()
        04-20 23:37:09.900  3480  3480 D conversations: ConversationsOverviewFragment.onResume()
        04-20 23:37:09.985  3480  3480 D conversations: app switched into foreground

**Comment by doak** [comment]
@iNPUTmice, do you need any more information?

**Comment by doak** [comment]
Any help I can provide? The issue still exists.

**Comment by doak** [comment]
Any help I can provide? The issue still exists.

**Comment by doak** [comment]
Any help I can provide? The issue still exists.

**Comment by doak** [comment]
Any help I can provide? The issue still exists.

**Comment by iNPUTmice** [comment]
@doak It seems to be device or even ROM specific. So either you hope that one day someone with your device comes along or you help yourself and debug it yourself.
