### ISSUE TITLE
[Feature request] More features of QR code

### ISSUE THREAD

**Issue by SoyaLeaf** [iNPUTmice/Conversations#2977]
Using QR code seems more convenient than using strings，but there are too few features currently available in Conversations.

Here are some ideas:

- [ ] 1. Provide button to save QR code picture
- [x] 2. Get a QR code image from the gallery
- [x] 3. Open flashlight in a dark environment
- [ ] 4. Add a shortcut to scan QR code.
- [ ] 5. App icon in the middle of QR code

P.S. QR code seems to be not friendly to the PC. 0.0

**Comment by tdemin** [comment]
> P.S. QR code seems to be not friendly to the PC. 0.0

Most PC clients allow you to verify the keys by hand, so you can simply open account settings to do verification. 😉

**Comment by SoyaLeaf** [comment]
@tdemin 

yep... so whether some content should be displayed on the QR code image, such as displaying the Jid string at the bottom of the image. In this way, when the user shares the QR code, the user on the pc side can perform some operations better without parse the QR code.

Sorry, I don't seem to express it well. :)

**Comment by wiktor-k** [comment]
This is a good idea! Actually the "share" button on account settings should just display QR code image on screen and more options could be available from there (on the botton of the QR image or so).

Imagine how many clicks and searching is needed to exchange contact info with a live person...

**Comment by Echolon** [comment]
Like to refer to my idea, too: Shortcut for QR-Code scanning #2896

**Comment by allo-** [comment]
Twidere creates a bar code with the avatar in the background. this looks very pretty and is a real incentive to share the barcode.
