### ISSUE TITLE
MUC disconnects after network changes

### ISSUE THREAD

**Issue by bodems** [iNPUTmice/Conversations#2983]
#### General information

* **Version:** 2.12
* **Device:**  Motorola Moto G4 Play
* **Android Version:** Android 7.1.2 LineageOS
* **Server name:** jabber.space.bi
* **Server software:** prosody (don't know the version)
* **Installed server modules:** Stream Management, CSI, Message Carbons
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Be in Multi User Chat and receive messages
2. Change Network or loose connection
3. Often new messages in a MUC aren't received anymore and their is no hint (sometimes there is a hint), that there was a disconnect with the MUC.

#### Expected result

Conversations should reconnect to the MUC. If I disable my account in settings and enable it, new MUC messages can be received. This behavior started with 2.0 and it wasn't a problem with earlier versions. A friend of me also can reproduce this behavior.

**Edit:** This only effects MUC messages, not "normal" one-to-one messages

**Comment by licaon-kter** [comment]
Can you repro this with another server?

**Comment by gimbar** [comment]
I'm experiencing similar problems. If there's a network problem I'll lose connection to my MUCs.
Sometimes there's an option to reconnect, sometimes there just aren't any messages.

Worked fine in pre 2.0 versions of Conversations.

**Comment by whitetornado** [comment]
any news about this? I missing also some messages. Maybe mobile internet is not always connected to the server, can that be a reason?

**Comment by mw80** [comment]
Maybe related to this issue? https://issues.prosody.im/1129
Had the same problem and it figured out mam muc is not working.
