### ISSUE TITLE
Add Google Play store description on Transifex

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#3004]

**Comment by wiktor-k** [comment]
Excellent idea and something that I was thinking about too. The auto translated Google description just doesn't make sense at all!

**Comment by licaon-kter** [comment]
Still want this...and then copy it to Fastlane

**Comment by iNPUTmice** [comment]
I've tried to get fastlane running for the better part of today (which would be the only realistic way to manage that many translations on Google Play); it is an absolute mess and I don’t need that right now in my life.

**Comment by licaon-kter** [comment]
But what about Triple T?
