### ISSUE TITLE
Long messages are cut off

### ISSUE THREAD

**Issue by tyler71** [iNPUTmice/Conversations#3023]
#### General information

* **Version:** 2.6.1+pcr
* **Android Version:** Android 9.0 stock
* **Conversations source:** PlayStore Beta Channel
#### Steps to reproduce
* Receive a [long message](https://pastebin.com/raw/CAjB4Bn3) of about 4090 characters
* Message is cut off with a `...` eg `maleA -> male...`
#### Expected result
Should have method of viewing full message if desired
Message Options to include a "[Expand message](https://i.imgur.com/nEGG05J.png)" option
#### Actual result
Unable to view full message in conversations chat
The full message is kept, just not displayed since it lets you copy, share or quote the full message

**Comment by Lykos153** [comment]
This is really annoying. I don't even see the need for an "expand message" option. Just show the message full length. What's the problem?

**Comment by licaon-kter** [comment]
The bubble is fragile, it breaks if the message is too long.

**Comment by licaon-kter** [comment]
The bubble is an Android thing on screen, that's the fragile part.

**Comment by Lykos153** [comment]
We are constantly running into this issue. This is becoming a real problem in our group chat. We need to explain it to every new user. Users don't expect this behavior, please do something about it. Part of the information does not reach the destination and the only indicator are there small dots that are easy to overlook.

There must be a better way to handle this. If you really can't stuff more text into the bubble (I still don't get what would happen if you did), maybe you could automatically split long messages into more bubbles. Or at least add an "expand" option as suggested by tyler71....

**Comment by subpub** [comment]
It also affects when irc server sends a looong initial join message (you may argue who would read that. But what if)

**Comment by Darkspirit** [comment]
Imagine you send some long personal messages to a quiet and insecure friend you miss and discover weeks later that your messages have been cut off with `...` as if you have been an angry or super disappointed. It happened. :-/ (Severity: As long this bug exists there should be a warning in Readme.md and the app store to not use this app for the most relevant conversations one can have.)

**Comment by ToEatFreshBabies** [comment]
Why cannot long messages be fragmented into sequential [numbered] messages to avoid truncation?

Why accept a long message without indicating prior to sending it would be truncated?

**Comment by Darkspirit** [comment]
.

**Comment by Darkspirit** [comment]
.

**Comment by iNPUTmice** [comment]
If we ever do a rewrite it will be fixed automatically due to the use of the framework libraries. But implementing this in the current code is not possible.

**Comment by Nemris** [comment]
@iNPUTmice I have a custom fork of Conversations for personal uses. I'd like to work on the issue to see what happens, but narrowing down the logic responsible for cutting the message is going over my limited Java-Fu.

Could you show me where said logic is, if it's not a problem?
