### ISSUE TITLE
In irregular intervals conversations is offline and does not automatically reconnect

### ISSUE THREAD

**Issue by tapete** [iNPUTmice/Conversations#3047]
#### General information

* **Version:** 2.2.1
* **Device:** Huawei Y6 SCL-L21
* **Android Version:** eg Android 5.1.1
* **Server name:** self hosted (dynamic IP)
* **Server software:** prosodi 0.10
* **Conversations source:**  F-Droid

#### Steps to reproduce

In irregular intervals (perhaps 1/week) my device is shown offline to other users and I don't get push messages. In this case conversations stays offline until the next time I use it. Then it reconnects and everything is fine.

I tried:
- battery optimization set to normal
- exclude conversations from battery optimization
- activate foreground service in conversations settings

#### Debug output

No abnormal log data found

**Comment by licaon-kter** [comment]
If app from F-Droid, you do not have Push messages anyway

Any logs? Eg. Turn screen off while logging, wait a bit, send message....

**Comment by tapete** [comment]
Perhaps push message is the wrong word (sorry, I am new to android). I mean the android system messages which pop up at the top of the home screen.

The prosody log does not show abnormality. 
The conversations log I did not find yet, sorry, can you help me regarding this?

**Comment by licaon-kter** [comment]
_Notification of new message_, you did enable "heads-up" too in app settings, right?

For the log, you need a PC and a USB connection, then `adb logcat ...`, use your favourite search engine to find info about this.

**Comment by tapete** [comment]
Heads-up messages are enabled and work when conversations is connected. The only problem is that conversations sometimes disconnects which occurs rarely like 1 time per week.

Sorry, I would love to help to improve the app but writing logs this way is beyond my capabilities.

**Comment by thevietnamm** [comment]
i have the same problem , i disable optimization of all my device system chek on the foreground , and the problem persist

**Comment by licaon-kter** [comment]
@thevietnamm Device? Android version?

**Comment by thevietnamm** [comment]
i have 8.1 but i try this in andorid 5.0 6.0.1 and 7.1 and it the same result, sorry my bad english im from colombia.

**Comment by licaon-kter** [comment]
@thevietnamm Device? This happens (ex. only) once a week for you too?

**Comment by thevietnamm** [comment]
NO, it does not happen to me randomly it's as if for some reason the app's background stops working

**Comment by tapete** [comment]
"NO, it does not happen to me randomly" When does it happen? Every time you swipe of conversations?
"it's as if for some reason the app's background stops working" This is the same for me.

**Comment by tapete** [comment]
I just took a look at the android app settings. When conversations works fine, a conversation process is listed in the list of "active apps". When conversations is offline, the list of active apps does not show the process. So obviously the background process crashes or was shut down by android.

**Comment by thevietnamm** [comment]
@tapete Exactly what happens if there are no conversations after a while it blocks conversations.

**Comment by iNPUTmice** [comment]
What you are experiencing could be [App Standby]( https://developer.android.com/training/monitoring-device-state/doze-standby#understand_app_standby) that kicks in if you haven’t use Conversations in *a while*. Possible work arounds are enabling the foreground service from the expert settings or switching to the Play Store version with push support.

**Comment by tapete** [comment]
I think App Standby is the answer to this problem. Foreground service in the expert settings was already activated. As I have no Play Store, I think I will need to use conversations more often that no standby occurs.

**Comment by brighterness** [comment]
> App Standby
@iNPUTmice 

Could you envision a way to use Tasker [[app](https://tasker.joaoapps.com/)] to overcome that?

**Comment by licaon-kter** [comment]
@brighterness Foreground service ON will be default in 2.3.0

**Comment by zz-ha-dum** [comment]
could app standby be circumvented by Tasker briefly giving Conversations focus?

@iNPUTmice

**Comment by zz-ha-dum** [comment]
@brighterness

maybe periodically giving Conversations focus?  

screen off
wait some time
launch conversations
home

cooldown sometime
