### ISSUE TITLE
Quote non-text messages

### ISSUE THREAD

**Issue by contrapunctus-1** [iNPUTmice/Conversations#3125]
Contacts coming from WhatsApp miss the ability to quote messages which aren't just text, e.g. files, audio, video, and images. It'd be nice to have this.

**Comment by zz-ha-dum** [comment]
stanza analog of html anchor?

**Comment by manchito** [comment]
Me and some friends are already working on this. Hopefully we'll come out with a generic way of quoting messages based on XEP-0367.

Up until now you can indeed quote. The logic is mostly already there and we are busy implementing the UX and solving a couple of bugs.

We'll try to keep this issue updated as we go.

**Comment by benjaminbischoff** [comment]
Is there something new about that feature?

**Comment by manchito** [comment]
Here are some teaser pics ;)

![01](https://user-images.githubusercontent.com/7458030/48316893-bf095280-e5e9-11e8-931c-9b9222860b34.png)
![02](https://user-images.githubusercontent.com/7458030/48316895-c29cd980-e5e9-11e8-9615-3aebadf0c7d3.png)

Feel free to test the [branch](https://github.com/olomono/Conversations/tree/message-quotation) if you want.

We plan to make the PR soon

**Comment by licaon-kter** [comment]
@manchito what do ChatSecure/Dino/Gajim/Legacy users see?

**Comment by contrapunctus-1** [comment]
Nice work, great to see this coming along 😃 A question - what does tapping the quoted file do? Opening the file might be nice, but that is inconsistent with the inline audio player. Maybe tapping the quoted file could jump to the original message with the file?

**Comment by manchito** [comment]
@licaon-kter 

When Quoting text, clients not supporting XEP-0367 see it as before:

`> Original text`
`Comment`

With files & co. they see the URI:

`>  aesgcm://...`
`Comment`

`> geo:52.517036,13.388858`
`Comment`

@contrapunctus-1 

> Opening the file might be nice, but that is inconsistent with the inline audio player. Maybe tapping the quoted file could jump to the original message with the file?

The latter is the current behaviour

**Comment by horazont** [comment]
@manchito Could you please outline how and which XEPs you use? XMPP is a federated system after all, it would be great to have an opportunity to discuss this feature, standards-use-wise, before it’s getting merged in this (rather influential) client.

Ideally, some discussion on the [standards mailing list](https://mail.jabber.org/pipermail/standards/) would be great.

(I have a particular interest in this, since "rich" quoting somewhat overlaps with reactions, for which I have some idea, too.)

**Comment by manchito** [comment]
@horazont we use [XEP-0367: Message Attaching](https://xmpp.org/extensions/xep-0367.html)

To keep compatibility with non-standard clients though, which still use the ">" method, Conversations sends _both_ the XEP-compliant reference _and_ the legacy quotation.

`<message to='antonio@milan.lit/ship' from='prospero@milan.lit/island id='RgEGnjqy'>`
`  <attach-to id='oldmessage1' xmlns='urn:xmpp:message-attaching:0'/>` _XEP-0367_
`  <body>`
`    > aesgcm://...` _legacy_
`    Nice picture!`
`  </body>`
`</message>`

A standard client then should strip out the legacy quotation if it matches the content (or the file/geo URI) of the referenced message. At least that is what we do. Hopefully this won't be necessary when most of the clients support XEP-0367. Without that addition they just see the comment as a regular message.

**Comment by horazont** [comment]
Any reason why you chose Message Attaching over References? https://xmpp.org/extensions/xep-0372.html

I think Attaching *might* lead to suboptimal display in some existing clients. The intent of Attaching was e.g. a bot which replies to and annotates a message, while References was made more for use-cases like yours.

(I heard of clients implementing some stuff based on Message Attaching, but I don’t know which clients and which stuff off the top of my head, I’ll try to figure that out.)

**Comment by SamWhited** [comment]
> I think Attaching might lead to suboptimal display in some existing clients. The intent of Attaching was e.g. a bot which replies to and annotates a message, while References was made more for use-cases like yours.

This seems like the exact same thing as what you just said (except it's not a bot). Message Attaching was actually used for this originally too, so I think it would be fine. If another client displays things slightly differently, it will still get the point across that one message was referencing another.

**Comment by horazont** [comment]
@SamWhited 
The idea of attaching is that the attached message might be shown out-of-order right below the target message. This might be confusing and unintended. Sorry, I didn’t make the difference I expect clear in my previous post.

**Comment by SamWhited** [comment]
> The idea of attaching is that the attached message might be shown out-of-order right below the target message.

Exactly how a client displays it shouldn't matter; if it does I probably need to tweak that in the XEP to make it less strict.

**Comment by horazont** [comment]
Showing a message with a quotation out of order would be not-so-great. While other message attachment use-cases such as bots which add meta-information profit from this feature. Likewise, attachments might very well be hidden by default et cetera et cetera. It is semantically very different from a reference/quotation in my opinion.

**Comment by SamWhited** [comment]
> Showing a message with a quotation out of order would be not-so-great.

Yah, I suppose that's fair. Maybe a message could be considered an attachment if it's already in the same thread? Or maybe attaching just needs to be made more specific to the bot use case and something similar be created for quotes but with that specific idea in mind. Or maybe an attribute could be added to attachments with an enum of reasons so the client can decide how it wants to display it? Eg. `use='followup'` or `use='quote'` or similar?

**Comment by maanAlbalkhi** [comment]
@horazont
> Any reason why you chose Message Attaching over References? https://xmpp.org/extensions/xep-0372.html

Message Attaching fits well our use case of commenting a message by its id. We do not see References supporting this. The nearest one would be [3.4](https://xmpp.org/extensions/xep-0372.html#usecase_previous), but it does not allow a body and does not specify the way a message can be uniquely identified. Furthermore, even if 3.4 covered our use case other use cases outside our scope would still have to be implemented in order to be compliant with the whole XEP.

Additionally, Message Attaching seems simpler and fully specified while References seems more like a Proto-XEP than a finished specification. 

It's true that the terminology used in Message Attaching is a little misleading when it comes to referencing a message, but the logic is right. The small change @SamWhited proposed would solve the issue with the different display possibilities and we could add it right away to our implementation. We would then use `use='quote'`.

**Comment by maanAlbalkhi** [comment]
We renamed the branch to [message-attaching](https://github.com/olomono/Conversations/tree/message-attaching).

**Comment by SamWhited** [comment]
@maanAlbalkhi I tried to ask via XMPP but you're rejecting messages from strangers, FYI:

I'm drafting an update to Message Attaching that includes a "type" element that can be set to either "followup" or "reference". A value of "followup" means the traditional behavior: eg. a bot might be sending more info about a link that an end user sent previously and clients may choose to re-order the messages to place the followup after the original message, or display it in some other way. A value of "reference" means that the messages should not be reordered and clients may choose to display a link to the original message, or display it as a quote, etc.

Does this cover your use case? Anything else you feel is missing? I'll also try to put in a few more security considerations and fix some poor wording. Suggestions for the terminology are welcome if those don't sound good too.

**Comment by cmrd-senya** [comment]
Hello!
Is it possible to make the reply functionality support [XEP-0201](https://xmpp.org/extensions/xep-0201.html) -- threads? When you reply to a message you can pass the thread identifier in your message stanza. When having a thread identifier in a message every party can embed the original message with all the contents (including attachments) to the response message.

This approach has some positive side effects, like when you're communicating with some software-driven   entity (a bot) this entity can identify the original message too.

**Comment by maanAlbalkhi** [comment]
@SamWhited 
> Does this cover your use case?

Thank you for the update. The value *reference* would fit our case.

> Anything else you feel is missing?

Currently, we would just suggest the integration of legacy quotations.

**Comment by maanAlbalkhi** [comment]
@SamWhited 
> I tried to ask via XMPP but you're rejecting messages from strangers

Sorry for that. I wrote you directly.

**Comment by SamWhited** [comment]
> Currently, we would just suggest the integration of legacy quotations.

What are legacy quotations?

Also, the message you sent me was OMEMO encrypted but I don't use OMEMO and can't read it. Also I still can't reply, it says you're rejecting message still (and I don't give presence subscription to people I don't know for the most part, sorry).

**Comment by Shura0** [comment]
Hello.
don't you think that sending message back as attach is silly? Partner have the message already, so it would be better to point him what message do you mean. It would be ideal with XEP-0201 Threads. And when partner gets message with link to other one (with thread feature) he can stylish message view on his side as he want.

**Comment by selurvedu** [comment]
Bump

**Comment by iNPUTmice** [comment]
This is not feasible from a technical perspective before the rewrite.

**Comment by stevenroose** [comment]
Classic example of a new contributor, @manchito, wanting and trying to do some work, even searching for fitting XEPs, to then be scared away by veterans because he chose the wrong XEP because there's multiple XEPs to do various things and some other client already has some other implementation of said XEP.

How can we improve or get rid of this kinds of stories? 3 years ago a much wanted feature was implemented but discarded based on dubious and honestly not very constructive feedback.

**Comment by iNPUTmice** [comment]
The decision not to merge this had nothing to do with the XEP. I don't
recall what XEP was being used but if it was 'the wrong' one that could
have very easily been fixed.

The sole reason is that the architecture of Conversations currently just
doesn't allow for this. The PR is an unmaintainable nightmare. Which isn't
the fault of the contributor but mine for not considering maybe having to
reference other messages.
