### ISSUE TITLE
Feature Request: Function to share the message archive encryption key with new clients

### ISSUE THREAD

**Issue by allo-** [iNPUTmice/Conversations#3129]
When you sign in with a new device (or when it were offline for some time), the OMEMO encrypted archived messages show up as "cannot be decrypted".

It would be nice to have a function "ask other client for decryption key", which either transfers the actual encryption key for the content with the new client (i.e. encrypted using OMEMO so it is tranfered securely) or better to ask the other client to re-upload the archived messages with an additional key. 
The other client could ask for confirmation using the request information like "Device X requests the chat logs from May 1 to May 23. [send] [do not send] [list messages]".

**Comment by zz-ha-dum** [comment]
Like the matrix client Riot?

**Comment by allo-** [comment]
Anything which allows to share older logs with new clients will do. As they are stored in MAM with the keys of other clients, it seemed useful to share the encryption key with the new client. Not for new messages, but for reading older ones.

On the other hand, there is probably no big problem when two clients are using the same key.  
This could even be useful for https://github.com/siacs/Conversations/issues/2830, as the (same) key of the offline device is refreshed by the device which is online all the time.

But this issue should not be centered around fixing both bugs. If it is easier/better to implement this issue e.g. by sending the logs via an encrypted channel or sharing the symmetric keys instead of the OMEMO key, the solution does not need to solve #2830 at the same time.

For key distribution or setting up an encrypted channel, showing a QR code seems to be safe solution.

**Comment by licaon-kter** [comment]
@allo- OMEMO....can't decode twice...

**Comment by kousu** [comment]
The point of OMEMO is that there is one key per device and you cannot swap them around, but that you can have multiple keys for multiple devices. Sure you *could* share if you dug into the databases and knew what you were doing, but it's not a supported use case. Breaking this assumption will break the security in a lot of subtle ways in lots of cases.

**Comment by allo-** [comment]
My point isn't about sharing the device encryption key, but about syncing messages.

I would rather not share a OMEMO key (I guess this would not work because of PFS anyway), but the derived key used for the actual message encryption, so other clients can (only) decrypt the archive.

Another option could be to sync the actual messages between different clients. I think of a UI and protocol like this:
- Both users start sync mode
- The sender shows a PIN
- The receiver enters the PIN
- A session key is generated (e.g. using DH) and verified using the PIN
- The receiver requests one or more ranges that are missing from his archive, e.g. ``20190301-20190520``, ``20191001-`` (missing end means send everything up to now).
- The sender sends the requested messages
- The receiver fills up his archive with the received messages

Especially for older messages this sync would be useful anyway, as many servers store only a few weeks of archived messages, so sharing the key alone would only bridge some gaps and do not allow to fill up others. On the other hand, sharing the key would be a solution that does not require that complicated new protocols and UIs and allow for at least the last few days, that are directly visible after logging in on a new device.

**Comment by licaon-kter** [comment]
Backup covers one case, this might be interesting for some.

**Comment by iNPUTmice** [comment]
Device to Device message transfer (securely) is a rabbit hole that I currently don’t want to climb into. Once `omemo:1` is implemented, stable and well tested we might revisit this.
