### ISSUE TITLE
Unread msgs notification reminder

### ISSUE THREAD

**Issue by xeverse** [iNPUTmice/Conversations#3137]
Repeat the notif sound-ringt
wnenever there are unread msgs.

**Comment by licaon-kter** [comment]
Some OEMs have this as a system feature.

**Comment by brighterness** [comment]
This too can be accomplished with another app:  [Light Flow](https://play.google.com/store/apps/details?id=com.reactle.android.lightflowuniversalkey&hl=en_US)

Fire notification (visually, sound, vibration, LED, in any combination).

Now I am a Light Flow apologist.  Noice.  Andy's app plays very  nicely with Conversations.

**Comment by contrapunctus-1** [comment]
Missed Notifications Reminder (Periodical sound reminder for missed notifications) - https://f-droid.org/app/com.app.missednotificationsreminder
