### ISSUE TITLE
[FR] Separate private message window

### ISSUE THREAD

**Issue by SoyaLeaf** [iNPUTmice/Conversations#3142]
Private message and group chat information are mixed. It is very messy and inconvenient to view.
Maybe a new window can be provided to send a private message. :-)

**Comment by Echolon** [comment]
Like Dino does already.

for me it would be enough if the PMs are shown differently

**Comment by licaon-kter** [comment]
@Echolon what happens when the user/contact leaves the MUC? This is confusing...it looks like an 1:1 but it's not since the contact is not in your roster

**Comment by Echolon** [comment]
Yes, I dont like it, too actually.

I would prefer a way to better present in the chat what is private and what not. even so, if you receive a private message, conversation should directly offer the other to switch to PM mode too. Problem is that lots of users dont get what PMs are. then they just answer normally, which can be embarrasing or so I think

**Comment by SoyaLeaf** [comment]
> what happens when the user/contact leaves the MUC?

Disable EditText, and only show history records.I think this will be great.
