### ISSUE TITLE
OpenFire/Conversation file upload issue

### ISSUE THREAD

**Issue by teymoori** [iNPUTmice/Conversations#3149]
#### General information

* **Device:** OnePlus 
* **Android Version:** Android 8
* **Server name:** OpenFire
* **Server software:** HTTP file upload
  
Hi
I am using last version of Conversation and Openfire server with ubuntu 16
I installed HTTP file upload plugin on open fire
when i want to upload file to server, i get this 2 lines error from Conversations
i disabled encryption on file uploading. i set http file upload limit size with unlimited value on openfire side. whats problem? 

`D/conversations: server did not report max file size for http upload
could not find file to upload - /storage/emulated/0/Conversations/Media/Conversations Images/26d2be7d-16d4-45f1-8fff-b233bd66b55a.jpg (Permission denied)`

**Comment by licaon-kter** [comment]
Any file fails like this? You've granted "storage permissions" ?

**Comment by teymoori** [comment]
I granted that permission to Conversation

**Comment by myjibit** [comment]
which server works better with Conversations? OpenFire or Ejabbered?
i want implement p2p messaging with file upload for 50 users

**Comment by licaon-kter** [comment]
@myjibit I've setup both Prosody & ejabberd.

**Comment by myjibit** [comment]
problem not resolved
i get error on uploading to openfire
`server did not report max file size for http upload`
i disabled encryption but receive:
`http upload failed SSL handshake aborted: ssl=0x73086fa7c0: I/O error during system call, Connection reset by peer`
