### ISSUE TITLE
Feature request: Disable the LED in Silent/Quiet Hours mode

### ISSUE THREAD

**Issue by Bjoem** [iNPUTmice/Conversations#3154]
#### General information

* **Version:** 2.2.8+fcr
* **Conversations source:** F-Droid

Please add an option to disable the LED in the Silent/Quiet Hours mode, so that the notification LED does not blink the hole time while I'm asleep.

**Comment by licaon-kter** [comment]
Notifications from other apps don't trigger the LED?

**Comment by licaon-kter** [comment]
Not sure.

Also it's the Quiet setting in Conversations or in Android, or both?

**Comment by Bjoem** [comment]
If I turn the Notification LED in the Options menu of Conversion off, then the LED won't blink on a received message. That's the behavior I'd like to have in the time frame of the Silent/Quiet Hours mode (the option in Conversation, I don't  know how it's called in English)

**Comment by brighterness** [comment]
I prefer the LED in quiet hours.  If it's optional I will keep it enabled.

I use [Light Flow](https://play.google.com/store/apps/details?id=com.reactle.android.lightflowuniversalkey&hl=en_US) for most every notification.  Quiet Hours does not trigger its filter match.

**Comment by Bjoem** [comment]
> If it's optional I will keep it enabled.

And you could, if it where optional, which it isn't, that's why i'd asked for it.

**Comment by brighterness** [comment]
>  i'd asked for

If there is a change in functionality as a result of your request my request is to retain both. 

Have you tried Light Flow?  There is a free version.  Well.. there was.  I will not in good conscience recommend anyone install an app that's the adware flavor of malware.  

1. Disable LED notification in Conversations
2. create a new configuration for Conversations
2b.  either simply for the app fired notification
2c.  or finer grained for a particular contact.  For example all communication from my youngest brother is marked pink.  the flash pattern delineates the channel of communication.

**Comment by Bjoem** [comment]
> Disable LED notification in Conversations

That's the like given up.

> Have you tried Light Flow?
2 create a new co...

I don't want to, because:
- i would like to minimize the use of closed source apps.
- i don't want another app running.

What i imaged was an Checkbox in the main configuration menu, somewhere near the "LED Notification" that anyone can trigger on or off.
Like:
If (Respect_Silent_Hours_for_LED_Notification.Checked = True) then No LED between 22:00-07:00* 
else if (Respect_Silent_Hours_for_LED_Notification.Checked = false) then Always use the LED (Standard)

*whatever the user defined in his silent hour

**Comment by 9662** [comment]
Which Android version? You have exactly what you are looking for at least from 7 and up in the Android settings.

**Comment by 9662** [comment]
> Can you point me to the menu?

On me phone it's under Settings → Sound → Do not disturb → Block visual disturbances

Use “Settings → Sound → Automatic rules” to configure when you want silent mode on/off.

**Comment by Bjoem** [comment]
> On me phone it's under Settings → Sound → Do not disturb → Block visual disturbances
Use “Settings → Sound → Automatic rules” to configure when you want silent mode on/off.

That is a great way to turn off everything and the options are really nice. 
But I just want conversation to not use the LED (in a configurable time frame), other application should be still be able to use the LED.

**Comment by 9662** [comment]
Then what you probably want is an application that filters what notifications do get through at certain configurable times. I do not know if such a solution already exists.

As a requirement, IMHO this probably falls way outside the scope of Conversations.

**Comment by Bjoem** [comment]
> probably falls way outside the scope of Conversations.

Ok lets try this again:
- Conversation already has an option to be **silent on a configurable time frame**.
- Conversation already has an option to **turn the the LED usage on an off**.

All I want is to **combine them**.

I'm sorry if that wasn't easy to understand, didn't seams like witchcraft or bad voodoo to me.
