### ISSUE TITLE
Remember playback position of a voice message

### ISSUE THREAD

**Issue by alexara** [iNPUTmice/Conversations#3157]
#### General information

* **Version:** 2.2.8
* **Device:** Samsung Galaxy S4 Mini
* **Android Version:** LineageOS 14.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Play back a voice message
2. Do one of the following things:

* Close the conversation
* Open the contacts details / settings page etc.
* Open an image from the current conversation
* Play back any other voice message

The voice message will stop playing at this point.

3. Play back the voice message again

#### Expected result

The voice message starts to playback at the position where it was stopped.

#### Actual result

The voice message starts from the beginning.

**Comment by licaon-kter** [comment]
Yup, nice addition
