### ISSUE TITLE
[Feature Request] More efficent barcode sharing

### ISSUE THREAD

**Issue by tyler71** [iNPUTmice/Conversations#3162]
#### General information

* **Version:** eg 2.2.9+pcr

#### Steps to reproduce

1. Long press on QR barcode scanner button in contacts / existing conversation list

#### Expected result
Show the 2d barcode for the account. It is likely the majority of users will have one account. For users with more then one account, long pressing would reveal a choice for which account to reveal

[Multiple account barcode](https://i.imgur.com/yRgMvka.png)
![Multiple account barcode - small](https://i.imgur.com/FtFaLiK.png)

#### Actual result
Tool tip of
> Scan 2D Barcode

Currently to share a barcode you have 2 paths to follow.
1.
* Tap on a existing conversation you are having with someone
* Long press on your own avatar

Does the user have existing conversations / buddies?
Catch-22 for new users with this route. To *add* a friend, you must have be having a conversation with a *existing* friend.
To share in person you must open a conversation with another user. This conversation is in the background while sharing the 2d barcode and tapping anywhere reveals the conversation. This could reveal private conversations accidentally.

2.
* Manage Accounts
* Tap on Account you want to show barcode of
* Tap share icon
* Share as 2d barcode

This is a very buried action. Scanning is at the very front of the app.
___

I see a more fluid on-boarding to be
* Install
* Login
* Long press on QR scan while the other user taps on QR scan. 
* Scan.
* Repeat vice versa
This feels more intuitive (to me) since it becomes a single location for adding / verifying friends.

**Comment by licaon-kter** [comment]
How do you discover this exactly if you don't know about it?

**Comment by dennisguse** [comment]
I like the idea.
Instead of press (scan) vs. long-press (present), why not use a menu as it is used for the attachments?

**Comment by brighterness** [comment]
> How do you discover this exactly if you don't know about it?

How can you discover something you already know?

**Comment by licaon-kter** [comment]
@brighterness What do I know exactly?

**Comment by brighterness** [comment]
> What do I know exactly?

I am to know the unknown and everything you know?

@licaon-kter 

I assumed your initial discovery comment was made in jest.

**Comment by licaon-kter** [comment]
@brighterness No, long press actions are not "obvious"

**Comment by tyler71** [comment]
When I didn't know anything about it, I tried long pressing after pressing it because a scanner was unusual to have nothing to scan and I thought it would have "more options".
It's not like there's anything else in that "page" of the app that appears to be related to it.

**Comment by herrwusel** [comment]
Can confirm tyler71. Didnt know where to find my own barcode and tried to long press the icon. It might be a solution to make 2 buttons.

**Comment by contrapunctus-1** [comment]
Presenting one's own QR code definitely takes too many steps, and the QR code symbol seems widely-recognized enough to justify removing the tooltip.

**Comment by tyler71** [comment]
Is it possible to have the share barcode inside the scanner?
This would
* Avoid long-press
* Maintain a single button on the main page
* Have easy discoverability

[![](https://i.imgur.com/hMtLc4z.jpg)](https://i.imgur.com/ARVOitw.jpg)
