### ISSUE TITLE
Feauture: Keep playing audio on screenlock

### ISSUE THREAD

**Issue by paskalito** [iNPUTmice/Conversations#3164]
So that one can listen to longer voice messages without having, to stop the screen from locking in one way or the other. and also save quiet some energy (for 30 min messages i suppose)

**Comment by unicorntaco** [comment]
Could be used for Push To Talk also :wink: 

https://github.com/siacs/Conversations/issues/1239
https://github.com/siacs/Conversations/issues/1234

PTT is an extant XEP

audio/video calls is attempted in this hybrid
https://github.com/cmeng-git/atalk-android

**Comment by tuxayo** [comment]
Maybe not that much a dup? #2733 is about being able to hear long message (either by keeping screen on or by keeping playing while locked).

This one is about being able to lock the screen during play to save energy.

**Comment by tuxayo** [comment]
Another reason for this request: lock the screen to be able to put the phone in a pocket without risking unintended actions.

**Comment by licaon-kter** [comment]
This wii

**Comment by Echolon** [comment]
Thanks! works like a charme for me!

**Comment by paskalito** [comment]
this issue is not fully solved, but for current stat is:

As in Conversations 2.8.1
- screen is Prevented from locking - thus audio playback isnt aborted (hudge improvement)
- playback still stops when locking device. (so no real way to save energy or not hoding your device in your hand while on the go)
- switches to earpiece now. which blacks out screen. but then there is no volume control #3705 and the screen is not locked to unnatended actions can still occur after playback as @tuxayo pointed out.
