### ISSUE TITLE
Cannot connect in WLAN

### ISSUE THREAD

**Issue by holgis** [iNPUTmice/Conversations#3170]
#### General information

* **Version:** 2.2.8+fcr
* **Device:** Xperia Z1 Compact
* **Android Version:** Android 8.1 LineageOS
* **Server name:** trashserver.net
* **Server software:** prosody 0.10
* **Conversations source:** F-Droid

#### Issue

When phone is connected to a working WLAN (other internet traffic working fine) Conversations is unable to connect the account but shows "Connecting ..." forever. (Maybe related to issue #2870)

I found out that if you disable WLAN for some seconds and wait until Conversations is connecting via mobile network, it will still stay connected even if you enable WLAN again.

Issue can be solved by switching off "Developer options" -> "Mobile data always active".

Problem for user is that Conversations does not show that account is not connected but still tries to connect.

Same problem also occurs on a Google Nexus 5X with Android 8.1 stock.
 
#### Steps to reproduce

1. Use a phone with Android 8.1 and "Developer options" -> "Mobile data always active" enabled
2. Disconnect your account in Conversations "Manage accounts" -> "Disable all accounts"
3. Make sure you are connected to a working WLAN
4. Try to connect your account "Manage accounts" -> "Enable all accounts"
5. See message "Connecting ..."
6. Switch back to main screen in Conversations
7. See that there won't be any message that Conversations is not connected

#### Expected result

1. Conversations can connect via WLAN when "Developer options" -> "Mobile data always active" is enabled on a Android 8.1 system
2. Conversations shows error message if it cannot connect to server after a defined period of time

#### Actual result

1. Conversations does not succeed to connect via WLAN when "Developer options" -> "Mobile data always active" is enabled on a Android 8.1 system
2. Conversations does not shows any error message if it cannot connect to server

#### Debug output

Output of adb logcat
[logcat.txt](https://github.com/siacs/Conversations/files/2362601/logcat.txt)

**Comment by Rallyefahrer** [comment]
Maybe same issue as #3139

**Comment by holgis** [comment]
> Maybe same issue as #3139

I'm not sure. My guess is that this issue is related to Android 8.1 since the problem just came up after an update to that version but was not there before. Issue #3139 is on Android 7.1.2.

@Rallyefahrer can you check if disabling "Developer options" -> "Mobile data always active" is solving your issue as well?

**Comment by Rallyefahrer** [comment]
Hey @holgis, "Developer options" -> "Mobile data always active" is already disabled. Never enabled this. Issue is still there, with the same symptom as your issue ("Conversations is unable to connect the account but shows "Connecting ..." forever")

**Comment by StraToN** [comment]
Same symptoms as well, but no option enabled in Developers options either. Conversations is unable to connect over WLAN, while it succeeds over mobile data. I've been wondering if this could be a firewall problem though, but explicitely opening XMPP ports didn't change anything.

**Comment by licaon-kter** [comment]
@StraToN logcat says what?

**Comment by StraToN** [comment]
@licaon-kter Logcat says these 3 lines:
`01-22 09:14:21.756 31811  9251 D conversations: julian.murgia@jabber.fr: xml parser mishandled SocketException(Socket closed)
01-22 09:14:21.756 31811  9251 D conversations: julian.murgia@jabber.fr: not changing status to OFFLINE because thread was interrupted
01-22 09:14:21.756 31811  9251 D conversations: julian.murgia@jabber.fr: not force closing socket because thread was interrupted`
