### ISSUE TITLE
QR-Code to save initial login credentials and host

### ISSUE THREAD

**Issue by dadosch** [iNPUTmice/Conversations#3180]
So instead of typing in Username and Password, you would simply scan the QR-Code once from your service provider and the login would be more hassle-free.

To be more precise, especially when Conversations is used by less-experienced users it would make life easier for them (kids in school/workers in a company). The barcode would be shown only very shortly.

As far as I looked, there is no standard for encoding Username and Password in a QR-Code, but we could base64 encode the password and username, and then make a text/json out of it or something similar.

**Comment by wiktor-k** [comment]
Username could be encoded as a usual XMPP URI (e.g. `xmpp:user@example.com`) and password could just be added as a parameter. So scanning QR code that contains `xmpp:user@example.com?password=hunter22` would provide all necessary information.

**Comment by dadosch** [comment]
regarding the password: there are so many special chars (Ä ß æ ç ة ?) so I think at least [URL-encoding](https://en.wikipedia.org/wiki/Percent-encoding) the password would be a good idea, wouldn't it? Like it's done [here with the message](https://xmpp.org/extensions/xep-0147.html#actions-message)

**Comment by wiktor-k** [comment]
Well, yeah, URL-encoding is a must when using URIs so I just assumed that :)

By the way this issue seems like not much implementation effort (add a button, invoke scanner, fill in username and password fields), maybe someone could contribute a PR?

**Comment by SoyaLeaf** [comment]
It's dangerous,I don't think it's a good idea to save the username and password in a qrcode. 
it requires the server to have such features but can't be done on the client only.

Maybe it should work like google OAuth...

**Comment by wiktor-k** [comment]
> It's dangerous,I don't think it's a good idea to save the username and password in a qrcode.

Why? This is a case of pre-provisioned account. Even TOTP secrets are served in qrcode in "plain text".

Actually I think it's more secure than letting the user choose a password because with QR code you can easily generate a high entropy password and asking the user to re-type `bqRNeeFc8ODc1ZU74wr3yupTmf4nWsdR` wouldn't work at all.

> it requires the server to have such features but can't be done on the client only.

Client, in this case Conversations, would just grab the password from a QR code and paste it in the password field.

> Maybe it should work like google OAuth...

At the end of the day the OAuth flow just returns a token that serves a role of the password. The only difference is when the Google account is 2FA protected but even then, you can 2FA login on your browser and see the QR code there that would contain the XMPP password. And the password could be auto-generated by the server.

Another alternative is Client Certs, Conversations supports this but users would have to have lock screen enabled at all times.

**Comment by dadosch** [comment]
> It's dangerous,I don't think it's a good idea to save the username and password in a qrcode.
> it requires the server to have such features but can't be done on the client only.

My intention is that people don't have to type in their password on a screen display because they would either choose a simple, short, insecure password from the beginning or give up when typing in a long secure pre-provisioned one.

People don't have to type in their password all the time, usually once when setting up.

**Comment by SoyaLeaf** [comment]
But if someone gets the user's QR, he can log in and do whatever he wants,
and we are not sure that the user will not lose his QR.

**Comment by c3431936** [comment]
> Another alternative is Client Certs, Conversations supports this but users would have to have lock screen enabled at all times.

Do you say that I can login to a xmpp account using a certificate instead of using a password?

Does well known xmpp server software support this without big changes?

**Comment by wiktor-k** [comment]
> Do you say that I can login to a xmpp account using a certificate instead of using a password?

Yes, that's what I'm saying.

> Does well known xmpp server software support this without big changes?

I guess every good server does? Look for `SASL EXTERNAL`. For example [Prosody has a module](https://modules.prosody.im/mod_auth_ccert.html), ejabberd has it [built-in as `c2s_cafile`](https://docs.ejabberd.im/admin/configuration/#global-options).

Do note that only in TLS 1.3 client cert is sent encrypted. So if you're using TLS 1.2 or lower the client cert is sent in the clear (that is equivalent to sending username in plaintext). It's not bad from security point of view but it may impact your privacy.
