### ISSUE TITLE
[FR] Only playback voice messages when earpiece is activated or otherwise demanded

### ISSUE THREAD

**Issue by alexara** [iNPUTmice/Conversations#3185]
#### General information

* **Version:** 2.3.0-beta2
* **Conversations source:** self build (latest HEAD)

If you playback a voice message it will start playing immediately on the speakers until hold your phone next to your ear. 
Once you put it away from your ear again, it will continue playing loud.

So, there's no possibility to definitely only hear your voice message in private (unless you got headphones plugged in).

To solve this issue, I would suggest to play the voice message only if the phone is put to the ear OR if the 
user confirms to play it loud on the speakers by pushing a new toggle button ![screenshot_20180919_210008](https://user-images.githubusercontent.com/13819719/45775092-0f4ddf00-bc4f-11e8-9ad1-74fe312d8f94.png), which could be placed next to the play button. 

The process would be the following: 
* Press play to activate the voice message
* Put it to your ear to start listening on the earpiece OR also press the ![screenshot_20180919_210008](https://user-images.githubusercontent.com/13819719/45775092-0f4ddf00-bc4f-11e8-9ad1-74fe312d8f94.png) to start listening on the speakers

**Comment by stevenroose** [comment]
Alternatively, the play button could just have a 3-sec delay or so...
