### ISSUE TITLE
[UI] Advanced encryption choice --> Easy encryption choice

### ISSUE THREAD

**Issue by Echolon** [iNPUTmice/Conversations#3195]
Hi,

I already suggested this to other clients, too: Most users (ok, maybe not absolutely in Conversastions) can neither diffentiate between all the encryption choices nor practically handle anything else than OMEMO really. So I would like to suggest, to switch the interface choice from

Unencrypted
OMEMO
OpenPGP

to

Unencrypted
Encrypted (OMEMO)

For all advanced users OpenPGP should be only added by opt-in from expert settings (!). Yes I know Daniel don't like Expert Settings, but still here is my suggestion. Feel free to change title and discuss.

Cheers

**Comment by wiktor-k** [comment]
I like the idea. OpenPGP really is for experts (even the omemo comparison page says so), but with OMEMO being enabled by default on Conversations do people actually click it and wonder what is it for?

**Comment by Echolon** [comment]
@wiktor-k  Let's say it like this: One of the first questions I get from friends usually is "What is OMEMO?" - Furthermore they don't even recognize that the chat is encrypted (which is mostly good in the first place). However, if the context offers them to decide between 

Unencrypted <--> Encrypted (Name of encryption) 

it should be much easier to understand what is basically happening or what it is for.

PS: Recently, a friend was asking me about why I think it is important to encrypt messages. I started talking and explain and after 5 minutes she came up with the question: "But what is encryption acutally?" - Just in case you needed an impression of the cosmic distances we are trying to bridge ;)

**Comment by zz-ha-dum** [comment]
Privacy: Human Right, bulwark of individuality 

Encryption: a tool to safeguard privacy

adblock: another context tool to safeguard privacy

**Comment by wiktor-k** [comment]
Another suggestion would be to start with OMEMO setting set to `Always` instead of current `Default on`. That makes the encryption toggle disappear altogether from chats.

 I think it would be perfect match especially for Quicksy (where majority of contacts would also use Quicksy) but may be also beneficial for Conversations users that use `@conversations.im` accounts (they generally have contacts that also use Conversations).

**Comment by licaon-kter** [comment]
Yes and no, do you have stats on clients usage? How many have OMEMO? How many have it included in base install? What happens when the server/client doesn't support it?

It's tricky, but I find the current way (ON but easy to switch off just in case) better.

**Comment by wiktor-k** [comment]
> What happens when the server/client doesn't support it?

For Quicksy you don't have this problem as you control what's the client and server. Additionally it's by design that most Quicksy people will have Quicksy contacts (if this doesn't hold true then it's a problem in Quicksy in general).

**Comment by licaon-kter** [comment]
It more about your contacts....my post applies to Q too.

**Comment by Echolon** [comment]
I think there should be always the option to toggle back to 'Unencrypted'. But default on is good.

**Comment by wiktor-k** [comment]
There is always option to disable encryption, either in chat or in settings. If you hide the option in chat you won't get questions like "But what is encryption acutally?" or "What is OMEMO?". Wasn't that your objective?

Using "encrypted" as a name for the OMEMO toggle is not technically correct - the traffic is TLS encrypted to the server and OMEMO and OpenPGP are *end-to-end* encryption schemes.
