### ISSUE TITLE
Feature request:Make group members local in conference member list

### ISSUE THREAD

**Issue by martinmix** [iNPUTmice/Conversations#3210]
It will be nice to have the group members to be local because some time I am seeing blank page in group details page. After sometime the member list is visible.

**Comment by licaon-kter** [comment]
Aren't they constantly changing?

**Comment by martinmix** [comment]
when i am using other apps and after some time coming to conversations ...that time list is blank..After 2 minute the list is visible.
When the internet or data problem is there also the same problem is there

**Comment by licaon-kter** [comment]
Right, so how often should the list update?
