### ISSUE TITLE
Search function: Suggest contacts + Chat specific search

### ISSUE THREAD

**Issue by Echolon** [iNPUTmice/Conversations#3243]
Hi,

there are already a few issue about improving the search function, which I will name as overview:

_#1654 Search clear button_
_#2219 Add message history viewer with filter archive by date and keywords_
_#2241 Don't search archived messages when it is off in account_
_#3101 Search function - Jump to chat from result_
_#3233 Enhancement of search: Search activity feedback_

Maybe it should be combined into one single issue, because I like to add another two suggestions:

### Suggest Contacts in search

If you start searching for something, I think it would be helpful to suggest contacts, too. In those terms, it maybe would make sense to show the seach icon in the front and not the QR-code one, I think you more likely search for things, than you add people.
If you don't know what I am talking about, go here https://twitter.com/iNPUTmice and seach for 'input....' or so. Then you see word and account suggestions at the same time.

### Chat specific search

It would be nice too, to have a chat specific search, meaning, you can search for words which will be only extracted from the current or defined chat. But no idea so far who to set this up.

Cheers

**Comment by BaumGuard** [comment]
> it maybe would make sense to show the seach icon in the front and not the QR-code one

There is a fork of Conversations called Pix-Art Messenger. And there stands the search-icon next to the QR-code-icon. It also supports some more functions than Conversations: You can make a backup of your chat-history and your OMEMO-keys and move it to a new device easily. I've already wrote an issue for Conversations on GitHub about that but Daniel Gultsch hasn't answered. So I think, he isn't interested in that.

**Comment by Echolon** [comment]
Yeah, I know, maybe I will drop the idea there, too. But this is only about the seach function.

**Comment by benjaminbischoff** [comment]
> ### Chat specific search
> It would be nice too, to have a chat specific search, meaning, you can search for words which will be only extracted from the current or defined chat. But no idea so far who to set this up.
Just as an suggestion/idea for the UI. Implement it the same way like the "big search", that you click on the "three dots icon/context menu" and get the point "search within this chat/Nachricht, bzw. Chat durchsuchen"

**Comment by eveofdestruction** [comment]
channel/muc indexing/search seems like a plugin

**Comment by oathzed** [comment]
@iNPUTmice Is this on the horizon anytime soon? XD

**Comment by oathzed** [comment]
@iNPUTmice 

To add to this: "Chat specific search
It would be nice too, to have a chat specific search, meaning, you can search for words which will be only extracted from the current or defined chat. But no idea so far who to set this up."

It would be good to be able to search for something and then press the bubble to jump to that place in the search, or just show it how its laid out in the regular chat.

**Comment by licaon-kter** [comment]
@oathzed this was mentined before as non technically possible in the current code structure

**Comment by oathzed** [comment]
> @oathzed this was mentined before as not technically possible in the current code structure

Okay interesting, thanks for the explanation.
