### ISSUE TITLE
Enrich copied / shared messages with Date/Time and Author

### ISSUE THREAD

**Issue by Edcrfv248** [iNPUTmice/Conversations#3252]
#### General information

* **Version:** 2.2.9+fcr
* **Device:** Samsung Galaxy S5 Neo (SM-G903F)
* **Android Version:** Android 6.0.1 Stock
* **Server name:** dismail.de
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Copy / Quote message
2. paste somewhere else

1a. Share to another application

#### Expected result

It would be great if not only the message text would be transfered but also Date/Time and Author
e.g.

[28.10., 21:18] Someone: Some Text

#### Actual result

Only the text is transfered

Some Text

Thank you very much and keep on rockin!

**Comment by benjaminbischoff** [comment]
IMHO is that an unexpected behaviour for the user ..., see WhatsApp and co, and also some people will not be aware of that and would share personal information ....

**Comment by licaon-kter** [comment]
This is a duplicate right? I can't find the other issue although I've commented a bit earlier 🤦
