### ISSUE TITLE
Feature request: delete old OMEMO fingerprint

### ISSUE THREAD

**Issue by luweitest** [iNPUTmice/Conversations#3253]
#### General information

* **Version:** 2.2.8+fcr
* **Device:** Xiaomi5
* **Android Version:** Android 8.0.0 MIUI
* **Conversations source:** F-Droid

#### Steps to reproduce

1. During testing and using of multiple clients, lots of devices and fingerprints is created; especially when using web client as converse.js, each session will create a new fingerprint, which causes a lot of old fingerprints that will not be used anymore. "clear devices" seems have prevented those old fingerprint be announced on the server, but local fingerprints cannot be deleted.

#### Expected result
Hope those redundant fingerprints could be deleted locally too, even If that will cause previous encrypted messages unavailable (it is good in some situation).

**Comment by github-k8n** [comment]
This is still an issue, got a whole bunch of "other devices" keys that are no longer in use and don't know how to get rid of them, it's really cluttering up the account settings page...

**Comment by rranjithkumar100** [comment]
yes Its an issue

**Comment by ltGuillaume** [comment]
Same here!

**Comment by m3thm4th** [comment]
@iNPUTmice Please re-open this. The issue has not been solved.
