### ISSUE TITLE
[Feature Request] Add support for Huawei Push Agent

### ISSUE THREAD

**Issue by athanasio** [iNPUTmice/Conversations#3254]
#### Feature request

With the ongoing issues on Huawei EMUI-based phones, which require multiple changes in the phone's configuration, and based on the fact that Huawei has 15.8% market share worldwide, it might be a good idea to implement Huawei Push Agent along with Google play services and Apple's push service.

https://developer.huawei.com/consumer/en/service/hms/catalog/huaweipush_agent.html

**Comment by licaon-kter** [comment]
Issues for users that got Conversations from Google Play store?

**Comment by athanasio** [comment]
> 
> 
> Issues for users that got Conversations from Google Play store?

Yes, by default Conversations is getting its background process killed shortly after screen is off. Turning this behaviour off requires navigating through a few menus, and again it is not 100% foolproof. Implementing their version of push notifications would probably fix this.

**Comment by bahur142** [comment]
So, that could be the reason why 3 of my friends (all with Huawei devices) not receiving messages until they open Conversations. All of them bought the app from Play Store. One workaround is to lock the app in the memory, so the tcp connection remain persistent.

OFF-Topic:
Recently I had installed matrix-synapse server. The architecture is different from XMPP, but the idea of decentralization of the services is the same. Well, more heavy than Prosody. And along with the Riot client for Android, all push notifications works even on huawei devices without to lock the app in the memory. Well, both the server & client are quiet heavy than Prosody & Conversations, but until now I like them. Sorry for the offtopic.

**Comment by licaon-kter** [comment]
@bahur142 You must set the app to be whitelisted in several places, depends on Android version, see https://dontkillmyapp.com -> Huawei
