### ISSUE TITLE
The error message "Error fetching OMEMO key!" does not indicate which key in a group chat.

### ISSUE THREAD

**Issue by Perelandra0x309** [iNPUTmice/Conversations#3269]
#### General information

* **Version:** 2.3.5+fcr
* **Device:** eg Google Nexus 5X
* **Android Version:** 8.1.0 LineageOS for MicroG 15.1.20181029
* **Server name:** conversations.im
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send a message in a chat room where someone has a broken key?  

#### Expected result

It would be helpful for the error message "Error fetching OMEMO key!" to indicate which key is the problem in a group chat.

#### Actual result

"Error fetching OMEMO key!" and the message seems to send however it is unclear if one or more contacts will not receive the message or who to contact to troubleshoot their key issue.

#### Debug output

This is more of a GUI issue to help with troubleshooting, not a request to fix the actual issue which may be related to someone's server setup, not Conversations itself.

**Comment by Echolon** [comment]
^^
Realted:
#3081 #3262
