### ISSUE TITLE
feature request: delete Account from the server

### ISSUE THREAD

**Issue by benjaminbischoff** [iNPUTmice/Conversations#3304]
Especially to make it easier to switch the server if problems occurs (otherwise it would be possible to send further messages to the old account without getting any information of its status...).
Yes, it is possible via Gajim/Pidgin, but I think there are a lot of users, that only use conversations.

So, please implement that it will be possible to delete an account on the server as well.

UI suggestion/idea: Implement it like in Gajim, that you request by deleting the account in the app, if it also should be removed from the server with a warning, that the account will not be longer usable, including all contacts!

**Comment by meaz** [comment]
I think it is important, especially with the GDPR...

**Comment by git001** [comment]
and in case of quicksy.im. I  wasn't able to login with the quicksy credentials from the app via gajim. Therefore it would be really nice to have a **delete account from server** button

**Comment by locness3** [comment]
This is especially important for Quicksy.

**Comment by licaon-kter** [comment]
Yay https://codeberg.org/iNPUTmice/Conversations/commit/1fff1a064919354be3caf1535f8221b5cd25e192

**Comment by locness3** [comment]
Yay! Congrats on moving to Codeberg

**Comment by licaon-kter** [comment]
available since 2.12.3

/close this
