### ISSUE TITLE
Feature Request: Snackbar to start Orbot

### ISSUE THREAD

**Issue by SkewedZeppelin** [iNPUTmice/Conversations#3312]
Commit 875810e1c784e55fdabfd48ac75282f2bc8e4a2d added options to start or install Orbot if needed in EditAccountActivity, a snackbar in ConversationFragment similar to the disabled account one would be very helpful/informative.

I tried giving it a go but made a mess with the listener callbacks and context to launch intents.
Here is my attempt: https://gist.github.com/SkewedZeppelin/109a3e35c3008b78988d08cb03f85993

**Comment by licaon-kter** [comment]
What's the usecase exactly? When do you need it?

**Comment by SkewedZeppelin** [comment]
@licaon-kter 
Convenience for when Orbot stops running for whatever reason.

It would also bring in line with the current UX that exists:
- Account Screen: Enable / Start Orbot
- Conversation activity: "You have disabled this account, Enable" / [this request]

**Comment by licaon-kter** [comment]
Did you test the current behaviour? What happens when you touch the "some accounts can't connect" notification?

**Comment by SkewedZeppelin** [comment]
@licaon-kter that notification takes a long while to appear. And clicking "Try again", doesn't actually start Orbot.

Maybe that should be a bug report on its own, using Orbot 16.0.5-RC-1-tor-0.3.4.0 with background starts allowed. I think it might be because Conversations tries to launch the Orbot activity instead of just sending a broadcast.

**Comment by licaon-kter** [comment]
Well the launch should be even better, depending on why it stopped (eg. OEM ROM aggresively suspending the app and cutting connection to sawe battery), a simple broadcast is useless.

**Comment by eveofdestruction** [comment]
How is framing this as a Conversations feature better than using Tasker or similar as the watchdog?

> Convenience for when Orbot stops running for whatever reason.

**Comment by licaon-kter** [comment]
I'm not sure this issue should be open anymore.
