### ISSUE TITLE
OMEMO: Show visible notice for non-encrypted self messages

### ISSUE THREAD

**Issue by blacoste** [iNPUTmice/Conversations#3356]
#### General information

* **Version:** 2.3.11+fcr
* **Device:** OnePlus 6
* **Android Version:** H2OS 9.0.3
* **Server name:** self hosted
* **Server software:** prosody
* **Installed server modules:** Carbon Copy
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join a MUC or conversation with two different devices on a same account
2. Enable OMEMO on one of the two devices
3. The other device sends clear message (not OMEMO)
4. Message is displayed as usual (but without shield icon)

#### Expected result

Something clearly visible showing that the device has not used OMEMO.

#### Actual result

The message rightfully doesn't contain the shield but this is a bad way to alert an user.

**Comment by iNPUTmice** [comment]
Please post a screenshot. It works for me

**Comment by licaon-kter** [comment]
@blacoste Lock icon = encrypted, shield icon = encrypted with verified key

**Comment by blacoste** [comment]
Sorry, this only occurs when using two devices on same account. I updated the procedure.

**Comment by licaon-kter** [comment]
Pics please and explain which is which.

**Comment by iNPUTmice** [comment]
This is expected behaviour (also in 1:1); when a message comes from your own devices then it is assumed that you know whether or not you send that message.

**Comment by blacoste** [comment]
This is my use case: 
One device was missconfigured and OMEMO was deactivated on this device. 
So part of the conversation with my correspondent was not enciphered (messages sent on this device) unless he tells me that something was wrong. This happened for days.

That's a shame that we could not take benefit of the fact that I set the security on one device to OMEMO and that it could have clearly report to me that something was wrong. 

There is not only the fact that we known that we send or didn't send the message, but we should ensure that confidentiality is OK and report issues to the user whenever it is possible.
