### ISSUE TITLE
Audio ducking with earphones

### ISSUE THREAD

**Issue by DrugsMaster** [iNPUTmice/Conversations#3360]
#### General information

* **Version:** 2.3.7+fcr
* **Device:** Google Pixel
* **Android Version:** Android 9
* **Conversations source:** F-Droid

#### Problem appears when

Listening to music through the in plugged earphones, then receive a message notification while the phone is blocked or the app is in background. The volume of music is fully ducked to 0%, which doesn't seem to happen without earphones When listening to music without earphones the volume ducks to 20-40%.

#### Expected result

The volume should duck till the same level as without using earphones (20-40%)

#### Actual result

The volume ducks completely to a 0 level.

**Comment by licaon-kter** [comment]
2.3.11 behaves the same?

**Comment by DrugsMaster** [comment]
Yes, 2.3.11**+fcr** behaves the same. Also I tried to play music by Google Play Music and Telegram.
