### ISSUE TITLE
show description of received images

### ISSUE THREAD

**Issue by genofire** [iNPUTmice/Conversations#3378]
The [XEP-0066](https://xmpp.org/extensions/xep-0066.html) has the option for description files.
It would be nice, if `x>desc`  would be shown as an overlay like subtitle over this image.

e.g.
```xml
<message from='stpeter@jabber.org/work'
         to='MaineBoy@jabber.org/home'>
  <body>Yeah, but do you have a license to Jabber?</body>
  <x xmlns='jabber:x:oob'>
    <url>http://www.jabber.org/images/psa-license.jpg</url>
    <desc>This description should be shown</desc>
  </x>
</message>
```

Bye the way, the `<body>` should not been ignored - it could also be not equals with `x>url` - and be used as a description for multi received images ` <x xmlns='jabber:x:oob'>` . (should i create a bug issue for this?)

Maybe this should be shown above the image.

----

Maybe something like a message box :

![a](https://user-images.githubusercontent.com/6905586/52739020-48a53380-2fd0-11e9-884a-e1b2db4f213a.png)

for message like:
```xml
<message from='stpeter@jabber.org/work'
         to='MaineBoy@jabber.org/home'>
  <body>Contant of &lt;body&gt;</body>
  <x xmlns='jabber:x:oob'>
    <url>https://www.jabber.org/images/first-image.jpg</url>
    <desc>content of x:first&gt;desc</desc>
  </x>
  <x xmlns='jabber:x:oob'>
    <url>https://www.jabber.org/images/last-image.jpg</url>
    <desc>content of x:last&gt;desc</desc>
  </x>
</message>
```

**Comment by bleedingcrow** [comment]
I anticipate my amusement providing false descriptions

**Comment by genofire** [comment]
Closed without reaction from @iNPUTmice  :cry:

**Comment by iNPUTmice** [comment]
We currently don’t have the capability of making this work with e2ee. Will revisit once omemo:1 has been adopted.
