### ISSUE TITLE
2.4.0 and later - MUC show offline as grey out

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#3381]
...as until 2.3.12, so they stand out, now unless you enable advanced mode, and then only if you read all the text, you can find them.

**Comment by licaon-kter** [comment]
Fix this you bot! :))

**Comment by iNPUTmice** [comment]
This makes it inconsistent with normal contacts where we don’t care about that either. I think there could be a future where we borrow the gray out indication that Dino is doing. But not now and not just for groups.
