### ISSUE TITLE
Stops updating from MAM archive after sending a message with another client

### ISSUE THREAD

**Issue by Mat406** [iNPUTmice/Conversations#3408]
#### General information

* **Version:** 2.4.2+fcr
* **Device:** Samsung Galaxy S4
* **Android Version:** 7.1.2 - Lineage OS
* **Server name:** Self hosted
* **Server software:** Prosody 0.11.1
* **Installed server modules:** Conversations lists all as available, including: Stream Management, Carbons, MAM, Client State Indication
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Leave Conversations offline.
2. Message someone quite a bit on another client (I used Gajim 1.1.2 with about 900 messages not synced)
3. Reconnect Conversations
4. Send or receive another message, on the other client, to/from the same person you were talking to while Conversations is updating from the MAM archive

#### Expected result

Conversations keeps updating from the MAM archive until it's received all the missed messages.

#### Actual result

Conversations keeps updating till another message is sent or received from another client. 

#### Debug output

Although I didn't use adb logcat, I did use an app that shows the same logs/output.
Also, I replaced my account with "{account}"

[03-13 05:35:41.900 27884:28026 D/conversations]
{account}: running mam query with=*, order=NORMAL, after=1nFtb05wRFboftnh, catchup=true, ns=urn:xmpp:mam:2

[03-13 05:35:43.601 27884:28026 D/conversations]
found auth tag as part of omemo key

[03-13 05:35:43.603 27884:28026 D/conversations]
AxolotlService ({account}):  Received Message with session fingerprint: 058ac8112f9a9e887488ab47479232a2a4153b9504c0078a61ee452b69c55e2659

Those last two messages kept repeating as it worked through the MAM archive, then a few seconds after sending a message over Gajim, it ended with:
[03-13 05:36:38.371 27884:28026 D/conversations]
{account}: finished mam after 750(375) messages. messages left=true count=12850

#### Extra info

* There were roughly 900 messages to catch up on and it stopped after about 375 of them, a few seconds after the message was sent from another client.
* If no messages are sent/received through Gajim while Conversations is updating from the archive, it receives all the messages correctly.
* Disabling and re-enabling the account doesn't finish downloading them either.
* The only way to see the missed messages is to clear the history and scroll up again, though I couldn't test if you can interrupt that with a message as well, as after clearing the history twice it wouldn't load the messages again, saying "no messages on server."

**Comment by iNPUTmice** [comment]
There is a hard cut off after 750;  this has nothing to do with live incoming messages.

**Comment by Mat406** [comment]
Thanks for the extra info. Could there be an expert setting to raise the 750 limit, or is it a technical limitation?

I could be wrong, but if you reach the 750 limit can't you disable and re-enable the account to get another 750 archived messages, so long as someone hasn't sent a message since? I presume in that situation Conversations would pull from the last message received.

With this issue though, you can post from Conversations and it'll keep pulling from the archive, and it's only after another client messages the same contact, or receives one from them, that Conversations stops, or after the 750 cut-off is reached.

In this instance it stopped syncing at about 375 messages, though in the past I've had it stop after only a handful, depending on when the message is sent to/from another client.
