### ISSUE TITLE
Change "allow public listening" option

### ISSUE THREAD

**Issue by meaz** [iNPUTmice/Conversations#3418]
On some servers, the default behavior when one creates a muc is to set it as "allow public listing" which can be a problem for some reason. For example, it can lead to have the muc listed there: [Christopher Muclumbus](https://search.jabber.network).

It would be great if we could disable this directly on Conversations. It is possible on Gajim, in the muc configuration options.

**Comment by iNPUTmice** [comment]
Do you want to change this for channels or for group chats? It is off by default for all group chats created by Conversations.

**Comment by meaz** [comment]
Sorry @iNPUTmice I don't know what is the difference between Channels and Groups Chats, I thought that was just two different way of saying MUC. So what I mean is for MUC, even those created by another client.

**Comment by meaz** [comment]
Ok I got it: Channels are public muc and Group Chats are private muc. Not too obvious... 
ANyway, what I mean is the possibility to change "allow public listing" in Channels then. Even those not created by COnversations.

**Comment by bleedingcrow** [comment]
Meta in the channel could request monitoring agent ignore analogous to interweb robots.txt
