### ISSUE TITLE
Approving Registration Requests for members-only muc

### ISSUE THREAD

**Issue by meaz** [iNPUTmice/Conversations#3420]
When someone tries to enter a members-only muc, he gets a message saying "This muc is allowed to members only" (or something like this in English :) with a LEAVE button. If his demands is legitim, the only solution he has is to find the admin jid and to contact him. Also, that means that the admin doesn't know aything about new users trying to join in.

It would be nice if the muc admin/owner could receive a notification so that he could approve the membership of this user to this a room.

There is a feature in XEP-0045 for requesting membership with a room, and the client could possibly show a button for this: [xep-0045](https://xmpp.org/extensions/xep-0045.html#register)

**Comment by licaon-kter** [comment]
What about spam?

**Comment by meaz** [comment]
I thought about it... We could just refusse the access to the private-muc. Or event add its name to a blacklist? I don't know if it's doable.

**Comment by ToEatFreshBabies** [comment]
Could not the description contain an alternative JID contact?
