### ISSUE TITLE
Don't put on top chats with notifications disabled

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#3433]
#### Steps to reproduce
1. Have some high message rate chat
2. Don't want to be notified now, I'll read later
3. Disable notifications
4. Chat in other chats

#### Wanted result
The "silenced" chat stays in its last position, but all the other chats are bumped on top of it.

#### Actual result
The high message rate chat that I don't want to be bothered by constantly gets bumped as the top chat.

**Comment by licaon-kter** [comment]
@sokai Because?

**Comment by spaetz** [comment]
Sometimes that might be want you want. On the other hand, if the chat remains at the bottom, there is no indication at all that there have been new messages so it would be rather easy to completely miss new messages. Not sure what the best way would be...

**Comment by licaon-kter** [comment]
The text is still bold, the date is updated as usual, just don't put that on top.

**Comment by bleedingcrow** [comment]
See also

https://github.com/siacs/Conversations/issues/3480

**Comment by Mikaela** [comment]
I think this could be helpful, while I prefer the related issue #3480.

**Comment by licaon-kter** [comment]
Still want this yes...

**Comment by iNPUTmice** [comment]
Closing in favor of #3480 as the solution described in here seems to be very confusing and #3480 is much more straight forward for what are probably similar results.

**Comment by licaon-kter** [comment]
That's a different issue, I don't want to pin anything, but I don't want chats that I silenced to become top pinned just by having activity.
