### ISSUE TITLE
Feature request: allow pinning/favouriting chats on top

### ISSUE THREAD

**Issue by Mikaela** [iNPUTmice/Conversations#3480]
#### General information

* **Version:** 2.5.2+pcr
* **Device:** Nokia 1
* **Android Version:** Android 8.1 Go Stock
* **Server name:** blesmrt.net
* **Server software:** Prosody?
* **Installed server modules:** all supported in server info
* **Conversations source:** Play Store Beta

#### Steps to reproduce

1. Open Conversations with very active chats
2. Try to look for a specific chat that is important for you and send a message there quickly.

#### Expected result

I am able to long touch MUCs or contacts and select "pin/favourite" so they stay on top of the main screen until I unpin them. I think this could also resolve https://github.com/siacs/Conversations/issues/3477 without dedicated self-chats/notes-to-self.

#### Actual result

I see ~25 chats that keep jumping all the time and if no one said anything in the chats I am looking for, they take scrolling and I may accidentally glance over them and scroll down further. I may also start trying to read the active chats and while that happens another chats becomes active so I may not just finish what I wanted to do and put my phone away. (See also https://github.com/dino/dino/issues/384#issuecomment-502442947)

**Comment by eveofdestruction** [comment]
this pairs well with squelching https://github.com/siacs/Conversations/issues/3433

**Comment by Mikaela** [comment]
I am still having this issue.

**Comment by licaon-kter** [comment]
This would be nice...

**Comment by rms-joe** [comment]
Just to mention, u can do: bookmark -> search.

But I have to admit that I find it difficult to stay on top of things in the roster sometimes, where pub channels, 1:1, private groups, everything is mixed. 

I kick out 1:1 contacts from time to time to have a better overview, because they come back into the roster anyway when they txt me.
