### ISSUE TITLE
[Feature request] Add pause button to "Record voice"

### ISSUE THREAD

**Issue by jesse-git** [iNPUTmice/Conversations#3517]
#### General information

* **Version:** 2.5.5+fcr
* **Android Version:**  Android 9, LineageOS
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open any conversation of a buddy
2. Tap  paperclip  icon, then "Record voice"

#### Expected result

Voice recorder starts recording with "Cancel", "Attach", and "Pause" buttons.  I would suggest that the pause button is large enough and well placed so that  the other two buttons are not accidentally pressed.

Upon pressing "Pause", the button should change text to "Resume" or similar. ( This behavior would be similar to how Google's voice recognition works using the "Google" app.) (Alternatively, an icon could be used instead to pause and resume, with a cancel and attach button.)

#### Actual result

Voice recorder starts recording with only "Cancel" or "Attach" buttons.

**Comment by anjandev** [comment]
I wanna implement this but according to the mediarecoder docs [https://developer.android.com/reference/android/media/MediaRecorder.html#pause()](https://developer.android.com/reference/android/media/MediaRecorder.html#pause()):

`pause()` method was Added in API level 24. Conversations' current min api level is 16. I have the code sitting on my hard drive. If anyone has a solution to this, I will continue working on this.

**Comment by licaon-kter** [comment]
@anjandev can't you just `if sdk> then show pause` ?

**Comment by anjandev** [comment]
@licaon-kter I am very new to android app development and I did not know that was an option. Thank you. I will look into solving this problem if I can...

**Comment by anjandev** [comment]
I think this issue can be closed since the PR was closed.

**Comment by jeyakeethan** [comment]
> 
> 
> @anjandev can't you just `if sdk> then show pause` ?

But Whether the app will work on sdk below 24 or will not work?

**Comment by licaon-kter** [comment]
@jeyakeethan That functionality will be shown only on supported Android versions, yes.
