### ISSUE TITLE
Unable to match Open-Keychain

### ISSUE THREAD

**Issue by stevenleeS0ht** [iNPUTmice/Conversations#3525]
#### General information

* **Version:** 2.5.5+fcr
* **Device:** Honor 9
* **Android Version:**  Android 8 (stock)
* **Server name:** *If this information is essential, please ask me later*
* **Server software:** Not known
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

When disable omemo, and enter a conversation, push "Lock" button, and choose OpenPGP, a dialog show up (ask me to install open-keychain). Actually, I have already installed open-keychain. And there is a key in open-keychain.

When I restarted Conversations, the same situation occurs. No matter how many times I retries, same thing happened.

#### Expected result

What is the expected output? 

It should pop up a dialog to let me choose the key.

#### Actual result

Let me install open-keychain.

#### Debug output

Since Conversation didn't crash, if this section is necessary, please ask me.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
You'd need some logs from the device.

**Comment by stevenleeS0ht** [comment]
@licaon-kter , Oh, it works when open OpenKeyChain and run on background. But it won't work when Didn't start openkeychain. Is that a expected behavior?

Why cannot Conversations call the intent of OpenKeyChain?

**Comment by licaon-kter** [comment]
Then this might be a ROM issue, eg. Blocking the start by other app intents, like Huawei can
