### ISSUE TITLE
Google Talk images not viewable

### ISSUE THREAD

**Issue by ildar** [iNPUTmice/Conversations#3527]
#### General information

* **Android Version:**  Android 7 (LOS)
* **Server name:** Google
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Receive an image from Hangouts peer
2. See the bare https://plus.google.com/photos/albums/... link

#### Expected result

An image.

Please note that viewing in an external app isn't an option: the URL requires authentication.

Please make it visible!

**Comment by iNPUTmice** [comment]
If the URL requires authentication it is probably not possible for Conversations to download it either (without implementing their proprietary authentication schema). I personally have absolutely no desire to work on something like that. If you provide a PR and it is not too complicated I might consider merging it.

**Comment by ildar** [comment]
Also stickers look like weird URLs. IM with weird stickers? :-\

**Comment by iNPUTmice** [comment]
Google has decided to care about XMPP 10 years ago. Why should we care about them?
