### ISSUE TITLE
Simplifying UI strings

### ISSUE THREAD

**Issue by oksjd** [iNPUTmice/Conversations#3544]
As a translator of several FOSS apps on Android, a situation I often find myself in is the verbosity of the source strings and in some cases, unnecessary descriptions complicating the translation process.
## Verbosity
> The pin we have sent you has expired.

I translated literally into:

> Verification code expired.

Omitting the "we" part.

We should do our best to leave only the essential part in the UI.

Another example is this string, which I have translated before in Pix-Art

> Do not use the restore backup feature in an attempt to clone (run simultaneously) an installation. Restoring a backup is only meant for migrations or in case you’ve lost the original device.

My first translation
> Do not ~~use the~~ restore backup ~~feature in an attempt to clone (run simultaneously) an installation. Restoring a backup is only meant~~ except for migrations or ~~in case you’ve lost~~ the loss of the original device.

After a while I felt that it's inappropriate to use negative, so

> Restore backups only for migrations and the loss of the original device.
## Unnecessary descriptions

> We have sent you another SMS with a 6 digit code.

I translated literally into:

> Verification code resent.

If in the future, the 6 digit code turns out to be insufficient, or we decided to send via email, the string will need to be translated again. Which, is a waste of translator resources. 

The strings should be as much reusable as possible.
## Term inconsistencies
> We have sent you another SMS with **a 6 digit code**.
> The **pin** we have sent you has expired.

We as experienced users know the two expressions are referring to the same thing. But as a newcomer, this kind of inconsistencies can be confusing.

And it's confusing translators as well.

**Comment by oksjd** [comment]
Besides the arbitrary rules in Transifex, its machine translation capability is also fairly limited compare to Weblate. And in Transifex only similar strings from the same project can be displayed in the "Suggestions" area, unlike Weblate, which in contrast can source strings not only from online translators (even the Chinese Baidu translator is included) but also other projects.

**Comment by oksjd** [comment]
So all above can be summed up as follows:
please do something for translators! Don't let us do the repetitive work over and over again (in vain)! Be gone, the verbose and ambiguous source strings!

**Comment by licaon-kter** [comment]
Why not just PR the English strings with your new shorter ones?

**Comment by oksjd** [comment]
I received a automated email from OpenKeychain when joining their team, send from https://www.localizationlab.org/. This might be the way out.

**Comment by oksjd** [comment]
erinm wrote:
> Hello oksjd,
> 
> Thank you for your interest in joining the OpenKeychain
> localization team and the Localization Lab community!
> The Localization Lab is a global community of volunteer
> translators who support the translation and
> localization of Internet freedom tools like the one
> you’ve requested to contribute to. To learn more about
> our work and the projects we support, visit
> localizationlab.org.
> 
> Before you begin translating, we would like to know
> more about you so that we can best integrate your
> efforts into the project and community. When you have a
> moment, please fill out the following Contributor
> Questionnaire and read through the Contributor Roles &
> Guidelines.
> 
> ***You are not required to respond to the following
> questionnaire (if you are not comfortable responding to
> the survey or using Google services), however we will
> not add you to the translation team if you do not at
> least respond to this message so that we have an
> assured channel of communication.***
> 
> Contributor Questionnaire:
> https://docs.google.com/forms/d/e/
> 
> 
> Contributor Roles & Guidelines:
> http://www.localizationlab.org/roles-guidelines 
> 
> Meet the Projects:
> A complete list of the Internet freedom tools and
> training materials that we support is available here:
> https://wiki.localizationlab.org/index.php/Projects
> 
> Join the Discussion:
> There are several ways for you to keep in touch with
> Localization Lab staff, developers and project managers
> of the tools you translate, as well as fellow
> translators and activists. Please feel free to use any
> of the following methods to pose questions, begin
> discussion or request assistance related to
> localization and all things Internet freedom. 
> 
> * Sign up for Mattermost:
> https://community.internetfreedomfestival.org/signup_user_complete/?id=
> 
> * Join the Localization Lab Channel once you have
> signed up:
> https://community.internetfreedomfestival.org/community/channels/localization-lab-chat
> 
> * Google Group and Mailing List:
> https://groups.google.com/forum/#!forum/otfl10n 
> * Email: info@localizationlab.org 
> 
> Welcome, and thank you again for your interest in
> contributing to the Localization Lab projects!
> 
> Best Regards,
> The Localization Lab Team

**Comment by licaon-kter** [comment]
And ??? What's the point of that email from anothel project?

**Comment by oksjd** [comment]
> What's the point of that email from another project?

The Localization Lab Team is a team dedicated to coordinate translation in FOSS apps. You can have a read at the email yourself. I think it would be great if Conversations can join the team.

**Comment by oksjd** [comment]
> What's the point of that email from another project?

Sorry I misunderstood your question. The email is an equivalent of our interview process, like the issue I raised before #3542 

>Yes. Just by looking at the transifex request I have no idea who that person is. Thus I changed the procedure to ask applicants to go through our group chat and introduce themselves.
See https://github.com/siacs/Conversations/blob/master/README.md#translations
>However we can also do this on Github. Please apply again and leave your transifex name in this issue (or talk to me on the group chat)

**Comment by gsantner** [comment]
#2789 ?

**Comment by iNPUTmice** [comment]
A lot of the strings have been simplified in 2.8.2 - If you have other concrete suggestions please create a PR so we can discuss them.
