### ISSUE TITLE
SOCKS5 file transfer slow/sometimes stalling

### ISSUE THREAD

**Issue by Black-Nr1** [iNPUTmice/Conversations#3549]
#### General information

* **Version:** 2.5.8 and 2.5.9
* **Device:** Xiaomi Redmi 7 (and others)
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** latest prosody (Arch Linux)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid (Play store: same behaviour, tried both)

#### Steps to reproduce

1. Start Conversations 2.5.8 or 2.5.9
2. Send a picture/file to another Conversations user

#### Expected result
File transfer is fast, happens nearly immediately
What is the expected output? 

#### Actual result

What do you see instead?
File transfer hangs at "0% completed", and it can take up to 30 sec before the file is transferred. Sometimes, it stalls forever and the transfer has to be cancelled.
Conversations up to and including 2.5.7 is fine. The problem is introduced with 2.5.8 and persists in 2.5.9. Attached is the debug output of both 2.5.7 and 2.5.8 sending a picture.

[logcat-2.5.7.txt](https://github.com/siacs/Conversations/files/3666562/logcat-2.5.7.txt)
[logcat-2.5.8.txt](https://github.com/siacs/Conversations/files/3666563/logcat-2.5.8.txt)

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
Did you lose your issue? https://github.com/siacs/Conversations/issues/3545

**Comment by iNPUTmice** [comment]
What version is the receiving client on?

**Comment by Black-Nr1** [comment]
The receiving client is on 2.5.7. The delay/stalls occur when at least one part is on Conversations 2.5.8. In this case, the sender was on 2.5.8 and the receiver on 2.5.7.

**Comment by iNPUTmice** [comment]
Please update the receiving client as well and make sure every participating client is on the latest version.

**Comment by licaon-kter** [comment]
Also don't update to 2.5.9 on Xiaomi...but 2.5.8 or if avilable 2.5.11

**Comment by Black-Nr1** [comment]
2.5.11 wasn't on F-Droid yet, so I compiled it by myself (2.5.11-fcr). The problem is gone, file transfer is fast again as it was before 2.5.8.. That's great!

However, the option "Keep service in foreground" in "Expert settings" seems to be missing. As a result, notifications are no longer working and I have to wake my phone manually to check if somebody has sent something to me.

**Comment by licaon-kter** [comment]
@Black-Nr1 you need to modify as targetsdk 25 too, as F-Droid does, to see the checkbox.


But, IIRC even if that is not seen it should default to always on.

**Comment by Black-Nr1** [comment]
Thanks, that worked! Now the checkbox is there and notifications work again (but it defaults to "off", the same way as in all the F-Droid releases).

**Comment by Black-Nr1** [comment]
Unfortunately, the person who reported back to me on the slow/stalling SOCKS5 file transfer wasn't reliable. The file transfer delay ("0% completed") is persisting also with 2.5.11. Here's the logcat of a full stall, hanging at 0% completed with bog standard 2.5.11-fcr without any modifications. Sorry for the confusion!
[logcat-2.5.11-fcr.txt](https://github.com/siacs/Conversations/files/3670253/logcat-2.5.11-fcr.txt)

Text messages work perfectly, also during the stalling file transfer. Switching back to 2.5.7 solves the problem immediately.

**Comment by iNPUTmice** [comment]
> Please update the receiving client as well and make sure every participating client is on the latest version.

**Comment by Black-Nr1** [comment]
Here is a new logfile. Both sides are now on 2.5.11-fcr (downloaded from F-Droid).
[logcat-2.5.11-fcr-on-both-sides.txt](https://github.com/siacs/Conversations/files/3675941/logcat-2.5.11-fcr-on-both-sides.txt)

**Comment by iNPUTmice** [comment]
That log has the file successfully transmitted after 11 seconds...

**Comment by Black-Nr1** [comment]
I took the first log I could produce. The thing is: up to 2.5.7, all file transfers were lightning fast and happened immediately. With 2.5.8, something changed. Now, all of the file transfers shows "0% completed" and is delayed for some time. 11 seconds as in this case, often more than 30 seconds, and some times up to full stalls that have to be cancelled. A downgrade to 2.5.7 fixes them all. What I want to say is: something has changed with 2.5.8 which makes file transfer via proxy65 noticeably slower. Up to 2.5.7, this was never any issue. Every file transfer within a network with a reasonably short ping happened blazingly fast - instantly. Mobile 4G, fiber, whatever. This changed with 2.5.8 and still persists with 2.5.11.

**Comment by Black-Nr1** [comment]
Look at this one. Didn't take more than a few tries to produce:
[logcat-2.5.11-2.txt](https://github.com/siacs/Conversations/files/3677414/logcat-2.5.11-2.txt)

**Comment by Black-Nr1** [comment]
The first picture this morning, and I was close to abort the transfer, when it finally got transferred after about 8-10 minutes of waiting. As a final test, we both switched back to 2.5.7, and the problem was gone.
[logcat-2.5.11-3.txt](https://github.com/siacs/Conversations/files/3679766/logcat-2.5.11-3.txt)

**Comment by iNPUTmice** [comment]
I’m unable to reproduce timeouts of 8-10 minutes. 10-20 seconds (5 per candidate for 2-4 candidates) is normal; anything higher than that I have not experienced.
Would be interesting to see a logcat of both sides.
Are you using firewall applications on either of the devices?

**Comment by Black-Nr1** [comment]
Both mobile phones are stock, without any firewall applications. No rooting or whatsoever. The prosody server runs behind a FreeBSD-based firewall. I have not changed any of the rules in a long time, and I can not see something extraordinarily either in a prosody debug log or in the firewall logs. And I think it's quite unlikely that any of these components can be the culprit, because when downgraded to 2.5.7 or lower, the problem disappears immediately, without changing anything else. I will provide you with a logcat of both sides, as soon as possible.

**Comment by iNPUTmice** [comment]
For the record I’m relatively certain that this is not something on the server side. However clients should either (ideally) fail to established a direct connection or at least run into a 5 second time out. That‘s why I was asking for firewalls on the phone; because those could prevent the former.

**Comment by Black-Nr1** [comment]
Eventually, I managed to convince my counterpart to carry out a logfile while receiving a picture file. Here are logcat debug logs of both the sender and receiver part. The transfer stalled for some minutes. 2.5.11-fcr from F-Droid on both sides.
[sender-s.txt](https://github.com/siacs/Conversations/files/3699077/sender-s.txt)
[receiver-st.txt](https://github.com/siacs/Conversations/files/3699079/receiver-st.txt)

**Comment by iNPUTmice** [comment]
@Black-Nr1 thank you for gathering those logs. It's currently unclear to me what causes the delay. Originally I thought it had something to do with the direct jingle candidates feature that has been introduced in 2.5.8; However as indicated in the receiver log connecting to that fails after 5 seconds (as planned); And it is the direct proxy candidate that takes for ever to connect.

**Comment by Black-Nr1** [comment]
I created a diff between 2.5.7 and 2.5.8 to see what has changed. In Config.java, there is a new line that sets the jingle direct candidates to "true". After reading your reply, and out of plain curiosity, I changed this to "false" and recompiled. Now the problem is gone! But keep in mind that I'm not an advanced programmer, and I do not really understand java. I sent a bunch of files to multiple phones, and the file transfer is now as fast as with 2.5.7. And no stalls so far. In this case, 2.5.11-fcr (with the above mentioned modification) on my side, and 2.5.7 (and some other versions that I do not know - guess it's mostly 2.5.11 from Google playstore or F-Droid) on the receiver side. Hope this information can help you.

**Comment by iNPUTmice** [comment]
You have to be careful not to mix up the 5-10 second delay that was observed here: https://github.com/siacs/Conversations/issues/3549#issuecomment-536994343 and the multiple minute delay that was observed in your latest post.

The 5-10s delay can in fact be removed by disabling direct candidates. That’s not a big surprise. However the multiple minute wait in connecting to the proxy candidate seems to be a different phenomenon.

**Comment by Black-Nr1** [comment]
Ok, I see the difference. Thanks for expaining! The 5-10 sec delay is not really a problem, although it didn't happen before 2.5.8 and can be a little bitt annoying. I understand that this comes with the implementation of Jingle file transfer, so this is meant to be that way. Maybe it might be an idea to make a switch to disable direct candidates in the expert settings? However, I see that the multiple minute delays have to be another thing, though they didn't occur at all since I disabled Jingle direct candidates... will observe further.

**Comment by Black-Nr1** [comment]
After a lot of try and error, I can confirm that the problem is solved. 2.5.12 works fine, and the transfer problems are completely gone. But now to the more interesting part: as far as I can see, the problem was introduced somewhere back in time, with the use of epoll with prosody. Switching back to select resolved all file transfer delays. However, it remains unclear to me why these delays didn't occur with 2.5.7. And what about the epoll implementation? Is there something in prosody that triggers the problematic behaviour, or got epoll faulty at some place, with some of the updates in the past? Or is it the aarch64 implementation of epoll? The kernel itself? Maybe something in LuaSocket? I don't know. But if you're running prosody and are encountering file transfer problems in combination with SOCKS5, check which network backend the server is using, and consider switching back to select.

**Comment by ToEatFreshBabies** [comment]
Did the socks5 server in question require authentication?

**Comment by Black-Nr1** [comment]
Yes. It is part of the prosody xmpp server.
