### ISSUE TITLE
Jingle Transfer - popup dialogue on receive

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#3555]
...else recepient might just ignore it thinking that they can download the file later at any time, as expected with http_upload.

2.5.11+fcr 

"Nick (jid@domain) is sending you NOW a video/audio/apk/pdf/image size 1234Mb. Download/Cancel"

**Comment by ToEatFreshBabies** [comment]
Could this be option constrained to the network interface for  lte/5g?

**Comment by licaon-kter** [comment]
I see this a lot, specially with normies that can't grasp that their 8 min 4K video won't really compress under 100Mb or so. :)

**Comment by iNPUTmice** [comment]
You already get a notification. Not sure why we need more of them.
