### ISSUE TITLE
Show channel avatars in public channel search

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#3558]
Currently only avatars are fetched and displayed of already joined rooms. It'd be fancy if Conversations displayed all available avatars from the public list of `https://search.jabber.network`

There's already an API for that: https://search.jabber.network/avatar/v1/conversations@conference.siacs.eu

**Comment by licaon-kter** [comment]
Fix it bot!

**Comment by anubister** [comment]
Sorry for the duplicate, I'll close it.
However why was this one closed ?
