### ISSUE TITLE
Add categories to the media browser like "time" and "file type"

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#3563]
The current media browser simply lists all received files chronologically, which becomes quiet unclear and makes it hard to find a specific file if there are many.
Additional the view is reset once the browser is reopened and the search starts again.

Therefore categories would increase the UX a lot, for example:

##### Time: 
```
**-- Today --**
File 1, ..., File n

**-- Yesterday --**
File n+1, ..., File m

**-- Octobre 7th to 13th --**
File m+1, ..., File k
```

##### File type:

```
Add titles like
**-- Images --**
File 1, ..., File n

**-- Audio records --**
File n+1, ..., File m

**-- Videos --**
File m+1, ..., File k
```

**Comment by joriscode** [comment]
I'm totally in favor of this feature!
Can I suggest the category _link_ that would end the burden of infinite scroll up browsing?
And also the category _documents_ (`.txt`, `.pdf`)

**Comment by iNPUTmice** [comment]
I think at this point Conversations should focus on being an instant messenger and not a file manager.

**Comment by ericschdt** [comment]
> I think at this point Conversations should focus on being an instant messenger and not a file manager.
Maybe Conversations should turn on message expiration by default so it does not become a file or text collector. Whatever, you are the boss! ;-)
