### ISSUE TITLE
How to change media location ?

### ISSUE THREAD

**Issue by Zibc** [iNPUTmice/Conversations#3565]
Hello,

I have a situation where a user has his local storage (/storage/emulated/0) that is getting quite full. The user realised that there was plenty of media in /storage/emulated/0/Conversations

Is there a possibility to move that location to the sd card ?

I already rad in another issue that Conversations is supposed to do that automatically, but this is not happening on that user's phone, neither on mine.

Otherwise, would it be possible to just provide a location manually ?

**Comment by contrapunctus-1** [comment]
I have the same issue on my Nokia 6.1 (TA-1089), Android 9. 🙁

**Comment by TrickTrackNO** [comment]
Very low end devices quickly face this.  Not everyone can afford a flagship phone.

**Comment by licaon-kter** [comment]
Use Syncthing to backup on another device, eg. PC and then clean up often.

**Comment by iNPUTmice** [comment]
> Is there a possibility to move that location to the sd card ?

No there is not.
