### ISSUE TITLE
Can't paste as quote

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#3575]
2.5.12 F-Droid, Xiaomi Android 10 MIUI11

#### Steps to reproduce

1. have some text in clipboard (other app or copy a message)
2. long press the input field

#### Expected result

Allow to PASTE, PASTE AS QUOTE and other options

#### Actual result

Allowed to PASTE and other options

Might be related to https://github.com/siacs/Conversations/issues/2518 aka Xiaomi issue.

How to debug?

**Comment by licaon-kter** [comment]
Fix it bot!

**Comment by iNPUTmice** [comment]
This functionality uses private Android API that apparently isn’t available on some ROMs.
