### ISSUE TITLE
MUC - Invitations process

### ISSUE THREAD

**Issue by tbeitter** [iNPUTmice/Conversations#358]
If I invite someone (conversations users) to a conference they get joined to the channel without confirmation or even a notification on their side. They see this new conference only by - accidentially - looking at the list and cannot decline to join.

Is this the desired behaviour or is there something wrong on our side/server?

**Comment by ge0rg** [comment]
Besides of the UX problem where people don't notice they are in a group chat now, this also has security implications:

* you can see the user's presence in the MUC
* you can see the user's full JID if you are a room admin
* you can send IQs to the user's client

It would be better to limit the auto-join in two ways:

1. Only automatically follow invitations from people subscribed to your presence (that requires 'direct' as opposed to 'mediated' invitations)
2. Only auto-join non-public rooms (not sure how to best implement this)
