### ISSUE TITLE
[Quicksy] Copy paste phone number and verification code

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#3596]
#### General information

* **Version:** 2.6.1
* **Device:** Samsung Galaxy S8
* **Android Version:**  Android 9 (stock)
* **Conversations source:** PlayStore

#### Steps to reproduce

1. At the screen to enter phone number: Make it possible to paste the number into the field.
-> Currently, long pressing on the input field does not trigger any action.

2. At the verification screen: Allow to paste the four numbers into the fields by a single paste
-> Currently, long pressing lets one paste the number, but it's actually not entered.

This would make it even more "quicksy" and comfortable. :)

**Comment by iNPUTmice** [comment]
I’m adding a `pr-welcome` label. If anyone wants to do this note that pasting the phone number should be relatively smart in that it needs to handle pasting phone numbers with spaces in it and pasting phone numbers with or without country code. Behaviour may need to be different depending on which of the two fields (country field or number field) you are pasting this in. It may also need to strip leading zeros. (Essentially you want to run the paste through phonenumber.parse() and then see if the country code matches and do something smart.
