### ISSUE TITLE
Metadata (time, encryption, delivery) should be smaller

### ISSUE THREAD

**Issue by alyssarosenzweig** [iNPUTmice/Conversations#3621]
To stay out of the way (and allow the user the focus on the message content, while still having access to the metadata), this bar should be a little bit smaller than it currently is relative to the text. It should probably also have a bit lower opacity.

**Comment by subpub** [comment]
What about collapsing metadata till user clicks on it?
Looks cleaner
![Video](https://upload.jabberfr.org/edS-OAWutDBCP_18/392984_1.mp4)

**Comment by alyssarosenzweig** [comment]
That might also be an option, but note even in that video, the metadata
(once collapsed) is still smaller/lower contrast :)

Of course, this begs the question of which pieces of metadata matter
normally and which don't. I suspect delivery notifications (and read
notifications if my PR is merged) ought to always be displayed, but
those are small/symbols and can fit snugly without drawing attention, be
small/low contrast/etc. Time/dates might make more sense to collapse,
but most SMS apps seem to display that stuff and I think it probably
makes sense for us to continue to do so, just slightly less prominently.

**Comment by licaon-kter** [comment]
I actually don't like the separated metainfo, smaller I do see a benefit, but still include it.

Eg. even worse when some parts are inside but others outside, lock vs date: https://monal.im/blog/mam-and-rethinking-the-ui/

**Comment by eveofdestruction** [comment]
Please don't make it smaller.  I have the text size set to the largest now.
