### ISSUE TITLE
make whispers more prominent

### ISSUE THREAD

**Issue by rms-joe** [iNPUTmice/Conversations#3647]
I'd like to pick up muppeths idea to make whispers more prominent in MUCs.

As it happens easily you overlook it and shout answer into MUC.

For example by different background color or "whispered" in red instead of grey.

**Comment by rms-joe** [comment]
Just to clarify: as far as I see these issues have been about writing pm's. That's not my point.
I'm good with that.

**Comment by iNPUTmice** [comment]
I currently can’t think of a way to make them more prominent without looking weird.
