### ISSUE TITLE
Allow denying subscription requests

### ISSUE THREAD

**Issue by singpolyma** [iNPUTmice/Conversations#3652]
#### General information

* **Version:** 2.6.2+pcr
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Receive subscription request
2. Tap the conversation

#### Expected result

See a button "Deny request"

#### Actual result

See "Contact added you to contact list" with a button "add back" but no button to deny this request.

#### Why is this needed?

Without a way to deny, the conversations keep coming back every time I re-log-in since the server will send the subscription request stanza again until it is denied.  I currently have to solve this by logging in using another client to deny the requests so they can go away in my Conversations view.

**Comment by buiniyslavik** [comment]
You can deny a request by holding the "add back" button, there will be a menu with block options. It should be made more obvious, though.

**Comment by TrickTrackNO** [comment]
"every time I re-log-in"

why are you logging out?

**Comment by iNPUTmice** [comment]
As @buiniyslavik pointed out you can already do that.
As for making it more obvious: That’s the problem with mobile. We don’t have enough screen estate to make a button for everything.

**Comment by SamWhited** [comment]
I wonder if a little downward facing chevron or something on the button would make it more obvious that it's long-pressable? This is also an issue I have with various apps frequently, but I'm not sure if there's a common pattern for it on Android. On other systems a chevron or stacked dots or something normally indicates "this can be expanded".
