### ISSUE TITLE
Need to write PM before being able to read MUC chat

### ISSUE THREAD

**Issue by blind-coder** [iNPUTmice/Conversations#3655]
#### General information

* **Version:** 2.7.0+fcr
* **Device:** any
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** prosody 0.11.3
* **Installed server modules:** roster, saslauth, tls, dialback, disco, private, vcard, version, uptime, time, ping, pep, register, mam, admin_adhoc, posic, groups, http, http_upload_external, storage_sql, proxy65, carbons, cloud_notify, csi, auth_ldap, offline, smacks
* **Conversations source:** Google Play

#### Steps to reproduce

This seems to trigger:
Join MUC with other person
Write OMEMO messages
OMEMO messages are readable
Reinstall / Wipe Conversations
Log in to account again
Select existing MUC from bookmarks
Have other person send you a message

#### Expected result

Being able to read the message.

#### Actual result

"The message was not encrypted for this device."

#### Debug output

No access to user's device.

Proposed 'fix' (workaround) is to have both users send each other a private message using OMEMO, then all FUTURE messages are readable.

**Comment by licaon-kter** [comment]
OMEMO has [Forward Secrecy](https://en.wikipedia.org/wiki/Forward_secrecy), by design.

Use PGP if you want messages to be decrypted in the future.

/close as not an issue

**Comment by blind-coder** [comment]
@licaon-kter 
Thank you for the quick answer!
However, I feel like this does not address the issue.
The users are both still part of the same MUC, connected with the same credentials. However the user who reinstalled Conversations can not read NEW messages sent by the other user. I'm not talking about PAST messages, but about NEW messages sent to an existing MUC after reinstalling Conversations.

**Comment by licaon-kter** [comment]
I did not understand that from your OP.

Ok, strange then, it should just work. You can repro this with a new MUC?

**Comment by iNPUTmice** [comment]
OMEMO:1 will make those things a little easier to detect. But with the current omemo version you have to either have mutual presence subscription or send a message first.
