### ISSUE TITLE
Quoting /me messages loses the user name

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#3669]
#### General information

* **Version:** 2.7.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. someone says `/me does something`
2. Conversations shows `UserNick does something`
3. long press and quote the message

#### Expected result
`UserNick does something`

#### Actual result
`/me does something`

**Comment by mdosch** [comment]
I also stumbled upon this a while ago and was told this is standards compliant behavior.

> and the receiving client performs string-matching on the first four characters of the data included in the <body/>
https://xmpp.org/extensions/xep-0245.html

So the XEP seems to be very strict (see also Example 4) and doesn't consider quoting. :(

**Comment by licaon-kter** [comment]
Not sure what this has to do with `/me` parsing.

The 245 rules should matter when **posting**. 

When quoting I'm not posting `/me` but I'm copying a string from the screen, that string DOES NOT have `/me` in it _(as it is rendered for the user)_ so it does not make sense to treat it like that, when I press the quote button/action I should get `the text shown on screen` not `the contents of <body>`.

Eg. What do I get when I copy with the mouse the result of `/me` in a text client? Does it magically replace my clipboard buffer with `/me something` or copies the plain text of `Nick something`.

This is an UI issue, not a XMPP one, IMHO. :)
