### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by msiep** [iNPUTmice/Conversations#3672]
#### General information

* **Version:** 2.7.1+fcr
* **Device:** T-Mobile / Alcatel REVVL 5049W
* **Android Version:**  Android 7.0
* **Server name:** N/A
* **Server software:** N/A
* **Installed server modules:** N/A
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Conversations app menu > Settings > Backup / Create backup

#### Expected result

A usable backup file in /storage/emulated/0/Conversations/Backup and hopefully some sort of confirmation message.

#### Actual result

An icon very briefly flashes at the top right and otherwise nothing appears to happen. When I look in /storage/emulated/0/Conversations/Backup there's a 72 byte file ending in .ceb corresponding to just one of my 3 accounts in the Conversations app. When I try to restore that file on another device it asks me to enter the password for that account, which I do, and it then says it's unable to decrypt the backup. But obviously with the file only being 72 bytes, there's no way it could contain the actual backup.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

04-10 16:47:43.256  5268 14476 D conversations: BackupFileHeader{app='Conversations', jid=7207710014@s.ms/Conversations.wvIn, timestamp=1586558863237, iv=f6b818a3cffd7f602c7042f1, salt=c1dd8a030179ef86369d32347ff89763}
04-10 16:49:29.161  5268  5268 D conversations: ignoring onTaskRemoved because foreground service is activated
04-10 16:50:40.765  5268  5268 D conversations: action: null
04-10 16:50:40.775  5268  5268 D conversations: ConversationsOverviewFragment.onStart()
04-10 16:50:40.777  5268  5268 D conversations: ConversationsOverviewFragment.onResume()
04-10 16:50:40.859  5268  5268 D conversations: app switched into foreground
04-10 16:50:44.711  5268  5268 D conversations: ConversationsOverviewFragment.onPause()
04-10 16:50:45.383  5268  5268 D conversations: app switched into background
04-10 16:50:51.321  5268 14642 D conversations: BackupFileHeader{app='Conversations', jid=7207710014@s.ms/Conversations.wvIn, timestamp=1586559051306, iv=32c6550084e754f975f615bc, salt=8663b819b4ae33182c5e23d085bf3a2f}

**Comment by iNPUTmice** [comment]
More interesting would be the logcat during create. not during restore.

**Comment by msiep** [comment]
That is from during create.

**Comment by msiep** [comment]
Does the fact that create give that logcat provide any clues as to what the problem is?
Thanks!

**Comment by msiep** [comment]
Just checking in about this. To be clear, I know for certain that the logcat I provided is from attempting to create a backup, not attempting to restore one.
