### ISSUE TITLE
App crashes on tablet when audio calling

### ISSUE THREAD

**Issue by nillebor** [iNPUTmice/Conversations#3682]
#### General information

* **Version:** 2.8.0
* **Device:** Samsung Tab A 2016 SM T580
* **Android Version:**  Android 9 (LineageOS)
* **Server name:** jabber.de
* **Conversations source:** PlayStore

#### Steps to reproduce

when calling via the app on 2 tablets, the completely crashes and closes. the app crashes when the called party accepts the call. Video calls work without problems. Calling also works on mobile phones (with LineageOS). has any other similar problems?

i would also like to be able to switch the calls to speakers. an associated button is of course also missing. I would also find it good if a call sign could be heard for the caller, now all you have to do is look at the display to see if the call has already been answered.

I know that the function is only new, there may be a bug or two

**Comment by iNPUTmice** [comment]
> i would also like to be able to switch the calls to speakers. an associated button is of course also missing. 

Audio calls will have that button. Video calls are on speaker by default

> I would also find it good if a call sign could be heard for the caller, now all you have to do is look at the display to see if the call has already been answered.

Audio calls do have audible feedback starting with `master` or 2.8.1 - for video calls you need to look at the screen anyway.

I’m leaving that issue open for the crashes. (Also note for the future that it is generally better to split problems/feedback into separate issues; otherwise it is very difficult to track them.)

**Comment by nillebor** [comment]
when a call is made from the tablet to the phone, call setup is normal. After accepting the call, calls are explained in the top bar (status bar). if you go to the message above, conversation is closed.

when you make a call from a cell phone it sounds normal. when the call is answered conversations are completely closed.

what can i do to help you find the fault?

**Comment by nillebor** [comment]
I can do that on another tablet test, with the same result

    Version: 2.8.0
    Device: Lenovo Tab4 10 Plus
    Android Version: Android 10 (LineageOS 17.1)
    Server name: jabber.de
    Conversations source: PlayStore

**Comment by iNPUTmice** [comment]
The current working theory is that this happens with audio calls on devices that don’t have an earpiece. This will probably be fixed for 2.8.2

**Comment by nillebor** [comment]
thx
