### ISSUE TITLE
[FR] Display time of incoming/outgoing/missed call

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#3685]
Just like it's done for chat messages already. This would definitely improve the UX further more. :)

**Comment by iNPUTmice** [comment]
Please elaborate on what you need that information for.

**Comment by ericschdt** [comment]
Considering it again, I think the date or at least the time of a missed call would be sufficient in order to know if it's worth calling back.

**Comment by iNPUTmice** [comment]
Closing in favor of #3692
