### ISSUE TITLE
Option to mute/unmute the loudspeaker while the call is ringing

### ISSUE THREAD

**Issue by Perflyst** [iNPUTmice/Conversations#3686]
I would like to mute myself or enable the loudspeaker while the call is not connected yet

**Comment by iNPUTmice** [comment]
The way the app works right now this will be very hard to implement. I’m trying to keep the Jingle calling code clean.

**Comment by ericschdt** [comment]
Perflyst, if you are talking about incoming calls, usually one can press the "volume down" button to mute a ringing. Is this indeed hard to implement?

**Comment by Perflyst** [comment]
@ericschdt I dont want to mute a ringing. I want to activate loudspeakers before the call starts, so that when someone says something, it is immediately audible to everyone nearby.
