### ISSUE TITLE
Right way switching a phone with Quicksy

### ISSUE THREAD

**Issue by Schlumpf** [iNPUTmice/Conversations#3690]
#### General information

* **Version:** 2.8.0
* **Server name:** quicksy.im
* **Quicksy source:** PlayStore

#### Question
What is the right way to switch a phone as a Quicksy user?
My friend has a new phone and moved his apps with a backup tool. But on the new phone, Quicksy asks him for a password. If he tries, to use Conversations on the new phone with the extracted password from the old Quicksy phone, he gets an error, telling something about "Verletzung der Richtlinien".
What should he do?

**Comment by iNPUTmice** [comment]
When in doubt you can always uninstall Quicksy and reinstall from scratch.
In general copying the password from Quicksy to Conversations should work though. Maybe they didn’t copy it properly; you get that error after too many failed attempts. Make sure the password is correct and the maybe wait a bit until you try again.

**Comment by Schlumpf** [comment]
OK, it is likely that he has entered the password too often, he has first tried all his default passwords. Is there a possibility to unlock the password again?

**Comment by iNPUTmice** [comment]
If the old phone is still around and the password has never been changed
they should still have the password visiabilty toggle and should be able to
view it and copy it to the new phone.
To circumvent the server error log out (disable the account) and don't make
any more attempts for a while.
