### ISSUE TITLE
Tones are silent when calling with vibrate & silent

### ISSUE THREAD

**Issue by tyler71** [iNPUTmice/Conversations#3697]
#### General information

* **Version:** HEAD (b6d38f8e8)+fsd
* **Device:** Nokia 7.1
* **Android Version:** 10
* **Server name:** self hosted
* **Server software:** ejabberd 20.04
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Set phone to vibrate / silent
2. Call another user

#### Expected result

Ringing (dialing), connected / busy and disconnect tone

#### Actual result

No sound. However, you can switch between sound and vibrate / silent during the call and the tones will resume.

#### Debug output

[No Sound](http://dpaste.com/2VGE4M4)
[Sound](http://dpaste.com/16DFDCW)

___

I am able to hear the tones on a Samsung J3 Android 8.1 device in sound / vibrate / silent mode.

**Comment by iNPUTmice** [comment]
I actually believe this is expected behaviour on Android. We have to pretend that the sounds are 'media' (music) for them to play in silent mode. Which I believe is wrong.
