### ISSUE TITLE
Calls don't work with personal DNS filter running

### ISSUE THREAD

**Issue by afonari** [iNPUTmice/Conversations#3703]
#### General information

* **Version:** 2.8.1 fdroid
* **Device:** BLU R1 HD
* **Android Version:**  Android 6 (stock)
* **Server name:** conversations.im
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Install personal DNS filter: https://github.com/IngoZenz/personaldnsfilter
2. Try to make a call. It gets stuck on Connecting phase.

Workaround. Add conversations to the white list.

**Comment by iNPUTmice** [comment]
Is this surprising? Is there anything Conversations should be doing differently?

**Comment by afonari** [comment]
> Is this surprising?

Not sure. I can message contacts when DNS filter is running. So this is something about audio/video. I can see that stun server (stun.conversations.im) is correctly resolved.

> Is there anything Conversations should be doing differently?

Probably not, I've created this case to mainly provide a workaround.

**Comment by licaon-kter** [comment]
It can't UDP that one?

No issue with Netguard here. ;)

**Comment by iNPUTmice** [comment]
I’m closing here. You might want to monitor: IngoZenz/personaldnsfilter/issues/82
