### ISSUE TITLE
No notification about videocalls

### ISSUE THREAD

**Issue by mase76** [iNPUTmice/Conversations#3704]
#### General information

Version:2.8.1
Device: Sony XperiaX
Android Version: Lineage 16.1 without Gservices
Server name: self hosted
Server software: Prosody 0.11.5
Installed server modules: Stream Managment, CSI, MAM, Turncredentials (100% compliant) 
Conversations source: F-Droid

#### Steps to reproduce

1. Doing a voicecall when Conversations is in the background or display is off.

#### Expected result

I get a notification about the call like normal phone calls.

#### Actual result

Nothing happens, until I take conversations to foreground. Normal messages work as expected. Battery optimization is turned off, and the foreground service is activated.

**Comment by licaon-kter** [comment]
Some logs from adb logcat would be nice.

**Comment by iNPUTmice** [comment]
It is highly likely that this is a server problem. CSI holds back the jingle messages.

https://gist.github.com/iNPUTmice/a28c438d9bbf3f4a3d4c663ffaa224d9#side-note-for-prosody-admins

**Comment by mase76** [comment]
I have updated mod_csi_battery_saver. It works now!
