### ISSUE TITLE
Make some adjustment to make org.webrtc Resolvable by Android Studio.

### ISSUE THREAD

**Issue by stevenleeS0ht** [iNPUTmice/Conversations#3711]
When open Android Studio,

It indicate the following error message below cursor `Cannot resolve symbol 'webrtc'`

#### General information

* **Version:** 2.6.0
* **Device:** Xiaomi Mi A1
* **Android Version:**  Android 9 (stock)
* **Server name:** conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 19.09.1 or prosody 0.11.3 (if known)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by kriztan** [comment]
You have to compile it yourself and than place the resulting aar into the libs folder with the given name in the build config file

**Comment by iNPUTmice** [comment]
What @kriztan points out is indeed correct. This is also mentioned in the compile instructions in the readme.
