### ISSUE TITLE
User question, how to make a audio or video call via Conversations?

### ISSUE THREAD

**Issue by stevenleeS0ht** [iNPUTmice/Conversations#3713]
Since 2.8.0, it's is said to support audio and video call, it is great. But I don't yet figure out how to do that.

And I am sure that the server I use support xep0215.

**Comment by iNPUTmice** [comment]
Use the call icon in the title bar. Make sure your contact has Conversations 2.8.0+. And you and your contact have presence subscription. And your contact isn’t using Tor.

**Comment by stevenleeS0ht** [comment]
@iNPUTmice , what is presence subscription?
