### ISSUE TITLE
Properly separate unread from read messages; Properly restore scroll position

### ISSUE THREAD

**Issue by ltGuillaume** [iNPUTmice/Conversations#3714]
#### General information

* **Version:** 2.8.2+fcr
* **Device:** Samsung Galaxy S5
* **Android Version:**  Android 9 (LineageOS 16)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open a conversation
2. Close and wait for a load of new messages
3. Open the conversation again

#### Expected result

- Restoring the scroll position to where it was when leaving the conversation in step 2.
- A clear distinction between the messages already seen and those yet to be read (depending on the scroll position when closing the conversation in step 2). A separator stating "New messages" would be the most intuitive thing to do.

#### Actual result

- I have to scroll back to where I left manually, every single time, because the conversation is opened either at the bottom, or somewhere far below the last message I saw. It kind of acts like the scroll position is saved as a percentage, which obviously won't work when new messages have been received (haven't checked the source).
- I have to re-read multiple messages in order to find out where I was before, which is so annoying that I just give up and thus miss out on several discussed topics in the conversation.

What also happens is that the conversation is wrongfully opened at the bottom and shortly after a whole stream of new messages are added while constantly jumping to the bottom. This can go on for many seconds.

**Comment by iNPUTmice** [comment]
There are currently no plans to implement this in Conversations 2.x - the outdated/non existent paging mechanism makes this virtually impossible.

**Comment by ltGuillaume** [comment]
> There are currently no plans to implement this in Conversations 2.x - the outdated/non existent paging mechanism makes this virtually impossible.

Sorry to hear that. I thought it would be quite easy to save the id of the first visible message just before exiting a room and then scrolling back to it when reopening it. That would pretty much be all it would take.

**Comment by iNPUTmice** [comment]
Storing the ID isn't the issue. Scrolling back to it is. That's probably
also why you sometimes see weird jumps and stuff like that.

**Comment by ltGuillaume** [comment]
Yeah it's basically so bad that I'd say 1/7 times it actually jumps back to the _proper_ position, the other times I'm searching my ass off for where I previously ended up ;-)

And adding a divider bar right after the stored ID isn't a possibility then?

**Comment by ltGuillaume** [comment]
> And adding a divider bar right after the stored ID isn't a possibility then?

?
