### ISSUE TITLE
Indicate server support for Audio/Video calls

### ISSUE THREAD

**Issue by jacksgt** [iNPUTmice/Conversations#3716]
Hello,

thank you for the excellent audio and video calling feature!

I thought it would be useful to indicate whether the server correctly announces a STUN/TURN server via XEP-0215 in the 'Server Info' page.

Manage Accounts > Show Server Info
![Screenshot_20200511-084856](https://user-images.githubusercontent.com/11589682/81530043-ba516600-9368-11ea-8a9b-3f76b148962b.png)

**Comment by iNPUTmice** [comment]
That’s yet another round trip on every start of the app that I would like to avoid. I think by now the [Compliance Tester](https://compliance.conversations.im) has also taken over the role of the server info screen.
