### ISSUE TITLE
If multiple URLs are present in a message, only the first one is copied

### ISSUE THREAD

**Issue by marmistrz** [iNPUTmice/Conversations#3718]
#### General information

* **Version:** 2.8.1.
* **Device:** N/A
* **Android Version:**  N/A
* **Server name:** N/A
* **Server software:** N/A
* **Installed server modules:** N/A
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Receive a message containing multiple URLs
2. Right click the second URL
3. Click "copy URL"
3. Paste.

#### Expected result
The second url is pasted

#### Actual result
The first url is pasted

#### Debug output

I guess N/A, because it's clearly an UI-related bug.
Let me know if it's really needed, then I'll get the logcat.

**Comment by iNPUTmice** [comment]
The copy URL to clipboard is a crude work around for not being able to select text. I think at the current time it's not really worth trying to improve work arounds.
