### ISSUE TITLE
[Feature request] Support Message Moderation

### ISSUE THREAD

**Issue by meaz** [iNPUTmice/Conversations#3722]
It would be nice if COnversations could support XEP-0425: Message Moderation. Prosody has a module for that: [mod_muc_moderation]( https://modules.prosody.im/mod_muc_moderation.html)
and conversejs already supports this, so I guess this is something possible.
That would be really useful to moderate a muc from a smartphone.

**Comment by iNPUTmice** [comment]
Currently not on our TODO list.
