### ISSUE TITLE
Client Cert Account can only not be added on setup process

### ISSUE THREAD

**Issue by TuxCoder** [iNPUTmice/Conversations#3724]
#### General information

* **Version:** 2.8.1+fcr (fdroid)
* **Device:** Xiaomi Mi Note 4, and other
* **Android Version:**  Android 9 (linageos)
* **Server name:** self hosted client cert only
* **Server software:**  prosody 0.11.2
* **Installed server modules:** Stream Managment, CSI, MAM,...
* **Conversations source:** F-Droid

#### Steps to reproduce

1. wipe app data
2. try to add an account with client certifiacate

#### Expected result
Be able to add an account with client certificate at setup time

#### Actual result

Can only add account with password

#### Current Workaround

Add dummy user on conversation.im and delete that later

**Comment by iNPUTmice** [comment]
Would it be possible to get a client certificate for your server? I currently don’t have the time and resources to set one up myself.

**Comment by TuxCoder** [comment]
ofc, you have me a pm contact?

**Comment by iNPUTmice** [comment]
daniel (at) gultsch (dot) de is both my email and my XMPP address
