### ISSUE TITLE
Auto hide call controls

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#3726]
...after a few seconds, show call controls if user touches the screen, hide if they touch again.

**Comment by iNPUTmice** [comment]
I think controls should remain discoverable. Otherwise people won’t know how to leave.

**Comment by licaon-kter** [comment]
The natural reaction is to touch the screen, and then the controls popup.

**Comment by ericschdt** [comment]
> I think controls should remain discoverable. Otherwise people won’t know how to leave.

People know that they still can use the back button if they want to leave by single tap. :)
Otherwise what licaon-kter says
> The natural reaction is to touch the screen, and then the controls popup.
