### ISSUE TITLE
Feature request: visual icons / color coding for a/v

### ISSUE THREAD

**Issue by tyler71** [iNPUTmice/Conversations#3727]
When receiving a call, it'd be nice if the call had a visual icon, perhaps color coded, to indicate the type of call beyond the message `Incoming [video] call`
![small](https://user-images.githubusercontent.com/4926565/81851811-e870aa80-950e-11ea-802a-f2604884d5ab.jpg) ![smallvideo](https://user-images.githubusercontent.com/4926565/81851815-e870aa80-950e-11ea-88c7-71468162d8c2.jpg)

(used [feather icons](https://feathericons.com/?query=camera) to demo)

**Comment by iNPUTmice** [comment]
I’m sorry but this doesn’t look very good.
