### ISSUE TITLE
Add room configuration for logging

### ISSUE THREAD

**Issue by larchange** [iNPUTmice/Conversations#3728]
#### General information

* **Version:** 2.8.2
* **Device:** Xiaomi
* **Android Version:**  Android 10 (stock)
* **Server name:**  self hosted
* **Server software:** metronome 3.14
* **Installed server modules:** MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Create a private room
2. Invite account B with account A
3. Discuss
4. Disconnect B
5. A send message
6. B reconnect 

#### Expected result
B should receive A's message

#### Actual result

B don't see the message

That's because Conversations don't set "logging configuration". I believe that should be the default in private muc or it need to be togglable in room configuration.

To mitigate this metronome has just added a way to configure default configuration if not provided by the client.

**Comment by licaon-kter** [comment]
Account - account - menu - Archive is Always?

**Comment by iNPUTmice** [comment]
Most servers make a distinction between logging (meaning public logs, accessible over a website) and MAM (archive available only to members).
We enable mam on most servers. See https://github.com/iNPUTmice/Conversations/blob/master/src/main/java/eu/siacs/conversations/generator/IqGenerator.java#L527-L529
If your server offers an option to enable MAM please let me know what exactly that option is called and point me to some documentation.
However we won’t enable logging by default as at least on most servers this means something else.

**Comment by maranda** [comment]
@iNPUTmice Metronome uses muc#roomconfig_enablelogging to enable channel logs, MAM as well as HTTP logs are just interfaces to the MUC logging facilities, if the HTTP interface module is loaded Metronome will check if the room is public (not hidden) before making the logs available.

**Comment by maranda** [comment]
Also before logging can be enabled the room needs to be persistent

**Comment by iNPUTmice** [comment]
From the perspective of Conversations I think it is unwise to enable 'logging' by default which some servers might treat as public logging even if Metronome specifically does have additional safety checks in front of it.

**Comment by maranda** [comment]
From the perspective of paragraph 7.2.12 of the XEP nothing says logs are http logs, the text is very clear the fact that unwisely most servers assume so is wrong, also nothing but muc#roomconfig_enablelogging is officially registered as valid FORM_TYPE for room configuration and the description clearly says:

> Whether to Enable Logging of Room Conversations

To be clear @iNPUTmice, I'm not trying to make an argument but protocol wise Metronome is correct here. So it's up to C now, and what I suggested was to add a menu option into the channel details view to enable logging not to do it by default.

**Comment by iNPUTmice** [comment]
Currently there are no plans for adding an extra button to configure logging.

Registering an extra field just for MAM has been brought up a couple of times with the XSF (last thread i found on this is from 2016) but never led anywhere. If this is important to you to have a field registered for that please bring this up with the XSF and I will support you.

**Comment by maranda** [comment]
For me it's not important at all, I know about the extra fields proposals, but I'm between the ones against that and made my opinion clear several times in the XSF chat. Alas I don't agree on enabling any form of logging by default, which is what C is doing because MAM == logging, and that's the same reason I don't think an extra field is necessary.
