### ISSUE TITLE
[Feature request] Missed call notifications

### ISSUE THREAD

**Issue by truenicoco** [iNPUTmice/Conversations#3732]
When a call is missed, a user has to manually open the conversations app to notice it. It would make sense that they are somehow more noticeable, on the lock screen for instance. A simple message-like notification would be OK I guess.

**Comment by iNPUTmice** [comment]
The other person can just send you a message if it was something important.

**Comment by jugendhacker** [comment]
I also think this is an important feature, because for normal phone calls you'll also get a notification for missed calls and so the caller might expect that it's the same with conversations and so won't send another message.
