### ISSUE TITLE
Phone in standby does not receive calls

### ISSUE THREAD

**Issue by morgenroth** [iNPUTmice/Conversations#3733]
#### General information

* **Version:** 2.8.3+pcr
* **Device:** Google Pixel 3a
* **Android Version:**  Android 10 (stock)
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** smacks, csi, mam, cloud_notify, omemo_all_access, pep_vcard_avatar, turncredentials (and more)
* **Conversations source:** PlayStore
* **Battery optimization:** Conversations is exluded from optimization

#### Steps to reproduce

1. Put device in sleep (push power button once)
2. Wait a minute
3. Try to initiate a call to the device from another device

#### Expected result

What is the expected output? 

The call screen appears and signals the call.

#### Actual result

What do you see instead?

The calling app shows the state "Ringing...", but the callee does not see anything until the device is switched on.

#### Hard guess

It looks like the device does not get any push notification via GCM for calls.
Does phone calls also trigger the GCM wake-up procedure?

**Comment by iNPUTmice** [comment]
#3704

**Comment by morgenroth** [comment]
Sorry, I did a search but did not associate that one with my issue.
Thanks for the pointer! 🙂

**Comment by morgenroth** [comment]
Just for documentation:
In my case, with prosody 0.10, an update of the csi module was not sufficient. I solved the issue for me by updating the server to prosody 0.11.
