### ISSUE TITLE
Echo when calling some specific devices

### ISSUE THREAD

**Issue by manderseck** [iNPUTmice/Conversations#3734]
#### General information

* **Version:** 2.8.3+fcr
* **Device:** Fairphone 2
* **Android Version:**  Android 7.1.2
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Call a contact that uses a Fairphone 2.
2. I will hear myself with a echo as long as I'm talking.

There shouldn't be an echo as this is very annoying. This was confirmed with other contacts using different phones. There I don't have an echo.

#### Additional information

Seems like this issue happens on phones where the hardware echo cancellation is broken and other apps have this issue as well, see the Fairphone forum:
https://forum.fairphone.com/t/echo-when-calling-via-some-apps-telegram-signal-hangout/28849/4
Since it looks like they cannot fix the hardware echo cancellation it would be cool if the mentioned switch to a software solution was a rather easy one.

**Comment by ericschdt** [comment]
Maybe an expert setting would help here as users could test it themselves easily and if it's a working solution it could be proposed as change for everyone in the included blacklist.

**Comment by susobaco** [comment]
I'm sorry, but I don't know if I understood correctly, the echo is on the phone that calls, which is not a faiphone, when you talk on a fairphone? It's like this.
Because I think that happens to me too when we call from my fairphone to a non-faiphone.

**Comment by iNPUTmice** [comment]
If you hear an echo; It's the other device that is broken.

**Comment by susobaco** [comment]
No, from my fairphone, I hear it perfect, it's the other smatphone that's not fairphone that hears its own echo. You mean it's mine that's broken?

**Comment by iNPUTmice** [comment]
@susobaco yes we are saying the same thing. If person A hears an echo it's device B that is broken. So if you (person A) call person B and person B hears an echo than your device is broken.

**Comment by susobaco** [comment]
Thank you, if you need me to run any tests, I'm at your disposal

**Comment by manderseck** [comment]
Of course I can test, too. Thanks for putting it on the roadmap so quickly!

**Comment by tapete** [comment]
Just for information.. A contact of mine was also claiming that he hears an echo when he was talking to me. I have a Huawei honor 5x KIV-L21.

**Comment by dingdongnigetou** [comment]
Maybe a solution:

Some device is not support hardware AEC, but webrtc use hardware AEC by default.

We can disable the hardware AEC when device is not supported. So how?

Let's check the newest [example ](https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/examples/androidapp/src/org/appspot/apprtc/PeerConnectionClient.java)on webrtc.

`
return JavaAudioDeviceModule.builder(appContext)
  .setSamplesReadyCallback(saveRecordedAudioToFile)
  .setUseHardwareAcousticEchoCanceler(!peerConnectionParameters.disableBuiltInAEC)
  .setUseHardwareNoiseSuppressor(!peerConnectionParameters.disableBuiltInNS)
  .setAudioRecordErrorCallback(audioRecordErrorCallback)
  .setAudioTrackErrorCallback(audioTrackErrorCallback)
  .setAudioRecordStateCallback(audioRecordStateCallback)
  .setAudioTrackStateCallback(audioTrackStateCallback)
  .createAudioDeviceModule();
`

So we can code like this `setUseHardwareAcousticEchoCanceler(WebRtcAudioUtils.isAcousticEchoCancelerSupported()`

It works for me, fix the echo issue.

**Comment by iNPUTmice** [comment]
> `setUseHardwareAcousticEchoCanceler(WebRtcAudioUtils.isAcousticEchoCancelerSupported()`

This is already the default setting.

I think the problem with echo cancellation are devices that claim to have it but don’t work properly.

**Comment by dingdongnigetou** [comment]
> I think the problem with echo cancellation are devices that claim to have it but don’t work properly.

In that case maybe we can always set it as false, force to use software AEC.
