### ISSUE TITLE
Feature request: Allow configuration of a port range for incoming connections

### ISSUE THREAD

**Issue by Andy-2639** [iNPUTmice/Conversations#3736]
There are XMPP servers without TURN support. To allow AV calls, it might helpful to support to limit the ports used for incoming connections (or UDP in general) to a user-defined range. So the user can configure (1:1) port-forwarding in his router. 
FileZilla and Miranda NG are examples for software supporting user-defined port ranges for incoming connections.

The option might be hidden behind Advanced/Expert settings like the port configuration for the XMPP server.

Supporting UPnP might also be useful.

**Comment by iNPUTmice** [comment]
This would only work in one specific network and is not a general solution.
