### ISSUE TITLE
Feature request: use XEP-0065 SOCKS5 as fallback when TURN is not available

### ISSUE THREAD

**Issue by Andy-2639** [iNPUTmice/Conversations#3737]
Conversations uses TURN for NAT traversal. As this is also used for SIP afaik, this seems to be a natural solution. However, not all XMPP servers advertise a TURN server.
At least ejabberd 20.04 needs an IP address configured for the TURN server. This can be problematic in case of an server with an dynamic IP address.

XEP-0065 also mentions (optional) UDP support. So please add support for using XEP-0065 as fallback when neither direct connection nor TURN is available (maybe also allow to use XEP-0065 TCP for AV calls when XEP-0065 UDP is unavailable).

**Comment by iNPUTmice** [comment]
I don’t think that XEP-0065 UDP is implemented anywhere. So we don’t gain anything by implementing it. On new setups you might just as well set up TURN.
