### ISSUE TITLE
Wrong chat overview sorting

### ISSUE THREAD

**Issue by jugendhacker** [iNPUTmice/Conversations#3740]
#### General information

* **Version:** 2.8.3+fcr
* **Device:** Samsung J5 2015 (j5nlte)
* **Android Version:**  Android 10 (LOS)
* **Server name:** self hosted: jugendhacker.de
* **Server software:** ejabberd 20.04
* **Conversations source:** F-Droid

#### Steps to reproduce

1. someone sends a message to a MUC while being offline
2. later the person comes online again and the message is being send with the old timestamp

#### Expected result

Conversations should still order the chats in the overview by their real newest message (the one with the newest timestamp).

#### Actual result

Conversations does display the MUC further down in the list, based on the the timestamp of the message that arrived last.

**Comment by licaon-kter** [comment]
Also in the MUC the message has the old date, so you have: new messages, old one, new messages :)

**Comment by jugendhacker** [comment]
> Also in the MUC the message has the old date, so you have: new messages, old one, new messages :)

That's not bad in my eyes, because without displaying the newly arrive message with old timestamp at the bottom you won't even register that a old message arrived...

**Comment by iNPUTmice** [comment]
I agree that this would be correct behaviour. However our database currently doesn’t support storing two time stamps. This has to wait until we eventually refactor the entire app.
