### ISSUE TITLE
Old accounts do not log in, new account does

### ISSUE THREAD

**Issue by Mothsdroyp** [iNPUTmice/Conversations#3741]
#### General information

* **Version:** 2.8.3+fcr
* **Device:** Galaxy S9
* **Android Version:**  Android 10 (stock)
* **Server name:** jabber.at, jabber.calyxinstitute.org jabber.lightwitch.org
* **Server software:** per servers above
* **Installed server modules:** per above public servers
* **Conversations source:** F-Droid

I updated conversations regularly.  Sometime after an update the jabber.at and jabber.calyxinstitute.org servers started saying "unauthorized", while the newly created account at lightwitch.org would log in.  

I downloaded a different app "aTalk" from F-droid to trouble shoot.  On the same device all accounts would log-in with aTalk, but only the 1 of 3 as above would log in from conversations.  On a computer all accounts log-in from chat client.  

On conversations I tried deleting accounts and re-creating, but it still said "unauthorized" for all except lightwitch.org, while still logging in with aTalk app on the same Samsung device.

Unfortunately I was unable to get adb logcat -s conversations to give me output (bad cable perhaps).  I will try again to get this log output later.

**Comment by licaon-kter** [comment]
Did you enable Tor by mistake?

**Comment by iNPUTmice** [comment]
I don’t think there is anything I can do about this if it worked fine on Conversations 2.8.x or 2.7.x or what ever. There haven’t been any changes to the login code in 2 years. If your password contains any non ascii characters you could try to temporarily change your password to something ascii. (To rule out potential character encoding issues)

**Comment by Mothsdroyp** [comment]
I did not enable TOR by mistake.

I have deleted and re-created my accounts and it still does not log in 2 of 3 accounts.

I have tried to get the logs off my Samsung Galaxy S9, but have found it difficult probably due to some Samsung "security" feature.  I will keep trying.

Thank you!

**Comment by iNPUTmice** [comment]
As I said previously you can change your password to something that only contains ASCII characters. The current master fixes a bug that occurs if your password contains some special characters. If this doesn’t help I don’t have any debug angle for helping you with that.

**Comment by Mothsdroyp** [comment]
Changing the password did work!
I had a randomly generated password using ASCII only.  Changing the password caused the account in question and the second account (password not changed) to start working.
I do not understand what the bug was and am happy to have the program functioning again.
Thank you again iNPUTmice for the excellent work and assistance.
