### ISSUE TITLE
Unclear security of video/audio calls

### ISSUE THREAD

**Issue by Roxxor91** [iNPUTmice/Conversations#3743]
#### General information

* **Version:** 2.8.2
* **Device:** Sasmung A3 2016
* **Android Version:**  Android 9 (LOS)
* **Server name:** self hosted
* **Server software:** prosody 
* **Installed server modules:** All needed Modules for Conversations
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Read Readme
2. No Information about Video/Audio Call Security/Technology used

#### Expected result

Find Information about Video/Audio security/technology

#### Actual result

I do not find Information about Video/Audio security/technology

#### Comment
Hi!
Thanks for the great new feature of video/audio calls. But how about security? As I see the technology is based on WebRTC? Is that correct? How about security? Is there transport encryption? End-to-End encryption? No encryption? It would be nice if the security would also be visible from the Readme/Store Information.
If there is no encryption, maybe this would help to implement it: https://jitsi.org/blog/e2ee/

**Comment by MATETH1987** [comment]
``https://github.com/iNPUTmice/Conversations/issues/3743#issue-620939665
