### ISSUE TITLE
Feature Request: Alert in the same way as for normal calls

### ISSUE THREAD

**Issue by heurekus** [iNPUTmice/Conversations#3747]
With my alerting settings, I have an ascending volume for alerting calls, i.e. very quiet at the beginning and then rising. Conversations, however, starts with the maximum volume set for alerting. Especially for quiet environments that is not ideal.

So my feature request: Honor the settings for ascending alerting tone volume. If there is no access to this setting from inside the app, perhaps it is worth considering a dedicated Conversations settings option to have an ascending volume for the alerting tone?

**Comment by iNPUTmice** [comment]
Conversations uses a normal notification to play the ringtone. This means Conversations doesn’t play the ring tone but your operating system does. It supports all features that your operating system lets you configure for notifications. If you are missing a certain feature (like ascending volume) please open a feature request with Android.
