### ISSUE TITLE
Feature Request: Upgrade a voice call to a video call

### ISSUE THREAD

**Issue by heurekus** [iNPUTmice/Conversations#3748]
It would be nice to be able to start a Conversations call as voice only (with device held to the ear) and then to upgrade it to video mode by pressing a video button (and thus also activating speaker mode at the same time). Later downgrade to voice only would also be nice (I know, this later part is sort of possible already today with switching the video off).

**Comment by iNPUTmice** [comment]
I have deliberately decided not to do this to keep both the UI and the call negotiation code simple and maintainable.
