### ISSUE TITLE
Display MUC JID in details instead of "hosted at ..." when "advanced mode" is selected

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#3750]
#### General information

* **Version:** 2.8.3
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Create a private non-anonymous MUC

#### Expected result

The MUC details says something like
`foobar@conference.blabla.im`

#### Actual result

`Hosted at conference.blabla.im`

#### Why do I need that?

Yes it's a random name, but I wanted to join my own MUC again with Dino, which simply did not autojoin or list the MUC on the server. In the end I had to invite myself via Conversations, which felt a little bit weird. I finally also got to know the MUC JID as Dino displays it. :)

I see no reason not to show the MUC JID, especially when the "advanced mode" is selected.

**Comment by iNPUTmice** [comment]
You can add a bookmark (usually this is added by default) to sync Dino.
