### ISSUE TITLE
Code Review: potential bugs in `eu/siacs/conversations/parser/MessageParser.java` line 843

### ISSUE THREAD

**Issue by stevenleeS0ht** [iNPUTmice/Conversations#3753]
The code is follow:
```java
mXmppConnectionService.getJingleConnectionManager().deliverMessage(account, packet.getTo(), packet.getFrom(), child, remoteMsgId, serverMsgId, timestamp);
```

However, `deliverMessage` method expect `(Account, Jid, Jid, Element, String, long)`, there is one more argument provided to this method.

**Comment by iNPUTmice** [comment]
I’m sorry I have no idea what you are trying to say.

**Comment by stevenleeS0ht** [comment]
@iNPUTmice , the Actual arguments are more than expected parameter.

This cause build failure.

**Comment by iNPUTmice** [comment]
Travis builds master just fine.
