### ISSUE TITLE
Please make the “X out of Y accounts connected” optional

### ISSUE THREAD

**Issue by kseistrup** [iNPUTmice/Conversations#3756]
#### General information

* **Version:** 2.8.4+fcr
* **Device:** Samsung Galaxy S8
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** prosody 0.11.5
* **Installed server modules:** Irrelevant
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Start Conversations, if not started automatically when phone was rebooted.
2. Observe the little permanent notification in the upper left corner of the phone, telling you that X out of Y accounts are connected.

#### Expected result

There should be no such notification in the top bar.

There should only be such notifications in case of an error: i.e., if an account has been disconnected.

#### Actual result

I see a permanent status thing that tells me how many of my XMPP accounts are connected right now. It cannot be swiped away and I cannot seem to find a setting that disables the behaviour.

The notification bar of my phone would be a very busy place if every running app put a notification there telling me that they were functioning correctly. Perhaps some people like to see it, who knows, but I find it just adds to all the distracting background noise of my day.

I don't mind seeing a notification (one that can be swiped away) in case of an error, but a non-removable notification about normal conditions is just noise. I would like to be able to disable it.

Thank you.

**Comment by iNPUTmice** [comment]
Please go read the readme: https://github.com/iNPUTmice/Conversations/blob/master/README.md#im-getting-this-annoying-permanent-notification

Note that F-Droid until recently lowered the targetSdk version so you don’t have to see this. However F-Droid builds are out of my immediate control.

**Comment by kseistrup** [comment]
Thanks!
