### ISSUE TITLE
message notice tone must be a ringtone

### ISSUE THREAD

**Issue by ulfi** [iNPUTmice/Conversations#3761]
#### General information

* **Version:** 2.8.4 + fcr 
* **Device:** Xperia XZ2
* **Android Version:**  Android 10 (stock) (build 52.1.A.2.1)
* **Server name:** jabber-germany.de
* **Server software:** not known
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce
No notifikation sound (tone) after update of Conversations including phone fuction or last android 10 security update.

Selecton of notification tone no more possible. On both, notification and ringtone I can only select ringtones. If I do it on notification, which each message there will be an cintinous ringtone (several times repeated)

#### Expected result
Notigication tone which will be only once repeatet

#### Actual result
If I do it on notification, which each message there will be an cintinous ringtone (several times repeated)

#### Debug output
n/a

**Comment by licaon-kter** [comment]
And yoir Android notification settings thing does not allow you to select whatever you want?

**Comment by ulfi** [comment]
Yes, I can select something else. But once I can't find the notification sounds (but this is a minor issue) and second the sound will be continous replayed (not only one time likenitifikations).
The same issue my mother reported with her Xperia XZ3.
It's strange to here the notification of a message, till you look on the message.

**Comment by licaon-kter** [comment]
XZ2 Compact on stock Pie here works as expected. Strange.

**Comment by ulfi** [comment]
I checked Otter phones like Xperia XA2 with Mai patch Kegel which also works fine. 🙃
But there must be a reason?!

**Comment by ulfi** [comment]
I checked Otter phones like Xperia XA2 with Mai patch Kegel which also works fine. 🙃
But there must be a reason?!

**Comment by ulfi** [comment]
Now I saved the settings, deinstalled conversions and installed it with reloading the settings.
Now it seams to be working like expected. Either I can select a notification tone and also it looks like it will be only once repeated.

**Comment by iNPUTmice** [comment]
Yes. There is a known bug on relatively old installations that then get upgraded to Android 10. You need to reinstall in those cases.
