### ISSUE TITLE
Failed external Video Call with Conversations (Port-Issue?)

### ISSUE THREAD

**Issue by JohnSheridan1** [iNPUTmice/Conversations#3762]
#### General information

* **Version:** 2.8.4
* **Device:** Lenovo Vibe+ ZUK / Wiko / Samsung
* **Android Version:**  Android 6 (stock), Android 9 Lineage, Android 5
* **Server name:** self hosted, fixed IP
* **Server software:** openfire 4.5.1
* **Installed server modules:** Openfire Meetings
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Openfire Server 4.5.1 behind a firewall to the Internet (Open Ports: 5222, 5223, 7777, 7443, 5262, 5263, 4443, 5275, 5276, 10000, 50000-50250) with fixed IP_Address
2. Conversations 2.8.4 on Mobiles
3. Video Call inside the Intranet ok, from outside it looks like that the other device is found and you can connect (Fon is ringing) but if you want to take the call there comes the message "Connection not possible" and abort. For a test we disabled the firewall, but even this doesn't fix the problem (Text-Messages (OMEMO) works fine).

#### Expected result

Inside the same IP-Range Video-Calls are working. What can be the reason and finally the result, that Conversations doesn't work if one of the Fones is outside the same IP-Range?

#### Actual result

No Video-Call outside Intranet possible.

**Comment by licaon-kter** [comment]
I don't see any STUN/TURN server listed there, does OpenFire include one?

**Comment by licaon-kter** [comment]
Ping @guusdk

**Comment by iNPUTmice** [comment]
Yes; you do have to setup STUN/TURN otherwise it won’t work.
https://discourse.igniterealtime.org/t/preparing-openfire-for-audio-video-calls-with-conversations/87828

**Comment by guusdk** [comment]
Openfire does not ship with a TURN server (a plugin is being worked on). There is a STUN server plugin, but I've not tested it with Conversations. The best bet is to work using extdisco, as described in the article that @iNPUTmice linked.

I notice that @JohnSheridan1 mentions OFMeet, which is an Openfire plugin that provides video conferencing functionality by embedding the Jitsi Meet stack. That feature that's provided by OFMeet is not compatible with video conferencing as provided by Conversations (and similar solutions), as in Conversations will not be able to join an OFMeet-provided conference. They're two different, incompatible solutions.

**Comment by iNPUTmice** [comment]
More information regarding coturn can be found here: https://gist.github.com/iNPUTmice/a28c438d9bbf3f4a3d4c663ffaa224d9 (I've also just updated that guide to mention the OpenFire plugin)
