### ISSUE TITLE
urn:xmpp:jingle:apps:file-transfer:5

### ISSUE THREAD

**Issue by singpolyma** [iNPUTmice/Conversations#3764]
It seems that only `urn:xmpp:jingle:apps:file-transfer:3` is used by Conversations (latest from play store) -- it appears that that was the version in 2011/2012 -- any reason it's not been updated to also offer 4 or 5?

**Comment by iNPUTmice** [comment]
It _seems_ that way? I don’t know why it seems to you like that so there is nothing I can do about it.
