### ISSUE TITLE
local client's STUN/TURN configration?

### ISSUE THREAD

**Issue by testbird** [iNPUTmice/Conversations#3768]
As only a fraction of the servers support STUN/TURN discovery, would it be possible to configure a (public or own private) STUN/TURN server in the client(s) to allow calls to work even without explicit server support?

A locally configured STUN/TURN may even be preferred above a server supplied one, e.g. for privacy, performance, or networking reasons.

**Comment by iNPUTmice** [comment]
This would be extremely confusing to the average user. Just ask your server admin to provide them for you or switch servers.

**Comment by licaon-kter** [comment]
@testbird [41% and rising](https://compliance.conversations.im/test/turn/) is more than "a fraction"

**Comment by testbird** [comment]
Ok, it's really nice to see that the default support for average users is improving.

An override option that allows to use a less crowded, user or admin specified, TURN relay server for better connections could still make sense.

**Comment by licaon-kter** [comment]
You realize that if you can use your own TURN you could use your own XMPP server to begin with, right?

**Comment by testbird** [comment]
Yes, I can do, but would not be for me directly.

What I have in mind are average users, which have an email account with included xmpp account at their providers. And the providers are not putting much effort in the XMPP support, and the users very attached to their email+xmpp contact address (good service otherwise).

By default calls don't work for them, but it might be possible to call them if I configure a custom STUN/TURN in my client before calling them. Or, they could generally use calls with their account, if they configured a custom STUN/TURN in their client.

**Comment by testbird** [comment]
Um, I've looked at XEP-0215, it talks about multiple ways to discover STUN/TURN servers, but left me puzzled about which will get selected.

Between two participants on different servers, which STUN/TURN will get used?

The calling or the called party?

The only hint I saw was
> "This [xep-0215] method SHOULD be used only as a fallback when the relevant [other] service discovery technologies  are not available to the XMPP entities involved (typically a client and server).

Relevant sources mentioned, in order, were:
* configuration defaults
* manual user configuration
* (DNS SRV, DDDS, SLP, S-NAPTR, U-NAPTR, etc.) discovery

Though it explicitly mentions client side configured servers to have a higher priority, it's not mentioning from which party.

**Comment by testbird** [comment]
The benefits of the client-side STUN/TURN server variable mentioned in xep-0215, I'd see:

* The call feature could work in many more cases, even automatically, if the client could remember the last incoming/outgoing public server as default server for following calls. 
* Throughput problems could be mitigated by configuring a specific nearer or less crowded relay (to be used as override, e.g. during travel).
