### ISSUE TITLE
using values from resolver example.com:5280 tls: false

### ISSUE THREAD

**Issue by ana-jd** [iNPUTmice/Conversations#3772]
#### General information

When i login to my ejabberd server i have the issue : stream opening error : 

2020-06-08 15:05:36.016 3374-4248/eu.siacs.conversations D/conversations: patient.test2@example.com: using values from resolver example.com:5280 tls: false

On ejabberd side : 
2020-06-08 15:13:02.592 [info] <0.835.0>@ejabberd_listener:accept:333 (#Port<0.26851>) Accepted connection 197.129.44.243:55214 -> 10.142.0.2:5280
2020-06-08 15:13:02.592 [info] <0.926.0>@ejabberd_http:init:168 started: {fast_tls,{tlssock,#Port<0.26851>,#Port<0.26852>}}

* **Version:** 2.6.0
* **Device:** Samsung a20s
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** ejabberd 17.01
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Build app
2. run it on a smartphone
3. use expert connexion parameters
4. connect
5. I have the issue "stream opening error"

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by ana-jd** [comment]
why did you close this issue without a response or guidance to another issue that could help ?

**Comment by licaon-kter** [comment]
Latest ejabberd head is 20.04 not 17.01

Latest Conversations is 2.8.6

Why do you connect to 5280 insteod of 5222?
 
What OS for server?

**Comment by ana-jd** [comment]
+ On my servers i use ejabberd 17.01 for few years now. Could that have an impact ?

+ I do use Conversations 2.8.6

+ i connect to 5280 because this is the open port
  - 
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/api": mod_http_api
      "/upload": mod_http_upload
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    captcha: false
    certfile: "/opt/ejabberd-17.01/conf/server.pem"
    tls: true

Or could it be fast_tls ?

**Comment by licaon-kter** [comment]
That's the open port for something.

You need an open port for c2s aka port 5222, see https://docs.ejabberd.im

**Comment by ana-jd** [comment]
Ok i see. Thank you very much.
