### ISSUE TITLE
No call buttons in UI

### ISSUE THREAD

**Issue by sonicnkt** [iNPUTmice/Conversations#3776]
#### General information

* **Version:** 2.8.6
* **Device:** multiple
* **Android Version:**  Android 7.8.9
* **Server name:** self hosted
* **Server software:** prosody 0.11
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

Hi im kinda pulling my hair out here. I just set up a prosody server (quite basic atm) and tested conversations (latest release on f-droid). Everything works great but i wanted to try voice/video calling just for fun.  But i don't have any buttons in the ui to initiate such a call. 

Like i said my prosody server is quite basic at the moment but as far as i understand calling should work fine atleast in the same network without a stun/turn server setup as its using p2p connections. 

Is this function missing in the f-droid version? 
Everything else works great. 
Sorry if i have missed something but i cant find any information in the ui or old issues.

**Comment by licaon-kter** [comment]
Install and configure coturn.

Read https://gist.github.com/iNPUTmice/a28c438d9bbf3f4a3d4c663ffaa224d9

/close this

**Comment by iNPUTmice** [comment]
You probably need mutual presence subscription. And your contact obviously needs latest Conversations as well.
