### ISSUE TITLE
Feature Request: Option to change playback device during calling

### ISSUE THREAD

**Issue by oksjd** [iNPUTmice/Conversations#3777]
This option is available on the stock MIUI dialling interface along with other features like call recording.

Consider the following scenario: the Android device is currently connected to an external Bluetooth audio playback device. It might be headphones. loudspeakers or boomboxes. The call is answered on the phone, but the tiny headphones are nowhere to be found, or the audio is embarrassingly coming out of the loudspeaker.

Of course it's possible to just turn off Bluetooth to use the internal speakers, however an option to switch playback device might be more flexible.

Coincidentally Google is also introducing this feature in the Android 11 release.
https://www.xda-developers.com/files/2020/06/Media_Controls.gif

**Comment by oksjd** [comment]
Just a humble suggestion. If it's too difficult to implement or the implementation varies from vendor to vendor, I'm more than happy to simply turn off bluetooth in the aforementioned occasions.

Congratulations on finally supporting video+audio calling! Working flawlessly on private IPv4 address, ULA IPv6 and globally routable IPv6. The fact that mixing these also worked really surprised me. Video calling heated up an old Huawei Mate 8 quite a bit, though.

**Comment by iNPUTmice** [comment]
Managing output devices is already quite challenging. At this point I'd rather not add any additional complexity.
