### ISSUE TITLE
History is not loaded from server if there were too many subsequent calls

### ISSUE THREAD

**Issue by vampik** [iNPUTmice/Conversations#3778]
#### General information

* **Version:** 2.8.6
* **Device:** Motorola G7 Plus
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** ejabberd 20.04
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send or receive some messages to a contact
2. Make or receive some calls from the contact (in my case, it was around 25-30 calls)
3. Clear the history and close the conversation
4. Re-open the conversation with the contact

#### Expected result

Chat history should be loaded from the server.

#### Actual result

History is not loaded from the server.

History is loaded from the server if I manually delete jingle messages from the archive database on the server.

**Comment by licaon-kter** [comment]
This is about an unencrypted chat, right?

**Comment by vampik** [comment]
> 
> 
> This is about an unencrypted chat, right?
Right.

**Comment by vampik** [comment]
Am I right that Conversations loads history in pages, 50 messages per time? I guess this happens when a page contains no text messages, but only jingle ones. I'm not a code expert, just my guess.
