### ISSUE TITLE
Media files duplication

### ISSUE THREAD

**Issue by vampik** [iNPUTmice/Conversations#3780]
#### General information

* **Version:** 2.8.6
* **Device:** Motorola G7 Plus
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** ejabberd 20.04
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send or receive some media (images, files etc) from a contact using http-upload.
Files are stored in Internal Memory/Conversations folder.
2. Clear the history with this contact and close the conversation.
3. Re-open the chat. History is reloaded from the server. Media files are re-downloaded (either manually or automatically depending on the settings).
Files are downloaded again and stored in Internal Memory/Conversations folder under a different name.

Now we have two identical sets of files in Internal Memory/Conversations folder.

I propose to:
1) either delete the corresponding media files when clearing the history
2) or better solution - keep the files, but do not re-download them. Just use already existing files after reloading the history.

**Comment by licaon-kter** [comment]
Original name gets lost (see that issue) and downloading media might not be a thing users expect (see its issue). Tricky...

Maybe based on size the app can check hashsums then deduplicate.

**Comment by iNPUTmice** [comment]
Unfortunately the current architecture doesn’t allow for that. But I will keep that in mind for a potential rewrite.
