### ISSUE TITLE
No stanza sent for jingle file transfer

### ISSUE THREAD

**Issue by singpolyma** [iNPUTmice/Conversations#3781]
#### General information

* **Version:** 2.8.6+pcr
* **Device:** Nokia 2
* **Android Version:**  Android 7.1.1
* **Server name:** self hosted
* **Server software:** prosody
* **Conversations source:** PlayStore

#### Steps to reproduce

1. add +12266661234@cheogram.com as a contact
2. Select "choose picture"
3. Choose a picture to send

#### Expected result

The server should receive a Jingle session-initiate stanza

#### Actual result

I currently have logs to show every stanza coming in from my JID, and no stanza comes it at all when I do this.  If I send a normal chat message, that stanza shows up in the logs so there's no issue there.  And Jingle file transfers from Gajim also work fine.

UI in Conversations says "waiting..." forever on the picture, since my server does not respond since it does not receive any stanza.

#### Debug output

```
06-12 23:20:13.257  1826  1826 D conversations: singpolyma@singpolyma.net send ping (action=ui,lowTimeout=false)
06-12 23:20:16.058  1826  1826 D conversations: ConversationsOverviewFragment.onStart()
06-12 23:20:16.069  1826  1826 D conversations: ConversationsOverviewFragment.onResume()
06-12 23:20:16.230  1826  1826 D conversations: app switched into foreground
06-12 23:20:23.741  1826  1826 D conversations: ConversationsOverviewFragment.onPause()
06-12 23:20:57.145  1826  1851 D conversations: singpolyma@singpolyma.net: running mam query with=+12266661234@cheogram.com, end=2020-06-13T03:16:37.546Z, order=REVERSE, catchup=false, ns=urn:xmpp:mam:2
06-12 23:20:57.333  1826  1826 D conversations: action: eu.siacs.conversations.action.VIEW
06-12 23:20:57.342  1826  1826 D conversations: ConversationFragment.onAttach()
06-12 23:20:57.392  1826  1826 D conversations: reInit(hasExtras=true)
06-12 23:20:57.392  1826  1826 D conversations: trimming conversation
06-12 23:20:57.422  1826  1826 D conversations: scrolledToBottomAndNoPending=true
06-12 23:20:57.423  1826  1826 D conversations: jump to first unread message
06-12 23:20:57.523  1826  1826 D conversations: ConversationFragment.onBackendConnected()
06-12 23:20:58.069  1826  2618 D conversations: singpolyma@singpolyma.net: persisted roster in 694ms
06-12 23:20:58.088  1826  1888 D conversations: skipping shortcut update
06-12 23:20:58.240  1826  1888 D conversations: skipping shortcut update
06-12 23:20:58.245  1826  2618 D conversations: singpolyma@singpolyma.net: persisted roster in 175ms
06-12 23:20:59.645  1826  2389 D conversations: singpolyma@singpolyma.net: finished mam after 0(0) messages. messages left=false count=0
06-12 23:20:59.646  1826  2389 D conversations: singpolyma@singpolyma.net: found 0 pending receipt requests
06-12 23:20:59.852  1826  2389 D conversations: singpolyma@singpolyma.net: gained mutual presence subscription with +12266661234@cheogram.com
06-12 23:20:59.911  1826  1888 D conversations: skipping shortcut update
06-12 23:20:59.917  1826  2618 D conversations: singpolyma@singpolyma.net: persisted roster in 219ms
06-12 23:21:00.113  1826  1888 D conversations: skipping shortcut update
06-12 23:21:00.118  1826  2618 D conversations: singpolyma@singpolyma.net: persisted roster in 201ms
06-12 23:21:07.813  1826  1826 D conversations: app switched into background
06-12 23:21:09.565  1826  1826 D conversations: guessMimeTypeFromUriAndMime content://com.android.providers.media.documents/document/image%3A43863 and mime=null
06-12 23:21:09.621  1826  1826 D conversations: reInit(hasExtras=false)
06-12 23:21:09.633  1826  1826 D conversations: scrolledToBottomAndNoPending=true
06-12 23:21:09.633  1826  1826 D conversations: jump to first unread message
06-12 23:21:09.707  1826  1826 D conversations: app switched into foreground
06-12 23:21:09.708  1826  1826 D conversations: ConversationFragment.onBackendConnected()
06-12 23:21:11.713  1826  1826 D conversations: ConversationsActivity.commitAttachments() - attaching image to conversations. CHOOSE_IMAGE
06-12 23:21:11.778  1826  1826 D conversations: singpolyma@singpolyma.net: not compressing picture. sending as file
06-12 23:21:11.779  1826  1826 D conversations: attachFile: type=2
06-12 23:21:11.779  1826  1826 D conversations: counterpart=null
06-12 23:21:11.779  1826  1826 D conversations: guessMimeTypeFromUriAndMime content://com.android.providers.media.documents/document/image%3A43863 and mime=image/jpeg
06-12 23:21:11.826  1826  1826 D conversations: received uri permission for content://com.android.providers.media.documents/document/image%3A43863
06-12 23:22:47.746  1826  1826 D conversations: app switched into background
06-12 23:23:01.205  1826  1826 D conversations: reInit(hasExtras=false)
06-12 23:23:01.245  1826  1826 D conversations: scrolledToBottomAndNoPending=true
06-12 23:23:01.245  1826  1826 D conversations: jump to first unread message
06-12 23:23:01.270  1826  1826 D conversations: load more messages for +12266661234 prior to 2020-06-13T03:21:11.779Z
06-12 23:23:01.321  1826  1826 D conversations: app switched into foreground
06-12 23:23:01.322  1826  1826 D conversations: ConversationFragment.onBackendConnected()
06-12 23:23:18.802  1826  1826 D conversations: ConversationsOverviewFragment.onStart()
06-12 23:23:18.804  1826  1826 D conversations: ConversationsOverviewFragment.onResume()
06-12 23:23:21.489  1826  1826 D conversations: ConversationFragment.onAttach()
06-12 23:23:21.490  1826  1826 D conversations: ConversationsOverviewFragment.onPause()
06-12 23:23:21.557  1826  1826 D conversations: reInit(hasExtras=true)
06-12 23:23:21.557  1826  1826 D conversations: trimming conversation
06-12 23:23:21.602  1826  1826 D conversations: scrolledToBottomAndNoPending=true
06-12 23:23:21.602  1826  1826 D conversations: jump to first unread message
06-12 23:23:21.654  1826  1826 D conversations: load more messages for +12266661234 prior to 2020-06-13T03:21:11.779Z
06-12 23:23:26.912  1826  1826 D conversations: desired=112.0 real=120
06-12 23:23:26.912  1826  1826 D conversations: preliminary count=6
06-12 23:23:27.068  1826  1826 D conversations: desired=112.0 real=115
06-12 23:23:27.068  1826  1826 D conversations: final count 6
06-12 23:23:31.500  1826  1888 D conversations: skipping shortcut update
06-12 23:23:31.502  1826  2618 D conversations: singpolyma@singpolyma.net: persisted roster in 259ms
06-12 23:23:32.591  1826  1826 D conversations: reInit(hasExtras=false)
06-12 23:23:32.604  1826  1826 D conversations: scrolledToBottomAndNoPending=true
06-12 23:23:32.604  1826  1826 D conversations: jump to first unread message
06-12 23:23:32.648  1826  1826 D conversations: load more messages for +12266661234 prior to 2020-06-13T03:21:11.779Z
06-12 23:23:32.667  1826  1826 D conversations: ConversationFragment.onBackendConnected()
06-12 23:23:33.923  1826  1826 D conversations: ConversationsOverviewFragment.onStart()
06-12 23:23:33.924  1826  1826 D conversations: ConversationsOverviewFragment.onResume()
06-12 23:24:00.690  1826  1826 D conversations: ConversationsOverviewFragment.onPause()
```

**Comment by iNPUTmice** [comment]
Does Conversations know the contact is online? (Green send button)

**Comment by singpolyma** [comment]
Yes

**Comment by iNPUTmice** [comment]
What’s the resource of the contact?

**Comment by singpolyma** [comment]
No resource. Most clients that show this show it as blank,  it I think 
the component actually sends presence from a bare jid.

**Comment by iNPUTmice** [comment]
Does [this APK](https://gultsch.de/files/Conversations-2.8.7-beta-conversations-playstore-compat-universal-release.apk) fix the issue for you?

Do you know if this used to work in the past? Or is jingle file transfer a new feature in cheogram.com?

**Comment by singpolyma** [comment]
It did used to work with both conversations and gajim, but new versions 
of each stopped working with our jingle some time ago and I've just this 
week been making changes to get it working again. Have Gajim working 
again, so working on conversations compatibility now.

That linked APK crashes when I try to jingle a file to cheogram:

Version: 2.8.7-beta+pcr(391)
Last Update: 2020-06-13
SHA-1: 6f:80:8b:e7:c4:81:e6:f0:16:f7:19:ba:9d:6e:d7:af:c3:1c:44:5e

java.lang.NullPointerException: Attempt to invoke virtual method 'int 
java.lang.Object.hashCode()' on a null object reference
at java.util.Hashtable.hash(Hashtable.java:172)
at java.util.Hashtable.containsKey(Hashtable.java:339)
at eu.siacs.conversations.entities.Presences.has(Presences.java:108)
at 
eu.siacs.conversations.entities.Message.fixCounterpart(Message.java:749)
at 
eu.siacs.conversations.services.XmppConnectionService.sendMessage(XmppConnectionService.java:1423)
at 
eu.siacs.conversations.services.XmppConnectionService.resendMessage(XmppConnectionService.java:1567)
at 
eu.siacs.conversations.services.XmppConnectionService.lambda$sendUnsentMessages$12$XmppConnectionService(XmppConnectionService.java:1563)
at 
eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$Zlu0Fd3njB1X5EkTa4klnNMqsF0.onMessageFound(lambda)
at 
eu.siacs.conversations.entities.Conversation.findWaitingMessages(Conversation.java:194)
at 
eu.siacs.conversations.services.XmppConnectionService.sendUnsentMessages(XmppConnectionService.java:1563)
at 
eu.siacs.conversations.services.XmppConnectionService.access$900(XmppConnectionService.java:160)
at 
eu.siacs.conversations.services.XmppConnectionService$4.onStatusChanged(XmppConnectionService.java:391)
at 
eu.siacs.conversations.xmpp.XmppConnection.changeStatus(XmppConnection.java:227)
at 
eu.siacs.conversations.xmpp.XmppConnection.finalizeBind(XmppConnection.java:1260)
at 
eu.siacs.conversations.xmpp.XmppConnection.lambda$sendServiceDiscoveryInfo$4$XmppConnection(XmppConnection.java:1234)
at 
eu.siacs.conversations.xmpp.-$$Lambda$XmppConnection$ZvoSBGNOmf67dcD_h3B33nvgPQM.onIqPacketReceived(lambda)
at 
eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:757)
at 
eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:635)
at 
eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:483)
at 
eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:801)
at 
eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:467)
at 
eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:375)
at 
eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:454)
at java.lang.Thread.run(Thread.java:761)

**Comment by iNPUTmice** [comment]
I’ve replaced the APK in place with a possible fix for the crash.
(See recent changes in master)

**Comment by singpolyma** [comment]
Still crashes, but new backtrace:

Version: 2.8.7-beta+pcr(391)
Last Update: 2020-06-13
SHA-1: 6f:80:8b:e7:c4:81:e6:f0:16:f7:19:ba:9d:6e:d7:af:c3:1c:44:5e

java.lang.IllegalArgumentException
at 
com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
at 
eu.siacs.conversations.xmpp.jingle.AbstractJingleConnection$Id.<init>(AbstractJingleConnection.java:51)
at 
eu.siacs.conversations.xmpp.jingle.AbstractJingleConnection$Id.of(AbstractJingleConnection.java:73)
at 
eu.siacs.conversations.xmpp.jingle.JingleConnectionManager.startJingleFileTransfer(JingleConnectionManager.java:418)
at 
eu.siacs.conversations.services.XmppConnectionService.sendFileMessage(XmppConnectionService.java:1375)
at 
eu.siacs.conversations.services.XmppConnectionService.sendMessage(XmppConnectionService.java:1424)
at 
eu.siacs.conversations.services.XmppConnectionService.resendMessage(XmppConnectionService.java:1567)
at 
eu.siacs.conversations.services.XmppConnectionService.lambda$sendUnsentMessages$12$XmppConnectionService(XmppConnectionService.java:1563)
at 
eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$Zlu0Fd3njB1X5EkTa4klnNMqsF0.onMessageFound(lambda)
at 
eu.siacs.conversations.entities.Conversation.findWaitingMessages(Conversation.java:194)
at 
eu.siacs.conversations.services.XmppConnectionService.sendUnsentMessages(XmppConnectionService.java:1563)
at 
eu.siacs.conversations.services.XmppConnectionService.lambda$new$1$XmppConnectionService(XmppConnectionService.java:224)
at 
eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$V7FL_axuFonosKINhhamQRKkpZ8.onContactStatusChanged(lambda)
at 
eu.siacs.conversations.parser.PresenceParser.parseContactPresence(PresenceParser.java:324)
at 
eu.siacs.conversations.parser.PresenceParser.onPresencePacketReceived(PresenceParser.java:374)
at 
eu.siacs.conversations.xmpp.XmppConnection.processPresence(XmppConnection.java:780)
at 
eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:639)
at 
eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:483)
at 
eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:801)
at 
eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:467)
at 
eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:375)
at 
eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:454)
at java.lang.Thread.run(Thread.java:761)

**Comment by iNPUTmice** [comment]
I hadn’t considered Jingle with a bare JID to be a valid use case. So they were multiple places that either don’t support this or outright prevent it.
Anyway I have updated the APK again with the safety check that caused the crash removed.

**Comment by singpolyma** [comment]
With that APK it now works! Conversations reports delivery failed when it 
in fact succeeds, but that's a very different kind of problem I can 
chase.

Thanks!

**Comment by iNPUTmice** [comment]
Ok. Let me know if you have reason to believe that Conversations is behaving badly.
I’m closing here since the original issue has been resolved.

**Comment by iNPUTmice** [comment]
FWIW we had a discussion around this in the XSF chat a while ago and using XMPP-IM presences without resource doesn’t seem to be spec compliant behaviour.

I’m not just going to revert the 'fixes' I made but you should know that those weren’t really fixes.
