### ISSUE TITLE
Confusing "call connected" tone/sound

### ISSUE THREAD

**Issue by di72nn** [iNPUTmice/Conversations#3782]
#### General information

The "call connected" tone used in Conversations sounds either very similar or exactly like the default "call **ended**" tone (at least on Lineage OS, maybe also on AOSP).
A friend of mine also complained about the same problem on MIUI, but I haven't had the chance to check it.

* **Version:** 2.8.6
* **Android Version:**  Android 8 and 9 (official Lineage OS, no GApps)
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Initiate a voice call.
2. Pick up on the other end.

#### Expected result

The "call connected" tone is different from the default "call disconnect" tone.

#### Actual result

A confusing tone is heard.

Thank you very much for the app and for implementing audio calls in particular!

**Comment by iNPUTmice** [comment]
The code is here:
https://github.com/iNPUTmice/Conversations/blob/2.8.6/src/main/java/eu/siacs/conversations/xmpp/jingle/ToneManager.java#L112-L116
feel free to test and suggest something else.

**Comment by iNPUTmice** [comment]
No reaction from op. Closing.

**Comment by di72nn** [comment]
I asked a couple of people about this. It was unanimous that `TONE_PROP_PROMPT` should be used as the call "ending" tone (apparently it is widely used in phone dialers).
Call "connected" tone is not usually present (or enabled by default) in phone dialers, so there's no consensus. `TONE_CDMA_ABBR_INTERCEPT` (~150 ms) seems to be noticeable enough, but not too distracting for that role.

There's also a suggestion to add a short vibration as a call "connected" indicator, but that may be a matter of preference.

**Comment by iNPUTmice** [comment]
I’ll give that a shot thank you.

**Comment by iNPUTmice** [comment]
Hi,

thank you for your suggestion. I've listened to the alternative and I personally like the status quo better.
