### ISSUE TITLE
Photo capture issue

### ISSUE THREAD

**Issue by ana-jd** [iNPUTmice/Conversations#3783]
#### General information

Photo capture is not functional. Video recording et voice recoding, file attachment function just great but not photo capture.

When i take a photo it is not attached and i can't send it.

* **Version:** 2.8.6+
* **Device:** Sumsung S10
* **Android Version:**  Android 9 (stock)
* **Server name:** conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 19.09.1
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** HEAD

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
Please provide logcat out.

**Comment by ana-jd** [comment]
i'll do ASAP

**Comment by iNPUTmice** [comment]
No reaction from op. Closing here.
