### ISSUE TITLE
Jingle file transfer, says "delivery failed" even though it succeeded

### ISSUE THREAD

**Issue by singpolyma** [iNPUTmice/Conversations#3786]
Hi, me trying to get jingle transfer to cheogram.com to work again.

So, here is what Conversations debug log says when I do a transfer to any +1<tel>@cheogram.com JID:

```
06-15 14:25:17.078  1298  1298 D conversations: send file message
06-15 14:25:17.711  1298  4243 D conversations: successfully connected to our own proxy65 candidate
06-15 14:25:17.718  1298  4243 D conversations: ...: sending S5B offer with 3 candidates
06-15 14:25:17.845  1298  1358 D conversations: ...: other party received offer
06-15 14:25:18.043  1298  1358 D conversations: ...: received candidate error
06-15 14:25:20.269  1298  4249 D conversations: established connection with jingle.cheogram.com:1080
06-15 14:25:20.271  1298  4249 D conversations: ...: elected candidate jingle.cheogram.com:1080 (priority=8323071,ours=false)
06-15 14:25:20.271  1298  4249 D conversations: we were initiating. sending file
06-15 14:25:20.390  1298  4260 D conversations: successfully transmitted file:/storage/emulated/0/...
```

So, debug log seems to thing it worked.  And Cheogram also agrees that it worked and relays over MMS as requested.  However, Conversations' UI (using the custom APK you sent me on the last issue) says "delivery failed" with error message "unknown request"

Looking at the XMPP-side chatter between Conversations and cheogram.com, it looks pretty straightforward:

1. session-initiate (from Conversations)
2. session-accept (from cheogram)
3. candidate-error (from cheogram)
4. candidate-used (from Conversations)
5. session-info (checksum, from Conversations)
6. I have code to send session-info, `{urn:xmpp:jingle:apps:file-transfer:5}received` when done, when it is present Conversations debug log has an additional message about an unknown IQ.  Removing this code from Cheogram gets rid of that debug line, but does not change the behaviour otherwise.

I'm spelunking around Conversations' jingle code trying to find all the ways it could fail, but if you have any guesses where I should look that would be super helpful :)

**Comment by iNPUTmice** [comment]
What’s the response to the session-info? I think Conversations might fail if it gets an IQ error back for that.

**Comment by singpolyma** [comment]
Yes! That was it, thanks.
