### ISSUE TITLE
[Request] Add the option to search inside individual conversations like you can do on the conversation homepage

### ISSUE THREAD

**Issue by oathzed** [iNPUTmice/Conversations#3787]
#### General information

* **Version:** 2.4.1-playstore
* **Device:** Pixel 2
* **Android Version:**  Android 10 (stock)
* **Server name:** dismail.de
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Inside a conversation select the search icon on the top right to search inside that conversation

#### Expected result

What is the expected output? 

This isn't added

#### Actual result

What do you see instead?

Nothing

**Comment by iNPUTmice** [comment]
#3243
