### ISSUE TITLE
Add button to mute the microphone during a call

### ISSUE THREAD

**Issue by merge** [iNPUTmice/Conversations#3789]
#### General information

* **Version:** 2.8.6+fcr
* **Device:** Nexus 5X
* **Android Version:**  Android 8.1 (LineageOS)
* **Server name:** jabber.at
* **Conversations source:** F-Droid

#### Steps to reproduce

1. audio call (be called or call)

#### Expected result

Have a button to mute the microphone during a call.

#### Actual result

Only the one button to hang up. No option to mute the mic.

**Comment by iNPUTmice** [comment]
Please provide a screenshot of the in-call UI. The vast majority of users (including myself) do have a mute button next to the hang up button.

**Comment by iNPUTmice** [comment]
No reaction from op. Closing.
