### ISSUE TITLE
Jingle RTP sessions: Initiator doesn’t parse transport-info prior to session-accept

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/Conversations#3790]
As the initiator of a Jingle RTP session we don’t parse transport-infos that arrive prior to the session-accept (as we need information from the session-accept to properly process them). However we should just batch up the entire transport info with all candidates for later processing instead of the (improperly) processed candidate like we do right now.

**Comment by ostasevych** [comment]
If this refers to this case: I cannot receive a call from JSXC. Just after establishing the connection it breaks. Observed at 2.8.6. Witn 2.8.7. it doesn't work the same...
