### ISSUE TITLE
Bluetooth No Audio Input

### ISSUE THREAD

**Issue by Adam-Stambaugh** [iNPUTmice/Conversations#3791]
#### General information

* **Version:** 2.8.6+fcr
* **Device:** Google Pixel (Sailfish)
* **Android Version:**  LineageOS 16.0 (AOSP 9.0)
* **Server name:** conversations.im
* **Server software:** ejabberd 19.05.13-conversations.im
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Connect bluetooth headset or a PC setup with ofono and pulseaudio configured to use it.
2. Call someone.

#### Expected result

They would be able to hear you.

#### Actual result

They can't hear you. If I toggle off bluetooth audio with the option right of the hang-up button, then they can hear me through the built-in mic. It happens consistently. I can't get any form of bluetooth audio input to work with it, while they work fine with other apps and the system.

**Comment by licaon-kter** [comment]
Works for me with BT heaphones.

Logs?

**Comment by Adam-Stambaugh** [comment]
It's not the cleanest, grabbed it while in a bit of a hurry, but it has me connecting my headset and initiating a call via Conversations.
[logcat - bluetooth conversations test.txt](https://github.com/iNPUTmice/Conversations/files/4787467/logcat.-.bluetooth.conversations.test.txt)

**Comment by iNPUTmice** [comment]
Works fine here as well.

> If I toggle off bluetooth audio with the option right of the hang-up button

That’s not a switch. If it shows the bluetooth icon it just means that bluetooth is being used. Pressing it doesn’t toggle anything. https://github.com/iNPUTmice/Conversations/blob/master/src/main/java/eu/siacs/conversations/ui/RtpSessionActivity.java#L743-L746

**Comment by Adam-Stambaugh** [comment]
> Works fine here as well.
> 
> > If I toggle off bluetooth audio with the option right of the hang-up button
> 
> That’s not a switch. If it shows the bluetooth icon it just means that bluetooth is being used. Pressing it doesn’t toggle anything. https://github.com/iNPUTmice/Conversations/blob/master/src/main/java/eu/siacs/conversations/ui/RtpSessionActivity.java#L743-L746

Oh sorry, I was not rigorous enough in my testing. Must have disconnected around the same time. My headphones were dying at the time. Disconnecting my headphones does pass the input back to the built-in mic just fine.

**Comment by Adam-Stambaugh** [comment]
I ended up flash LineageOS 17.1 to my Pixel. After that it started working fine. I have no idea why Conversations had issues while Linphone and the built-in phone app didn't, but seems like it was an issue with the older version of LineageOS. Thank you, anyway!
