### ISSUE TITLE
Direct search - apply to all roster views

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#3793]
...like invite contact _(has search icon already)_ or share _(needs search icon too)_ and others that I might have missed.

**Comment by iNPUTmice** [comment]
The screen you are seeing when using 'share with Conversations' is not the roster view but the open conversation view. You can hit + to go to the contacts screen (which will have a search icon).

**Comment by licaon-kter** [comment]
But no Direct Search....
