### ISSUE TITLE
Allow to provision accounts using QR code in Welcome Activity

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/Conversations#3796]
The QR code scanner in the welcome activity (first screen in Conversations) should allow to scan QR codes with some JSON string roughly similar to the following in order to easily add new accounts.
```json
{
  "protocol": "xmpp",
  "address": "user@domain.tld",
  "password": "secret"
}
```
Tools like `ejabberdctl register ` or `prosodyctl` should display a matching QR code directly at the console. (Likewise some registration web interfaces could display them after successful registration)

**Comment by iNPUTmice** [comment]
implemented in 15489547b79cc7ecc31b5bbdb65342ac6c582906

**Comment by Zash** [comment]
I thought there existed an URI form for this already, `xmpp://username:password@server.tld`

**Comment by mimi89999** [comment]
There are already 2 different types of codes in Conversations. The code for adding a contact and the code for registering on a server. I fear that if a third type of code will start being used, users might mix them up and share the wrong one.

**Comment by licaon-kter** [comment]
Can they really share from the app the code to register on a server?
