### ISSUE TITLE
Unexpected call retracting on Samsung phones with Android <= 6

### ISSUE THREAD

**Issue by vampik** [iNPUTmice/Conversations#3802]
#### General information

* **Version:** 2.8.7
* **Device:** Samsung J5 2016
* **Android Version:**  Android 6 (stock)
* **Server name:** self hosted
* **Server software:** ejabberd 20.04
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Make a call to a contact
2. Move the phone to the ear before the connection established

#### Expected result

Call continues.

#### Actual result

Call is retracted.

I've encountered another issue with older Samsung phones. It is not as critical as screen blinking but it affects user experience. My friend was unable to call me until I figured this out and asked him not to move the phone to the ear before the connection is established.

This happens because onStop() calls retractSessionProposal() if the connection is not yet established"

```
        if (jingleRtpConnection != null) {
            releaseVideoTracks(jingleRtpConnection);
        } else if (!isChangingConfigurations()) {
            if (xmppConnectionService != null) {
                retractSessionProposal();
            }
        }
```

Could this be fixed somehow? I guess just removing retractSessionProposal() from here might have side effects?

**Comment by licaon-kter** [comment]
Seen this too on A5 (2015).
