### ISSUE TITLE
unable to find STARTTLS for registration process

### ISSUE THREAD

**Issue by aviral0809** [iNPUTmice/Conversations#3805]
While connecting to my openfire server from conversations app I'm getting following response:
**unable to find STARTTLS for registration process** in my logs.
In the openfire server configuration and I'm using ip instead of domain name and my openfire server is behind the load balancer. 
Rarely  its  getting connected on server most of the time I'm getting server not found message   on my mobile application.

**Comment by iNPUTmice** [comment]
Conversations will only register (and login) over a secure connection.
