### ISSUE TITLE
The standard keyboard shortcut for correcting messages doesn't work

### ISSUE THREAD

**Issue by marmistrz** [iNPUTmice/Conversations#3806]
#### General information

* **Version:** 2.8.6
* **Device:** F(x)tec Pro1
* **Android Version:**  LineageOS 16.0
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Type a message and send it
2. Press ctrl+up

#### Expected result
App should enter last message correction (this is a fairly standard shortcut, supported by Gajim and Rocket.Chat)

#### Actual result
Nothing happens

#### Debug output

Probably N/A, but let me know if this would actually help with anything, I'll get a logcat.

**Comment by marmistrz** [comment]
Thanks!

**Comment by marmistrz** [comment]
On 2.8.9+fcr (F-Droid) ctrl+arrow up doesn't seem to do anything for me.

**Comment by marmistrz** [comment]
(I'll try debugging it during the weekend, I just reported it quickly as soon as I noticed)

**Comment by marmistrz** [comment]
I've managed to find the root cause. If logging is added to the new implementation of `onKeyDown`, only the following events appear:
```
07-25 13:57:24.597  8574  8574 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=4504791, downTime=4504791, deviceId=0, source=0x101 }
```
In particular, there is no key event for ctrl+up emitted. 

This may happen due to the fact that `EditText` handles ctrl+arrow left/right as moving the cursor to the next word and the key event is probably not propagated to `ConversationFragment`. I can confirm that `ctrl+o` causes two events to be emitted: the first one for `ctrl`, the other one for `ctrl+o`

I suppose that `EditMessage` is the correct place to add support for this keyboard shortcut.
However, I don't see any easy way of fixing it: `ConversationFragment` communicates information **to** `EditMessage` using `KeyboardListener` and we need the other direction, and `EditMessage` is the child/descendant of `ConversationFragment` as far as I can see.

Please reopen.

**Comment by marmistrz** [comment]
I've managed to find the root cause. If logging is added to the new implementation of `onKeyDown`, only the following events appear:
```
07-25 13:57:24.597  8574  8574 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=4504791, downTime=4504791, deviceId=0, source=0x101 }
```
In particular, there is no key event for ctrl+up emitted. 

This may happen due to the fact that `EditText` handles ctrl+arrow left/right as moving the cursor to the next word and the key event is probably not propagated to `ConversationFragment`. I can confirm that `ctrl+o` causes two events to be emitted: the first one for `ctrl`, the other one for `ctrl+o`

I suppose that `EditMessage` is the correct place to add support for this keyboard shortcut.
However, I don't see any easy way of fixing it: `ConversationFragment` communicates information **to** `EditMessage` using `KeyboardListener` and we need the other direction, and `EditMessage` is the child/descendant of `ConversationFragment` as far as I can see.

Please reopen.

**Comment by iNPUTmice** [comment]
It looks like you are emitting Ctrl+left when hitting control up on your
keyboard. You probably need to press Ctrl right on your keyboard if the
phone is turned counter clockwise.

**Comment by marmistrz** [comment]
For my device's hardware keyboard both ctrl keys seem to emit left ctrl, so I can't check if right ctrl works at the moment. I'll check an external USB keyboard later today.

But why would only right ctrl work in Conversations?
My experience with Gajim/Rocket.Chat is that leftctrl+up works for these apps and this was the expected UX.

**Comment by marmistrz** [comment]
I can confirm that using an external USB keyboard, rightctrl+up doesn't work either.
```
07-25 18:22:58.080 18245 18245 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=12213213, downTime=12213213, deviceId=12, source=0x101 }
07-25 18:22:58.246 18245 18245 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=12213381, downTime=12213381, deviceId=12, source=0x101 }
07-25 18:22:59.318 18245 18245 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=12214453, downTime=12214453, deviceId=12, source=0x101 }
07-25 18:23:04.154 18245 18245 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=12219285, downTime=12219285, deviceId=12, source=0x101 }
07-25 18:23:04.651 18245 18245 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x88, repeatCount=1, eventTime=12219786, downTime=12219285, deviceId=12, source=0x101 }
07-25 18:23:04.696 18245 18245 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=2, eventTime=12219837, downTime=12219285, deviceId=12, source=0x101 }
07-25 18:23:04.731 18245 18245 E conversations: KeyDown: 43, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_O, scanCode=24, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=12219869, downTime=12219869, deviceId=12, source=0x101 }
07-25 18:23:05.810 18245 18245 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=12220949, downTime=12220949, deviceId=12, source=0x101 }
07-25 18:23:05.977 18245 18245 E conversations: KeyDown: 43, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_O, scanCode=24, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=12221117, downTime=12221117, deviceId=12, source=0x101 }
07-25 18:23:06.527 18245 18245 E conversations: KeyDown: 113, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x8, repeatCount=0, eventTime=12221669, downTime=12221669, deviceId=12, source=0x101 }
07-25 18:23:10.502 18245 18245 E conversations: KeyDown: 114, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_RIGHT, scanCode=97, metaState=META_CTRL_ON|META_CTRL_RIGHT_ON, flags=0x8, repeatCount=0, eventTime=12225637, downTime=12225637, deviceId=12, source=0x101 }
07-25 18:23:12.074 18245 18245 E conversations: KeyDown: 114, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_RIGHT, scanCode=97, metaState=META_CTRL_ON|META_CTRL_RIGHT_ON, flags=0x8, repeatCount=0, eventTime=12227213, downTime=12227213, deviceId=12, source=0x101 }
```

**Comment by iNPUTmice** [comment]
Looks to me like a bug in Android. There is no onKeyDown() event fired for Ctrl-Arrow up and Ctrl-Arrow Down. It works correctly for Ctrl-Arrow Left and Ctrl-Arrow Right as well as the corresponding onKeyUp event.

**Comment by marmistrz** [comment]
However, https://github.com/alt236/KeyEvent-Display---Android displays a separate event for ctrl+up.

**Comment by marmistrz** [comment]
@iNPUTmice for some reason the sequence tab, ctrl-up works and corrects the message. Probably because it focuses the send button.
