### ISSUE TITLE
Video calls to IOS: monal, siskin IM not working

### ISSUE THREAD

**Issue by dfszb** [iNPUTmice/Conversations#3807]
#### General information

* **Version:** 2.8.6
* **Device:** Oneplus 5t
* **Android Version:**  Android 9 (stock)
* **Server name:** conversations.im
* **Conversations source:**F-Droid

#### Steps to reproduce

1. Install the software on Iphone (software is either monal or siskin im)
2. Video Call from contact from Iphone or vice versa.

#### Expected result
Connection is made and call works

#### Actual result

Conversations and other side stays in 'connecting'.

Not including more info as this is probably expected.

**Comment by iNPUTmice** [comment]
Monal uses an incompatible standard and won’t be compatible.

Siskin should be compatible if you use their latest beta. (And network conditions may apply as I don’t know if they support 0215 yet.)

**Comment by tmolitor-stud-tu** [comment]
To all people finding this in the future: Monal reimplemented all A/V stuff beginning with version 6.0 and now uses the same standard like Conversations, Dino, Siskin etc.
