### ISSUE TITLE
Permanent "connected" notification, with F-Droid version.

### ISSUE THREAD

**Issue by shh0** [iNPUTmice/Conversations#3811]
#### General information

* **Version:** 2.6.8.7+fcr
* **Device:** Xiaomi Mi A1
* **Android Version:**  Android 9 (stock)
* **Server name:** self
* **Server software:** prosody 0.11.4
* **Installed server modules:** all
* **Conversations source:** F-Droid

Hello,
I'm getting this permanent notification about being connected, though I'm using the F-Droid version of Conversations.
Here, you write that this wouldn't be the case: https://github.com/iNPUTmice/Conversations#im-getting-this-annoying-permanent-notification
Is there any checkbox to switch this notification off that I missed? Thanks and cheers…

**Comment by iNPUTmice** [comment]
F-Droid is now forcing the notification too.

**Comment by licaon-kter** [comment]
@shh0 use the Notification settings to hide that Foreground channel, only.
