### ISSUE TITLE
https://quicksy.im website provides no visible app impression

### ISSUE THREAD

**Issue by testbird** [iNPUTmice/Conversations#3812]
For the intended audience, https://quicksy.im can seem questionably real or lead to dismissing if wanting "to have a look", and there is nothing to see.

Maybe some of the icon graphics or appstore screenshot clippings can be shown on the homepage, too.

**Comment by iNPUTmice** [comment]
I recommend you link potentially interest parties directly to the play store. The website is aimed at people who understand what XMPP and Conversations are to tell them the differences between Quicksy and Conversations.
