### ISSUE TITLE
[feature request] show more information about received vcard

### ISSUE THREAD

**Issue by nycex** [iNPUTmice/Conversations#3817]
#### General information
* **Version:** 2.8.7
* **Android Version:**  Android 10
* **Conversations source:** F-Droid

#### Steps to reproduce
1. go into the contacts app
2. select contact
3. share via conversations
4. send the message
5. click on "OPEN CONTACT"

#### Expected result
You see information like the name of the contact and possibly also the phone number of a contact before importing preferably even before having to click on any button.

#### Actual result
Even if you fully import the contact, you never actually see, what the name of the imported contact is.

**Comment by joe-average-user** [comment]
+1

**Comment by iNPUTmice** [comment]
At this point I don’t think I want to maintenance burden of implementing previews for all possible file formats.

**Comment by joe-average-user** [comment]
Well, what kind of maintenance do you expect for displaying _some selected_ vcard field if you ought to know anyway that it is a contact, else you cannot display "open contact" ... ?

**Comment by nycex** [comment]
Would you accept a pull request on this issue?

**Comment by iNPUTmice** [comment]
> Would you accept a pull request on this issue?

This depends. The initial coding is not what I’m worried about. Maintaining is. And a one time PR doesn’t remove the burden of having to maintain it for years. However if you can proof that it is only ~2 lines of code or what than I'm happy to look at the PR.
