### ISSUE TITLE
Closing / Quitting multiple conversations with one click event.

### ISSUE THREAD

**Issue by suuhm** [iNPUTmice/Conversations#3821]
#### General information

* **Version:** 2.8.x
* **Android Version:**  Android 9 (stock)

#### Expected result

It would be great if there is a way to close / quit multiple or all conversations with one click (insteat of manually swipe it away for example)

Is there a way to do this as a feature?

**Comment by iNPUTmice** [comment]
I don’t think we need a short cut for that action.
