### ISSUE TITLE
Feature request: Call UI button to return to chat

### ISSUE THREAD

**Issue by UniqueActive** [iNPUTmice/Conversations#3825]
Hello,

first of all great work on the A/V calls, they are a really good experience so far :)

One thing I find very inconvenient though is getting back to sending messages while on call. There is no button to switch to chat and pressing back in the Android UI ends the call.

I suggest the following:
1. Adding a button in the call UI to return to chat (and vice versa) and
2. changing the behaviour of the back button to simply go back to chat without hanging up, since I expect the call to end when I hang up, not when I try to go back to the previous screen.

Let me know your thoughts!

**Comment by licaon-kter** [comment]
Press HOME....open Conversations

**Comment by UniqueActive** [comment]
> Press HOME....open Conversations

@licaon-kter I am aware of that solution and am currently resorting to that, but I find it unintuitive and bad UI and UX, which is why I opened the issue :)
