### ISSUE TITLE
"Retracted call" UI when returning to Call with app switcher

### ISSUE THREAD

**Issue by UniqueActive** [iNPUTmice/Conversations#3826]
#### General information

* **Version:** 2.8.8+fcr
* **Device:** Samsung Galaxy S8
* **Android Version:**  Android 9 (LineageOS)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Start a Call
2. Use the Android app switcher button (or press the home button)
3. Switch back to Conversations using the app switcher

#### Expected result

The regular call interface of the ongoing call shows

#### Actual result

The "Retracted call" interface shows, though the call timer is still ticking and the call is still correctly ongoing

**Comment by iNPUTmice** [comment]
This is only during dialing and expected behaviour in order to get out of a call quickly in case you pressed a wrong button.

**Comment by UniqueActive** [comment]
> This is only during dialing and expected behaviour in order to get out of a call quickly in case you pressed a wrong button.

@iNPUTmice I am not sure I understand you correctly; for me this happens during an ongoing call, not dialing, and the call is still ongoing, not stopped. Did I misunderstand you or did you misunderstand me?
