### ISSUE TITLE
Support ctrl+enter for sending messages 

### ISSUE THREAD

**Issue by marmistrz** [iNPUTmice/Conversations#3827]
#### General information

* **Version:** 2.6.0
* **Device:** F(x)tec Pro1
* **Android Version:**  LOS 16.0

#### Description

Currently we have an option to use enter as send.
On devices with a hardware keyboard, however, it's desirable to use enter as a newline and ctrl+enter (or some other shortcut) as send.

I'll file a PR in a while.

**Comment by licaon-kter** [comment]
2.8.8 right?

**Comment by marmistrz** [comment]
Yes.
