### ISSUE TITLE
Group Shows "No members" and inviting  does not work

### ISSUE THREAD

**Issue by fymwpm** [iNPUTmice/Conversations#3829]
#### General information

* **Version:** 2.8.8 +fcr 
* **Device:** Fairfone 3
* **Android Version:**  Android 9 
* **Server name:** jabb.im
* **Server software:** 
* **Installed server modules:** 
* **Conversations source:** F-Droid, 

#### Steps to reproduce

1. Created new group
2. Invite participants
3. Post to group
4. Confirm With participants,that Post ist beeing Received.
5. Wait for some time
6. Post to group again

#### Expected result

What is the expected output? 
Post will be received by group members.

#### Actual result

Post ist Not beeing  sent Error message Shows: only participants to the group are allowed to send. When looking at group Details no participants are shown. When group participants Look at group Details, my Account ist shown as owner and all participants are visible.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
Try another server too

**Comment by fymwpm** [comment]
Test Started With Jabber.de will Report on Test result.

**Comment by fymwpm** [comment]
Created new Account at jabber.de
Added existing contact
Created new private group under Jabber.de Account.
Invited contact
Succesfully exchanged Messages in private group.
Restarted Phone
Opened conversations
Group Shows No participants
Error reproduced With different account

**Comment by iNPUTmice** [comment]
It looks like Conversations is unable to connect to the group chat server. I suggest you get in contact with your server admin to figure out why.

**Comment by fymwpm** [comment]
As I said, I tried it with two different servers. Problem occured on both. Could you please suggest a server which works with conversations?

**Comment by licaon-kter** [comment]
Can you try with both accounts on trashserver.net or draugr.de ?

**Comment by fymwpm** [comment]
Tried it on trashserver and there it works.
Thanks for your support!

**Comment by licaon-kter** [comment]
That jabb.im server doesn't look that good, maybe that's why: https://compliance.conversations.im/server/Jabb.im/

Eg. ejabberd is at version 20.04 they have a 3years old one.

**Comment by fymwpm** [comment]
This looks like an explanation, should have verified this before chosing jabb.im. Thanks for this information.
