### ISSUE TITLE
Improve tolerance for bad connections/interruptions

### ISSUE THREAD

**Issue by UniqueActive** [iNPUTmice/Conversations#3830]
Hello!

When calling from Germany with my partner in India, the calls frequently end due to connectivity issues. When using Linphone for the same purpose and in the same situations every day throughout the past year, we found it to be more tolerant to interruptions in the connection, while Conversation seems to terminate the call very quickly once the connection is lost for about a second.

I imagine this would be a general issue for people who live in places with bad connectivity and internet infrastructure, so improving the tolerance for internet drops that last a few seconds would do a great deal for a lot of people who don't live in places with fantastic internet infrastructure. So instead of terminating the call after a second or so, it would be great if it tried to reconnect or just kept waiting for signal for 3-5 seconds before terminating.

I don't know how much control you have over this behaviour since you use an external library for much of the actual calling, but since Linphone is able to provide great tolerance to interruptions, I reckoned I should at least bring it up here because calling again every 5-10 minutes gets old very quickly. :)

**Comment by Allespro** [comment]
I have similar problem. When I try to call from my phone to another which isn't in local network, ringtone starts but no connection.

**Comment by ValdikSS** [comment]
@iNPUTmice, I have the same issue on a near-perfect internet connection on both sides. The call is drops without any prior problems with network connection stability. Some time disconnection could happen only in seconds after the call has been established, the other time it may work for a dozens of minutes.

Here's the log which I recorded during the call. Both phones were on (different) Wi-Fi networks. I suppose the phone performs some background network operations and then trigger 'reconnection' notification, even if there was no reconnection (`MdiSyncBackgroundTaskService MdiSyncModule`?). This happens on Wi-Fi and LTE. Both conversation parties have 2.9.2+pcr.

Check `12-26 13:04:45.459`.

[logcat.zip](https://github.com/iNPUTmice/Conversations/files/5742955/logcat.zip)

**Comment by ValdikSS** [comment]
@iNPUTmice, just a while ago today, during 15 minutes voice conversation the connection dropped for 8 (!) times, every 30 secs - 3 minutes.
If you have any clue of the reasons of that, at least what could be checked, let me know.

**Comment by Allespro** [comment]
Hello. I just created two accounts on 404.city and make call. Everyting working good. Works from local and different networks.

**Comment by ValdikSS** [comment]
@UniqueActive, do you still see this issue on recent Conversations versions? It seems fixed for me, I'm now able to talk hours without interruptions.

**Comment by iNPUTmice** [comment]
This has been improved in 2.10.3 https://github.com/iNPUTmice/Conversations/blob/master/CHANGELOG.md#version-2103
