### ISSUE TITLE
Make buttons for loudspeaker and microphone accessible instantly after triggering a call

### ISSUE THREAD

**Issue by Norbert80** [iNPUTmice/Conversations#3831]
It would be great to change Conversations/Quicksy so that loudspeaker and microphone are already accessible at the very beginning of call initialization.

It is annoying to carefully listen and watch for call initialization procedure with the phone not on the ear until I can turn on the loudspeaker.

Most phone apps have loudspeaker and microphone buttons accessible instantly. Android GSM call app, Signal, Linphone and others...

**Comment by iNPUTmice** [comment]
This is pretty hard to due in the way we structured our code and I don’t think it's worth doing.

**Comment by heurekus** [comment]
I use voice calling in Conversations quite heavily and also stumble over this quite often - I start the call and would like it to be on speaker by pressing a button straight away before the other end accepts the call so I don't need to look (same as for normal voice calls). Would be a really nice feature to have!

**Comment by aslmx** [comment]
I had a usability training once and was taught that one key of usability is learnt-behavior-patterns. (most important example: the save button ;)). 
I think it would be beneficial if A/V-Calls in conversations behaved similar to how A/V Calls work in generic Android dialer.

I support this FR and would appreciate the issue being reopened.

**Comment by Norbert80** [comment]
@iNPUTmice There seems to be broad interest in a solution to this problem. Can we reopen it?

**Comment by iNPUTmice** [comment]
This has been implemented in https://codeberg.org/iNPUTmice/Conversations/commit/17c1b175bf3fccfaa2ea22fa70d3b2589d0c624a and will likely ship with 2.14.0
