### ISSUE TITLE
Feature Request: Implement Requesting Voice for moderated MUCs

### ISSUE THREAD

**Issue by dduenker** [iNPUTmice/Conversations#3835]
#### General information

* **Version:** 2.8.8+fcr
* **Device:** OnePlus 3T
* **Android Version:**  Android 10 (LineageOS 17.1)
* **Server name:** trashserver.net
* **MUC:** angrytux@conference.trashserver.net
* **Server software:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join a moderated Channel (e.g. angrytux@conference.trashserver.net)
2. Try to write in the channel - you cannot, as you are a visitor
3. Try to request voice - you cannot, there is no option in Conversations to do this

#### Expected result

Upon Joining a moderated MUC, the text input field could contain a "request voice" button, which enables the user to ask for permission to participate in the conversation.

#### Actual result
 
I cannot send anything to the channel, nor can i figure out how to request voice with this client.

#### More Information
The feature is described in [xep-0045](https://xmpp.org/extensions/xep-0045.html#requestvoice)

**Comment by dduenker** [comment]
Thanks, that is a workaround, which i will make use of, but the implementation of a more intuitive way would appear more favorable for the average user nonetheless.
Or at least a hint, that sending private messages to an admin is a viable method of obtaining voice.

**Comment by dduenker** [comment]
Update: Whispering is not really a solution, when the the option to send a direct message to an admin is greyed out and thus unusable.
As i do not actually get to see more than their name, i do not even know where to send a message by hand. How should i know on which server the account of the admin is?

**Comment by iNPUTmice** [comment]
MUC has many many features. I don’t think Conversations should implement them all. We have to draw the line somewhere and I think we should draw it here.
The main issue with requesting voice is that this essentially requires you to also grant voice requests. And this will introduce a complexity to Conversations that really only benefits a tiny minority of users.

**Comment by mdosch** [comment]
I think a button to request voice would already help. Especially as some MUCs switch to moderated when there is a spam wave going on. MUC admins/operators will also have a full-featured client like gajim at hand for handling those requests.

**Comment by tarbindmitry** [comment]
**you guys, send me invite, please!**
+79269003509

**Comment by licaon-kter** [comment]
We've got grant member, grant admin and grant owner.

Is voice so complicated?

**Comment by raucao** [comment]
I just ran into this issue, too. As @mdosch explained, a button to request voice would solve the problem for all users joining moderated public channels. And it would not require new moderator features (i.e. granting voice) directly in Conversations.

As it stands right now, a person only using Conversations, and no other client, is unable to participate in public moderated channels at all.

**Comment by mdosch** [comment]
Conversations moved to codeberg and I'm not sure whether github issues still get read.
https://codeberg.org/iNPUTmice/Conversations/issues

Am 30. Oktober 2023 16:06:15 UTC schrieb "Râu Cao" ***@***.***>:
>I just ran into this issue, too. As @mdosch explained, a button to request voice would solve the problem for all users joining moderated public channels. And it would not require new moderator features (i.e. granting voice) directly in Conversations.
>
>As it stands right now, a person only using Conversations, and no other client, is unable to participate in public moderated channels at all.
>

**Comment by licaon-kter** [comment]
afaik they still are, no need to open a duplicate issue elsewhere instead, imho
