### ISSUE TITLE
Feature Request: Status and Priority Support

### ISSUE THREAD

**Issue by lord-aerion** [iNPUTmice/Conversations#3836]
Before this gets dismissed offhand, yes, I have read the FAQ and seen the rationale behind the motivation to not include these "legacy features. I disagree with this rationale, however, as it paints a very one-sided picture.

The problem is the curse of having to be connected 24/7. Skype, WhatsApp, Hangouts, etc. are all designed to be online 24/7, however it is not always desirable to be contactable. While many people may forget or be too lazy to set a status, as argued in the FAQ, I would argue that people have been "trained" to not set a status because of developers gradually removing this option from chat clients. This is akin to saying that people don't use wired headphones anymore, which is why Apple removed the headphone socket from devices (and other manufacturers followed suit).

The ability to set my own status is important to me, so that I can be offline when I want or need to be, or indicate that I don't wish to be disturbed. I use multiple XMPP accounts, all for different purposes. I need the ability to be offline on one account, and set DND on another. The current rationale does not allow for such a use case; it's an alway on approach, take it or leave. The only way to be offline or set any other status to indicate you're not available is to either turn your phone off, disconnect it from WiFi/mobile data, or to uninstall the app. None of these "solutions" are practical or acceptable.

Similarly, the ability to set priority is important. When I'm on my desktop, that's where I want to receive my messages, without both my mobile phone and my tablet going off with an alert too. When I'm away from my desktop, say to make tea in the kitchen, I want to receive my messages on my mobile or tablet there instead.

Not having these features in Conversations means not having control over one's conversations. No one seems to ask the question whether all users _want_ to be online at all times, and to call this old behaviours that need to be got rid of is bizarre to say the least, if not bordering on arrogance.

The argument that I might not want my contacts to know that I was using my computer at 4am holds no water either. What if I don't care? As it happens, I don't, as my friends and family know that I'm often online in the middle of the night as I'm a sound engineer and work evenings, coming home at 2, 3, 4am. And if I did care, guess what? I'd set my status to offline. When I put my phone away, I actually quite like the idea that it automatically sets my status to Away, and then later to Extended Away, so that it tells my contacts that I'm not likely to respond soon.

The modern "replacements" for these alleged legacy features are not replacements at all as they do not address the same use cases.

It feels very much like this is the personal opinion of the developer, rather than a technological argument. The statuses are argued to be a horrible metric and to not work because of lack of user actions, rather than because of a technological shortcoming or a poor implementation of the feature.

I actively use both statuses and priorities, and would most definitely like to see these added to Conversations. They do serve a purpose, even more so now that we are spending so much of our time online, with not many options to get away from it.

**Comment by iNPUTmice** [comment]
The FAQ is actually a little bit outdated on that topic. You can set your status message and your availability. Go to expert settings and enable 'Manage availability manually'.

There are also other XMPP clients that provide you with a 'more traditional' XMPP user experience. Namely Yaxim and Xabber. This is not mean to be as a _f* off_ but as a general reminder that this is the beauty of XMPP. You have a choice between different clients. If all clients would behave the same there would be no point in having different clients.

**Comment by lord-aerion** [comment]
Thanks for pointing out the steps. I've taken a look at it, but it's setting one's status is not exactly user friendly. It's quite hidden away, and requires multiple steps to get to, not exactly something one does on the fly.

I agree with you that the beauty of XMPP is that you have a choice in clients. I have already looked at the clients you mention, as well as others, but unfortunately there isn't much meaningful choice. If there was, I wouldn't have bothered requesting this feature in Conversations.

Xabber refuses to implement OMEMEO, and I quote from their most recent comment from 2018 on Github "just don't try to press me into buying this bullshit about e2e and infect me with this crypto-cancer."

Yaxim has no support for OMEMO, citing issues with Smack as well as lack of time (in 2018). An offer by another developer to help in 2018 has gone unanswered and the feature request remains open until this day.

Pix-Art Messenger is nothing more than a Conversations clone with an improved menu structure and OpenPGP support.

Stork IM doesn't work my XMPP accounts (two different servers), and even if it did, it doesn't support settings status per account, making it pretty useless if you want to be online on your business account and DND on your personal account.

aTalk is very buggy, with frequent dis- and reconnnects, OMEMO errors that mysteriously go away and then come back, and has a UI that is as far removed from Material Design as it can be.

Several other are either (very dodgy lookin) Conversations forks, obsolete, tied to a specific server, lack features I want/need or have such poor ratings that they're not even worth trying.

There really isn't as much choice as one might think.

I also fundamentally disagree with the notion that there's no point in having different clients if all offer the same functionality. Some clients are better designed than others. Stork and aTalk, for example, make setting one's status as easy as it is on desktop clients, just one tap away. Conversations and Pix-Art Messenger have this hidden away, obscured behind several steps. And even when it comes to Conversations and Pix-Art Messenger, with the latter merely being a fork of the former, I prefer Pix-Art Messenger because of its better designed menu structure. So there is definitely  space in the market for multiple XMPP clients, even if they offer the same features.

**Comment by licaon-kter** [comment]
> Pix-Art Messenger is nothing more than a Conversations clone with an improved menu structure and OpenPGP support.

Umm Conversations has OpenPGP  support, what do you mean?

**Comment by lord-aerion** [comment]
Oops, that was meant to be OTR, which I see has been removed anyway in a recent update. Not that I care either way as I use OMEMO.
