### ISSUE TITLE
Feature Request: Improved manual availability (Status)

### ISSUE THREAD

**Issue by lord-aerion** [iNPUTmice/Conversations#3837]
Manually setting a status and/or message is cumbersome. It first needs to be activated under "Expert Settings" (I didn't even know this feature existed until it was pointed out to me), then requires 4 taps to get to before one can change one's status, and finally another two taps to get back to the main screen.

In comparison, aTalk has the status menu available from the main screen, just one tap away:
![aTalk set status](https://user-images.githubusercontent.com/11840341/88198432-97321500-cc3b-11ea-80e3-47ca8f7f8823.png)

Stork IM has it inside the main menu, again just one tap away:
![Stork IM set status](https://user-images.githubusercontent.com/11840341/88198534-b5981080-cc3b-11ea-928a-f34f8ab49489.png)

I'm also puzzled as to why this needs to be hidden away in an Expert Settings menu, with a "Please be careful with these" warning. Pix-Art Messenger simply has an "Availability" entry under "Settings".

**Comment by licaon-kter** [comment]
Touch your avatar....touch status icon...?

**Comment by lord-aerion** [comment]
How illogical. I would _never_ have found that. Furthermore, that drives home the point about the need for an Offline option even more, instead of having to click the 3 dots menu -> Manage Accounts -> hit the toggle.

**Comment by lord-aerion** [comment]
Why not simply make the status icon available in the top bar, with a menu similar to the other aforementioned apps?

**Comment by iNPUTmice** [comment]
Moving this away from the account screen would mean that you can’t set status individually any more (or you ask for the account first in which case you will end up with the exact same number of touches.)

**Comment by lord-aerion** [comment]
aTalk manages to do this from the main screen, with a global status, as well as a per account status, all from within the same menu, and with just one tap.

![Screenshot_20200722-180010](https://user-images.githubusercontent.com/11840341/88205872-4c1cff80-cc45-11ea-8838-f8b898ac8336.png)
