### ISSUE TITLE
Feature Request: Add Offline status

### ISSUE THREAD

**Issue by lord-aerion** [iNPUTmice/Conversations#3838]
The current manual status option only provide

- Online
- Away
- Not Available
- Busy

An option to go offline entirely is absent, however, in contrast to aTalk and Stork IM.

![Screenshot_20200722-164625](https://user-images.githubusercontent.com/11840341/88199391-b7160880-cc3c-11ea-8866-340f7bf0b243.png)
![Screenshot_20200722-164657](https://user-images.githubusercontent.com/11840341/88199403-baa98f80-cc3c-11ea-8fb8-e80e56a0be19.png)

Can you please add an offline option?

**Comment by licaon-kter** [comment]
Account - toggle account off

/close this

**Comment by lord-aerion** [comment]
While that certainly achieves the desired result, from a UX perspective it's inconsistent. This belongs in the status menu, together with the other possible statuses. It's no logical to have to perform one status action in one place, and other status action in another.

**Comment by iNPUTmice** [comment]
As @licaon-kter pointed out you can just disable the account.

**Comment by lord-aerion** [comment]
I read that. As I pointed out it is inconsistent to have to perform what's essentially the same action in two different places. I don't see why having an Offline status added to the already existing statuses would be an issue.  It certainly would make for a better and more consistent experience.

**Comment by licaon-kter** [comment]
Could you join the support MUC so we don't volley comments here?
