### ISSUE TITLE
Parse IPv6 URIs properly

### ISSUE THREAD

**Issue by tdemin** [iNPUTmice/Conversations#3841]
#### General information

* **Version:** 2.8.9
* **Device:** bq Aquaris X
* **Android Version:**  Android 10 (Lineage OS)
* **Conversations source:** Play Store

#### Steps to reproduce

1. Add any valid IPv6 HTTP link with no domain but the IP instead to your message and send the message.
2. Conversations will display a broken link.

* **Expected result:** Conversations displays a properly highlighted link
* **Actual result:** Conversations displays a broken link where only http(s):// is highlighted.

Screenshot:
![Screenshot_20200724-193705_Conversations_1](https://user-images.githubusercontent.com/26599554/88402853-20d11680-cde5-11ea-958e-1abd5b400651.png)

**Comment by iNPUTmice** [comment]
Fixed in ca08c27eef6493d799fdd6600ac8cc9e36ba0002
