### ISSUE TITLE
Conversation crashes on startup

### ISSUE THREAD

**Issue by numbenutzer** [iNPUTmice/Conversations#3842]
#### General information

* **Version:** 2.8.9+fcr(395)
* **Device:** Samsung Galaxy S7 (herolte)
* **Android Version:**  Android 9 (lineageos 16)
* **Server name:** self hosted
* **Server software:** prosody
* **Conversations source:** F-Droid

#### Steps to reproduce

Switch from any app to conversations, either by home screen or task selection.
This is not reproducable all the time, but at least several times a day.

The problem is existing for several months now, but I can't tell since which version. :-(
At the moment I am investigating, if this is an Android or conversations issue, because it's the only app that crashed, but the error message seems to lead in the direction of rendering, which should not be caused by the app itself.

#### Expected result

Conversations opens.

#### Actual result

Conversations crashes.

#### Debug output

CONVERSATIONS Exception

java.lang.IllegalArgumentException
	at android.os.Parcel.createException(Parcel.java:1954)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3756)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
	at android.app.Activity.startActivityForResult(Activity.java:4587)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
	at android.app.Activity.startActivityForResult(Activity.java:4545)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
	at android.app.Activity.startActivity(Activity.java:4906)
	at android.app.Activity.startActivity(Activity.java:4874)
	at eu.siacs.conversations.ui.XmppActivity.switchToContactDetails(XmppActivity.java:524)
	at eu.siacs.conversations.ui.XmppActivity.switchToContactDetails(XmppActivity.java:515)
	at eu.siacs.conversations.ui.ConversationFragment.onOptionsItemSelected(ConversationFragment.java:1247)
	at android.app.Fragment.performOptionsItemSelected(Fragment.java:2669)
	at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3183)
	at android.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:371)
	at android.app.Activity.onMenuItemSelected(Activity.java:3547)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
	at android.widget.AbsListView$3.run(AbsListView.java:4052)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.view.SurfaceControl.nativeCreate(Native Method)
	at android.view.SurfaceControl.(SurfaceControl.java:630)
	at android.view.SurfaceControl.(SurfaceControl.java:60)
	at android.view.SurfaceControl$Builder.build(SurfaceControl.java:386)
	at com.android.server.wm.WindowContainer.onParentSet(WindowContainer.java:184)

LOGCAT

--------- beginning of crash
07-23 21:35:38.106  6167  7203 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 7203 (RenderThread), pid 6167 (s.conversations)
07-23 21:35:38.258 13754 13754 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-23 21:35:38.258 13754 13754 F DEBUG   : LineageOS Version: '16.0-20200712-UNOFFICIAL-herolte'
07-23 21:35:38.258 13754 13754 F DEBUG   : Build fingerprint: 'samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU2ERD5:user/release-keys'
07-23 21:35:38.259 13754 13754 F DEBUG   : Revision: '0'
07-23 21:35:38.259 13754 13754 F DEBUG   : ABI: 'arm64'
07-23 21:35:38.259 13754 13754 F DEBUG   : pid: 6167, tid: 7203, name: RenderThread  >>> eu.siacs.conversations <<<
07-23 21:35:38.259 13754 13754 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-23 21:35:38.259 13754 13754 F DEBUG   : Abort message: 'Failed to set damage region on surface 0x75db0c5880, error=EGL_BAD_ACCESS'
07-23 21:35:38.259 13754 13754 F DEBUG   :     x0  0000000000000000  x1  0000000000001c23  x2  0000000000000006  x3  0000000000000008
07-23 21:35:38.259 13754 13754 F DEBUG   :     x4  feff71647164636d  x5  feff71647164636d  x6  feff71647164636d  x7  7f7f7f7f7f7f7f7f
07-23 21:35:38.259 13754 13754 F DEBUG   :     x8  0000000000000083  x9  a208e0b119efa6a1  x10 fffffff87ffffbdf  x11 0000000000000001
07-23 21:35:38.259 13754 13754 F DEBUG   :     x12 fffffffc7ffffbdf  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
07-23 21:35:38.259 13754 13754 F DEBUG   :     x16 000000768d2b32a8  x17 000000768d1f2540  x18 00000000ffffffff  x19 0000000000001817
07-23 21:35:38.259 13754 13754 F DEBUG   :     x20 0000000000001c23  x21 0000000000000083  x22 00000075ee0fe1b0  x23 00000075e83a14b0
07-23 21:35:38.259 13754 13754 F DEBUG   :     x24 0000000000000001  x25 00000075e83a1424  x26 00000075ee0fe198  x27 00000075e83a1422
07-23 21:35:38.259 13754 13754 F DEBUG   :     x28 0000000000000000  x29 00000075ee0fdaf0
07-23 21:35:38.259 13754 13754 F DEBUG   :     sp  00000075ee0fdab0  lr  000000768d1e6210  pc  000000768d1e6230
07-23 21:35:38.329 13754 13754 F DEBUG   : 
07-23 21:35:38.329 13754 13754 F DEBUG   : backtrace:
07-23 21:35:38.329 13754 13754 F DEBUG   :     #00 pc 0000000000022230  /system/lib64/libc.so (abort+112)
07-23 21:35:38.329 13754 13754 F DEBUG   :     #01 pc 0000000000008388  /system/lib64/liblog.so (__android_log_assert+328)
07-23 21:35:38.329 13754 13754 F DEBUG   :     #02 pc 00000000004ad034  /system/lib64/libhwui.so (android::uirenderer::renderthread::EglManager::damageFrame(android::uirenderer::renderthread::Frame const&, SkRect const&)+180)
07-23 21:35:38.329 13754 13754 F DEBUG   :     #03 pc 00000000004a65fc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::FrameBuilder::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, bool, android::uirenderer::BakedOpRenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::Re
07-23 21:35:38.329 13754 13754 F DEBUG   :     #04 pc 000000000010ba60  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+192)
07-23 21:35:38.329 13754 13754 F DEBUG   :     #05 pc 00000000004ab96c  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+652)
07-23 21:35:38.329 13754 13754 F DEBUG   :     #06 pc 0000000000461130  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+176)
07-23 21:35:38.329 13754 13754 F DEBUG   :     #07 pc 0000000000119b48  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+248)
07-23 21:35:38.330 13754 13754 F DEBUG   :     #08 pc 000000000000ff68  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+264)
07-23 21:35:38.330 13754 13754 F DEBUG   :     #09 pc 000000000008b574  /system/lib64/libc.so (__pthread_start(void*)+36)
07-23 21:35:38.330 13754 13754 F DEBUG   :     #10 pc 0000000000023c64  /system/lib64/libc.so (__start_thread+68)
07-24 07:56:16.322 13767 13799 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 13799 (RenderThread), pid 13767 (s.conversations)
07-24 07:56:16.485 32495 32495 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-24 07:56:16.485 32495 32495 F DEBUG   : LineageOS Version: '16.0-20200712-UNOFFICIAL-herolte'
07-24 07:56:16.485 32495 32495 F DEBUG   : Build fingerprint: 'samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU2ERD5:user/release-keys'
07-24 07:56:16.485 32495 32495 F DEBUG   : Revision: '0'
07-24 07:56:16.486 32495 32495 F DEBUG   : ABI: 'arm64'
07-24 07:56:16.486 32495 32495 F DEBUG   : pid: 13767, tid: 13799, name: RenderThread  >>> eu.siacs.conversations <<<
07-24 07:56:16.486 32495 32495 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-24 07:56:16.486 32495 32495 F DEBUG   : Abort message: 'Failed to set damage region on surface 0x75e88ad180, error=EGL_BAD_ACCESS'
07-24 07:56:16.486 32495 32495 F DEBUG   :     x0  0000000000000000  x1  00000000000035e7  x2  0000000000000006  x3  0000000000000008
07-24 07:56:16.486 32495 32495 F DEBUG   :     x4  feff71647164636d  x5  feff71647164636d  x6  feff71647164636d  x7  7f7f7f7f7f7f7f7f
07-24 07:56:16.486 32495 32495 F DEBUG   :     x8  0000000000000083  x9  a208e0b119efa6a1  x10 fffffff87ffffbdf  x11 0000000000000001
07-24 07:56:16.486 32495 32495 F DEBUG   :     x12 fffffffc7ffffbdf  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
07-24 07:56:16.486 32495 32495 F DEBUG   :     x16 000000768d2b32a8  x17 000000768d1f2540  x18 00000000ffffffff  x19 00000000000035c7
07-24 07:56:16.486 32495 32495 F DEBUG   :     x20 00000000000035e7  x21 0000000000000083  x22 00000075ef3af1b0  x23 00000075ea5a1e70
07-24 07:56:16.486 32495 32495 F DEBUG   :     x24 0000000000000001  x25 00000075ea5a1de4  x26 00000075ef3af198  x27 00000075ea5a1de2
07-24 07:56:16.486 32495 32495 F DEBUG   :     x28 0000000000000000  x29 00000075ef3aeaf0
07-24 07:56:16.486 32495 32495 F DEBUG   :     sp  00000075ef3aeab0  lr  000000768d1e6210  pc  000000768d1e6230
07-24 07:56:16.575 32495 32495 F DEBUG   : 
07-24 07:56:16.575 32495 32495 F DEBUG   : backtrace:
07-24 07:56:16.575 32495 32495 F DEBUG   :     #00 pc 0000000000022230  /system/lib64/libc.so (abort+112)
07-24 07:56:16.575 32495 32495 F DEBUG   :     #01 pc 0000000000008388  /system/lib64/liblog.so (__android_log_assert+328)
07-24 07:56:16.575 32495 32495 F DEBUG   :     #02 pc 00000000004ad034  /system/lib64/libhwui.so (android::uirenderer::renderthread::EglManager::damageFrame(android::uirenderer::renderthread::Frame const&, SkRect const&)+180)
07-24 07:56:16.575 32495 32495 F DEBUG   :     #03 pc 00000000004a65fc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::FrameBuilder::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, bool, android::uirenderer::BakedOpRenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::Re
07-24 07:56:16.575 32495 32495 F DEBUG   :     #04 pc 000000000010ba60  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+192)
07-24 07:56:16.575 32495 32495 F DEBUG   :     #05 pc 00000000004ab96c  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+652)
07-24 07:56:16.575 32495 32495 F DEBUG   :     #06 pc 0000000000461130  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+176)
07-24 07:56:16.576 32495 32495 F DEBUG   :     #07 pc 0000000000119b48  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+248)
07-24 07:56:16.576 32495 32495 F DEBUG   :     #08 pc 000000000000ff68  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+264)
07-24 07:56:16.576 32495 32495 F DEBUG   :     #09 pc 000000000008b574  /system/lib64/libc.so (__pthread_start(void*)+36)
07-24 07:56:16.576 32495 32495 F DEBUG   :     #10 pc 0000000000023c64  /system/lib64/libc.so (__start_thread+68)
07-24 18:16:57.432 32509 32542 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 32542 (RenderThread), pid 32509 (s.conversations)
07-24 18:16:57.588 19068 19068 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-24 18:16:57.588 19068 19068 F DEBUG   : LineageOS Version: '16.0-20200712-UNOFFICIAL-herolte'
07-24 18:16:57.589 19068 19068 F DEBUG   : Build fingerprint: 'samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU2ERD5:user/release-keys'
07-24 18:16:57.589 19068 19068 F DEBUG   : Revision: '0'
07-24 18:16:57.589 19068 19068 F DEBUG   : ABI: 'arm64'
07-24 18:16:57.589 19068 19068 F DEBUG   : pid: 32509, tid: 32542, name: RenderThread  >>> eu.siacs.conversations <<<
07-24 18:16:57.589 19068 19068 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-24 18:16:57.589 19068 19068 F DEBUG   : Abort message: 'Failed to set damage region on surface 0x75d14bdc80, error=EGL_BAD_ACCESS'
07-24 18:16:57.589 19068 19068 F DEBUG   :     x0  0000000000000000  x1  0000000000007f1e  x2  0000000000000006  x3  0000000000000008
07-24 18:16:57.589 19068 19068 F DEBUG   :     x4  feff71647164636d  x5  feff71647164636d  x6  feff71647164636d  x7  7f7f7f7f7f7f7f7f
07-24 18:16:57.589 19068 19068 F DEBUG   :     x8  0000000000000083  x9  a208e0b119efa6a1  x10 fffffff87ffffbdf  x11 0000000000000001
07-24 18:16:57.589 19068 19068 F DEBUG   :     x12 fffffffc7ffffbdf  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
07-24 18:16:57.589 19068 19068 F DEBUG   :     x16 000000768d2b32a8  x17 000000768d1f2540  x18 00000000ffffffff  x19 0000000000007efd
07-24 18:16:57.589 19068 19068 F DEBUG   :     x20 0000000000007f1e  x21 0000000000000083  x22 00000075ef3771b0  x23 00000075ee936a30
07-24 18:16:57.589 19068 19068 F DEBUG   :     x24 0000000000000001  x25 00000075ee9369a4  x26 00000075ef377198  x27 00000075ee9369a2
07-24 18:16:57.589 19068 19068 F DEBUG   :     x28 0000000000000000  x29 00000075ef376af0
07-24 18:16:57.590 19068 19068 F DEBUG   :     sp  00000075ef376ab0  lr  000000768d1e6210  pc  000000768d1e6230
07-24 18:16:57.674 19068 19068 F DEBUG   : 
07-24 18:16:57.674 19068 19068 F DEBUG   : backtrace:
07-24 18:16:57.674 19068 19068 F DEBUG   :     #00 pc 0000000000022230  /system/lib64/libc.so (abort+112)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #01 pc 0000000000008388  /system/lib64/liblog.so (__android_log_assert+328)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #02 pc 00000000004ad034  /system/lib64/libhwui.so (android::uirenderer::renderthread::EglManager::damageFrame(android::uirenderer::renderthread::Frame const&, SkRect const&)+180)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #03 pc 00000000004a65fc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::FrameBuilder::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, bool, android::uirenderer::BakedOpRenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::Re
07-24 18:16:57.674 19068 19068 F DEBUG   :     #04 pc 000000000010ba60  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+192)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #05 pc 00000000004ab96c  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+652)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #06 pc 0000000000461130  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+176)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #07 pc 0000000000119b48  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+248)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #08 pc 000000000000ff68  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+264)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #09 pc 000000000008b574  /system/lib64/libc.so (__pthread_start(void*)+36)
07-24 18:16:57.674 19068 19068 F DEBUG   :     #10 pc 0000000000023c64  /system/lib64/libc.so (__start_thread+68)

**Comment by iNPUTmice** [comment]
This seems to be an issue with the ROM.
