### ISSUE TITLE
Send an image as file issue

### ISSUE THREAD

**Issue by vampik** [iNPUTmice/Conversations#3845]
#### General information

* **Version:** 2.8.9
* **Device:** Motorola G7 Plus
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** ejabberd 20.04
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send an image as file (to send it uncompressed)
2. Delete the file you just sent

#### Expected result

Image remains in the chat history

#### Actual result

A black square instead of an image

I think the issue is that Conversations links to the local file in it's original location.

I propose to either:

1) Copy files to Conversations/Media/Conversations {Files,Images,Videos} before sending and link to there.

2) Add ability to re-download the file from server (preferably to Conversations/Media/Conversations {Files,Images,Videos}, not the original location).

Now there's just a black square without ability to do anything. While images sent as images may be deleted and re-downloaded on demand.

**Comment by vampik** [comment]
> 
> 
> /close as duplicate #3033 ?

That issue was closed without any resolution

**Comment by iNPUTmice** [comment]
I’m not sure that I agree with the 'Expected result' here. I think most users would expect the file not to get duplicated (if not necessary)

**Comment by vampik** [comment]
@iNPUTmice 
1) What's about the second proposal? Add ability to re-download the file from server. Preferably to Conversations/Media/Conversations {Files,Images,Videos}, not to the original location. Unlike another deleted files, there is no "Redownload image" option. There is only the square of Malevich with "Share" and "Copy link address" options.
2) 
> I’m not sure that I agree with the 'Expected result' here. I think most users would expect the file not to get duplicated (if not necessary)
Another popular messengers doesn't agree. Telegram copies images (and only images! not documents etc) sent as files to its images directory. The reason is the same as explained in this ticket - to remain the image in the chat history even if it gets deleted form original directory.

**Comment by vampik** [comment]
@iNPUTmice 
After some time (may be some restarts) I now see "File was deleted" message instead of the black square and it finally has a "Redownload image" option, like I requested.
Looks like a bug. User shouldn't see a black square. User should see "File was deleted" with "Redownload image" option.

**Comment by iNPUTmice** [comment]
There is a file watcher that monitors file deletions and marks a file as deleted. If that's not working for you, you can take a look at the code if you want.

**Comment by vampik** [comment]
@iNPUTmice  
> There is a file watcher that monitors file deletions and marks a file as deleted. If that's not working for you, you can take a look at the code if you want.

Could you point me to that code please so I don't have to search through the whole repository?

**Comment by iNPUTmice** [comment]
https://github.com/iNPUTmice/Conversations/blob/master/src/main/java/eu/siacs/conversations/services/XmppConnectionService.java#L238-L245

**Comment by vampik** [comment]
@iNPUTmice 
Oh, I know why it didn't work for me. I send files from the external SD card, not the so called external storage (which is in fact in the internal memory).
