### ISSUE TITLE
Feature Request: Change voice message playback speed (Fast Forward)

### ISSUE THREAD

**Issue by dimezZz** [iNPUTmice/Conversations#3850]
Running Version: 2.8.10+pcr

Requested Feature for future version: Change voice playback speed (Fast Forward) to 1.5x, 2x, 2.5x, 3x, 3.5x?. 

Extra Suggestion: It would be nice to have it function where you click a little icon (that says 1x, 2x, etc) somewhere (on the voice message bar maybe?), so you can change the speed on the fly, at any point while playing the message, not only just before you click play.

**Comment by iNPUTmice** [comment]
I think this is a very specialized task that is better left to external players.
