### ISSUE TITLE
Can't see presence of other user

### ISSUE THREAD

**Issue by warren-ru** [iNPUTmice/Conversations#3853]
#### General information

* **Version:** 2.8.9
* **Device:** Honor 20 Pro
* **Android Version:**  Android 10
* **Server name:** self hosted
* **Server software:** prosody 0.11.4
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

Can't see other user presence. The audio ring button appears only when user becomes online.
Xabber shows user status properly

**Comment by warren-ru** [comment]
Is presence indicated by sent message button only? (I saw it a while ago)
No other indication?

**Comment by iNPUTmice** [comment]
> Is presence indicated by sent message button only? (I saw it a while ago)

Yes

This is a bug tracker. Please use the community channel on `xmpp:conversations@conference.siacs.eu?join` for questions.
