### ISSUE TITLE
Attachments are lost when switching to chat during call

### ISSUE THREAD

**Issue by tyler71** [iNPUTmice/Conversations#3854]
#### General information

* **Version:** 2.8.10+pcr
* **Device:** Nokia 7.1
* **Android Version:**  Android 10
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Attach item (audio recording, video, picture)
![Screenshot_20200805-112639](https://user-images.githubusercontent.com/4926565/89450059-cc943380-d70e-11ea-9fe6-740d38e3d7c3.png)
2. Answer call from user you're attaching the message to
3. During the call, tap on switch to chat button
![Screenshot_20200805-112202](https://user-images.githubusercontent.com/4926565/89449600-28aa8800-d70e-11ea-9eef-5505103f707a.png)
4. Attachment is gone
___
This does not occur if the call is hung up, nor does it occur with the older method of getting to the chat window (tap home screen, conversations launcher, navigate to the contact)

**Comment by licaon-kter** [comment]
Attachments disappear when navigating away from a chat, yes...annoying.
