### ISSUE TITLE
Unable to reach server

### ISSUE THREAD

**Issue by jarvisv4** [iNPUTmice/Conversations#3858]
#### General information

* **Version:** NA
* **Device:** Android 8.0+ version devices
* **Android Version:** Android 8.0+ version
* **Server name:**  self hosted
* **Server software:** ejabberd 20.04
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. …On devices targeting Android 8.0+ and mostly observed on android 10 just turn off internet connection and keep the app idle for 2-4 hours.
2. Reconnect to the Internet and open app again.

#### Expected result

Accounts should be reconnected and able to perform chat.

#### Actual result

Instead of the app is unable to reach the server until the app is reopened or cleared data and restarted.

#### Debug output

-> Resolver: error resolving SRV record (direct TLS)[0m
-> de.measite.minidns.util.MultipleIoException: Poll timed out, failed to connect to /59.144.144.46 (port 53) from /:: (port 0) after 3000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to /122.169.123.80 (port 53) from /:: (port 0) after 3000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to /2404:a800:0:14::1:1019 (port 53) from /:: (port 0) after 3000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to /2401:4900:50:9::28 (port 53) from /:: (port 0) after 3000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to /8.8.8.8 (port 53) from /:: (port 0) after 3000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to e.root-servers.net/192.203.230.10 (port 53) from /:: (port 0) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to c.root-servers.net/2001:500:2::c (port 53) from /:: (port 0) after 5000ms: connect failed: ENETUNREACH (Network is unreachable)[0m

````

**Comment by licaon-kter** [comment]
Any network type?

Other servers behave the same?

**Comment by jarvisv4** [comment]
@licaon-kter 
**Other servers behave the same?**
Cannot test for different servers but at the same moment the app is able to connect to the same domain in TLS mode. The only request for ejabberd server isn't getting sent, as an exception is thrown while trying to find the server.

**Any network type?**
Tried in man networks and mostly observed while using mobile data.

**Comment by iNPUTmice** [comment]
This is an issue tracker meant to track bugs of the app. Please use the community group chat at `xmpp:conversations@conference.siacs.eu?join`
