### ISSUE TITLE
Links with Dollar symbols are not correctly recognized

### ISSUE THREAD

**Issue by jhaye** [iNPUTmice/Conversations#3859]
#### General information

* **Version:** 2.8.9+fcr
* **Device:** Google Pixel
* **Android Version:**  Android 10 (stock)

#### Steps to reproduce

Paste a link like https://epetitionen.bundestag.de/petitionen/_2020/_07/_06/Petition_113349.nc.$$$.a.u.html into a conversation.

#### Expected result

While dollar symbols in web links are uncommon, it should be properly recognized and turned into a link.

#### Actual result

The URL gets turned into a link, but only up until the first Dollar symbol occurs.

**Comment by iNPUTmice** [comment]
Fixed in 4040d5f6471d6c958321902f335014bdaeedbfa2
