### ISSUE TITLE
Minor confusing translation error: 'QR-Code' (English) becomes 'Barcode' in German translation

### ISSUE THREAD

**Issue by CEHitchens** [iNPUTmice/Conversations#3862]
/Edit: just spotted that this in fact is an already known "issue". How would one get this change request to the translators?
Yes, Aztec, Data Matrix, MaxiCode, PDF417,CyberCode ... and QR-Codes are all 2D barcodes, but somehow I am under the impression that "QR code" might be the equivalent to a "Kleenex" or "to xerox".

#### General information

* **Version:** 2.8.10+fcr
* **Android Version:** LineageOS 16.0
* **Conversations source:** F-Droid

#### Steps to reproduce

1. 3.dot menu
2. Manage accounts
3. Tap on respective account
4. Tap on " < " share icon
5. Spot that "QR-Code" is translated to "Barcode" in German there. 
#### Expected result

A minor translation adjustment for "QR-Code" to actually remain "QR-Code" as a bar code is something else and I could imagine others finding this confusing as well.
i.e. "Als QR-Code teilen" and "QR-Code anzeigen"

#### Actual result
Well, the term "Barcode" is used in the German translation

**Comment by licaon-kter** [comment]
Fix this on the Transifex portal

/close this

**Comment by CEHitchens** [comment]
OK, will search for that Portal.
Thanks.
