### ISSUE TITLE
compliance test: A/V call XEPs not tested

### ISSUE THREAD

**Issue by mickroll** [iNPUTmice/Conversations#3864]
#### General information

* **Version:** 2.8.10
* **Device:** Ulefone Armor X5
* **Android Version:**  Android 9 (stock)
* **Server name:** draugr.de
* **Server capabilities:** https://www.draugr.de/features/
* **Conversations source:** F-Droid

I can't make an a/v call to any contact. I guess this is because the server draugr.de does not support the required XEPs. However, running the compliance test for this server gives a 100% result.

#### Steps to reproduce

1. visit https://compliance.conversations.im/server/draugr.de/

#### Expected result

The compliance test should at least mention a missing XEP for a/v calls.
I am not sure if a 100% compliance is the correct output, either.

#### Actual result

No mention of a/v features whatsoever.
100% compliance

**Comment by iNPUTmice** [comment]
> The compliance test should at least mention a missing XEP for a/v calls.

1. It does test for the existence of STUN/TURN
2. It doesn’t check whether they have been setup correctly.
3. Depending on network conditions your contact’s server needs to support this as well.
4. This is not the issue tracker for the compliance tester.4
