### ISSUE TITLE
How to toggle between group chat name and list of participants in roster?

### ISSUE THREAD

**Issue by magoralczyk** [iNPUTmice/Conversations#3865]
It seems to me, that for group name lables conversations shows initially the comma seperated participants names ("alice, bob") instead of the rooms name ("Alice and Bob discuss sausages"). Just for fun: gajim shows the internal room name like "eyebelol": perfect!

But in conversations the has to be a switch, because on my phone I see the right name, and my childeren just see the participants. Both the same versions (current: x.x.10), both identically configured, both connected to the same server.
 
Help?

**Comment by licaon-kter** [comment]
This room is created by direct menu invites or by pressing + icon ->Private group->invite?

**Comment by magoralczyk** [comment]
this room is existent on the server befor even installing conversations.

**Comment by iNPUTmice** [comment]
It's a fall back mechanism. Conversations will show 'Name1, Name2' if no other name is provided.

Please use the conference channel at `xmpp:conversations@conference.siacs.eu?join` for this sort of questions.
