### ISSUE TITLE
Add support for SVG avatars

### ISSUE THREAD

**Issue by quinao** [iNPUTmice/Conversations#3866]
#### General information

* **Version:** 2.8.10+pcr
* **Device:** FairPhone2
* **Android Version:**  Android 7.1.2
* **Server name:** jabber.fr
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send messages to someone with a SVG avatar.
2. The avatar is not shown. Instead, there's a single letter as if this person didn't have an avatar at all. 

However, I can see PNG avatars.
Also, I can see these SVG avatars if I use another XMPP client (e.g. Dino).

**Comment by iNPUTmice** [comment]
Android has no built in support for SVG and I think it is unwise (security and complexity wise) to pull in a third party (native) library to render SVG avatars.
