### ISSUE TITLE
[Feature request] option to enable absolute timestamps always, and to show seconds

### ISSUE THREAD

**Issue by Soundtoxin** [iNPUTmice/Conversations#3868]
I would like to see the exact second a message was sent, and I would like to see a full timestamp for a message just sent (instead of relative timestamps like  "just now" or "5 mins ago"). It can be useful for things like checking the latency of a bridge by seeing the seconds on both ends. Maybe it could be under expert settings if it's controversial.
I also think it would be worth having a way to see a full timestamp in the message options popup. Element (Matrix) has something like this when you long-press a message.

**Comment by iNPUTmice** [comment]
I don’t think the added complexity is in the best interest of the vast majority of users.

**Comment by Soundtoxin** [comment]
IRC and Matrix both commonly make it trivial to display seconds.
I see having to subtract relative time from the current time instead of just seeing the actual time as added complexity. If I screenshot someone saying "I'll be outside in 5 minutes" and then look back at that screenshot in a few days, I won't even know what time of day it was sent.
Seeing seconds also gives an idea of how fast someone responded to something, which helps to determine how engaged someone is, maybe even their tone.

I fail to see the benefit of holding back those common features that are in various other chat programs. irssi didn't display seconds by default, but they made it easy to enable them. Now my irc chatlogs have more useful info and context. You can even notice things like 3 messages posted in the same second, meaning it was likely text pasted in from somewhere.

Please reconsider your decision.
