### ISSUE TITLE
Upgrade libwebrtc to M85

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/Conversations#3870]
libwebrtc m85 became stable a week ago. We might want to upgrade to that https://groups.google.com/g/discuss-webrtc/c/Qq3nsR2w2HU/m/7WGLPscPBwAJ

**Comment by licaon-kter** [comment]
Is that info on the open internet too?

**Comment by iNPUTmice** [comment]
@licaon-kter the stabilization? I use https://chromiumdash.appspot.com/releases?platform=Android but I can’t pretend to understand Google’s release cycles.

**Comment by licaon-kter** [comment]
No, I meant we can't read that OP link since it's not on the internet but in Google's silo accessible only to Google users.
