### ISSUE TITLE
Incoming Jingle call rings even if user is on a call in another app

### ISSUE THREAD

**Issue by singpolyma-shopify** [iNPUTmice/Conversations#3871]
Not sure if this can be fixed or not -- does andrioid have a way to detect "on a call" generally?  Had this happen today where an incoming conversations call basically fully interrupted an ongoing linphone outbound call.  Ideally it would return "busy" in that case.

**Comment by licaon-kter** [comment]
This should be fixed in HEAD if the other app sets the call properly (eg. like a normal phone call).
Ref: https://github.com/iNPUTmice/Conversations/issues/3746#issuecomment-665552477
