### ISSUE TITLE
[Small change] Move search icon on main conversation area

### ISSUE THREAD

**Issue by oathzed** [iNPUTmice/Conversations#3872]
Move a search icon to here instead of inside the 3 dot menu (see circled area) :

![Screenshot_20200902-115141](https://user-images.githubusercontent.com/52545913/92024312-e4150b00-ed12-11ea-98d3-8840f45510fa.png)

**Comment by licaon-kter** [comment]
And when in a conversations you'd put it where?

**Comment by oathzed** [comment]
> And when in a conversations you'd put it where?

top area aswell, tough to decide which is more important, and put rest in overflow.

**Comment by licaon-kter** [comment]
So Search Call Encryption Attach?

**Comment by oathzed** [comment]
> So Search Call Encryption Attach?

Search, call, encryption maybe I guess

Attach should honestly be done how like Pix-Art Messenger does it. So I'd put that where the send message button is. But that's just me and how every other messenger does it :P.

**Comment by iNPUTmice** [comment]
That's too many icons. Especially on smaller screens.

**Comment by licaon-kter** [comment]
>  So I'd put that where the send message button is. But that's just me and how every other messenger does it :P.

There are forks that do that yes, Skriva, Conion, Pix-Art... But no one backported any of those implementations here
