### ISSUE TITLE
'Paste as Quote' strips empty lines

### ISSUE THREAD

**Issue by agude** [iNPUTmice/Conversations#3876]
#### General information

* **Version:** 2.8.10+pcr
* **Device:** Pixel 3
* **Android Version:**  Android 11 (stock)
* **Server name:** self hosted
* **Server software:** prosody 0.11.5
* **Installed server modules:** I'd have to look...
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Copy text with empty lines
2. Select 'Paste as Quote'
3. All empty lines are stripped

#### Expected result

If I copy and paste the following text:

```text
This is the first line.

This is the second line.
```

I would expect:

```text
> This is the first line.
>
> This is the second line.
```

#### Actual result

But it actually gets pasted as:

```text
> This is the first line.
> This is the second line.
```

Preserving the empty lines would be nice during paste, especially for multi-paragraph quotes where the empty lines separate the paragraphs.

**Comment by agude** [comment]
Looks like this is the line the does it: https://github.com/iNPUTmice/Conversations/blob/c9e6653e33676c3df8502eb7a18d5dc24b7e7750/src/main/java/eu/siacs/conversations/ui/widget/EditMessage.java#L145

**Comment by Hund** [comment]
Why her there been no love for this issue? It's a pretty bad bug. :/

**Comment by Hund** [comment]
Why her there been no love for this issue?
