### ISSUE TITLE
Android 10 storage access denied 

### ISSUE THREAD

**Issue by aamir-github** [iNPUTmice/Conversations#3878]
#### General information

* **Version:** 2.6.0
* **Device:** Xiaomi Mi A1
* **Android Version:**  Android 10
* **Server name:** conversations.im, jabber.at or self hosted
* **Conversations source:** GitHub, cloned

Files were being uploaded accordingly until conversations was tested on android 9, as I upgraded the device to android 10, it started refusing to download and upload files. 
Screenshot (errors) are attached while uploading files (android 10). The device has almost 100GB free space

![Screenshot_2020-09-13-23-05-57-40_a3c2eebae1df5f3560351e87570fb732](https://user-images.githubusercontent.com/11234464/93025471-b8016000-f617-11ea-93bc-adf78f83c455.jpg)
![Screenshot_2020-09-13-23-06-16-46_a3c2eebae1df5f3560351e87570fb732](https://user-images.githubusercontent.com/11234464/93025474-bc2d7d80-f617-11ea-86f9-cb2516b7e6f7.jpg)

**Comment by licaon-kter** [comment]
Can you update to 2.9.0 and retry?

**Comment by iNPUTmice** [comment]
If you are unfamiliar with Android development I suggest you just get the binary from the PlayStore or from F-Droid.

**Comment by aamir-github** [comment]
@iNPUTmice I mentioned cloned, means using android studio

**Comment by aamir-github** [comment]
@licaon-kter tried 2.9.0 but didn't work either, it's working fine below 10 but on android 10, there are issues

**Comment by licaon-kter** [comment]
@aamir-github no issues here (multiple OEMs) when granting permission to access storage.

**Comment by aamir-github** [comment]
@licaon-kter here is the defaultConfig settings, kindly mention if I am missing anything
```
defaultConfig {
        minSdkVersion 21 
        targetSdkVersion 29 
        versionCode 397
        //versionName "2.8.10"
        versionName "2.9.0"
        archivesBaseName += "-$versionName"
        applicationId "eu.siacs.conversations"
        resValue "string", "applicationId", applicationId
        resValue "string", "app_name", "Conversations"
        buildConfigField "String", "LOGTAG", "\"conversations\""
    }
```

**Comment by licaon-kter** [comment]
This does not matter. 

Build compat fdroid debug and get a logcat of the error then.
