### ISSUE TITLE
Files not being transferred on self hosting (ejabberd)

### ISSUE THREAD

**Issue by aamir-github** [iNPUTmice/Conversations#3879]
#### General information

* **Version:** 2.8.10
* **Device:** Oppo F15
* **Android Version:**  Android 9 
* **Server name:** self hosted
* **Server software:** ejabberd 
* **Conversations source:** Cloned from Github

Data (files and text messages) are transferred successfully when I am using online servers e.g
`conversations.im, xabber.org, or chingwag.im`. But using ejabberd from my local machine where IP address (local machine) is used as the host, text messages are transferred successfully but files are not being transferred.
Error statement :
`Failed to connect from IP address ( 192.168.00.11 of windows machine on which ejabberd is configured) to IP address (192.168.22.33 of mobile device on which conversations is running)`

**Comment by licaon-kter** [comment]
Your device can read the links say in a browser?

**Comment by aamir-github** [comment]
> Your device can open the links say in a browser?

Yes, on both windows machine (ejabberd) and clients (android mobile devices) using host (ip) defined in the ejabberd config file
