### ISSUE TITLE
[Feature request] Change default value in the MUC method discover option

### ISSUE THREAD

**Issue by m-franck** [iNPUTmice/Conversations#3883]
**What ?**
Change default selected option from jabber.network to local server.

**Why ?**
Real life scenario:
User will not find local MUC if he does not have the curiosity to browse settings.
But family member/organisation might want to look for family/organisation MUC in priority, not foreign/unrelated MUC.

**Comment by iNPUTmice** [comment]
On the vast, vast majority of servers local search will only yield stale and empty MUCs. Private chats won’t be listed there anyway.
