### ISSUE TITLE
[Feature request] MUC method discover selection refactor

### ISSUE THREAD

**Issue by m-franck** [iNPUTmice/Conversations#3884]
**What ?**
Improve the current, excluding by design, radio button selector for MUC discover in advanced configuration.

**Why ?**
- Give same priority to local or external MUC.
- Avoid user to change this option when he want to browse MUC list.

**Propositions**

1. Instead of radio button, use checkbox
2. Add third option: local and jabber.network

**Out of scope but nice to have**
- Allow to quick change this setting in the MUC list.
- UX modification in the MUC list to have a visual separation between MUC from different origin: grouping or adding a separator between list.

**Comment by iNPUTmice** [comment]
For the vast majority of users jabber.network will be the right choice. Only a very, very niche user group will ever need the local discovery.
