### ISSUE TITLE
[Feature request] Indicate if recipient does not trust OMEMO identity

### ISSUE THREAD

**Issue by m-franck** [iNPUTmice/Conversations#3886]
**What?**
Show a warning if OMEMO is enabled but recipient does not approve it.

**Why?**
Avoid sending unreadable message to recipient, and so don't suppose that he will get the message but suggest him to approve the identity before.

**Comment by licaon-kter** [comment]
How can you check this?

**Comment by m-franck** [comment]
Nothing relevant on [OMEMO specification](https://xmpp.org/extensions/xep-0384.html) but... [Dino client seems to detect that](https://github.com/dino/dino/blob/7b58c1596aa13a7ef0dd7897e25f9a80c5929a07/plugins/omemo/src/ui/bad_messages_populator.vala#L155). 
Some reverse engineering might be needed.

**Comment by licaon-kter** [comment]
Oh, so you have received messages encrypted with OMEMO from said contact BUT they're not encrypted for THIS device... but won't you get a "Not encrypted for this device bubble" in Conversations then?

**Comment by m-franck** [comment]
After verification, you are right.
Dino does not detect that, he just warn after the first OMEMO unreadable message.

To make this feature possible, all Alice clients need to inform the server which identity is trusted, and Bob client should parse this list to compare with his current client identity.
And manifestly, this does not seem to exist currently in the OMEMO protocol.

I think we can close this issue.
