### ISSUE TITLE
combining XMPP with SMS and Matrix

### ISSUE THREAD

**Issue by Rik44444** [iNPUTmice/Conversations#3892]
Hello all, thanks for developing the great Conversations/Quicksy apps. This is a post to ask 2 questions, I hope you'll indulge me. The questions are:
1. To your knowledge, has it ever been tried to combine an app like Conversations/Quicksy, for communicating via the XMPP protocol, with an SMS app, in the same way that Signal offers its users the possibility of combining Signal messages with SMS messages?
2. To your knowledge, has it ever been tried to combine an app like Conversations/Quicksy, for communicating via the XMPP protocol, with the ability to communicate via the Matrix protocol?

**Comment by licaon-kter** [comment]
1. Use https://silence.im

2. Use bridges

/close this

**Comment by Rik44444** [comment]
ah yes thanks i am aware of the possibility to use bridges. But i am wondering if someone has ever attempted to develop an app where the 2 are combined, both as primary protocols
