### ISSUE TITLE
HTTP Upload service fails with TOR hidden services, HTTP host doesn't resolve to any address

### ISSUE THREAD

**Issue by h3x4git** [iNPUTmice/Conversations#3894]
#### General information

* **Version:** 2.9.0
* **Android Version:**  Android 6 (stock)
* **Server name:** self hosted (onion hidden service)
* **Server software:** prosody 0.11.5, on Linux Mint 18
* **Installed server modules:** every module in the Server Information list, except External Service Discovery that appears disabled
* **Conversations source:** F-Droid

#### Steps to reproduce

I set up a hidden service with TOR and used the xxxxxx.onion address as my VirtualHost in Prosody 0.11.5

For HTTP Upload, I set up a component with this address http.xxxxx.onion and declared the http_host address as simply xxxxxxx.onion

I also listed my component inside the disco_items object of the config file, like this
`disco_items = {
     {'http.xxxxxxxx.onion', 'http_upload'}
}`

HTTP Upload appears enabled in Conversations module list, with a 10MB max file size.

When I try and send a file to a user, the sending fails and when I check its error message it says that it couldn't resolve the "http.xxxxxxxx.onion" address, that no address is set for that hostame.

I'm confused, because I declared it in my configuration file and the module seems enabled and anyway, I read that it should still resolve to its onion root host.

I also enabled the  "mod_admin_web" module, which I can access via Tor Browser, so I'm actually outputting HTML data from that Prosody instance even if with another module

I can connect to my server using Conversations, accepting to use a self-signed certificate and exchange messages between users.

#### Expected result

I suppose it the "http.xxxxxxxx.onion" address should resolve to "xxxxxx.onion" where another module on a different port is regularly outputting HTML. I also declared an http_host directive in my config file to make sure clients do get information as to where the traffic should be aimed at with respect to HTTP Upload data.

#### Actual result

I can't send any file via HTTP Upload. When I disable it, files get sent with a direct connection upon recipient's approval.

#### Debug output

````
adb logcat -s conversations
````
I will provide the output of this as soon as possible

**Comment by licaon-kter** [comment]
You mean `httpS://xxx.onion` right?

**Comment by iNPUTmice** [comment]
This is probably rather something for the prosody help channel than the Conversations issue tracker.

**Comment by h3x4git** [comment]
I'm getting the same error after shifting to ejabberd
