### ISSUE TITLE
"Could not connect call" - PeerConnectionState changed to FAILED

### ISSUE THREAD

**Issue by codeInTheShell** [iNPUTmice/Conversations#3899]
#### General information

* **Version:** 2.9.0+fcr
* **Device:** Nokia 7.2
* **Android Version:**  Android 10 (stock)
* **Server name:** self hosted
* **Server software:** prosody 0.11.5
* **Installed server modules:** roster, saslauth, tls, dialback, disco, carbons, pep, blocklist, vcard4, vcard_legacy, time, ping, man
* **Conversations source:** F-Droid

#### Steps to reproduce

1. initate audio or video call from LTE to LTE
2. accept call

#### Expected result

established connection

#### Actual result

"Connecting" followed by "Could not connect call"

#### Debug output

10-05 15:41:51.243 D/conversations(30057): USER@SERVERNAME: packet delivered to JingleRtpConnection
10-05 15:41:51.244 D/conversations(30057): received candidate: audio:0:candidate:3134571567 1 udp 2122262783 2a01:598:b174:83bd:1:1:5edc:17aa 42344 typ host generation 0 ufrag dwdh::UNKNOWN
10-05 15:41:51.245 D/conversations(30057): USER@SERVERNAME: PeerConnectionState changed to CONNECTING
10-05 15:41:51.245 D/conversations(30057): onJingleRtpConnectionUpdate(CONNECTING)
10-05 15:41:51.247 D/conversations(30057): SurfaceViewRenderer was already initialized
10-05 15:42:03.397 D/conversations(30057): toggle forced foreground service after receiving event (action=ping)
10-05 15:42:03.408 D/conversations(30057): ForegroundService: on
10-05 15:42:06.319 D/conversations(30057): USER@SERVERNAME: PeerConnectionState changed to FAILED
10-05 15:42:06.330 D/conversations(30057): USER@SERVERNAME: PeerConnectionState changed to CLOSED
10-05 15:42:06.337 D/conversations(30057): eu.siacs.conversations.xmpp.jingle.ToneManager.transition(NULL)
10-05 15:42:06.338 D/conversations(30057): eu.siacs.conversations.xmpp.jingle.ToneManager: do not reset audio manager because RTC has control
10-05 15:42:06.338 D/conversations(30057): onJingleRtpConnectionUpdate(ENDING_CALL)
10-05 15:42:06.407 D/conversations(30057): USER@SERVERNAME: packet delivered to JingleRtpConnection
10-05 15:42:06.408 D/conversations(30057): USER@SERVERNAME: received session terminate reason=connectivity-error() while in state SESSION_ACCEPTED
10-05 15:42:06.571 D/conversations(30057): eu.siacs.conversations.services.AppRTCAudioManager.stop()
10-05 15:42:06.572 D/conversations(30057): stop: BT state=HEADSET_UNAVAILABLE
10-05 15:42:06.573 D/conversations(30057): USER@SERVERNAME: transitioned into TERMINATED_CONNECTIVITY_ERROR                                 
10-05 15:42:06.573 D/conversations(30057): onJingleRtpConnectionUpdate(CONNECTIVITY_ERROR)
10-05 15:42:06.573 D/conversations(30057): end card reached
10-05 15:42:06.574 D/conversations(30057): stopScoAudio: BT state=HEADSET_UNAVAILABLE, SCO is on: false
10-05 15:42:06.580 D/conversations(30057): cancelTimer
10-05 15:42:06.580 D/conversations(30057): stop done: BT state=UNINITIALIZED
10-05 15:42:06.587 D/conversations(30057): ForegroundService: on

###

I have tested this with 2 Nokia 7.2, both with identical setup and client version installed. I also tried it with a Samsung Galaxy S10. Wifi to wifi works, wifi to LTE as well, only LTE to LTE fails.

**Comment by iNPUTmice** [comment]
If you are hosting your own server refer to this documentation: help.conversations.im
