### ISSUE TITLE
Allow to start group video chats with jitsi

### ISSUE THREAD

**Issue by allo-** [iNPUTmice/Conversations#3908]
Conversations currently support 1:1 video chats. As far as I know, group video chats are hard to achieve with the method Conversations uses.
Other messengers have solved this by linking a Jitsi meet instance, see https://delta.chat/en/2020-07-30-summer-update

It would be worth to consider doing the same. The user configures a video chat server and then they can start a group video chat with a simple menu entry. As Jitsi meet has a nice web interface, it will be compatible across XMPP clients, but some may integrate it conveniently or suggest installing the Jitsi meet app instead of just displaying the link.

**Comment by licaon-kter** [comment]
/duplicate https://github.com/iNPUTmice/Conversations/issues/3891 I guess

**Comment by allo-** [comment]
I guess so. But you may consider this approach.
