### ISSUE TITLE
Improve blocking spammers when they send a subscription

### ISSUE THREAD

**Issue by mdosch** [iNPUTmice/Conversations#3910]
#### General information

* **Version:** 2.9.0+fcr
* **Device:** Samsung Galaxy S5 (klte)
* **Android Version:**  Android 10 (lineageos)
* **Server name:** mdosch.de
* **Server software:** prosody trunk nightly build 1354 (2020-10-21, 409ce7686c11)
* **Installed server modules:** Stream Managment, CSI, MAM, and a lot more
* **Conversations source:** Fdroid

#### Steps to reproduce

1. Receive a subscription + spam from a stranger
2. Usually conversations offer to block the sender if you get a message from someone who's not in your roster. In case of an subscription request it only shows the button to also add the spammer to the roster so you can't block quickly but have to go through the three dot menu.

#### Expected result

Blocking the spammer should be as easy as it is without a sub request so the button to directly block the spammer should be also shown when they send a subscription request alongside.

#### Actual result

See 2. in "steps to reproduce".

#### Debug output

None

**Comment by licaon-kter** [comment]
Wasn't there a "long press" action for block?

**Comment by mdosch** [comment]
Am 22. Oktober 2020 12:03:53 UTC schrieb Licaon_Kter <notifications@github.com>:
>Wasn't there a "long press" action for block?
>

Oh, I'll have to check that.

**Comment by mdosch** [comment]
Sorry for the German screenshots.

Message from a stranger
![Screenshot_20201022-151558_Conversations](https://user-images.githubusercontent.com/5103003/96877782-6059de00-147a-11eb-8c25-ce7091dff653.png)

Sub + message from a stranger
![Screenshot_20201022-151620_Conversations](https://user-images.githubusercontent.com/5103003/96877725-4fa96800-147a-11eb-8b35-d7c2833e421c.png)

Sub + message from a stranger and long press
![Screenshot_20201022-151639_Conversations](https://user-images.githubusercontent.com/5103003/96877655-3dc7c500-147a-11eb-96ad-16f26416a648.png)

**Comment by licaon-kter** [comment]
On the add contact button not on the message
