### ISSUE TITLE
In a search for old messages it is not possible to jump into the conversation in which they are

### ISSUE THREAD

**Issue by saraxe274** [iNPUTmice/Conversations#3912]
General information
Version: 2.9.0+fcr
Device: KLTE
Android Version: Android 10 (LO17.1)
Conversations source: F-Droid

Issue
When a search is performed on messages, only matching results are displayed without the possibility of directly accessing the corresponding part of the conversation. Is it a bug or has it not been implemented yet?

>

**Comment by iNPUTmice** [comment]
This is duplicate of at least one other issue. Please use the search function on github.
