### ISSUE TITLE
Add delete button for PGP key

### ISSUE THREAD

**Issue by OmlineEditor** [iNPUTmice/Conversations#3914]
#### General information

* **Version:** 2.9.0
* **Device:** RedMi Note 7
* **Android Version:**  Android 9 (stock)
* **Server name:**  self hosted
* **Server software:** prosody 0.11
* **Conversations source:** F-Droid

#### Steps to reproduce

1. configured PGP encryption
2. communication is going well
3. both interlocutors change and delete old keys
4. generate new PGP keys
5. I look at the settings, click on the properties of the interlocutor and want to delete the old PGP key.
6. no way to delete old keys

#### Expected result
I want to see a delete button to delete my interlocutor's PGP key

#### Actual result
I cannot delete the old key. I ask you to add a button to delete unnecessary old keys.
![delkey](https://user-images.githubusercontent.com/13348933/96935862-9f654f00-14cd-11eb-923f-e061bcda1455.png)

**Comment by licaon-kter** [comment]
OpenKeychain can't?

**Comment by iNPUTmice** [comment]
Technically that's not the key but just the ID. OpenKeychain manages keys.
