### ISSUE TITLE
Always see contact status

### ISSUE THREAD

**Issue by OmlineEditor** [iNPUTmice/Conversations#3915]
#### General information

* **Version:** 2.9.0
* **Device:** RedMi Note 7
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** prosody 0.11
* **Conversations source:**  F-Droid 

#### Steps to reproduce

1. I look at contacts in the list
2. I don't see who is online now, who has left or is busy
3. there is no status information near the contact.

Make it possible to always and constantly see the status of the contact in the full contact list and in the chat next to the contact's name.

![status](https://user-images.githubusercontent.com/13348933/96936627-16e7ae00-14cf-11eb-8e42-d695582d0c6c.png)

**Comment by iNPUTmice** [comment]
Please read the FAQ and past issues.

**Comment by OmlineEditor** [comment]
> Please read the FAQ and past issues.

I saw that there is this in the settings but it does not work as expected. In the general contact list, there is no permanent information about the status of the contact. and in chat, the status is displayed through the color of the send button. it is not intuitive and not convenient. please add a status next to your username.
