### ISSUE TITLE
voice chat encryption designation

### ISSUE THREAD

**Issue by OmlineEditor** [iNPUTmice/Conversations#3916]
#### General information

* **Version:** 2.9.0
* **Server software:** prosody 0.11
* **Conversations source:**  F-Droid

in the chat, when communicating with text, there are symbols indicating that the messages are encrypted. but in voice chat and video chat there is no indication that voice messages are encrypted. Please add symbols to indicate whether the voice is encrypted or not.

**Comment by OmlineEditor** [comment]
> /close as invalid, read the Readme or store description

I read it. but I can't find what the problem is with adding this symbol to indicate security. show me the text if I'm wrong.

**Comment by licaon-kter** [comment]
There's nothing to show, as opposed to files and messages, there is NO unencrypted mode.

**Comment by OmlineEditor** [comment]
> There's nothing to show, as opposed to files and messages, there is NO unencrypted mode.

written on the main page: Encrypted audio and video calls (DTLS-SRTP) 
is it a lie, no encryption?
