### ISSUE TITLE
[UX] show room logo on the room discovery screen

### ISSUE THREAD

**Issue by anubister** [iNPUTmice/Conversations#3917]
#### General information

* **Version:** 2.9.0+FCR
* **Conversations source:** F-Droid

#### Steps to reproduce

1. New conversation (bottom right icon)
2. "+" icon
3. "Discover chans" (not sure of the exact translation)

#### Expected result
Logos of the rooms are displayed, as on https://search.jabber.network/rooms/1
![Screenshot_2020-10-31 All rooms - search jabber network](https://user-images.githubusercontent.com/6146191/97776996-2751f580-1b6d-11eb-9596-c05fff27248f.png)

#### Actual result

Generic "#" logo
![chan_disco2_](https://user-images.githubusercontent.com/6146191/97776963-e1952d00-1b6c-11eb-941d-435c30bbe173.jpg)

Would be a small but nice UX improvement :-)
Number of participants would also an improvement as it help decision to join or not to join a room :-)

**Comment by licaon-kter** [comment]
/duplicate https://github.com/iNPUTmice/Conversations/issues/3558
