### ISSUE TITLE
Nag about saving password in a password manager

### ISSUE THREAD

**Issue by ilmaisin** [iNPUTmice/Conversations#3924]
#### General information

* **Version:** 2.9.0+pcr
* **Device:** Xperia L3
* **Android Version:**  Android 8.1.0
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Go to Manage Accounts
2. Open one of the accounts
3. Push the "back" button of the device

#### Expected result

The account configuration view should just close

#### Actual result

The configuration view closes, but I get asked to add the password to a password manager (Bitwarden in my case) even if I don't change the password or anything.

**Comment by licaon-kter** [comment]
And this is a Conversations bug because?

**Comment by ilmaisin** [comment]
> 
> 
> And this is a Conversations bug because?

Passive-aggressive comments are good for nothing.

Do you mean that this is an Android system bug and Conversations will not work around it?

**Comment by licaon-kter** [comment]
I don't know, is Bitwarden triggering on any password field?

**Comment by ilmaisin** [comment]
> 
> 
> I don't know, is Bitwarden triggering on any password field?

I am not sure if it is anyhow Bitwarden specific, since it works through the Android's Autofille framework. Maybe the solution would be to somehow make sure that the password field won't get immediately selected when the user opens the account view.
