### ISSUE TITLE
Change avatars for conversations-contacts (request)

### ISSUE THREAD

**Issue by redkir** [iNPUTmice/Conversations#3927]
Hello, I have a bit request for next versions.

Provide possibility to change avatars for other contacts on phone (only  phone-owner will see result, all settings and pictures will store on his device).

Thanx for nice app.

**Comment by iNPUTmice** [comment]
You can add them to your android phone book and it will automatically use the avatar from that. That's how you can overwrite the contact picture of the contact. Adding a third method will only cause confusion.

**Comment by redkir** [comment]
Like I use it now (as secure chat with family and friends) - app have no permission to contacts-list...
