### ISSUE TITLE
cannot make a call

### ISSUE THREAD

**Issue by pizdjuk** [iNPUTmice/Conversations#3928]
#### General information

* **Version:** 2.9.0
* **Device:** Xiaomi Red mi 5a
* **Android Version:**  Android 7.1.2
* **Server name:** draugr.de
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Try to make a call
2. Answer on the other side

#### Expected result

After connecting a call, can not hear any sound

#### Actual result

connected call without sound.

BTW, within the local network the calls work as expected

**Comment by licaon-kter** [comment]
Maybe their TURN server doesn't work. 

Can you test with 2 accounts on conversation.im ?

**Comment by pizdjuk** [comment]
I've already did some tests:

1) blabber.im <-> 404.city works like a charm
2) draugr.de <-> blabber.im dont wokr. Fails at connection

draugr.de and blabber.im both support XEP-0215

**Comment by iNPUTmice** [comment]
It's very likely that the participating servers are not setup correctly. You find more information on help.conversations.im - or as an end user pick a server that works.
