### ISSUE TITLE
Show time for calls

### ISSUE THREAD

**Issue by di72nn** [iNPUTmice/Conversations#3930]
Answering https://github.com/iNPUTmice/Conversations/pull/3689#issuecomment-622963303
> That’s why I would first like to understand what people are using that information for.

During call: "OK, see you in an hour".
N minutes later checking the chat log: when was that call again?

Something like that actually happened to me a couple of times. That's just a simple example, there's more.

Also, every message in the chat has a timestamp next to it. How come the time of a call is less important?

Another thing is that current implementation is inconsistent: normal calls show duration and missed calls show time at the same position.
I think it would be better to have the first line consistent for all types of calls (show time) and maybe add a second line with the duration for calls with duration > 0.

This last part is up for debate, but I strongly believe that call time should be displayed somewhere.

**Comment by iNPUTmice** [comment]
This is now available in Conversations.
