### ISSUE TITLE
Build and properly test libwebrtc m87

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/Conversations#3933]
M87 has been released: https://groups.google.com/g/discuss-webrtc/c/6VmKkCjRK0k/m/YyOTQyQ5AAAJ and is considered stable as of Nov 17.

(We also skipped M86 along the way).

**Comment by licaon-kter** [comment]
What's the plan for SDK<21?

pre-M86 from maven says:
```
> Task :processConversationsFreeCompatReleaseManifest FAILED
.../src/conversations/AndroidManifest.xml:43:5-71 Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [org.webrtc:google-webrtc:1.0.32006] /home/vagrant/.gradle/caches/transforms-2/files-2.1/e481d545e36ea0752a09ed35cd4e3c1f/google-webrtc-1.0.32006/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="org.webrtc" to force usage (may lead to runtime failures)
```

**Comment by iNPUTmice** [comment]
I don’t know. Does this apply to a library we compile ourselves as well? Or is this only for the maven version? (The official change logs don’t mention anything in this regard)

But we will stay on 16. Updating libwebrtc is not worth bumping to 21.

**Comment by licaon-kter** [comment]
I'd guess it applies, but I did not compile any version past M85 yet, to check.
