### ISSUE TITLE
"Contact" icon suggestion for _contact_book_

### ISSUE THREAD

**Issue by eyome** [iNPUTmice/Conversations#3936]
Hi,

In _already_opened_ panel:
![20201130_224618 - Copie2](https://user-images.githubusercontent.com/1254269/100796043-5a173400-3420-11eb-8e73-7f9e711cb230.jpg)

Pushing in this icon:
![Icon2](https://user-images.githubusercontent.com/1254269/100795776-e2490980-341f-11eb-8616-4c0b592001c1.jpg)

Leads to _contact-book_ panel:
![VyrnHdJ5SwqO5NbhtaF8OQ_2](https://user-images.githubusercontent.com/1254269/100796298-b11d0900-3420-11eb-923f-75027ba2ba8c.jpg)

In fact, it's disturbing because according to Material-design library:
https://material.io/resources/icons/?icon=contacts&style=baseline

This icon is named: "chat"
![baseline_chat_black_18dp](https://user-images.githubusercontent.com/1254269/100798426-ed059d80-3423-11eb-8433-e16631a18527.png)

**So it should lead to a _chat_ panel, not _contact-book_ panel.**

**What I propose:**
According to his name, "contact" icon would be more appropriate:
![baseline_contacts_black_18dp](https://user-images.githubusercontent.com/1254269/100798212-9ac47c80-3423-11eb-9b74-0d27b334921b.png)

Or "people" icon:
![baseline_people_black_18dp](https://user-images.githubusercontent.com/1254269/100798252-ae6fe300-3423-11eb-9387-6f05c50b5726.png)

Or "person" icon:
![baseline_person_black_18dp](https://user-images.githubusercontent.com/1254269/100798224-a152f400-3423-11eb-9d8e-e19fc7da1d3f.png)

As used by "Hangout" for example:
![image](https://user-images.githubusercontent.com/1254269/100794539-01df3280-341e-11eb-873b-5f20cc8ad1dd.png)

**Thank you!**

**Comment by iNPUTmice** [comment]
The button you are referring to doesn’t lead to the contact list but to the start conversation screen.
Behind that button is not only the contact list but also a way to start and join group chats and discover channels.
If that button had a contact icon you'd be wondering why the discover channels screen is hidden behind the contacts icon.
