### ISSUE TITLE
URL regex parsers treats . , ! _ * at end after numbers as part of the URL

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#3938]
#### General information

* **Version:** 2.9.1
* **Device:** S7
* **Android Version:**  Android 10
* **Conversations source:** F-Droid

#### Notes

The issue probably lies here: https://github.com/iNPUTmice/Conversations/blob/f93cb8ede1af2c216b07fe2429e70945f739d347/src/main/java/eu/siacs/conversations/utils/Patterns.java#L309

#### Steps to reproduce

Send

1. https://test.org/foobar. 
2. https://test.org/foobar123.

#### Expected result

[https://test.org/foobar](). 
[https://test.org/foobar123]().

#### Actual result

Correct: [https://test.org/foobar]().
Dot belongs to URL: [https://test.org/foobar123.]()

**Comment by licaon-kter** [comment]
You mean 2.9.1, right?

**Comment by ericschdt** [comment]
> You mean 2.9.1, right?

No, I'm from the future. ;) Changed it!

**Comment by iNPUTmice** [comment]
fixed in 8d45cc5827f9fb3f6535749cc7d5c624fc08f5b5
