### ISSUE TITLE
Phone icon (voice/video call) not appearing consistently

### ISSUE THREAD

**Issue by BeaverUI** [iNPUTmice/Conversations#3945]
#### General information

* **Version:** 2.9.1 android
* **Server name:** self hosted
* **Server software:** OpenFire
* **Installed server modules:** STUN & TURN /w media discovery
* **Conversations source:** F-Droid

Some contacts show a "phone" icon for voice/video calling, other contacts don't. This is not symmetrical, meaning one phone might show the phone icon and can actually call the phone without a phone icon, connection will be established. Connection obviously works, so I do not know why the phone icon would be missing.

Solutions tried so far:
- Downgrading Conversations does not resolve the issue.
- Restarting the OpenFire server does not change anything.
- Restart STUN/TURN servers, but they do work (voice calls can be held by cases where the phone icon appears)

I don't know how to actually debug this any further, but I am willing to help debugging things in case more input is needed.

**Comment by licaon-kter** [comment]
Did you get a chance to read https://help.conversations.im ?

**Comment by BeaverUI** [comment]
I see... thanks! Then, still, it's not clear in the UI why a call cannot be made. My suggestion would be to keep the button there, but change the color of the icon and/or display a textbox describing the reason that a call can not be made.

**Comment by licaon-kter** [comment]
Can you test between 2 accounts on conversations.im ? If that works better ask the Openfire devs
