### ISSUE TITLE
Last Update is not working, error in import org.webrtc.ThreadUtils; debug is not working, 

### ISSUE THREAD

**Issue by HackM3nt3** [iNPUTmice/Conversations#3946]
the last update is not working to make debugs or to build the apk
![conversations error](https://user-images.githubusercontent.com/13055051/101670302-fcd34200-3a20-11eb-9f90-c6a2306e02ad.png)

**Comment by iNPUTmice** [comment]
Please take a look at the README.md - it has instructions on how to build Conversations.
