### ISSUE TITLE
Duplicate media in Conversations directories

### ISSUE THREAD

**Issue by Nemris** [iNPUTmice/Conversations#3949]
#### General information

* **Version:** 2.9.2+fsr
* **Device:** Samsung Galaxy A40
* **Android Version:**  Android 10 (stock)
* **Server name:** draugr.de, jabber.at
* **Server software:** -
* **Installed server modules:** -
* **Conversations source:** Self-built (https://github.com/iNPUTmice/Conversations/commit/00bc7a4b0621c06d066d83f8763d344039d05d1c)

#### Steps to reproduce

1. Share a file in a two-person chat.

#### Expected result

Sending a file should not cause a copy of the same to be stored in the `Conversations {Images,Files}` directories.

#### Actual result

Sending a file _may_ cause a copy of it to be stored in the `Conversations {Images,Files}` directories, under a UUID-resembling filename.

The issue doesn't seem to occur for certain files, namely an 1x1 black pixel saved as .png, while it can occur for random .jpg files.

When the issue occurs, the logcat hints at https://github.com/iNPUTmice/Conversations/blob/master/src/main/java/eu/siacs/conversations/persistance/FileBackend.java#L662 being called, and the input file being copied to the so-called "private storage".

**Comment by iNPUTmice** [comment]
There is no file de duplication in place. If you share a file multiple times it will be stored multiple times.

**Comment by Nemris** [comment]
@iNPUTmice I understand - but is it intended behavior that when I _send_ a file, the file gets copied to another directory in the _sender_'s device?

**Comment by iNPUTmice** [comment]
Yes. (Due due the permission model of Android we don’t know that we've copied the file before)

**Comment by Nemris** [comment]
Why do we copy it, though?

**Comment by licaon-kter** [comment]
@Nemris so you can have it

Maybe you've recompressed it.

Depends.

**Comment by iNPUTmice** [comment]
Because we (essentially) only get permission to read it once. (And we want to keep it to preview it; and to send it at a later date in case we are offline)

**Comment by Nemris** [comment]
@licaon-kter I made sure that image files are left uncompressed in the settings.

**Comment by Nemris** [comment]
Moreover - when one such file is uploaded, a Gajim chat partner reports that the original filename is lost.

**Comment by licaon-kter** [comment]
See other issues about lost name.
