### ISSUE TITLE
Slow down (or optionally skip) large MAM sync

### ISSUE THREAD

**Issue by singpolyma** [iNPUTmice/Conversations#3963]
#### General information

* **Version:** 2.9.4+pcr
* **Device:** Nokia 2
* **Server name:** self hosted
* **Server software:** prosody 0.11.5
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Did not use my Android phone since October
2. Turned it on and connected Conversations

#### Expected result

I should eventually get all history sync'd, and my server should not care much that I have connected.

#### Actual result

Prosody process at 100% CPU, other clients have trouble sending messages or connecting.

**Comment by singpolyma** [comment]
After waiting some hours and then trying again, it seems to be going much better. So maybe some kind of fluke. I will re-open if I reproduce.

**Comment by licaon-kter** [comment]
@singpolyma what did the Prosody devs say?
