### ISSUE TITLE
Feature request: Gemini URI support

### ISSUE THREAD

**Issue by waweic** [iNPUTmice/Conversations#3964]
Hi, I recently noticed that Conversations doesn't highlight gemini: URIs. Implementing support for them should be pretty trivial. Would you be accepting a PR with this addition? Mastodon has already done this and I would quite like to share Gemini URIs over XMPP. 

Thanks for creating a great App!

**Comment by licaon-kter** [comment]
How to test, install https://github.com/snoe/deedum from F-Droid, open a site https://drewdevault.com/2021/01/07/History-will-not-remember-us-fondly.html in your normal browser, scroll down to the `⇒ This article is also available on gemini.` and click on it... see Deedum open.

**Comment by iNPUTmice** [comment]
We currently only support http and xmpp URIs. Extending this to other URIs is a maintenance burden that I currently don’t have time for.

As you can see in #3938, #3859, #3841 there aren’t even enough volunteers to properly maintain the existing URI schemes. If and when those get fixed I might reconsider this issue.

**Comment by licaon-kter** [comment]
@iNPUTmice why does this need maintenance? It's not an "intents" thing where an app can associate any?

I doubt it Firefox has special support.

**Comment by iNPUTmice** [comment]
Not the intent handling (that happens automatically) but the URI regex.

**Comment by waweic** [comment]
Thanks for your answer, I understand

**Comment by licaon-kter** [comment]
https://toot.fedilab.app/@apps/105832883032910525
