### ISSUE TITLE
Allow editing room description

### ISSUE THREAD

**Issue by pitchum** [iNPUTmice/Conversations#3968]
#### General information

* **Version:** 2.9.2
* **Device:** any
* **Android Version:**  any compatible version
* **Server name:** chapril.org (for example)
* **Server software:** ejabberd 20.07
* **Installed server modules:** MUC
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Create a public room
2. Edit room details

#### Expected result

I should be able to edit the description field.

#### Actual result

I can only edit room's name and subject, not description.

Room description can be useful, for example it is displayed on https://search.jabber.network/

**Comment by iNPUTmice** [comment]
We have no plans of displaying descriptions within Conversations. I find it confusing that we have three different methods of describing and naming MUCs. Therefor it would be confusing to offer users to edit something they won’t be able to see in the app.

**Comment by horazont** [comment]
@iNPUTmice 
I have two arguments in favour:

- The subject is in some room configurations volatile and can be changed by anyone, not just admins (in contrast to the description). It is thus less suitable as a "public" string describing the room (and as operator of s.j.n, I would prefer to have less volatile strings).
- Not all server implementations expose the subject to non-occupants; on those which do not, s.j.n cannot fall back to the subject (even when I get around to implement that, see the issue @pitchum just created). Specifically it seems as if ejabberd (tested with conversations@conference.siacs.eu) does *not* expose the subject to non-occupants via disco#info.

I like to think of the description as the externally visible string managed by the owner and it can easily explained UI-wise as "description of the room in public listings". The "subject" on the other hand is for joined members and may be a shared (and used as) "room whiteboard" for people to leave a kind of message (or quote of the day) (I know multiple rooms which use it that way, it was also common in -- bad example ahead -- IRC; just to convey the idea).
