### ISSUE TITLE
I cannot translate a string

### ISSUE THREAD

**Issue by susobaco** [iNPUTmice/Conversations#3973]
I don't know if it is a problem of the chain or of transifex, but, in chain nº 914, I enter the truduction, but it does not give me the option to save it.
![Captura de pantalla de 2021-01-22 14-16-10](https://user-images.githubusercontent.com/5635692/105495380-6602d200-5cbc-11eb-8f3e-74eb45d2aaaa.png)

**Comment by licaon-kter** [comment]
You've edited both `1` and `otro` ?

**Comment by susobaco** [comment]
I have not copied the sentence and I have translated only the text, this is the only string that happens to me.

**Comment by licaon-kter** [comment]
Can you answer my question?

**Comment by iNPUTmice** [comment]
I’m sorry I can’t say anything wrt how transifex works. Maybe try our group chat to see if there are other translators around (it will probably get more eyes than issues on Github) or contact Transifex support.

**Comment by susobaco** [comment]
@iNPUTmice Thank you I will try to contact them. @licaon-kter Sorry, I don't know if I understood the question. I only edited the text, as in the rest of the strings, I left the special character as it was.
