### ISSUE TITLE
Back button during call should go back to conversation without ending the call

### ISSUE THREAD

**Issue by stevenroose** [iNPUTmice/Conversations#3975]
#### General information

* **Version:** 2.9.4+pcr
* **Device:** OnePlus 6
* **Android Version:**  Android 9 (OxygenOS 9.0.2)
* **Server name:** n/a
* **Server software:** n/a
* **Installed server modules:** n/a
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Start a (voice) call (didn't test with video, assume it's the same)
2. Press the "back button", aka the < triangle on the soft button row.

#### Expected result

Going back to the conversation while the call moves to the background.

#### Actual result

Call hangs up.

**Comment by licaon-kter** [comment]
What should happen when they answer?
