### ISSUE TITLE
Conversations app resends messages to OMEMO conference when it reconnects

### ISSUE THREAD

**Issue by bgrprtr** [iNPUTmice/Conversations#3977]
#### General information

* **Server name:** self hosted
* **Server software:** prosody 0.11.7
* **Installed server modules:** MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join an OMEMO encrypted conference
2. Send some messages
3. Disconnect
4. Reconnect

#### Expected result

The messages are sent, no messages are resent.

#### Actual result

The messages have status "sending" despite they are __actually__ already delivered. When the device is reconnecting, it sends them again and makes the chat floody, but their status is still sending, and it resends them on every reconnection.

It seems similar to #1536, but instead of Slack gateway we observe this in an OMEMO enctrypted conference.

Some notes:

* Some messages are delivered successfully, but when there is a first message which has 'sending' status, then every new messages gets it too.
* Non-encrypted messages are always delivered successfully.
* If you 'edit' some of these "sending" messages, then it finally change its status to delivered and does not resend when Conversaions reconnecting.

**Comment by licaon-kter** [comment]
What other modules do you have installed? Did you follow any setup guides?

**Comment by iNPUTmice** [comment]
Please provide adb logcat output for the when you send the message and when
you reconnect.

**Comment by bgrprtr** [comment]
> What other modules do you have installed?

The following modules are enabled:

* announce
* bosh
* c2s
* carbons
* conference_duration
* conversejs
* dialback
* disable_tls
* disco
* groups
* http
* http_files
* legacyauth
* mam
* muc_mam
* muc_markers
* offline
* offline_email
* pep
* ping
* posix
* private
* proxy65
* pubsub
* roster
* saslauth
* speakerstats
* time
* tls
* uptime
* vcard
* version
* websocket

These modules are enabled for conferences:

* muc_markers
* muc_mam

> Did you follow any setup guides?

No. Generally, I did not.

**Comment by iNPUTmice** [comment]
No reaction from op. closing
