### ISSUE TITLE
jingle calls don't work inbackground

### ISSUE THREAD

**Issue by atuctuc** [iNPUTmice/Conversations#3980]
hallo,

since an update from f-droid i experience that conversations does not work with audio/video jingle calls, when the device is in background. chat messages are delivered but audio calls are not. when conversations is in forground, everything is working. 

it was working with older version as i remember.

* **Version:** 2.9.4+fcr

* **Device:** linage os without google playstore

**Comment by licaon-kter** [comment]
What does "device is in background" even mean? Maybe the app?

Did you disable battery optimisations for Conversations?

By won't work you mean "won't ring" when called?

Which device? Which Lineage version?

**Comment by atuctuc** [comment]
> What does "device is in background" even mean? Maybe the app?
sorry, yes, the app
adb logcat shows: conversations : app switch into background

> Did you disable battery optimisations for Conversations?
yes, the chat is working

> By won't work you mean "won't ring" when called?
yes, it does not ring, logcat shows no message

> Which device? Which Lineage version?
also on my huawei phone i have the same problem, i don't use push messages through play store. as i wrote, the chat messages are distributet,

**Comment by iNPUTmice** [comment]
This is very likely and issue with the server configuration (CSI)
There have been no recent changes in Conversations that would cause effects like this.

**Comment by atuctuc** [comment]
ok,. thanks, csi was missing, now its working
