### ISSUE TITLE
Sometimes video call connection fails

### ISSUE THREAD

**Issue by Andy-2639** [iNPUTmice/Conversations#3990]
#### General information

* **Version:** 2.9.6+fcr
* **Device:** Sony Xperia XA2
* **Android Version:**  Android 10 - LineageOS 17.1 January 21, 2021
* **Server name:** self hosted
* **Server software:** ejabberd 20.07
* **Conversations source:** F-Droid

#### 

Network topology:
 * my phone: IP 46.114.150.121 (CGNAT: 10.112.238.121) (mobile data)
 * ejabberd: 91.45.129.235 (behind NAT in 10.x.y.z net - TURN service knows public IP address)
 * contact (at that time): 93.222.196.89 (behind NAT in 10.a.b.c net) (WiFi)

I start a video call, the other contact picks up and Conversations tries to establish the connection. Some times the connection establishment is successful and the video call just works. Some times the connection establishment fails.

Screenshot of a packet dump of an ongoing successful video call (so the TURN service of ejabberd seems to work):
![Capture](https://user-images.githubusercontent.com/13392804/107154579-f2c3b600-6973-11eb-823c-4965586b649e.png)

The log of a failed connection establishment:
[log.txt](https://github.com/iNPUTmice/Conversations/files/5939591/log.txt)

I tried to reproduce this: In contrast to an earlier test, it's not connected to the phone charging.
I tried two audio calls first, both were working. Then a video call which also worked. Later, I tried another video call which didn't work, but an audio call directly afterwards worked.

My phone was always connected via mobile data. My contact was always the same and connected via WiFi.

When my phone is connected to my WiFi, the connection establishment works reliably. Also I didn't notice any connection establishment failures for audio only calls, regardless of mobile data or WiFi (but audio-only calls are rare, video calls are much more common for me).

**Comment by iNPUTmice** [comment]
There is probably something wrong with your STUN/TURN server setup.

Running TURN behind NAT is challenging at best and probably not a good idea.
