### ISSUE TITLE
Fingerprint problem on Android

### ISSUE THREAD

**Issue by omexlu** [iNPUTmice/Conversations#3999]
Hello,

I have the problem when the fingerprints can not be confirmed by each member for whatever reason I can not write anything on the cell phone (OMEMO).

However, on Gajim it works without problems.

What is the reason for this?

If there is only one where the fingerprints are not retrievable, I can not confirm the rest :/

What can I do about it without deactivation OMEMO?

**Comment by licaon-kter** [comment]
Is this in a private group? The fingerprint is of an online user?

**Comment by omexlu** [comment]
Yes, privat group, maybe the users was not online before I added them to the memberlist, how to do that all correctly? Thanks :)

**Comment by licaon-kter** [comment]
/duplicate https://github.com/iNPUTmice/Conversations/issues/3081

@omexlu kick them out now, so everyone can talk, invite them when they are online

**Comment by omexlu** [comment]
Is there no other way like Gajim does here, it still works?
