### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by omexlu** [iNPUTmice/Conversations#4001]
Hello, 

- Where can I see online users in group hat, I only see all members on the list but not only where is online?
- How can I chanfe channel-settings (gajim has more options) 

Thanks in advance

**Comment by licaon-kter** [comment]
> Where can I see online users in group chat, I only see all members on the list but not only where is online?

Upper right menu, details, members

> How can I change channel-settings (gajim has more options)

Use Gajim for changes, this is meant as an easy to use client, for admin work other clients can do better.

**Comment by omexlu** [comment]
There I see all members that are on the memberlist but not only them who are online? :/

Okay I use gajim for changes :)

**Comment by licaon-kter** [comment]
In private groups you can see all, online or not, but in says there if they are online or not...near their nicks, right?

**Comment by omexlu** [comment]
No, I see only all in the list, there is nothing whether they are online or not.

The same also in the contact list there is also not the status whether online or not.

**Comment by licaon-kter** [comment]
In private groups you see, are you sure that's a private group? Is OMEMO active?

About status, did you enable dynamic tags in options?

**Comment by omexlu** [comment]
Is a private group and OMEMO is active.
Dynamic tags is needed so see online status in group an kontakt list?

**Comment by omexlu** [comment]
Because I don't have this members on the friendliste but I don't think I need that because gajim shows me the online users in the group 😬

Something wrong here.

**Comment by omexlu** [comment]
I tried xabber just to see and there is a online-badge on memberlist of group-chat, here not :/

Forgot any setting?
