### ISSUE TITLE
Jingle using Conversations FOSS on LineageOS: no push no ring?

### ISSUE THREAD

**Issue by danjde** [iNPUTmice/Conversations#4002]
#### General information

* **Version:** 2.9.5+fcr
* **Device:** Samsung S3 Neo
* **Android Version:**  Android 9 (LineageOS 16)
* **Server name:** 3x1t.org
* **Server software:** prosody 0.11.5
* **Conversations source:** F-Droid

#### Steps to reproduce

1. go to a user chat and tap on phone icon
2. select "video call"
3. my phone is ringing but the remote not
4. only making Conversations come up on the remote phone too, I can hear (on the remote phone) the ringing and answering turn on rightly the video call.

#### Expected result

I expect the remote phone to ring even though Conversations is in the background

#### Actual result

On the remote phone no any activities, no any notify.

Can it depend on the missing PUSH service on LineageOS/Conversations FOSS or on modules to be enabled on the Prosody side?

Thanks!

**Comment by licaon-kter** [comment]
Is your server at 100% on https://compliance.conversations.im ? Did you read https://help.conversations.im yet?

Should work fine with the F-Droid version, where there's no Push, if messages reach fine.

**Comment by danjde** [comment]
My server is 90% compliance: https://compliance.conversations.im/server/3x1t.org/
I've read https://help.conversations.im, and enabled "mod_csi" and "mod_csi_battery_saver" but with no changes.
The strange thing is that the message notifications are received correctly, only the calls are not activated.
I will deeper.

Thanks

**Comment by iNPUTmice** [comment]
> enabled "mod_csi" and "mod_csi_battery_saver" but with no changes.
> The strange thing is that the message notifications are received correctly, only the calls are not activated.

You need a more recent version of mod_csi_battery_saver. Older versions block the call notification from coming through.

**Comment by licaon-kter** [comment]
@danjde modules can be updated separately, right? `hg pull` or smth :)

**Comment by danjde** [comment]
> You need a more recent version of mod_csi_battery_saver. Older versions block the call notification from coming through.
I've updated all modules January 22, seems fine.

> @danjde modules can be updated separately, right? `hg pull` or smth :)
Using `hg pull`.

**Comment by licaon-kter** [comment]
Server logs while this happens? Android logs?

**Comment by Zash** [comment]
You want `hg pull --update`. Or `hg update` if you already did `hg pull`.

**Comment by danjde** [comment]
Solved, problem was caused by two obsolete modules:
```
"throttle_presence"
"filter_chatstates"
```

Now Conversations audio/video call works fine!

Thanks to all!
