### ISSUE TITLE
[feature request] Ask whether image should be compressed when selecting image to send

### ISSUE THREAD

**Issue by raspbeguy** [iNPUTmice/Conversations#4003]
#### General information

* **Version:** 2.9.6+fcr

There are several use cases for sending pictures (as far as I'm concerned):
* When I send a picture of my kids to my family, or a beautiful landscape, I wish my picture not to be compressed, so the recipient can store the picture in their library in full quality.
* When I send a "utility" picture, like some weird stuff on the street or a funny cat, I wish to send it compressed (nobody would want to keep the picture anyway) so that it doesn't take more that a few seconds to send.

I know there is already a general setting that enables or disables image compression. What I would like is a way to choose it just before sending a picture. I know that some messaging app does that, but I can't remember which one (how helpful).

It could be a checkbox (see edited screenshot) or a submenu for exemple.

Thanks.

![Screenshot_20210216-170950_Conversations](https://user-images.githubusercontent.com/1781287/108090173-a0bd1780-707a-11eb-8c6b-b3980f4047ed.png)

**Comment by licaon-kter** [comment]
Enable Compress

When you wanna send a full size picture use attach -> file instead

/close this

**Comment by raspbeguy** [comment]
That would work. But that is not what one can call "obvious". I think that, even if that's written in the setting page, many "simple" users will need that someone explain it to them personally.

I can be wrong on that. If you think I'm wrong, you can close the issue.

**Comment by licaon-kter** [comment]
Simple users have simple needs.

When they think about this and find the setting it becomes obvious.

**Comment by iNPUTmice** [comment]
I think we shouldn’t overburder the user with too many options on something as simple as a send operation.
