### ISSUE TITLE
Cheogram Support

### ISSUE THREAD

**Issue by trymeouteh** [iNPUTmice/Conversations#4004]
Please add a setting for any XMPP account to have cheogram.com support.
When this is enabled, it will grab contacts from the systems contacts list and get the phone numbers and names. This will allow you to send a message to any number such as +12223334444@cheogram.com and the contact name will be displayed as the name of the contact from your contacts list. This will allow for uses to have a good user experience when using Conversations with a jmp.chat or soprani.ca account which is a service that allows you to send and receive SMS messages over XMPP.

Just a simple checkbox setting in the account setting to enable or disable this.

**Comment by iNPUTmice** [comment]
I like were this is coming from but I don’t think we should hard code support for a proprietary service
