### ISSUE TITLE
PGP Integrations without OpenKeychain

### ISSUE THREAD

**Issue by trymeouteh** [iNPUTmice/Conversations#4006]
Please add OpenPGP integation in Conversations to allow users to manage public PGP keys, save private keys, encrypt messages and decrypt messages without the need of OpenKeychain.

Please still have an option for OpenKeychain if users wish to use OpenKeychain as their PGP conacts list app.

**Comment by licaon-kter** [comment]
How exactly?

**Comment by iNPUTmice** [comment]
I don’t think it is in anyone's best interest to replicate the entire functionality of an app that took several years to develop in Conversations.
