### ISSUE TITLE
Displays call option for transport chats

### ISSUE THREAD

**Issue by jpds** [iNPUTmice/Conversations#4011]
#### General information

* **Version:** 2.9.6
* **Android Version:**  Android 11
* **Server name:** self hosted
* **Server software:** prosody
* **Conversations source:** F-Droid

Upon opening a transport chat with my server where my user registrations go, I can see the call button displayed.

**Comment by iNPUTmice** [comment]
This has been fixed in 53a038d90ebe5937405b2a58360c81b9b87e935a
