### ISSUE TITLE
Wakelock not removed after picture uploading to chat

### ISSUE THREAD

**Issue by redkir** [iNPUTmice/Conversations#4012]
#### General information

* **Version:** 2.9.6+fcr
* **Device:** Redmi Note 7
* **Android Version:**  Android 9
* **Server name: self hosted
* **Server software: 0.11.7 
* **Installed server modules: http_upload_external
* **Conversations source: F-Droid

#### Steps to reproduce

1. Upload picture to chat
2. Picture loaded well and shows in the chat
3. Close the Conversations (tap Home button and hide app)
4. Watch a list of wakelocks
5. New (unnecessary) values appear in the list of wakelocks

#### Expected result
What is the expected output? 
After uploading or downloading a picture, the program should remove wakelocks from the system list

#### Actual result
What do you see instead?
There are extra values in the list of wakelocks

![wk](https://user-images.githubusercontent.com/47091537/108531914-4de89780-72e8-11eb-8e67-0a93d4ca33d3.jpg)

**Comment by licaon-kter** [comment]
And that's bad because?

**Comment by redkir** [comment]
> And that's bad because?

That's really bad. If you talk in a big chat then the system will have a **very large list of unnecessary wakeloks. This will affect the performance of the device.** 

2Developer
Please make a separate Wakelock for uploading and downloading data from the chat, without new unique Wakelocks every time.

**Comment by licaon-kter** [comment]
@redkir can you show some stats of "normal chat" vs "normal chat + wakelocks" to prove your point?

Just saying "wakelock bad" is not enough.

**Comment by iNPUTmice** [comment]
Do you have evidence or documentation for that claim? (negative impact on
performance?)

**Comment by Simulant87** [comment]
no longer required wakeloks should be avoided, because it increases the battery drain. https://developer.android.com/training/scheduling/wakelock
