### ISSUE TITLE
How to write someone without contact-list adding? 

### ISSUE THREAD

**Issue by omexlu** [iNPUTmice/Conversations#4013]
Hello, 

How can I write someone a private message without adding him to my contact list first?

Thanks.

**Comment by iNPUTmice** [comment]
There is no button to do that.

**Comment by omexlu** [comment]
That's very bad all normal xmpp client can do that 😬😬

**Comment by omexlu** [comment]
@iNPUTmice yes I will do, but please insert such a function into conversations is a must have 😊
