### ISSUE TITLE
Video calls problem

### ISSUE THREAD

**Issue by hindamzali** [iNPUTmice/Conversations#4024]
#### General information

Version:** 2.6.0
Device:** Xiaomi Mi A1
Android Version:**  Android 9 (stock)
Server name:   self hosted server
Server software:** ejabberd 19.09.1 
Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

Hello everybody
I have a problem with webrtc video streaming
Video calls are not always successful.
sometimes the video of the caller appears without any problem but that of the receiver does not appear (black screen)
sometimes the opposite of this situation.
sometimes the two videos do not appear.
It's really intermittent.
I tried several things but without any results.
I want to tell you that the audio call goes through without any problem.
XMPP server signaling is always successful
Thank you for giving me the precious help in this topic

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
Video calls need ejabberd 20.04, can you update? Latest is 21.01

**Comment by iNPUTmice** [comment]
We have an issue template for a reason. Please fill out the issue template otherwise we can’t help you.
