### ISSUE TITLE
Cannot keep socket connection when screen off

### ISSUE THREAD

**Issue by ortuman** [iNPUTmice/Conversations#4026]
#### General information

* **Version:** 2.9.7+pcr
* **Device:** Xiaomi Mi Note 10 Lite
* **Android Version:**  Android 11 RKQ1.200826.002
* **Server name:** self hosted (jackal.im)
* **Server software:** jackal 0.50.0
* **Installed server modules:** Ping, Version
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Login into `Conversations`
2. After stream establishment has been completed move to background and wait for server defined timeout duration (5m @ jackal.im). 
3. When timeout is reached server disconnects stream with `connection-timeout` stream error.
4. `Conversations` automatically reconnects.

#### Expected result

What is the expected output? 

Socket connection stay alive after keepalive timeout is reached.

#### Actual result

What do you see instead?

Socket is closed over and over, forcing `Conversations` to reconnect, thus draining battery power.

#### Debug output

```
{"level":"debug","ts":"2021-03-01T14:20:31+01:00","msg":"RECV(c2s:14): <iq type=\"get\" id=\"z90HH1r8gD4g\" from=\"ortuman@jackal.im/Conversations.sC-1\"><ping xmlns=\"urn:xmpp:ping\"/></iq>","instance_id":"56c18a4b-0ede-42dc-b067-0c98ce79f6fd"}
{"level":"debug","ts":"2021-03-01T14:20:31+01:00","msg":"SEND(c2s:14): <iq id=\"z90HH1r8gD4g\" type=\"result\" from=\"ortuman@jackal.im\" to=\"ortuman@jackal.im/Conversations.sC-1\"/>","instance_id":"56c18a4b-0ede-42dc-b067-0c98ce79f6fd"}
-- moving to background and waiting for 5m --
{"level":"debug","ts":"2021-03-01T14:25:31+01:00","msg":"SEND(c2s:14): <stream:error><connection-timeout xmlns=\"urn:ietf:params:xml:ns:xmpp-stanzas\"/></stream:error>","instance_id":"56c18a4b-0ede-42dc-b067-0c98ce79f6fd"}
{"level":"debug","ts":"2021-03-01T14:25:31+01:00","msg":"SEND(c2s:14): </stream:stream>","instance_id":"56c18a4b-0ede-42dc-b067-0c98ce79f6fd"}
{"level":"info","ts":"2021-03-01T14:25:31+01:00","msg":"Unregistered C2S stream","instance_id":"56c18a4b-0ede-42dc-b067-0c98ce79f6fd","id":"c2s:14"}
```

#### Additional context

Note that other desktop clients such as `Psi+` or `Swift` send whitespace byte periodically when application is idle to avoid disconnection. 

And indeed, they are able to maintain their connection permanently for minutes and even hours.

**Comment by iNPUTmice** [comment]
I’m not sure I understand the issue.

The server has a time out after which it closes the stream. The server doesn’t seem to ping the client before enforcing that timeout? Instead the server expects the client to magically know what timeout the server has and ping the server before that timeout is reached?

**Comment by licaon-kter** [comment]
@ortuman does whitelisting Conversations in Android Battery Optimisations help?

**Comment by iNPUTmice** [comment]
@licaon-kter Even under the best conditions Conversations will only ping the server every 5 minutes.¹ So if the server imposes a 5 minute timeout it might just race Conversations' ping by a few (milli) seconds. Battery Optimizations are probably not the issue here.

¹ With Android restrictions Conversations might even ping every ~15 minutes.

**Comment by ortuman** [comment]
@iNPUTmice, by your answer I understand there's no any TCP hearbeat performed on client side? (neither ping iq nor whitespace)

Personally, and since we are talking about a mobile application, I would opt for the [whitespace keepalive](https://tools.ietf.org/html/rfc6120#section-4.6.1). I assumed this was the default behavior since the forementioned desktop apps were doing like that.

IMO you wouldn't need to _magically_ know what's the server timeout, as long as you are as much conservative as possible. (e.g. send whitespace by every 20s-30s after being idle).

Anyway, if I'm missing some context or just being noisy, I apologize for the inconvenience.

**Comment by iNPUTmice** [comment]
@ortuman Conversations ping the server roughly every 5-20 minutes with either a `<ping/>` or an `<r/>` if stream management has been negotiated. 

> IMO you wouldn't need to magically know what's the server timeout, as long as you are as much conservative as possible. (e.g. send whitespace by every 20s-30s after being idle).

Apparently that's not the case. Because Conversations does ping but it doesn’t ping enough for Jackal.

In any case I’m just using that to illustrate my point. You can’t just assume that the other side will send you something every $interval.

If you want to close the connection prematurely to conserve resources you need to ping (with ping or r), wait for a timeout (at least 30s or so) and then close the connection.

**Comment by ortuman** [comment]
Crystal clear @iNPUTmice. 

I'll see to increase keepalive timeout on server side to avoid constant reconnections then. 👍 

Greetings and thank you for the great work you are doing. 🙌
