### ISSUE TITLE
https://github.com/iNPUTmice/Conversations

### ISSUE THREAD

**Issue by MohsenNooriArdestani** [iNPUTmice/Conversations#4027]
Hello dears 
How can i Fixed this issue?

![photo_2021-03-01_19-02-55](https://user-images.githubusercontent.com/33203404/109519754-c7d70880-7ac0-11eb-8f43-10d7a7d57625.jpg)

**Comment by iNPUTmice** [comment]
If you have no prior experience building software I recommend you use the precompiled version from Google Play.

**Comment by MohsenNooriArdestani** [comment]
> If you have no prior experience building software I recommend you use the precompiled version from Google Play.

TNX
