### ISSUE TITLE
Insert write and invite for people not on contact list

### ISSUE THREAD

**Issue by omexlu** [iNPUTmice/Conversations#4029]
Hello, 

Please make it possible to write people not on the contact list and also to invite people to group-chat not on the contact list. 

This is very missing, not all people are my friends that I want to invite in the group chat. 

Thanks.

**Comment by iNPUTmice** [comment]
>  invite people to group-chat not on the contact list.

If you use the 'Enter XMPP Address' FAB button in the invite contact screen it will invite someone without adding them.


> Please make it possible to write people not on the contact list

There are no plans to support this.
