### ISSUE TITLE
Starting backup should provide some hint it is working.

### ISSUE THREAD

**Issue by resoli** [iNPUTmice/Conversations#4031]
#### General information

* **Version:** 2.9.7+fcr
* **Device:** OnePlus 3T
* **Android Version:**  LineageOS 17.1
* **Server name:** conversations.im
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open settings.
1. Tap on "Create Backup".

#### Expected result

What is the expected output?

Some feedback from the app: "Backup is started" or similar.

#### Actual result

What do you see instead?

No direct visible effect of the action, one may only note a new icon in the general notification area of the phone.

**Comment by licaon-kter** [comment]
You can raise the priority of that notification, to add vibration, sounds, etc, using your Android controls, right?
