### ISSUE TITLE
[Discussion] Conversations availability in google playstore

### ISSUE THREAD

**Issue by antisocrates** [iNPUTmice/Conversations#4034]
I am currently using Conversations from the F-Droid Playstore and have zero issues with it. Except when i am trying to promote it...

My problem is that, i have been trying for the past months to move people away from other unreliable platforms that track their users whats-app, signal, viber and all the mainstream platforms in general and one of the main issues in that transition is Conversations availability in google playstore.

A lot of people see the 2.5$ price-tag and get second thoughts. "Why would i use that if the alternatives are free", or "I don't want to share my credit card details with google, this beats the whole anonymity point for me" etc. Then there is Quicksy which uses phone number registration and is free in the play store... there i hear "How is this any better from whats-app if i have to share private information with it, might as well use viber that most of my friends use".

Luckily Conversations is available on F-Droid free of charge (as a FOSS project) which personally i am more than happy to use, but it's easy to see why people would find as a turn-off. I literally only use F-Droid for conversations, or i might as well buy it on playstore to have only one store in my phone. After all its a great application and 2.5$ is a pretty low pricetag for it, its worth much more. But again i can't pay for the application for everyone else that i want to bring to the platform.

As i see it the current policy is sabotaging the adoption of conversations by mainstream users. It is of course your project and you can judge its financial strategy, but if it was me i would base it off donations and the conversations.im server (that offers a 6month trial) and its excellent in stability.

As a sidenote, there are some free-of-charge forks of Conversations on the playstore, but i never suggest those to anyone and they don't offer anything of real value instead of renaming the project and uploading it free of charge (and not really sure if i trust them to be honest also).
So if situation stays the same i think i am probably going to create yet another fork on playstore, that doesn't even try to pretend it offers any extra features, but just states in the description that it has the same feature set as Conversations, but is free for easier adoption by the public.

Thank you for your time and this great project.

**Comment by iNPUTmice** [comment]
Neither donations nor conversations.im bring in enough money to pay rent.

**Comment by licaon-kter** [comment]
If you're not part of the solution you're gonna take part in the problem?

**Comment by antisocrates** [comment]
As i said i am only trying to PROMOTE YOU, not take away your lunch money. 

That being said, have fun with 3 forks already in playstore that don't even mention your conversations.im server, and a 4th one on the way.

Also you don't have to pay for hosting, plenty of xmpp servers already available.

**Comment by licaon-kter** [comment]
Do you even read your own posts?

Promotion for what purpose if in the end nobody pays for the app or the hosting?

**Comment by antisocrates** [comment]
> Do you even read your own posts?
> 
> Promotion for what purpose if in the end nobody pays for the app or the hosting?

First of all, people will pay for the conversations.im hosting. The only hosting i provide is for my own circle of friends. The friends of friends, or other people i promote it online as an alternative to mainstream android messaging platforms, will either have to use conversations.im or host their own. Soon they will see that its more wise financially to use conversations.im and not worry about it.

Second, more exposure equals more donations (donations which to part go currently to other forks), and more people trying to bring people over to the platform. Not everyone will host their own, believe me.

It's clear to me that you are shooting yourselves in the foot, but i am not going to push the issue further. You do what you consider to be best for you.

I know what i will do.

**Comment by licaon-kter** [comment]
Whatsapp is free, so is Signal, also Telegram, you know that, right?

Why would they pay monthly then if they won't even bother paying once, and less, for the app?

That's the issue... also, they can install from F-Droid and donate... today!

**Comment by iNPUTmice** [comment]
@antisocrates I have a couple of questions: What Open Source project do you run? How many users do you have? What are the revenue streams for you open source project? How much revenue do you make in each of those streams? How much work do you put into each of the services associated with each revenue stream each month?

**Comment by antisocrates** [comment]
> @antisocrates I am not running an open-source project that i expect revenue from, or to live exclusively from.
And i am not against you being payed for your work, which was necessary for the xmpp protocol to become more widespread, as better privacy-focused/decentralized way to communicate, especially in light of all the privacy-violation scandals.

All i am saying is, having a paywall up, certainly doesn't help adoption, and i have a feeling it doesn't really help your financial goals either. Most people seeing a pricetag in google playstore, won't think twice, and its a shame.
Also it's a same forks have setup their own donation account and are funneling users there. Users which could provide bug reports to make Conversations better.

I am sure you have some kind of statistics on your revenues from donations/server-subscription/binary-buys. If the revenue from the binary buys overshadow all the rest sources of revenue, keep doing that. (Although again i am not sure, if the bigger exposure due to more installs of a free-binary, wouldn't increase the other sources of revenue like donations/server-subscriptions).

Also i found it curious that Quicksy is available free-of-charge with its undesirable privacy-questionable features.

Anyway you know what is best for you hopefully, and the project is GPL so there is no issue. I was just curious.

**Comment by tarbindmitry** [comment]
hello, friend!
thank you!
look, we need one more invite!
send yours (or someone) invite for our russian friend.
his number is +79269003509

чт, 11 мар. 2021 г. в 15:14, antisocrates ***@***.***>:
