### ISSUE TITLE
Feature Request | Client Provisioning

### ISSUE THREAD

**Issue by 12nick12** [iNPUTmice/Conversations#4035]
It would be great to have the ability to provision the client. For example end user logs in with example@domain.com. There's then some sort of record or TXT file that would allow us to set configuration values (ex. disable encryption, enable full size file uploads).

**Comment by licaon-kter** [comment]
Which XEP is that?

**Comment by iNPUTmice** [comment]
Can you elaborate more about your use case? What settings do you want to set and why? What are full size uploads?

This could potentially be integrated into the QR code provisioning.

**Comment by iNPUTmice** [comment]
No reaction from op. closing.
