### ISSUE TITLE
[Feature Request] Automatic Attachment Folder Encryption

### ISSUE THREAD

**Issue by ezraimanuel** [iNPUTmice/Conversations#4037]
Can you add automatic attachment folder encryption feature to this app? so Conversations attachment folder cannot be opened using external File Manager.

something like this maybe: [https://source.android.com/security/encryption/full-disk](https://source.android.com/security/encryption/full-disk)

thank you

**Comment by licaon-kter** [comment]
Isn't your device already encrypted with Full Disk Encryption?

/close as duplicate #1948 and others

**Comment by ezraimanuel** [comment]
Yes, as in for whole device, part of the phone main feature... I was thinking about individual folder encryption support only for Conversations...  so if anyone can open File Manager or plugin through USB cable, the Conversations attachment folder remains encrypted. like container-stuff in VeraCrypt/EDS

**Comment by licaon-kter** [comment]
Well they can't open file manager or USB unless you let them or they have physical access to the unlocked device. When that happens it does not matter anymore where the files are as they are accessible anyway.
