### ISSUE TITLE
App failure trying to call SIP URI from conversation to cheogram-sip

### ISSUE THREAD

**Issue by ticktostick** [iNPUTmice/Conversations#4038]
#### General information

* **Version:** 2.9.8+pcr
* **Android Version:**  Android 5 
* **Server name:** self hosted all services
* **Server software:** ejabberd 20.07 , cheogram-sip (latest)(https://git.singpolyma.net/cheogram-sip)
* **Installed server modules:** Almost all
* **Conversations source:** PlayStore

#### Steps to reproduce

1.call SIP URL from conversation 

#### Expected result

call the URI 

#### Actual result

App failure

#### Debug output
PeerConnectionState changed to CONNECTING
onJingleRtpConnectionUpdate(RINGING)
packet delivered to JingleRtpConnection
received IQ-error from user@sip.mydomain.com@sip.mydomain.com/sip in RTP session. null
PeerConnectionState changed to CLOSED
onJingleRtpConnectionUpdate(RINGING)
transitioned into TERMINATED_APPLICATION_FAILURE

When calling from sip to conversation everything works great and call goes on without issue
But calling from conversation to SIP URI is the problem.
This error is in Asterisk  xmpp log not sure if it is related 
<--- XMPP received from 'asterisk' --->

stream:error
imprope addressing xmlns='urn:ietf:params:xml:ns:xmpp-streams
<textxml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-streams'
Missing apos;from apos; 
attribute

**Comment by iNPUTmice** [comment]
> received IQ-error from user@sip.mydomain.com@sip.mydomain.com/sip in RTP session. null

This gives us absolutely nothing to work with. Your bridge just says "No. I don’t want to" very early on without a proper error message even. I suggest you contact the bridge developer.
