### ISSUE TITLE
Feature Request: Use different server address and account name

### ISSUE THREAD

**Issue by aocard** [iNPUTmice/Conversations#4042]
I'd like to request the feature of being able to select an address to connect to that's different from the account name's address.

An example of where this would be useful, is if there is an account at a server, say user@server.org, and there arises the need to test out the server, or test the connection with Conversations, from localhost or an internal network.

Another case would be inside a network that does not support using the domain name to connect to itself. In the case above, inside the network pointed to by server.org, the domain name server.org wouldn't connect to anything.

It would be very useful for server maintenance to be able to specify different addresses for address.org and for the actual connection.

**Comment by licaon-kter** [comment]
Settings - Expert - Enable advance connection whatever

/close this
