### ISSUE TITLE
[Feature Request] Same account on different addresses

### ISSUE THREAD

**Issue by aocard** [iNPUTmice/Conversations#4044]
I think it could be useful if there was a way to create more than one entry for the same account, if they use different connection addresses.
This would be useful if it was required of someone to connect to a server from both a local address, and a domain name.

I'm not even sure this is possible, but if it is, seems like we could benefit from it.

**Comment by mwlczk** [comment]
@aocard : for thisyou can use a local "dns" server which resolves the domain to the local address.

**Comment by aocard** [comment]
Android is very problematic when it comes to this. In addition, my router is _very_ limited when it comes to features, I have no option to set it network wide.

**Comment by mwlczk** [comment]
I'm sorry if this sounds harsh:
but you should first try to resolve your infrastructure issues before asking other devs to work around these for you.

**Comment by aocard** [comment]
I really think this should be up for the application to do.
Assuming one can resolve such infrastructure issues implies one has full control over the local network's routing, which given the lack of features on modems/routers installed by providers for home use, is more than can be expected in many cases.

I believe everyone should be able to run services from their own devices and local networks; Not just those who can change our equipment on a whim, or have a full business-oriented networks set up.

**Comment by licaon-kter** [comment]
Yes, on devices that are capable of doing it.

You don't need "business", you need "good".

**Comment by iNPUTmice** [comment]
Here are two suggestions:
* Run a VPN to your server (will also get you a fixed IP etc)
* Point your SRV records to both your local and your external IP
