### ISSUE TITLE
[Feature Request] Introduce ability to drop missed messages from public channels after login.

### ISSUE THREAD

**Issue by Markios9** [iNPUTmice/Conversations#4046]
#### General information

* **Version:** 2.9.8-pcr
* **Device:** Leagoo KIICAA Power
* **Android Version:**  Android 7.0
* **Server name:** conversations.im, 

#### Feature Description

I have joined a  couple of public channels, like conversations, ejabberd, gajim, dino etc, which are fairly active.
Due not wanting to be constantly active, and due to preference i logout from my conversations account, until i need to use it, so it doesn't run constantly in the background.

The problem arises after i relogin. For example i just relogged-in after 1 week of absence, and i was bombarded with incoming messages across all public channels that i missed. 
This made using those chat rooms unavailable, as i have to wait every missed  message to be received first, before i send something (maybe this is due to limitation of my device not sure).

I would like a mechanism to drop missed messages from public channels unless they explicitly mention my nickname.

The only workaround i have found so far is to leave the chat room, and rejoin, which isn't ideal.

Thanks.

Clarification: Disabling notifications for those chat rooms is not enough, as the main problem is i am unable to send any message (stuck on sending) until every chat is up-to-date (retrieved history from server) which obviously can take an enormous time depending on how long you have been offline.
The only solution to this is to leave the chat room and rejoin.

**Comment by iNPUTmice** [comment]
> unless they explicitly mention my nickname.

This is not possible.

I understand the problem but I don’t like the proposed solution. However future versions of Conversations will make the catchup process more efficient.
