### ISSUE TITLE
https://conversations.im/ homepage has wrong informations

### ISSUE THREAD

**Issue by halogeno** [iNPUTmice/Conversations#4047]
#### General information

not necessary

#### Steps to reproduce

1. Go to https://conversations.im/

#### Expected result

Conversations is a Jabber/XMPP client for Android 5.0+ smartphones that has been optimized to provide a unique mobile experience.

#### Actual result

Conversations is a Jabber/XMPP client for Android 4.0+ smartphones that has been optimized to provide a unique mobile experience.

#### Debug output

not necessary

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
Thanks. Fixed.
