### ISSUE TITLE
ConversationFragment didnt show anything until I send a message 

### ISSUE THREAD

**Issue by hoAlimoradi** [iNPUTmice/Conversations#4048]
I put  ConversationFragment  in a new activity, just like ConversationsActivity, which enters a new activity by clicking on a line in cahtslist in ConversationsOverviewFragment, but the two-person chat list does not load unless I send a message or the Fragment page stays open for about 7 minutes.

**Comment by iNPUTmice** [comment]
Conversations is not a library. It is not meant to be used outside of Conversations.
