### ISSUE TITLE
Conversations doesn't cancel http_upload stuck at 0%

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#4052]
Conversations 2.9.9+fcr
Google Pixel 4A, GrapheneOS, Android 11
ejabberd 21.x + nginx + Holger's perl module for http_upload; 

I have somehow misconfigured my ejabberd server and now I cannot http_upload files anymore, i.e. they are stuck at 0%.
The effect seems to be simulateable if nginx is stopped and you try to upload something.

However Conversations doesn't cancel the upload if I long press and choose "cancel". It keeps saying "sending 0%".
Logging out and back in doesn't help, however in a private MUC, closing the MUC within Conversations and rejoining makes the state go from "sending 0%" to "sending..." and now it's possible again to cancel it.

The adb log remains silent i.r.t. relevant information. All I see is
```
04-09 12:58:31.058 D/conversations( 8484): AxolotlService (user@domain.tld): Finding devices without session for user@domain.tld
04-09 12:58:31.058 D/conversations( 8484): ConversationsActivity.commitAttachments() - attaching image to conversations. CHOOSE_IMAGE
04-09 12:58:31.096 D/conversations( 8484): user@domain.tld: not compressing picture. sending as file
04-09 12:58:31.096 D/conversations( 8484): attachFile: type=2
04-09 12:58:31.096 D/conversations( 8484): counterpart=null
04-09 12:58:31.096 D/conversations( 8484): guessMimeTypeFromUriAndMime content://com.android.providers.media.documents/document/image%3A824 and mime=image/jpeg
04-09 12:58:31.130 D/conversations( 8484): received uri permission for content://com.android.providers.media.documents/document/image%3A824
04-09 12:58:31.135 D/conversations( 8484): send file message
04-09 12:58:31.139 D/conversations( 8484): using 12-byte IV for file transmission
```

**Comment by heurekus** [comment]
Hm, I just had the same problem after upgrading to 2.9.9+fcr but I didn't touch my Prosody server at all. 

Image transmissions to different recipients suddenly fail at "sending 0%". Still works with older Conversations versions on other devices. Reboot of the phone didn't help. Tried to downgrade to 2.9.8 but Android wouldn't let me. So I deleted 2.9.9+fcr on the device and installed 2.9.8+fcr. Images worked again. Then upgraded to 2.9.9 and a few images were ok, but ultimately I ran into the issue again. So I deleted and re-installed 2.9.8 and so far, things are working. 

Strange coincidence that you experienced this in a different scenario just now.

**Comment by licaon-kter** [comment]
@heurekus logs?

**Comment by heurekus** [comment]
Unfortunately not, as it was on my main device on which I'm reluctant to experiment now that it's working again. Tried with a different device / Android version + 2.9.9+fcr and could not reproduce this so far there.

**Comment by ericschdt** [comment]
@heurekus it turned out to be caused by this issue: https://github.com/iNPUTmice/Conversations/commit/55b2f2656d92674b3d7a8e986669e3d3e38a4206

However, Conversations should permit to cancel at any stage. So this is clearly a bug imho.

**Comment by unbranched** [comment]
I was going crazy trying to find the issue... first on Prosody server confs, then my net, ports, then Android side, app settings, firewall, etc...
I can confirm that allowing system CAs it works again, bugs can happen. Trust system CAs until v2.9.10 is out.

**Comment by heurekus** [comment]
Ah, then this would make a lot of sense in my case as well!! On my main device on which I DON'T NOT TRUST SYSTEM CAs, the issue appeared with 2.9.9. On other devices with standard settings I couldn't reproduce it.
