### ISSUE TITLE
Add some description about video or audio call (webrtc) feature in README.md

### ISSUE THREAD

**Issue by evan0greenup** [iNPUTmice/Conversations#4053]
The description about security, performance, compatibility and mechanism.

It is very helpful for user and anyone who are interest about Conversations.

**Comment by stevenleeS0ht** [comment]
@evan0greenup , @iNPUTmice , until now, is there any encryption in realtime call?

**Comment by licaon-kter** [comment]
@stevenleeS0ht it says DTLS-SRTP right there, right?

Also, if you and your contact have verified your fingerprints (eg. Real life QR scan or smth) calls will get a green shield meaning they're OMEMO verified too.
