### ISSUE TITLE
Fork webrtc to your github account and add CI configuration

### ISSUE THREAD

**Issue by evan0greenup** [iNPUTmice/Conversations#4054]
Since webrtc is no longer build in JCenter. 

Why not just fork the webrtc in your own Github account and add CI file to automatically build aar.

This process can be done regularly. And the webrtc version can always keep up to date.

And the feature of Github source code analysis and statistics is more powerful then google source.

It is convenient for user to see what is going on.

**Comment by evan0greenup** [comment]
Just provide `.aar` download links on Github release page.

**Comment by iNPUTmice** [comment]
You are more than welcome to set this up.

You can start with your own repo and I’ll just copy the github ci file when you are done.
