### ISSUE TITLE
Add Fairphone 3 to AEC Blacklist

### ISSUE THREAD

**Issue by MarianLiebig** [iNPUTmice/Conversations#4059]
The Fairphone 3 has the same issues as described in case 3734. Maybe the device should also be added to the blacklist, or the AEC should bei deactivatable in the settings, since this list will be incomplete with the release of a new phone with this peculiarity.

**Comment by iNPUTmice** [comment]
Without access to each phone I’m unable to determine the model name that should go into the black list and verify that putting it on the blacklist does in fact improve the situation.
I can merge well tested PRs by third parties.
