### ISSUE TITLE
Scheduled messages

### ISSUE THREAD

**Issue by 3615pipou** [iNPUTmice/Conversations#4061]
Whether you have friends or family members who work and live different schedules than you, or you find yourself sending more “happy belated birthday” messages than you’d like, having the ability to schedule text messages ahead of time is an incredibly useful feature.

It would be great to see this feature implemented to Conversation !

Thanks for the great job you've already done !

**Comment by iNPUTmice** [comment]
We would need server support for this to do this reliably and there is none at the moment. And personally I don’t need this feature enough to invest time into writing a XEP and convince server developers to implement this.

**Comment by 3615pipou** [comment]
Hi, sorry to anwser you so late. 

Well my sms app doesn't offer reliability and it is just fine : at the day and time it try to send the sms, if it failed it just try the next time it get network access.

I don't think people need high reliability for this, so client side functionality is good enough.

**Comment by 3615pipou** [comment]
@iNPUTmice could you please reconsider this feature since it can be implemented client side ?
