### ISSUE TITLE
Add a visual indication of audio/video call encryption

### ISSUE THREAD

**Issue by marmistrz** [iNPUTmice/Conversations#4063]
With the current design it's unclear whether or not an audio/video call is encrypted. When OMEMO encryption is enabled one would expect to be so. For instance, Conversations could display a padlock or a crossed padlock to indicate encryption status in video/audio calls.

**Comment by iNPUTmice** [comment]
Calls are always encrypted. There a *verified* if the verified icon appears.

**Comment by marmistrz** [comment]
Then probably showing a padlock icon wouldn't hurt, because the current UX is inconsistent. Encrypted messages are padlock/shield, but encrypted calls are nothing/shield. Showing nothing suggests that the call is _not_ encrypted, because it's how unencrypted messages are displayed.

**Comment by licaon-kter** [comment]
Dino uses the lock icon.

**Comment by rofoms** [comment]
Thanks.

**Comment by licaon-kter** [comment]
@rofoms call encryption does not depend on OMEMO (chat encryption) it's always ON

The TURN connection just forwards the data, does not encrypt it per se, but on tls in might encrypt in ON TOP OF DTLS-SRTP so it's encrypted call inside TLS. Never unencrypted.

Regarding OMEMO, latest Conversations will show an EXTRA shiel during the call IF AND ONLY IF the users verified EACH OTHERS OMEMO first. But that's ON TOP OF DTLS-SRTP, the encrypted call.

**Comment by rofoms** [comment]
If the voice chat encryption is not tied to OMEMO and there is no TLS encryption to the server TURN, then you can perform a man-in-the-middle attack. you need to display a message on the screen that there is no encryption to the TURN server, let there be at least this warning. If possible, you need to check the encryption of voice chat with binding to OMEMO keys to increase security. Can you improve security to prevent a man-in-the-middle attack?

  
>Среда, 28 апреля 2021, 23:35 +03:00 от Licaon_Kter ***@***.***>:
> 
> 
***@***.*** call encryption does not depend on OMEMO (chat encryption) it's always ON
>The TURN connection just forwards the data, does not encrypt it per se, but on tls in might encrypt in ON TOP OF DTLS-SRTP so it's encrypted call inside TLS. Never unencrypted.
>Regarding OMEMO, latest Conversations will show an EXTRA shiel during the call IF AND ONLY IF the users verified EACH OTHERS OMEMO first. But that's ON TOP OF DTLS-SRTP, the encrypted call.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Дмитрий Соловьев

**Comment by licaon-kter** [comment]
Yes, MITM is possible, **but** with integrated verification _(as said above)_ you can be assured that your contacts device _(the verified ones)_ really called you. ;)

In the future when XEP-0384 version 0.7 is implemented this might be easier to secure.
