### ISSUE TITLE
user-agent and other

### ISSUE THREAD

**Issue by cDQK** [iNPUTmice/Conversations#4072]
In version 2.9.12 the HTTP calls of UserAgent was added, I wonder what features it works with? I think maybe it is wrapping the device model character, so it maybe to reveal the related privacy?

In practice I use conversations and pix-art messages clients to communicate with each other using the same account, but conversations cannot display any of the other profile: e.g. OMEMO fingerprints, resources, etc.

**Comment by cDQK** [comment]
and On poor network signal conditions, it loads the user avatar every time the network restarts the conversation, which I think is unnecessarily wasteful because it loads very slowly. Can this feature be turned off?

**Comment by licaon-kter** [comment]
These are not issues, close this and join the support channel: xmpp:conversations@conference.siacs.eu?join
