### ISSUE TITLE
How can I register using tigase server

### ISSUE THREAD

**Issue by ChenMoGe2** [iNPUTmice/Conversations#4073]
I register Conversations' account using tigase server,which say 'Registration Failed'.How can I register successfully?Thanks.

**Comment by licaon-kter** [comment]
@ChenMoGe2 which server? tigase.im ? sure.im ? xmpp.cloud ? Or your own?

This is not an issue, per se, better join the support channel:  xmpp:conversations@conference.siacs.eu?join
