### ISSUE TITLE
prosody certificate issue - no connection possible

### ISSUE THREAD

**Issue by g33xt4h** [iNPUTmice/Conversations#4075]
Hi Daniel,

with the newest update on the Play Store the Conversations app does no longer work with prosody.
I get the message "Domain nicht überprüfbar" and think it's because of the changes in commit ac7855a332e869d66061fb80c41f708a283a1602 where you changed the way certificates are handled.

Even after deleting the certificates and re-accepting it, no connection - nothing changed on server side.

Greetings
g33xt4h

**Comment by iNPUTmice** [comment]
This was changed in bc58fb0fbdf22c9518579d13c5d511f37d34367d Your certificate needs to contain the domain name. (Self signed is still fine.)
