### ISSUE TITLE
Account settings lost

### ISSUE THREAD

**Issue by scastilloml** [iNPUTmice/Conversations#4076]
Hello!

My phone sometimes (once a week or so) is powered off by itself.
Today, after one of this shutdowns, when I turned on the phone, I found that Conversations have lost account settings, showing me the screen to create a new account or asking me the user and password of an existing account.
I have a backup but is a bit old.

Perhaps the file with the settings became corrupted with unclean shutdown.

Where are accounts stored? I mean filename and path. Maybe i could recover it with foremost or other forensic tools.

Thank you and regards.

**Comment by licaon-kter** [comment]
You have root? If yes, `/data/data/eu.siacs.conversations/`

/not an app issue, close this and join the support channel instead: xmpp:conversations@conference.siacs.eu?join
