### ISSUE TITLE
domain not verifiable + forced to uninstall for downgrade

### ISSUE THREAD

**Issue by giostark** [iNPUTmice/Conversations#4078]
Hi ,
In F-Froid there is the 2.9.12+fcr version but have some bug. Upgraded regularly it say immediately "domain not verifiable" (in red) and keep stay offline like this forever. 
Downgrade the version via F-Droid is not possible . An "unknown error" stop the downgrade. 
So basically I have to uninstall the  2.9.12+fcr losing all the settings and history and put back the 2.9.11+fcr that work fine (for my use).
On F-Droid the app is marked as upgradable but conduce at this error all the time I have tried the upgrade. (3 attempts) 
Could be very annoying if all the users have to redo all the installation and setup the app from zero.    
Please do something before this came in a chain disaster.
My Android is 6.0.1.

**Comment by iNPUTmice** [comment]
This was changed in bc58fb0fbdf22c9518579d13c5d511f37d34367d. Your certificate needs to contain the domain name. (Self signed is still fine.)

**Comment by giostark** [comment]
So is by design , ok. My bad sorry. Thanks for the ultra fast response... I'm not that expert , I'll try to do what you suggest.

**Comment by giostark** [comment]
Thanks iNPUTmice for your amazing work :-)

Solved and updated... seems to work.

Generated a new key with the domain name.

openssl genrsa -out key.pem 4096
openssl req -new -sha256 -key key.pem -out csr.csr -subj '/CN=my.domain.name'
openssl req -x509 -sha256 -days 3650 -key key.pem -in csr.csr -out mycert.pem
cat key.pem >> mycert.pem

move the file mycert.pem in /opt/ejabberd/conf/

update the ejabberd.yml to point the new mycert.pem

**Comment by HumanG33k** [comment]
How can we use wildcard domain  *.domain lets encrypt ?

**Comment by iNPUTmice** [comment]
@HumanG33k a wildcard certificate for `*.example.com` is not valid for `example.com`. Your certificate needs to contain `example.com` as well as `*.example.com`
