### ISSUE TITLE
cannot select Conversations app on F-droid

### ISSUE THREAD

**Issue by luweitest** [iNPUTmice/Conversations#4083]
In F-droid -> Categories -> Internet, select "Conversations An encrypted,..." icon (which is at 3rd position when testing), F-droid crashes. It may be F-droid's bug, but other apps page could be selected and opened without problem.

**Comment by licaon-kter** [comment]
/close this as not an issue

Update F-Droid to 1.13-alpha0, refresh repos, retest

**Comment by luweitest** [comment]
Still crash. So it is F-droid's issue?

**Comment by licaon-kter** [comment]
@luweitest yes, maybe, report to gitlab.com/fdroid/fdroidclient/issues
