### ISSUE TITLE
Account selection not (easy) possible wenn starting an conversation 

### ISSUE THREAD

**Issue by stoeffel61** [iNPUTmice/Conversations#4085]
When using multiple accounts, contacts are displayed in the contact overview in such a way that it is not possible to determine which account they are for. If two or more accounts are registered, the Jabber contacts are duplicated in the list. However, there is no way to find out which account is linked to the contact.

**Comment by iNPUTmice** [comment]
This is by design. Having the same contact under the same account is a rare enough use case that we are deliberately ignoring in order to keep the UI simple and clean.

**Comment by stoeffel61** [comment]
It's understandable, thank you.
If you have a business and a private account, it is very inconvenient. I thought it could be easily solved via a shared avatar image or the text. But thank you very much for your commitment to Conversation. I promote it where I can.
