### ISSUE TITLE
[Feature Request] Support Jingle xtls for direct file transfers

### ISSUE THREAD

**Issue by Andy-2639** [iNPUTmice/Conversations#4092]
https://xmpp.org/extensions/inbox/jingle-xtls.html

When transferring files directly (not using HTTP upload), Conversations uses clear text communication for the data transfer despite OMEMO is available.

Gajim supports Jingle XTLS in such situations. So the file is transferred via a TLS connection. The X.509 certificates are transmitted as XMPP messages. Gajim's XML console doesn't indicate this but I guess that they are encrypted and signed with OMEMO.

While HTTP upload is popular, direct file transfer is necessary for files bigger than the server limit.

**Comment by iNPUTmice** [comment]
Conversations uses XEP-0396
