### ISSUE TITLE
new view for marking about read messages

### ISSUE THREAD

**Issue by glavupak** [iNPUTmice/Conversations#4099]
please change the appearance and icons for messages in the chat. Now you have made only a part of what is in the picture. in other messengers, it is more clear than you have now. Please improve the display for a more familiar and understandable one.
![galochki](https://user-images.githubusercontent.com/84747927/119410646-db75c200-bcf1-11eb-97b5-9e923515d649.jpg)

**Comment by licaon-kter** [comment]
You already have chat markers support.

So:
* sent messages are plain ones or have shield (for OMEMO)
* delivered messages have checkmarks
* you can see with chat markers the "X has read up to here" message on screen, so you know ifmthe message was read (you need to have presence both ways active)


/close as invalid

**Comment by glavupak** [comment]
If there is no OMEMO then there is no shield. I can't see that the message has been delivered. The message "X has read up to here" is very uncomfortable and unusual. Please make it more familiar as in other messengers.

**Comment by licaon-kter** [comment]
If the message has not reached the server it will get an error underneath, right?

I'm not familiar with the others, that's a fallacy.

**Comment by iNPUTmice** [comment]
Thank you for your suggestion. It will be taken into consideration for 3.x - However the 2.x branch is currently stable and wont receive any larger UI updates.
