### ISSUE TITLE
Push to talk

### ISSUE THREAD

**Issue by jookk** [iNPUTmice/Conversations#4101]
I have feature request.  Idea is to have voice message  button behave  as in Viber. Now: to record message you have to push and recording starts.
Request:  push and hold to record and send message  also.

**Comment by jookk** [comment]
Not duplicate with mentioned issue.

**Comment by licaon-kter** [comment]
Not even with #2308 ? :)

**Comment by jookk** [comment]
You are patient, thanks 😊
I mean something else. Looking forward to next release. I donated some translation :) very good work 👍
