### ISSUE TITLE
Camera image in video call not visible / black camera image

### ISSUE THREAD

**Issue by printfuck** [iNPUTmice/Conversations#4105]
Hi there,

I was testing my old S4 mini with Android 10 (Lineage). App version is 2.9.13+fcr from FDroid. 

As the title states, the camera image stays black during the whole call. 

There also wasn't any visible error. The attached logs also don't seem to throw any error except at the end, where i tried to switch (front/back) cameras.

I assume the problem to be linked to the experimental android build, but in in that case I am still wondering, why there wasn't any error thrown.

[log.txt (domains replaced)](https://github.com/iNPUTmice/Conversations/files/6604864/log.txt)

**Comment by licaon-kter** [comment]
Does Jitsi Meet show an image?

**Comment by printfuck** [comment]
Jitsi Meet seems to be able to grab video from the camera; at least I could see myself in a test conference room in the app.

**Comment by printfuck** [comment]
Ok, it is definitively an error of the ROM, that I'm using. I just looked at the whole system log and something called the mediaserver seems to be segfaulting repeatedly.
If there are still questions, on why jitsi meet works and not conversations, I could post the log file, otherwise this can be closed and I'm sorry for wasting your time.
