### ISSUE TITLE
It is recommended to increase the automatic answering function of video calls 

### ISSUE THREAD

**Issue by goldsoft8888** [iNPUTmice/Conversations#4108]
It is recommended to increase the automatic answering function of video calls, so that you can observe the situation at home at any time.

**Comment by licaon-kter** [comment]
Maybe you want https://guardianproject.info/apps/org.havenapp.main/ instead?

**Comment by iNPUTmice** [comment]
I don’t think a personal IM tool should be a surveillance tool (legitimate or not)

**Comment by goldsoft8888** [comment]
> 也许你想要[https://guardianproject.info/apps/org.havenapp.main/？](https://guardianproject.info/apps/org.havenapp.main/)

I just want to check the elderly and children at home when I work. They have limited mobility and are not allowed to take care of themselves.
