### ISSUE TITLE
Unable to make calls on openfire server, what ports to forward

### ISSUE THREAD

**Issue by BRUTme** [iNPUTmice/Conversations#4110]
Hello,

I have my own openfire xmpp server, everything works good on LAN with Conversations (messages, calls), but I am unable to connect a call over internet.  What ports to open / forward to enable calls over internet?

**Comment by licaon-kter** [comment]
https://discourse.igniterealtime.org/t/preparing-openfire-for-audio-video-calls-with-conversations/87828

Ping @guusdk

**Comment by guusdk** [comment]
From mobile, thus terse. Does this help?
https://discourse.igniterealtime.org/t/preparing-openfire-for-audio-video-calls-with-conversations/87828

Op wo 16 jun. 2021 18:00 schreef Licaon_Kter ***@***.***>:

**Comment by BRUTme** [comment]
thanx for your answers, I have read this article, but hos is it possible that the call is working inside the LAN on the same wi-fi, but not over internet, isnt the router just blocking some ports?
I have a windows server...

**Comment by guusdk** [comment]
Configuring a network to allow for audio/video transfer can be quite complex. There is no one-size fits all solution, as things depend greatly on the specifics of your environment. Exactly how that's configured best goes beyond the level of support that I'm willing to provide through Github comments.

Generally speaking, setting up a STUN or TURN server that is accessible by all parties helps, but there are no guarantees. My suggestion to you would be to first set up a STUN/TURN server, reviewing its documentation for best practices. If you have that up and running, configuring the external service discovery plugin for Openfire with the STUN/TURN server addresses should get you a long way.
