### ISSUE TITLE
Internal-server-error Database failure

### ISSUE THREAD

**Issue by resistance1404** [iNPUTmice/Conversations#4113]
hi.
i use conversation code and thank about this code.
My problem has occurred when storage is fully. when storage is fully your message can not send and has error delivery failed, when long touch on message click on show error and the error in "Internal-server-error Database failure". this message is not cancel even that storage is clear.
how we can fixed this problem?
regard

**Comment by iNPUTmice** [comment]
Internal server error means this is a  problem on the server. If you ran out of storage on the phone this is coincidental.
