### ISSUE TITLE
Quicksy tracks and reports on the user

### ISSUE THREAD

**Issue by rdravi110** [iNPUTmice/Conversations#4115]
F-Droid says Quicksy app tracks and reports user's activity. https://www.f-droid.org/en/packages/im.quicksy.client/
What does Quicksy track and report?

**Comment by iNPUTmice** [comment]
Those F-Droid badges are very broad and often don’t give you the full picture. You can read our privacy policy here: https://quicksy.im/#privacy

**Comment by licaon-kter** [comment]
@rdravi110 known F-Droid issue, you don't see the correct description on the website/client.

Click on the Metadata link and read the Description there.
