### ISSUE TITLE
How is development enviorenment?

### ISSUE THREAD

**Issue by mrmcan** [iNPUTmice/Conversations#4121]
I would like to know how developers of the project develop it? I tried to open it with Android Studio but it's not compatible. Can you please advise me about your environment?

**Comment by licaon-kter** [comment]
Clone repo, Android Studio, Open gradle project

Don't forget to put the .aar in libs/, see Readme

/close as invalid

**Comment by mrmcan** [comment]
I already did that and built the project successfully, but android studio project looks like its not compatible (please see below screenshot). Therefore i wanted to learn how is your build environment.

[https://imgbox.com/AksDXacz](url)
