### ISSUE TITLE
Disable blind trust of OMEMO keys by default

### ISSUE THREAD

**Issue by muppeth** [iNPUTmice/Conversations#4123]
Due to latest regulation in EU in regards to backdoors for communications (those e2e too), perhaps it would be good idea to disable blind trust of keys and instead force users to pay more attention and verify keys they are sending to. 

This could provide security against situation where server operator needs to inject additional key to listen  in on gov's request.

**Comment by licaon-kter** [comment]
The difference is what, a prompt the users will learn to click hastly?

**Comment by muppeth** [comment]
Maybe a prompt with some explanation or link to info on why it is important to not just click hastly could a way.

I think, especially in the current situation, educating users on basics of encryption might be more important then making it easier by blindly trusting.

**Comment by iNPUTmice** [comment]
People who know what they are doing can already do this.

I don’t think flipping the default for the BTBV switch is viable for the time being.
