### ISSUE TITLE
Add fields

### ISSUE THREAD

**Issue by jookk** [iNPUTmice/Conversations#4127]
I need to manually configure stun / turn server. Now this is not possible.

Please, add confiig fields so user can bypass dns srv records...

**Comment by licaon-kter** [comment]
Why manually? Why not use XEP-0215 as prescribed? coturn and eturnal and maybe other servers support it.

**Comment by jookk** [comment]
For security reasons. Its not necessary to show something over dns

**Comment by licaon-kter** [comment]
I don't follow, the stun/turn server host/port/credentials are served directly to the client, there's no need to setup anything on DNS, besides the actual XMPP domain. You can host your STUN/TURN on `myxmppdomain.com` with random ports (for spamming safety)

**Comment by jookk** [comment]
Sorry, so I can delete stun turn srv records?

**Comment by licaon-kter** [comment]
They are not used when XEP-0215 is used. Delete them.
