### ISSUE TITLE
"Error fetching OMEMO key!" in group chat

### ISSUE THREAD

**Issue by sokai** [iNPUTmice/Conversations#4131]
Hey,

today a user switched over to a new JID and I, as a admin of some groups on my own Prosody server, supported him.

Now we have 2 group chats with OMEMO enabled.
In both groups the new JID, which I invited, has a problem with two accounts in the group. He gets the `Error fetching OMEMO key!` error message.

Both (problematic) accounts are long-time members and worked with the old JID.
Luckily both accounts are in my own Prosody. One account (Gajim) was yesterday active (= wrote in the group) and is currently offline. The other account uses a iPhone (IMHO with CS) and is very sporadic online, because the communication (1to1 + groups) always is *a little buggy*.

And so I *solved* it:
1. I removed (the membership status of) that two accounts (in both group chats)
2. I invited the new JID.
3. Now the new JID is writing to the 2 accounts (unencrypted) and explains the situation. Then the 3 account should directly exchange their keys.
4. After that I will invite the two accounts again.

**But:** This isn't IMHO a solution?
Can someone maybe help?

Thanks in advance + KR!

**Comment by licaon-kter** [comment]
Is CS even developed anymore?

The axoloth nodes are open for their accounts?

**Comment by sokai** [comment]
Thank you @licaon-kter for the feedback!
> Is CS even developed anymore? I'd recommend Siskin now, has OMEMO in groups and A/V.
Good to know.
> The axoloth nodes are open for their accounts?
Can you plz explain that? (I have no clue what you mean, sry.)

**Comment by licaon-kter** [comment]
Clients should mark the nodes as open so (even non-)contacts can grab the keys.

Not sure if this is default on prosody or not.

**Comment by licaon-kter** [comment]
Also this sounds like a duplicate of https://github.com/iNPUTmice/Conversations/issues/3081

Mainly try ta have them actually online, or them posting etc

**Comment by sokai** [comment]
> Clients should mark the nodes as open so (even non-)contacts can grab the keys.
> 
> Not sure if this is default on prosody or not.

🤔 I don't know … (That is a new things for me + I'll investigate it.)

IMHO nothing has changed a long time on my Prosody + we (there are ~10 active accounts with different clients, mostly Conversations) never experienced such problems.

**Comment by sokai** [comment]
> Also this sounds like a duplicate of #3081 

You are right, it's the same problem, sry! (And [I also commented on 12 Nov 2019](https://github.com/iNPUTmice/Conversations/issues/3081#issuecomment-552804149) …)

Now I think about to close this issue here, but then the/this/my/our current problem isn't solved … 🙄

For me it seems not to be a *solution* to remove offline account, that work for a long time, from a group chat, when a new account is added to that group.

May it be possible to have Conversations act like Gajim and *ignore* that offline accounts until they are online/available?
So all accounts at least can write with encryption in that group. Reading the encrypted messages is a different thing. (And accounts that see encrypted messages but can't encrypt them, have at least a indicator, that something is wrong in the key exchange …)

**Comment by sokai** [comment]
> Clients should mark the nodes as open so (even non-)contacts can grab the keys.
> 
> Not sure if this is default on prosody or not.

**Comment by sokai** [comment]
After some investigation (and also with help from the Prosody MUC) I decided to close this issue as a dup of #3081 . It seems a client problem and no server problem …

I hope I can reopen #3081 to solve this technically understandable problem, which is horrible for the user experience,
Thank you @licaon-kter !
