### ISSUE TITLE
File and Image Transfer Problems

### ISSUE THREAD

**Issue by hfuentes87** [iNPUTmice/Conversations#4134]
I am using Conversations with an Ejabberd server 21.04, sending text messages in encrypted form without inconvenience. When I try to send files, audios or images I get the error message "failed to connect to myproject.com/3.223.115.185 (port 5443) after 10000ms". Any idea of the cause of the problem? Thanks!

**Comment by licaon-kter** [comment]
Maybe try to join xmpp:ejabberd@conference.process-one.net?join to get help on your ejabberd http_upload setup instead

/close as invalid

**Comment by jookk** [comment]
Is port opened in firewall? Try to examine ejabberd logs whats there. Try to make cname for upload.myproject.com
