### ISSUE TITLE
tap notification while viewing 'you are not participating' message.

### ISSUE THREAD

**Issue by norayr** [iNPUTmice/Conversations#4137]
I just encountered the following.

I entered a chat room, which brought me that 'You are not participating' message that i am not a member and i have no voice there.

Then I forgot about it, left the phone. Then I opened notifications and saw someone else also wrote me something. Tapped on notification, and it opened conversation window with 'You are not participating' message on top, but over the page where we talk with my contact.

i pressed 'ok' on that 'you are not participating' window, and i got the window with:

'channel details' on top.
then my contact's avatar and name.

below was my avatar and my name.

and below was this:

>This public channel has no participants. Invite your contacts or use the share button to distribute its XMPP address.

i guess that's not what supposed to be. 

summary: i am reporting two problems: one is the 'you are not participating' message that stayed over the place it shouldn't. second is that contact's profile was wrong, and partly about contact, partly about some group.

thank you.

**Comment by licaon-kter** [comment]
2.9.13? Which store? Android version?

**Comment by norayr** [comment]
android, fdroid.

**Comment by norayr** [comment]
i'll try to update the version. sorry.

**Comment by norayr** [comment]
omg, i am sorry, but apparently the device was running one of the conversations' forks, and the bug does not appear in conversations. checked versions 2.9.11 and 2.9.13.

**Comment by licaon-kter** [comment]
@norayr which one? Did you report to them too?
