### ISSUE TITLE
ConversationActivity like whatsapp with viewpager and tablayout 

### ISSUE THREAD

**Issue by Xscreamofeden** [iNPUTmice/Conversations#4138]
it would be very nice if the ConversationsActivity looks like whatsapp first Activity with the tab layout and viewpager if anyone can tell me how to acheive that i would be very greatful

**Comment by licaon-kter** [comment]
Screenshot of whatever that looks like?

**Comment by Xscreamofeden** [comment]
> Screenshot of whatever that looks like?

![5cbd78cd-1c6b-4597-b642-9d56a6edea0f](https://user-images.githubusercontent.com/73835179/128370856-910715b4-80e5-4fbf-92ce-62a570f90268.jpg)
![e933d577-5af0-412f-89dc-b708dfe2cfa1](https://user-images.githubusercontent.com/73835179/128370859-0caaa71c-17ff-4232-a255-d3da5855d300.jpg)



i want to build the Home activity like this, with the possibilité to bring the call history in the CallsFragmnt when the user swipe right

**Comment by licaon-kter** [comment]
Right, so contact https://gultsch.de/ directly, scroll down to contact info, and hire him for the work.

/close this as invalid

**Comment by Xscreamofeden** [comment]
> Right, so contact https://gultsch.de/ directly, scroll down to contact info, and hire him for the work.
> 
> /close this as invalid

I am very capable of doing the job myself.. I don't need to hire anyone .. I just need some clues and orientations.
Thanks anyway!

**Comment by licaon-kter** [comment]
@Xscreamofeden also, where's your app source code hosted?

**Comment by iNPUTmice** [comment]
We use Github as a bug and feature tracker. This is not a support forum.
