### ISSUE TITLE
Slide between multiple posted images

### ISSUE THREAD

**Issue by ravermeister** [iNPUTmice/Conversations#4144]
Hi, I would love to see the feature that multiple posted images would be possible to slide. Currently when your click on a posted image, your can choose the app to open it with, and have to repeat this step for every posted image. A feature to slide between every posted image, like it's possible in WhatsApp would be awesome 🙂

**Comment by licaon-kter** [comment]
It can be better describe as "include a gallery app in this app". Was requested a lot, all these years. Duplicate of many issues.

**Comment by ravermeister** [comment]
Duplicate
