### ISSUE TITLE
How to restore a lost chat of a muc member?

### ISSUE THREAD

**Issue by VasiliyArkhipov2** [iNPUTmice/Conversations#4153]
Our family shares a muc. Unfortunately one member lost its respective chat (I would guess due to insufficient storage left on the phone). 

Is it possible to restore the one muc from my backup to the other phone?

Thanks in advance.

**Comment by licaon-kter** [comment]
Nope.

**Comment by VasiliyArkhipov2** [comment]
The muc did not appear on the list although my mum was still a member of our group.
I invited her again but the old messages did not show up.

**Comment by iNPUTmice** [comment]
Those sort of questions are better suited for our community group chat xmpp:conversations@conference.siacs.eu
