### ISSUE TITLE
Allow loadspeaker

### ISSUE THREAD

**Issue by jookk** [iNPUTmice/Conversations#4160]
Sometimes, I need to call someone and make call at loudspeaker.
Please, consider adding loadspeaker button to call screen as on mobile telephony app.

**Comment by licaon-kter** [comment]
It already has that.

/close as invalid

**Comment by jookk** [comment]
Yes, 2.9.13. Loadspeaker button is shown after other side pick-up the call. 
Button is hidden on call screen.

**Comment by heurekus** [comment]
This has been unsuccessfully requested by me and others already before, see https://github.com/iNPUTmice/Conversations/issues/3831

**Comment by heurekus** [comment]
... and I still would really like to have this feature by the way, I would use it almost every day!

**Comment by ericschdt** [comment]
It would indeed be awesome to have the possibility to switch between `ear-piece`, `loudspeaker` and `Bluetooth headset`.
So maybe this FR can be expanded a little bit.

**Comment by iNPUTmice** [comment]
This has been implemented in https://codeberg.org/iNPUTmice/Conversations/commit/17c1b175bf3fccfaa2ea22fa70d3b2589d0c624a and will likely ship with 2.14.0
