### ISSUE TITLE
Bug: wrong notification bar colour

### ISSUE THREAD

**Issue by Millesimus** [iNPUTmice/Conversations#4176]
When switching the theme and returning to chats, the colour of the notification bar is set to default (light theme). The issue would disappear after a forced restart of Conversations.
<a href="https://user-images.githubusercontent.com/32270710/134109400-76443296-c3b2-4a55-b212-79e40031ceca.png"><img width="25%" src="https://user-images.githubusercontent.com/32270710/134109400-76443296-c3b2-4a55-b212-79e40031ceca.png" /></a>
I believe the issue appeared with yesterday's commits, probably something with the Fragments? I noticed it when switching through my themes, but I can reproduce it in a fresh master build (cf. screenshot).

**Comment by licaon-kter** [comment]
What notification bar exactly?

**Comment by Millesimus** [comment]
That bar where you have your clock, and your wifi symbol, and that you can swipe down to read Conversations notifications, switch your wifi or bluetooth off and whatnot. When Conversations is open, it is typically coloured in a darker green tone so that it is easier to discern it from the actual app content. As you can see on the screenshot, there is no difference in colour between the "Conversations" heading and the small area that I called "notification bar".

**Comment by iNPUTmice** [comment]
I can reproduce the issue. This will fix itself if you press the back button (finish the activity) and open it again. I can also only reproduce this for the main activity (ConversationsActivity) - Other activities are fine.

Tried an hour to fix this. Decided not care. Tagging this as pr-welcome.

**Comment by iNPUTmice** [comment]
Reverting bfc8668803374dcac78d3e09e4edcf368fca81d1 does not fix the issue for me.

**Comment by Millesimus** [comment]
Did 64a6edd3fb42e51db54a68f098004b20d665efc7 solve this issue? It seems to be gone…

**Comment by Millesimus** [comment]
Closing this for now, as I can no longer reproduce.
