### ISSUE TITLE
Invitation link for Groupchat turns to contact if dot added

### ISSUE THREAD

**Issue by Menelmacar** [iNPUTmice/Conversations#4182]
The xmpp:uri to join a Geoupchat is recognized as contact if the Charakter after the ...join is a dot, like in my example. In the example one is warned, because its a typical muc address, but that will not always be the case.
Conversations 2.10.0+fcr:

This is an invitation link for a groupchat:
xmpp:offtopic-lounge@muc.5222.de?join

This is an Invitation link to add as contact:
xmpp:offtopic-lounge@muc.5222.de?join.

**Comment by iNPUTmice** [comment]
This is not a valid join uri.

**Comment by Menelmacar** [comment]
The one with the dot?
Maybe. But people do it anyway and its recognized as a contact then, and if they join the "muc" and add it as a contact they complain the muc is offline and they can't write there, and its not easy to debug without access to the phone.
It will not happen to poweruser, but with not so technical experienced people.

Then maybe don't allow it as a contact adding, if its invalid anyway.
