### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Aman9das** [iNPUTmice/Conversations#4186]
I would like to propose the following changes:
- material round icons for send buttons
- themable, translucent date_bubble
- if send_button_indicates_status is off, themed send button
- better pink textured background

If you wanna see how it'll look, see: https://drive.google.com/file/d/1RegmZkeP0p6rQPU30OtH_mZJW09VZrMG/view?usp=sharing

**Comment by licaon-kter** [comment]
So you've integrated all those changes in a fork of a fork of Conversations?

**Comment by iNPUTmice** [comment]
Thank you for your suggestions. They will be taken into considerations for Conversations 3.x

**Comment by Aman9das** [comment]
Umm i can create a pr. What do you say @iNPUTmice ?

**Comment by licaon-kter** [comment]
How big are the code changes? Are they easily maintanaible?

**Comment by Aman9das** [comment]
The code adds to 2 java files.
And adds to 1 layout file

And around 7*5*5 resource files. (7 buttons, 5 colors, 5 resolutions)

And the pink textured backgrounds..

About maintainability, i can add comments.. the java code change is pretty bad quality i feel.. yeah its a pain.

I will tidy it up. But the layout file is only a slight modification (text appearance change and italics to bold)
And the resource change is more maintainable that the current state.

**Comment by iNPUTmice** [comment]
I’m not interested in merging any UI changes into 2.x
