### ISSUE TITLE
can not finish called

### ISSUE THREAD

**Issue by resistance1404** [iNPUTmice/Conversations#4197]
Hi. I am using voice call.I call the person and ended this call.when go back to app this call is not finished like below screen shot.
[screenShot](https://files.fm/f/b73hgc8ny)
After a few seconds, the program starts calling.
is there any way to fixed this bug?

**Comment by licaon-kter** [comment]
Which Conversations version?

Where did you install from?

Your contact uses which app/version?

The picture, explain it, we see one random icon, it doesn't even look like the Conversations UI...
