### ISSUE TITLE
Option to change path of "Conversations" folder

### ISSUE THREAD

**Issue by jojosoft** [iNPUTmice/Conversations#4204]
When using a MicroSD card as external storage (not in the mode which uses some black magic mounts to merge with internal storage), there currently seems to be no way to have Conversations save received images and similar data files on it. The path seems to always be /sdcard/emulated/0/Conversations, which is just the internal storage.

Almost all apps have some setting for the data folder path, so I would be very happy to have the same in Conversations.

**Comment by jojosoft** [comment]
/pleasedontclosewithoutactualconsideration 😅

Thank you for pointing out these other issues that despite my search I wasn't able to see.

It seems like many users would benefit from such a feature, doesn't it? No matter at which other comparatively big and well-developed app (which needs to store a larger amount of data) you look, all of them offer the option to select the data path, it's just one setting. For example, I use AntennaPod, Nextcloud, OsmAnd~ and AnkiDroid, and all of those have a setting which deals with this rather annoying part of the Android operating system. It's just standard in Android apps, and I would kindly ask you to think about it again if you really want to have "the very last word" in instant messaging. 😉

At the moment, you are getting only the primary storage path using [Environment.getExternalStorageDirectory](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()), which by the way has been officially deprecated. (For a good reason in my opinion.) It is standard to at least use [Context.getExternalFilesDirs](https://developer.android.com/reference/android/content/Context#getExternalFilesDirs(java.lang.String)), which returns an array of possible locations, including removable SD cards. Internal storage is often limited, so it is a problem for many users if all of their chat media is stored on internal storage and not the much larger SD card they specially intended for this exact use.

**Comment by 3615pipou** [comment]
I really don't understand why it is possible for so many applications but not for Conversations ?

**Comment by iNPUTmice** [comment]
The current permission model as of Android 11 don’t allow for this anymore. Future versions will use internal storage but not let the user choose.

**Comment by jojosoft** [comment]
...so let's assume that most users already use/want Android 11?

I admit they made things even more complicated, but of course writing to external storage is generally [still possible](https://stackoverflow.com/questions/66006842/).

**Comment by mjk-gh** [comment]
I am willing to pay **20 €** for the feature that Conversation lets users choose to store all chat texts, pictures, audio files, and videos to a user configurable storage location, _including external memory_ (microSD card, NanoMemory card, USB stick, ...), e.g. SDCARD:/Conversations.

**5 € extra**, if Conversation offers to move media from previous location to the new location.

**Another 5 € extra**, if that content is (_optionally/user-selectably!_) completely encrypted.


The page

  [https://androidexplained.github.io/android/android11/scoped-storage/2020/09/29/file-saving-android-11.html](https://androidexplained.github.io/android/android11/scoped-storage/2020/09/29/file-saving-android-11.html)

explains both the Media API way as well as the Storage Access Framework (SAF) way of accomplishing that, it seems.


Maybe someone with crowdfunding experience could set up a bounty somewhere? ([https://gitpay.me/](https://gitpay.me/) or whatever platform)
