### ISSUE TITLE
Option to select account to send crash report (stack trace)

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#4212]
### Issue
Currently only the first account, which is online, is picked to send bug reports. This may be unwanted for good reasons.

### Possible solution
It would be convenient to have a combobox to select the account from which the bug report shall be sent in the popup dialog of the crash report.

**Comment by iNPUTmice** [comment]
Crash reporting will not be re-implemented in Conversations 3.x

If you are worried about data leaking I encourage you to just disable crash reporting entirely.

**Comment by ericschdt** [comment]
The server of the first account registered does _not_ offer s2s connections and cannot send bug reports. Is that a reason enough? Would you accept a PR implementing this feature? Shouldn't add too much code.

**Comment by iNPUTmice** [comment]
>  Is that a reason enough?

I never denied that there is a reason for selecting an account. The point is just that we don’t need to make changes to an obsolete feature. Just don’t send in any reports. Tbh I haven’t really read any of them in years. There was never an automated system behind it that would sort them by version or anything. The vast, vast majority of crashes I get are from extremely outdated version of Conversations or fork (with crashes that only appear in that forks)
