### ISSUE TITLE
Display crash report (stack trace) before sending it

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#4213]
It would be convenient to see what data Conversations sends in beforehand before one takes the decision to send any data to the developer(s).

**Comment by iNPUTmice** [comment]
Crash reporting will not be re-implemented in Conversations 3.x

If you are worried about data leaking I encourage you to just disable crash reporting entirely.

**Comment by Yuubi-san** [comment]
@iNPUTmice
Could still be very useful for contributors/testers/etc. to have a kind of bare 'Copy formatted report' button, like NewPipe or (I believe) Gajim have. And don't enable the option by default then.
