### ISSUE TITLE
Wrong identifier (should be lowercase/insensitive) when attempting to read from xmpp field in address book

### ISSUE THREAD

**Issue by github-k8n** [iNPUTmice/Conversations#4215]
1. In commit https://github.com/iNPUTmice/Conversations/commit/4a6df90f0c3198ec9c198d35d3ba528d5965b970  please use  "lower(ContactsContract.CommonDataKinds.Im.CUSTOM_PROTOCOL)" under the SELECTION part and "xmpp" instead of "XMPP" under the SELECTION_ARGS part to make it case insensitive (nextcloud uses lowercase)
(I verified that with the current 2.10.1 it works if I manually change the protocol to "XMPP" instead of "xmpp")

2. For contacts above that use the xmpp IM field (instead of Jabber), it seems this does not fall back to the user-provided avatar. Not sure if that is intended (never noticed whether it's only either all from address book or all from user avatars....)

**Comment by tfl** [comment]
Thanks very much. It seems, not only Nextcloud is doing this but also Davx5. Today I build and installed the current branch and the problem Conversations was not able to reference/resolve my contact's avatar by Jabber-ID was gone. Cool!
