### ISSUE TITLE
conversation deletion

### ISSUE THREAD

**Issue by jookk** [iNPUTmice/Conversations#4219]
I found strange bug maybe. 
I want to destroy conversation with one person, going to menu, delete chat.
I normally think that all the files on device are destroyed. 
But, they arent deleted. Why is that? Why conversations app, simply lie about chat deletion? I think, everybody assumes, that chat destroy means chat and all the files are deleted from device.
Please, consider this behavior. User may have false feeling, that all the files are gone, but they are not.

**Comment by licaon-kter** [comment]
The same files might be reshared, so deleting from one chat will disappear from other too.

Now, if the app duplicates the file everytime it's shared....the others complain about this. :)

**Comment by jookk** [comment]
> The same files might be reshared, so deleting from one chat will disappear from other too.
> 
> ...the others complain about this. :)
Yes, I understand. To resolve issue:
Make standalone folders for chat. So one person, one folder. 
Want to delete? No problem, delete chat, delete persons folder.

**Comment by licaon-kter** [comment]
That would be #1466 #1540 #3539 #3582
