### ISSUE TITLE
Missing Avatar icons after migrating to a new phone

### ISSUE THREAD

**Issue by JStyle21** [iNPUTmice/Conversations#4229]
Hi,

I'm missing the avatar icons on my contacts after i migrated to a new phone, couldn't find any way to repopulate\redownload them.

I tried clearing cache, is it a server thing?

Any ideas?

**Comment by licaon-kter** [comment]
Nope, client should get them when users are online maybe?

**Comment by JStyle21** [comment]
Private conversation with 1 person
Other person has an avatar and it was there before the migration
Asked that person to refresh from his side but it didn't help

**Comment by JStyle21** [comment]
I also tried to reinstall the app, didn't help as well.

No idea what else i can try, could it be server related and not app?

**Comment by iNPUTmice** [comment]
You need mutual presence subscription and your contact actually needs to have an avatar published on the server
