### ISSUE TITLE
eu.siacs.conversations.axolotl.devicelist - Strictly allow only a single device to register for Axolotl/OMEMO

### ISSUE THREAD

**Issue by orlyjamie** [iNPUTmice/Conversations#4231]
I have a specific functionality I would like to achieve regarding axolotl. 

Basically I want to run my Android client in a single device mode when it comes to OMEMO meaning that on the backend server (ejabberd) I want to only allow a single device to be registered in the device list so if a second, third, fourth or any other subsequent device tries to register for the device list it will not be accepted.

Is anyone interested to help me look into this or know anyone who would be interested? (Will pay for time) 

For example: 

```
<items node="eu.siacs.conversations.axolotl.devicelist">
	<item id="current">
	<list xmlns="eu.siacs.conversations.axolotl">
	<device id="174235744"/>
	<device id="71071234"/>                      <-------------------------- DO NOT ALLOW                      
	<device id="22318128"/>                      <-------------------------- DO NOT ALLOW
	</list>
	</item>
</items>
```

**Comment by licaon-kter** [comment]
/duplicate of https://github.com/iNPUTmice/Conversations/issues/4221 ?

**Comment by orlyjamie** [comment]
True, it is pretty much a duplicate just realised. Closing.
