### ISSUE TITLE
Images are decoded without checking image size

### ISSUE THREAD

**Issue by sunshinelwj** [iNPUTmice/Conversations#4236]
When loading an image, Google suggests us to resize the image before decoding them, so as to save memory resource.
https://developer.android.com/topic/performance/graphics/load-bitmap.html

I noticed that in the following code of Conversations, images are decoded directly without resizing:
eu.siacs.conversations.persistance.FileBackend.java getUncompressedAvatar() (line number: 1056)
https://github.com/iNPUTmice/Conversations/blob/master/src/main/java/eu/siacs/conversations/persistance/FileBackend.java#L1059

eu.siacs.conversations.xmpp.XmppConnection.java sendRegistryRequest() (line number: 54)
https://github.com/iNPUTmice/Conversations/blob/master/src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java#L997

For the images to be displayed, in many cases, they are larger than required. Because the bitmap display in an app is memory consumption, maybe we should resize the images before decoding them, which can reduce memory overhead.

Thanks.

**Comment by licaon-kter** [comment]
Don't send big images?

Conversations does not show any image, that's your gallery.

**Comment by iNPUTmice** [comment]
I think static code analysis is not very useful in those scenarios. Take your time to understand the code.
