### ISSUE TITLE
Call UI doesn't show up on incoming call if the phone is locked

### ISSUE THREAD

**Issue by anyuta1166** [iNPUTmice/Conversations#4238]
If the phone is locked then call UI doesn't show up on incoming call until I unlock the phone. This happens on Xiaomi Redmi Note 9 Pro (Android 10, MIUI 12).
Incoming calls in another messaging apps (Telegram, Whatsapp) works fine.
On my older phones (Motorola G7 Plus, Samsung J5 2016) Conversations works fine too.
I use Conversations 2.10.2 from Google Play.

**Comment by licaon-kter** [comment]
Try to grab a logcat of that moment.

**Comment by anyuta1166** [comment]
> Try to grab a logcat of that moment.
[logcat_30.11.2021_21.48.34.txt](https://github.com/iNPUTmice/Conversations/files/7628083/logcat_30.11.2021_21.48.34.txt)

**Comment by anyuta1166** [comment]
After some investigation I've found that it seems to be a permissions issue. For some reason Conversations has some permissions disabled by default. Compare Telegram default permissions vs Conversations default permissons (these permissons are found in Apps -> Permissions -> Other permissons on Xiaomi devices):

![IMG_20211202_090614](https://user-images.githubusercontent.com/726409/144367774-4a43057e-36e2-446f-8e30-04052e71e1be.jpg)
![IMG_20211202_090449](https://user-images.githubusercontent.com/726409/144367777-f399d3f3-1676-4eec-a3ac-d4ed9cfadc69.jpg)

Enabling "Show on Lock screen" allows call UI to be shown while the phone is locked.

**Comment by anyuta1166** [comment]
Googling for these permissions gave me disappointing result.

It seems that Xiaomi has a hardcoded list of whitelisted apps to which these permissions is granted by default. All other apps has these permissions disabled by default.

The only possible workaround is to show a warning screen for Xiaomi users that instructs them to go to Apps -> Permissions -> Other permissions and manually enable necessary permissions.

**Comment by anyuta1166** [comment]
I'm probably closing this because this is not a Conversations issue.
