### ISSUE TITLE
OMEMO message not encrypted for this device

### ISSUE THREAD

**Issue by BentiGorlich** [iNPUTmice/Conversations#4239]
I have 2 Devices connected to a server account (openfire) and I get the message in the app "The Message was not encrypted for this device". Is that a limitation of OMEMO or is it a bug?

**Comment by licaon-kter** [comment]
See the Dino question that I've asked.

**Comment by BentiGorlich** [comment]
could you link it?

**Comment by BentiGorlich** [comment]
yeah nevermind :D you asked in my issue dino/dino#1151

**Comment by iNPUTmice** [comment]
General questions are better handled in the community group chat instead of github issues.
