### ISSUE TITLE
OMEMO/XEP-0363 vs. OMEMO/XEP-0234 Preferences

### ISSUE THREAD

**Issue by orlyjamie** [iNPUTmice/Conversations#4241]
### The goal
Currently I have implemented enforced OMEMO messaging by rebuilding Conversations with hardcoded configuration settings (Always use OMEMO). 

- My goal now is to ensure its technically impossible for users to send non-encrypted HTTP file uploads via XEP-0363 & as a bonus, to completely remove XEP-0234 for cleanliness 

### The assumption
However, after doing a lot of reading my current understanding is that Conversations supports sending encrypted files via both XEP-0363 (HTTP File upload) & XEP-0234 (JINGLE) and, that (according to this audit https://conversations.im/omemo/audit.pdf) XEP-0363 is the default choice for Conversations when users wish to send encrypted files.

### The questions
1. How does Conversations decide from the senders perspective whether to use HTTP vs. JINGLE encrypted file transfer? 
2. If I wanted to modify the code to ensure files could only be sent via HTTP + AESGCM/Omemo - what would be the best approach for that in terms of what files/functions to edit?

**Comment by orlyjamie** [comment]
Oh... I think I may have answered my own question...

After looking through one of the files involved with uploading: https://github.com/iNPUTmice/Conversations/blob/0fc191d0040e02fd809e4a634f77784b50ebd236/src/main/java/eu/siacs/conversations/http/SlotRequester.java

I noticed this config value `ENCRYPT_ON_HTTP_UPLOADED` 

```
        this.delayed = delay;
        if (Config.ENCRYPT_ON_HTTP_UPLOADED
                || message.getEncryption() == Message.ENCRYPTION_AXOLOTL
                || message.getEncryption() == Message.ENCRYPTION_OTR) {
            this.key = new byte[44];
```

Which can be found here: https://github.com/iNPUTmice/Conversations/blob/b6fe1898e7717af67bfc98fe6f05dc4a44820e28/src/main/java/eu/siacs/conversations/Config.java

```
public static final boolean ENCRYPT_ON_HTTP_UPLOADED = false;
```

@iNPUTmice Does this mean if I set this to `true` it will force all files to be encrypted on HTTP PUT/upload?

**Comment by licaon-kter** [comment]
If http is available and file size < http max size, upload file. If > max size, try Jingle.

**Comment by orlyjamie** [comment]
Cool thank you for explaining the logic around the preference, do you know anything about the boolean config value `ENCRYPT_ON_HTTP_UPLOADED` will this enforce encryption on ALL file uploads via the client if the client it built with this option?

**Comment by orlyjamie** [comment]
Why close for?
