### ISSUE TITLE
ENCRYPTION_MASK config option

### ISSUE THREAD

**Issue by orlyjamie** [iNPUTmice/Conversations#4242]
I have a question about this commit/config option(s) 

https://github.com/iNPUTmice/Conversations/commit/002dbf2e17556647dab559abfae5554befd0314b#diff-e1a596434cdddd2929cc6df2f0547616e89119f44e12e2e11d520b6d62ba365c

```
private static final int OTR = 4;
	private static final int OMEMO = 8;

	private static final int ENCRYPTION_MASK = OMEMO;
	private static final int ENCRYPTION_MASK = UNENCRYPTED | OPENPGP | OTR | OMEMO;

	public static boolean supportUnencrypted() {
		return (ENCRYPTION_MASK & UNENCRYPTED) != 0;
```

If I ware to remove all ENCRYPTION_MASK's and only leave `OMEMO` would this mean that it would be impossible for me to send unencrypted messages? (That is one of my goals, preventing users from accidently sending unencrypted messages).

@iNPUTmice @licaon-kter

**Comment by orlyjamie** [comment]
Bump?

**Comment by licaon-kter** [comment]
Pls don't bump.

**Comment by iNPUTmice** [comment]
Unfortunately you'll have to verify that yourself. This option is currently not used or tested.

**Comment by orlyjamie** [comment]
Thanks Daniel
