### ISSUE TITLE
Show saved password(s)

### ISSUE THREAD

**Issue by jf99** [iNPUTmice/Conversations#4244]
A friend of mine is replacing her old Android phone with an iPhone. Unfortunately she does not remember the password of her XMPP account. Is there any possibility in Conversations to show the saved password? If not, can the password be read out in another way (e.g. from a sqlite database file)? Thanks.

**Comment by licaon-kter** [comment]
Yes, if they have root, the history file in /data/data/eu.siacs.conversations/... has the password.

**Comment by jf99** [comment]
@licaon-kter Thanks. I will try it once I get my hands on it.
