### ISSUE TITLE
Fetching history from server

### ISSUE THREAD

**Issue by orlyjamie** [iNPUTmice/Conversations#4246]
I've used conversations for many years (playstore) but recently I built from src and I'm getting this message when I enter a chat with a user as a toast message. 

"Fetching history from server"

I'm setting up a server not to cache messages on the server, is there any way to disable this check from the client side via config value or something? As stated I never saw this on the Playstore version of conversations.

**Comment by licaon-kter** [comment]
Accounts - Account - upper right menu, Archive is setup as?

**Comment by orlyjamie** [comment]
Was set to Always archive. will play with this!
