### ISSUE TITLE
password readable in history sqlite table

### ISSUE THREAD

**Issue by FilLupin** [iNPUTmice/Conversations#4259]
Hi there,
while reading history table from 2.9.3+fcr, I noticed that password from accounts are readable.

Is there a way to avoid this?
Isn't there here a privacy issue?

Regards.

**Comment by licaon-kter** [comment]
/close as wontfix

If somebody can read that file they can already do anything to your system.

**Comment by FilLupin** [comment]
If someone access to a backup file, it does not means they can do whatever they want.
It does not seem mandatory to keep password in clear.

**Comment by licaon-kter** [comment]
Your Conversations backups (from within the app) are encrypted with the account password.

Whatever other backups that you do at your own will need to be secured too, but that's up to you.

**Comment by FilLupin** [comment]
Ok, I understand this is a choice done willingly by development team.

I precise my goal is not to question this choice but to understand better what can be done on android dev: does it seem impossible to store a hashed password in database, or is it because it does not seem necessary to hide the password in database?

**Comment by licaon-kter** [comment]
It needs the user to unlock it at every interaction? If not it still will be stored in memory? The same opponent that has root to read internal storage has root to read memory too, right? So? Why bother?

**Comment by FilLupin** [comment]
It make sense. 
Thank you for taking the time to answer me.:)
Cheers.
