### ISSUE TITLE
I would like to help out with the Swedish translations

### ISSUE THREAD

**Issue by Hund** [iNPUTmice/Conversations#4265]
I would like to help out with the Swedish translations. I noticed that there's a lot of missing strings.

It's been a long time, but I have experience with translating in the past. I used to be a translator for Ubuntu Linux and I have helped various smaller projects here and there.

**Comment by iNPUTmice** [comment]
I've authorized your join request on transifex.

**Comment by Hund** [comment]
Thank you!

**Comment by Hund** [comment]
It doesn't look like my request was accepted on my end?
