### ISSUE TITLE
A/V Calls - discovering devices

### ISSUE THREAD

**Issue by zugcity** [iNPUTmice/Conversations#4269]
Hello,
there seems to be an issue with audio and video calls. Conversations is running, receiving messages properly, but calls aren't working. It gets stuck on "discovering devices". The behavior is the same if all clients are in intranet. In order to place a call, both clients must have the chat opened.
This is a new issue for me, I use Prosody as server + coturn

**Comment by licaon-kter** [comment]
Devices? Android versions? Conversations installed from which store? Battery optimisations ignored?

**Comment by zugcity** [comment]
Multiple devices, mostly Xiaomi, Android versions from 6 to 10. Yes, battery optimisation disabled and the flag is set to run conversations in foreground. It was working for months without issues.

**Comment by zugcity** [comment]
Conversations is installed from F-Droid

**Comment by licaon-kter** [comment]
Any server logs?

**Comment by zugcity** [comment]
No, no status or error logs

**Comment by zugcity** [comment]
I created 2 new account..it seems to work properly on conversations.im server

**Comment by licaon-kter** [comment]
Better join and ask in
xmpp:prosody@conference.prosody.im?join

**Comment by iNPUTmice** [comment]
The usual suspect would be one of the csi modules on prosody. In any case this is probably not a Conversations issue.

**Comment by zugcity** [comment]
Hi,
thanks for the reply. I disabled the CSI module and it works properly now.

**Comment by iNPUTmice** [comment]
fwiw you don’t need to disable it entirely. just update it and/or use one that let's jingle messages through
