### ISSUE TITLE
Security audit of conversations

### ISSUE THREAD

**Issue by Bruno-Fabijanic** [iNPUTmice/Conversations#4271]
Hi,

Just letting you know about the latest audit.

https://link.springer.com/article/10.1007/s42452-021-04431-9#ref-CR3

**Comment by licaon-kter** [comment]
@Bruno-Fabijanic that's one year old and some questions about the audit were not answered

**Comment by Bruno-Fabijanic** [comment]
Thank you for you reply.

My question is are the messages being kept in the db for how long? Are they being deleted after you click Clear History in the chat client?

**Comment by licaon-kter** [comment]
@Bruno-Fabijanic https://nitter.fdn.fr/iNPUTmice/status/1380165051479433218

**Comment by Bruno-Fabijanic** [comment]
> @Bruno-Fabijanic https://nitter.fdn.fr/iNPUTmice/status/1380165051479433218

Thank you for the reply.

But still i cant find info related to my first question...

What is exactly stored in the db and how does it work in relation to messages.

**Comment by licaon-kter** [comment]
Read the code, find out...

**Comment by Bruno-Fabijanic** [comment]
I am, new to android studio and java. I am coding in other languages but thanks for the tip, i will try to find out cheers!
