### ISSUE TITLE
Speaker phone icon should be visible before call connects

### ISSUE THREAD

**Issue by SamWhited** [iNPUTmice/Conversations#4272]
When making a call the speakerphone icon is hidden until the call finishes connecting. This means that if you pull the phone away from your ear to turn the speaker phone on you miss the first few words after it connects and it makes for an awkward interaction. It would be nice if you could turn it on while it was still ringing so that you both know it's ringing if you're not holding it to your ear and so that you can have it pre-setup if you're planning on taking the call on speaker.

**Comment by licaon-kter** [comment]
And bigger, like the close call one, for hands-free situation.
