### ISSUE TITLE
AV call icon missing for only one contact

### ISSUE THREAD

**Issue by zpunout** [iNPUTmice/Conversations#4273]
The audio/video call button is missing for one of my contacts.
She can call me however.
Other contacts are working normally.
Issue exists in both Quicksy and Conversations.
Issue began a month ago after we simultaneously tried to call each other. 
Is this a server side issue? (We are both using @quicksy.im)
I'm happy to provide logs if someone explains how to do it.

**Comment by licaon-kter** [comment]
Contact details, both presence checkboxes are checked?

**Comment by zpunout** [comment]
Thanks for the reply.
"Receive presence updates" was unchecked.
Have set both presence checkboxes to checked now and rebooted device.
Took a few minutes, but the AV call icon has returned.
Thank you. Issue resolved.
Was my issue covered in the faq anywhere?

**Comment by licaon-kter** [comment]
See Readme
Close issue
