### ISSUE TITLE
FR: Keep the media files hidden/encrypted on disk

### ISSUE THREAD

**Issue by AnmolBaansal** [iNPUTmice/Conversations#4275]
Many users switch to conversations as a more secure messaging. While Conversations supports encryption using omemo/openpgp, the media shared is openly available on phone storage. These files can be seen by any other application.
Example:

- image files received are stored in Conversations folder
- images captured by camera are stored in DCIM

Some other messaging apps dont store files directly on disk but rather gives the option to user to export images to gallery ie disk

**Comment by AnmolBaansal** [comment]
Just to complete, I am not suggesting storing it openly in just another folder which is not DCIM, I am talking on implementing a proper, encrypted file storage container like telegram does.
I dont know if these are the right files but do have a look : https://github.com/DrKLO/Telegram/tree/master/TMessagesProj/src/main/java/org/telegram/messenger/secretmedia

**Comment by licaon-kter** [comment]
The device storage is already encrypted.

Adversary system level apps can extract your data anyway.

It all boils down to your threat level, if apps: easy, don't use untrusted apps. If system: get another ROM. Etc

**Comment by Nemris** [comment]
@AnmolBaansal By the way, `adb` should allow you to sort-of unregister your system apps so that they appear to be uninstalled. You might want to look into `pm uninstall --user 0`.

**Comment by AnmolBaansal** [comment]
Thanks @Nemris will definitely look into this.
