### ISSUE TITLE
Failed to resolve: org.sufficientlysecure:openpgp-api:10.0

### ISSUE THREAD

**Issue by hysapp** [iNPUTmice/Conversations#4276]
The `openpgp` Library could not be downloaded. This library seems to have been removed from Maven. Please share the `aar` file of this library for download.

**Comment by licaon-kter** [comment]
@hysapp builds fine for me, could you retry?

**Comment by hysapp** [comment]
> @hysapp builds fine for me, could you retry?

It's OK now.
