### ISSUE TITLE
F-Droid and newer webrtc question

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#4279]
As asked in the support channel, would it be ok with you to have F-Droid create a 2.10.3-beta/alpha/whatever _(not marked as recommended at least for now)_ which is 2.10.2 (at https://github.com/iNPUTmice/Conversations/commit/b5786787f011607b2aacc869c2a9d1c83ffc871f ) plus cherry picked newer commits that don't touch the webrtc subsystem?

I've already tried locally, meaning I've merged these, in order:
9843b72f6fc3993313c404c2ab0e5aa70b4c6a77
5d526a77e3899714750d5f56536364a5ed9b5149
51db83d62975d12e060320f3f35207cb1c0ec300
666ca485dbd0e00ac26b32fddcec295c15a7dc15
68fd17778ccd16a66f164ae1bb19a83e6d550a4b
eed5c5e74319520e7541102f906e02d81849ad62
b6442c0bd45f13ae701fa42863338b6192ee91e7
f2a67f899b5f4d5fbe1419f1b0568d9e84c35921
ecdb5af5473437ddc7d76cd5a5d620a8ea83db68
cf9d6e5ca324092dde52b9838063886120284729
fecc34431cd321131bedce0085d3aea291170fdf
12463911f171792f17138b276c047de347feb225
364ef2543d55e6f6424fd84518ce04798f76bc79
2553895300bfccf9b9e593acb034e4a679feacd1
cdc239b040678348b26cb19a4de39d13efc9f313
6bd552f6a32ca93826cb491f9b4bd757f9698227

The resulting APK works fine with a glitch: Audio/Video are not established if devices are not on the same LAN _(tested with older Conversations 2.10 iirc and Dino 0.3.0)_.

There's no logcat output tagged `conversations` when this happens so no `ICE` and no `candidate`.
Looking in the Dino output it appears that Conversations only sends type `hosts` of local VPN (NetGuard) IPs, eg. 10.10.10.5 or some IPv6. I'll reread all the commits included to get a clue of where the issue lies, but maybe you've got a pointer or two.

Ref: https://gitlab.com/fdroid/fdroiddata/-/issues/2064#note_841837255

It's my intention to restart the process of liberating webrtc soon, but for now just trying to get one more Conversations version released. :)

**Comment by licaon-kter** [comment]
Retested with on older local 2.10.2+fcr build that I have and it behaves the same, regarding the issue with connecting calls, and I vaguely remember having this issue in the past, with my local built versions, while the official F-Droid builds from the main server work fine. So it does not appear to be related with the way I've integrated the commits. :)

**Comment by singpolyma** [comment]
If the main issue is that the binary from Maven is not longer sufficient, I am hosting a content-addressable version of the latest WebRTC that can be used like this: https://git.singpolyma.net/cheogram-android/commit/3a38c76eb2015677691bbb3ad30810a251caa394#build.gradle

**Comment by licaon-kter** [comment]
Anyone can build it, not the issue.

Building it from FOSS only deps (not from 20Gb of binaries from Google) is... did you do that?

**Comment by singpolyma** [comment]
>Anyone can build it, not the issue.

Except that almost no CI can build it due to size constraints.

>Building it from FOSS only deps (not from 20Gb of binaries from Google) 
>is... did you do that?

No, obviously the liberation work would be great, but this seems for now 
equivalent to the old strategy of using binaries from Maven?

**Comment by licaon-kter** [comment]
> but this seems for now
equivalent to the old strategy of using binaries from Maven?

Which this? This issue? F-Droid building it (CI or not CI)? Or?

**Comment by singpolyma** [comment]
@licaon-kter Sorry, I just meant since the build was using a binary from Maven before, maybe a stable binary could be used now and the situation would not be worse.  Until F-Droid is able to build a "good" version

**Comment by licaon-kter** [comment]
Who makes that stable binary? How did they create it?

The Maven one was a compromise, based on some trust.

**Comment by iNPUTmice** [comment]
We have our own binary online as well. But according to f-droid this is not a trusted source.

**Comment by licaon-kter** [comment]
Updated with
60617618b819b1f427b6e639e6cbd05832e79796
8abacd23e8d29a75d0abd497dc842de4663e2a84
d6be6ddd18335d6a4cf437a8e4f2b425c57914f1
2cc49e5ba66785c12b283af727273187393c47f6
6fb465f91aae23db422ff2ab9277ec6b0f94a57b
282109db01932c1be8e6231879ef5a75d67f5b74
c03a8b784f38bd3eb1a92f8dc44d794cb19b5ab7
0b470534f1b634261901d31a43e11b8293f5ef2c
4129ca6af8f22fc64cca891052615d3d2755ad79
ad493938a03cadb4747613040bad9c28cf244789
3534c619fbd5d5e78f349ed13f8d10612af76114
48f8c1a6a0115bd2fd9782a9a4344e29b159a7bc
35c54f0ae968ba76b78fed6c7081d52d2404c9ef
be1fcfe4f93d9f06cae82cfe43c8c45bde591ed3
9b6a5709390f4550e74cceee4a20900759097143
d311e39569226f74f1ae8d1b948b88e6311a28d8
6d7058398ea529f0e16ef84ba415c61de7ff2973
4a5e27130c000f8dbcdfde7e8b6ba6416cab039b
882e7319edfcf848a3a622de99d2ae799d2da32c
eb6ae5b03c500a85282a2690c8008e51d1771435
aef5292567099e683e9342eca9507d6c43ae3d0b
f95ed284b51aef46bd9a490b31315ea6fcedae1d
56f01c29b9560879eb84ff6b2848fefda86a8cbe
5c4eccec13508a8687452adc96f0799813b6f3c3
330980391cbfba90071760cd7b2e15eb82dc4d81
99e4c3d2e0c10d5ea81bd5b4ddb5dad9f295687f
7731a864fd5095dd0cd795b47d3634499c8cd8e0
ed9886050607515aca3849066ea13d8ff6fd6bce

Works ok

Also, elsewhere https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10760 (same idea, without the webrtc changes)

**Comment by licaon-kter** [comment]
Updated with:
fbbd2edd94c9397b72bc4d2a4cdf07fec4a3360c
89428b0ad353e7ffd5ab71e0993b80c6f5c5ddbd
7c6ab7febca12cf629bca44fa929271d7accfa42
fbf1cacae3959c96c7beed4e73993d64564403b5
8834bc5084a8fb42ecfa813b166d6c7e23f58a7b
5943f1ad3ee9101738339d26fac7b865e2f64f50
36756fbd410d72e64b2e579eb383befaa806a407
de7eb2b5c7b28e538c05a0729109395504df7ecf
93c591634684b31660d852a92b5ee576a52ca9eb

:+1:

**Comment by iNPUTmice** [comment]
2.10.9 will be available on fdroid.

**Comment by licaon-kter** [comment]
Thanks
