### ISSUE TITLE
Conversations accept/trust new device fingerprint when BTBV is on and at least one device fingerprint is verified

### ISSUE THREAD

**Issue by andypl** [iNPUTmice/Conversations#4288]
Hello,

Probably I have found bug in Blind Trust Before Verification.

Blind trust before verification mean, that until at least one device is not trusted all new devices are automatically blindly trusted (BTBV). When at least one device is verified, new devices will not be automatically trusted, and user should veryfy it manually by trusted channel (the verified devices for example).

I have found, that this behaves different. 

Steps to reproduce:
1. Create two account: A1 and A2 on a different phones.
2. Connect from Conversations (device - A1D1)to account A1.
3. Connect from another (device - D1A2) Conversations to account A2.
4. Trust device fingerprint A2D1 in A1D1, and device fingerprint A1D1 in A2D1.

Now: 
1. Connect to account A1 another device called A1D2 (for example Gajim or Dino).
2. Send encrypted message to contact A2D1 from A1D2.

What happen?
On A1D1, fingerprint of A1D2 is automatically trusted and in A2D1 device fingerprint of A2D2 is also automatically trusted, but it should be not, because at least one device is verified - point 4 from scenario. "TLDR: Automatically trust all new devices of contacts that haven’t been verified before, and prompt for manual confirmation each time a verified contact adds a new device." https://gultsch.de/trust.html

**Comment by licaon-kter** [comment]
Why closed?

**Comment by andypl** [comment]
Because i misunderstand what checked checkbox mean when BTBV is on. It mean, that device fingerprint status is set to blinds trust, not verified.
