### ISSUE TITLE
Can't connect due to error resolving SRV record.

### ISSUE THREAD

**Issue by tuxayo** [iNPUTmice/Conversations#4289]
Since October, unrelated to an update, I got a Conversations client that can't connect to conversations.im.

```
10-21 03:30:01.688  1653  9397 E conversations: blabla@conversations.im: Resolver results were empty
10-21 03:30:01.692  1653  9399 D conversations: Resolver: error resolving SRV record (STARTTLS)
10-21 03:30:01.692  1653  9399 D conversations: de.measite.minidns.util.MultipleIoException: Operation not permitted, Connection refused, Operation not permitted, Connection refused, Operation not permitted, Connection refused, Network is unreachable, Network is unreachable
[...]
10-21 03:30:01.693  1653  9398 D conversations: Resolver: error resolving SRV record (direct TLS)
```

I though it was the mobile ISP but when giving network from another phone (Bluetooth tethering) then my Conversations works. And when it's my phone that gives network to another phone with Conversations, it also works (the other phone).

So my main phone Conversations work when internet access is not from mobile. And my mobile internet is able to make Conversations work on another phone.

It doesn't make any sense. Any clue about the cause or what I could do to gather more info?

version: 2.10.2+fcr

**Comment by licaon-kter** [comment]
Device? Android version?

**Comment by tuxayo** [comment]
So, I backed up the app with the built-in function, uninstalled it, and then installed and restored and now it works! Absolutely no sense.
