### ISSUE TITLE
GPG issue in Conversations

### ISSUE THREAD

**Issue by rikanox** [iNPUTmice/Conversations#4291]
PGP issue in Conversations. I imported my private GPG-key from GPA to OpenKeyChain. I enter my password and choose remember it "until cleared". 

But system demands to re-enter GPG-password after every reboot or after 24h working. How to save the password forever? I use this private key in Conversations only. Everything works well except this issue.

**Comment by licaon-kter** [comment]
Which app popsup exactly OpenKeyChain or Conversations? OKC does not have any settings?

**Comment by rikanox** [comment]
> Which app popsup exactly OpenKeyChain or Conversations? OKC does not have any settings?

I answered bellow (step 6).

Conversations uses OpenKeychain (OKS) as main solution for PGP/GPG.

1. I imported my 4096 RSA private key from desktop (GPA) to android (OKS)

2. I have added this keys to my jabber account in Conversations 

3. I'm sending an encrypted message from desktop (Gajim) to android (Conversations).

4. I see the banner _"New OpenPGP encrypted messages found. DECRYPT"_ in my Conversations chat.

5. I press _"DECRYPT"_ in Conversations chat

6. A window appears "_Enter password for_ [name of my private key]. _Remember it"_ with **only 4** options: _"until screen off", "for one hour", "for one day", "until cleared"._ This is OKS popsup as I understand.

7. I enter the password, select _"until cleared"_ and Conversations PGP works well before next reboot.

8. I have to repeat steps 4,5,6,7 again after every reboot or within 24 hours. 

9. The option existed to remember the password "forever". This was in OpenKeychain / Settings / Passwords and PINs ([proof](https://github.com/android-password-store/Android-Password-Store/issues/305#issuecomment-309239959)). Developers deleted this settings from "Passwords and PINs" ([proof)](https://github.com/open-keychain/open-keychain/issues/2205). Password remembering are now configured only at password entry. And there are only 4 options without "forever" (look to step 6)

10. Entering a 50-digit password several times a day is simply unrealistic. It makes frequent GPG/PGP chat almost impossible on Conversations.

**Comment by rikanox** [comment]
> So why is this a Conversations issue? 

This issue prevents from using PGP in Conversations daily and often. Only one way in your [FAQ:](https://github.com/iNPUTmice/Conversations/blob/master/README.md)

_"To use OpenPGP you have to install the open source app OpenKeychain and then long press on the account in manage accounts and choose renew PGP announcement."_

I'm sure other Conversations users have experienced this issue too. And I asked about it. 

Do you know **how to use PGP in Conversations without entering a password after a reboot?** Is it possible with imported private keys or not?

> Can you point in code where it's cleared after 24h (precisely?!)?

I seen only once when password cleared after (about) 24 hours. The reason is that I ussualy reboots several times per day. I will write more precisely when it happens again.

**Comment by licaon-kter** [comment]
Eg. I'd understand it asking for the password after a reboot, say it keeps it in memory, reboot clears it.

But without reboots?

**Comment by rikanox** [comment]
> But without reboots?

I answered [here](https://github.com/iNPUTmice/Conversations/issues/4291#issuecomment-1061082039) (last 3 sentences)

**Comment by licaon-kter** [comment]
Those don't make any sense, I say "without reboot" you say "24h but more reboots"

I meant 27-30h **without** ANY reboots.

Is your device broken? Why do you constantly reboot it?

**Comment by rikanox** [comment]
I seen **once** when password cleared after (aproximately) 24 Hours **without any reboots.**

And I see  the same issue **every time after reboot.**

My device is not broken. I reboot it often for personal circumstances (work, routes, networks, and so on).

Please respond to my question. Do you know how to use PGP in Conversations without entering a password after each reboot? Is it possible with imported private keys or not?

**Comment by iNPUTmice** [comment]
Conversations uses OpenKeychain and is thus limited by what OpenKeychain has to offer.

I recommend you use OMEMO.
