### ISSUE TITLE
"Downgraded SASL mechanism" - how to override?

### ISSUE THREAD

**Issue by luke-jr** [iNPUTmice/Conversations#4293]
ejabberd 21.04 was silently losing messages, so I downgraded to 20.04, but now Conversations refuses to connect. How can I override this?

**Comment by luke-jr** [comment]
Seems I can modify the history db with pinned_mechanism=-1 ?

**Comment by licaon-kter** [comment]
Which ejabberd issue is that?

What's different in your ejabberd config?

**Comment by iNPUTmice** [comment]
There should be an accept or ignore button in the account details (What used to be the Save button)

**Comment by baack** [comment]
> There should be an accept or ignore button in the account details (What used to be the Save button)

@iNPUTmice I have the same problem, the problem reason: server has "updated" ejabberd and I have the same message in Conversations and not able to login. I see no `Ignore` button you mentioned. I am using the latest f-droid version.
I would appreciate any help.

**Comment by licaon-kter** [comment]
Just retry to login, go to Accounts, your account, press save/connect/whatever it says in the lower right corner

**Comment by baack** [comment]
OK, it worked! Thanks for help @licaon-kter and the app @iNPUTmice 
1. The solution was to wait for 30 minutes or so, and then I got this error about SASL and the button became available.
2. It is not obvious for users. Maybe this feature should be reconsidered or redesigned, maybe a message popup should be displayed describing what is happening, what is the problem and what are the risks and solutions.
