### ISSUE TITLE
unable to compile it on android studio

### ISSUE THREAD

**Issue by apprenticius** [iNPUTmice/Conversations#4295]
Error:

/Conversations-master/src/main/java/eu/siacs/conversations/services/AppRTCAudioManager.java:27: error: package org.webrtc does not exist
import org.webrtc.ThreadUtils;

**Comment by licaon-kter** [comment]
Read README

/close as invalid

**Comment by apprenticius** [comment]
Yes, sorry my fault! - All is working fine, after I read the whole README (I didn't read to the end... :-( )

**Comment by apprenticius** [comment]
Building ./libwebrtc.aar I get many errors running Python ./tools_webrtc/android/build_aar.py. Unfortunately I have no idea, where the Mistake could be. Any help would be very kind...

~/AndroidStudioProjects/Conversations/build_aar/webrtc/src$ python3.8 ./tools_webrtc/android/build_aar.py
INFO:root:Building: armeabi-v7a
Done. Made 5497 targets from 328 files in 970ms
ninja: Entering directory `/tmp/tmpm4z2oyvy/armeabi-v7a'
[3159/4198] ACTION //build/android/byt...d/toolchain/android:android_clang_arm)
FAILED: obj/build/android/bytecode/bytecode_processor_java.turbine.jar gen/build/android/bytecode/bytecode_processor_java.generated.srcjar 
python3 ../../../home/elmar/AndroidStudioProjects/Conversations/build_aar/webrtc/src/build/android/gyp/turbine.py --depfile=gen/build/android/bytecode/bytecode_processor_java__header.d --generated-dir=gen/build/android/bytecode/bytecode_processor_java/generated_java --jar-path=obj/build/android/bytecode/bytecode_processor_java.turbine.jar --java-srcjars=\[\] --target-name //build/android/bytecode:bytecode_processor_java__header --classpath=@FileArg\(gen/build/android/bytecode/bytecode_processor_java.build_config.json:javac:interface_classpath\) --processorpath=@FileArg\(gen/build/android/bytecode/bytecode_processor_java.build_config.json:javac:processor_classpath\) --processors=@FileArg\(gen/build/android/bytecode/bytecode_processor_java.build_config.json:javac:processor_classes\) --turbine-jar-path ../../../home/elmar/AndroidStudioProjects/Conversations/build_aar/webrtc/src/third_party/turbine/turbine.jar --generated-jar-path gen/build/android/bytecode/bytecode_processor_java.generated.srcjar --java-version=1.8 --chromium-code=1 --warnings-as-errors @gen/build/android/bytecode/bytecode_processor_java.sources
Traceback (most recent call last):
  File "../../../home/elmar/AndroidStudioProjects/Conversations/build_aar/webrtc/src/build/android/gyp/turbine.py", line 15, in <module>
    import javac_output_processor
  File "/home/elmar/AndroidStudioProjects/Conversations/build_aar/webrtc/src/build/android/gyp/javac_output_processor.py", line 23, in <module>
    import lookup_dep
  File "../../../home/elmar/AndroidStudioProjects/Conversations/build_aar/webrtc/src/tools/android/modularization/convenience/lookup_dep.py", line 20, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'

**Comment by licaon-kter** [comment]
Use the .aar provided in the .github/.yml file in the meantime.

**Comment by apprenticius** [comment]
Now, it's running...
My python version missed "dataclasses". After installing "python -m pip install dataclasses" all works fine and finally I got the library "libwebrtc.aar".

Thank you so much for your patience.
