### ISSUE TITLE
Ringing tonality when discovering devices

### ISSUE THREAD

**Issue by tuxayo** [iNPUTmice/Conversations#4297]
Sometimes, the tonality starts when it's still discovering devices. Is that expected?

version: 2.10.2+fcr

**Comment by iNPUTmice** [comment]
This is relatively new in 2.10.0
https://github.com/iNPUTmice/Conversations/commit/7466d125056307a6c2a767a0e4a95b77343aa1f2

**Comment by tuxayo** [comment]
So it's desired to have a tonality when discovering devices? Can it be different then? To not give the impression that it's ringing on the other side when it's still connecting.
