### ISSUE TITLE
Error building application

### ISSUE THREAD

**Issue by hyperedgesystems** [iNPUTmice/Conversations#4298]
hello, I tried building the application, but encountered the following error:
`
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.
`
Can someone please help me figure it out?

**Comment by licaon-kter** [comment]
So you've cloned the repo, then in Studio you've pressed Import project... chose the folder... waited for it to sync?

**Comment by hyperedgesystems** [comment]
yes

**Comment by hyperedgesystems** [comment]
If I open the project in Android Studio that is the same as importing it right?

**Comment by licaon-kter** [comment]
Dunno, so your Studio is updated? Did you gradle sync and whatnot?

**Comment by hyperedgesystems** [comment]
yes

**Comment by hyperedgesystems** [comment]
it was during the sync that it gave the erorr

**Comment by licaon-kter** [comment]
As the error says try to update that thing first.
