### ISSUE TITLE
No Microphone Audio in Video Calls with Redmi Note 9S/Pro

### ISSUE THREAD

**Issue by hede5562** [iNPUTmice/Conversations#4301]
#### General information

* **Version:** 2.10.2+fcr
* **Device:** Xiaomi Redmi Note 9 Pro / 9S
* **Android Version:**  LineageOS 18.1
* **Server name:** self hosted (der-he.de)
* **Server software:** ejabberd 21.01-2 (100% compliant as per your test)
* **Installed server modules:** mod_adhoc, mod_admin_extra, mod_announce, mod_avatar, mod_blocking, mod_bosh, mod_caps, mod_carboncopy, mod_client_state, mod_configure, mod_disco, mod_echo, mod_fail2ban, mod_http_api, mod_http_upload, mod_last, mod_mam, mod_muc, mod_muc_admin, mod_offline, mod_ping, mod_pres_counter, mod_privacy, mod_private, mod_proxy65, mod_pubsub, mod_push, mod_push_keepalive, mod_roster, mod_s2s_dialback, mod_shared_roster, mod_sic, mod_stream_mgmt, mod_vcard, mod_vcard_xupdate, mod_version, mod_stun_disco
* **Conversations source:** F-Droid

#### Steps to reproduce

A
1. Start a video call

B
1. Start an audio call
2. Switch to the loudspeaker within the audio call

#### Expected result

A: Have audio with the video call

B: Have audio after activating the loudspeaker in the audio call

#### Actual result

A: No microphone in video call

B: No microphone if the device is switched to the loudspeaker in the audio call

#### Debug output

[conversations_audio_only.txt](https://github.com/iNPUTmice/Conversations/files/8378555/conversations_audio_only.txt)
[conversations_video_no_audio.txt](https://github.com/iNPUTmice/Conversations/files/8378557/conversations_video_no_audio.txt)

#### Additional Information

With the video call I do not have any microphone functionality and with the audio call it stops working with switching to the loudspeaker.

I have several devices available (friends, family, etc.) and this problem is present only on the Redmi Note 9S and the Redmi Note 9 Pro, both with LineageOS 18.1 installed. As far as I know one of the devices was used with the stock image and audio was fine - so I think this the problem probably is because of some configuration problem with the device / operating system. But maybe it is also resolvable in the app (conversations). There seems to be some kind of a "non-existent" microphone device if the loudspeaker is enabled (selected:SPEAKER_PHONE).

Would it be possible to have the microphone from the earpiece (selected:EARPIECE) while the speaker of the SPEAKER_PHONE is in use?

As the switching of the device is problematic the log conversations_audio_only.txt is probably more interesting. I switched the Audio device several times while logging (I do not remember how often I did it).

I do not know how Android works here. For example if the microphone has to be actively switched by the device or if this is a device/os feature. So please tell me if it is clear for you that the problem obviously is in the device/os.

**Comment by licaon-kter** [comment]
Does Jitsi Meet have the same issue?

**Comment by hede5562** [comment]
Sorry for stealing your time, but this seems to be a problem with the device/OS as the included phone app has the same problem.
