### ISSUE TITLE
Randomly disconnect and refuse to connect when on wifi

### ISSUE THREAD

**Issue by bhhaskin** [iNPUTmice/Conversations#4302]
I am having an issue where Conversations will randomly disconnect and refuse to connect when on wifi. It happens on multiple and different wifi networks. Toggling back to cell allows reconnect.

What would be the best way to start to debug this?

I am running android 12 on a pixel 5.

**Comment by bhhaskin** [comment]
I am not 100% sure what you mean by that. However I just found that toggling hostname DNSEC validation fixes the issue.

**Comment by iNPUTmice** [comment]
DNSSEC is known to not work reliably on some wifis and blocks the entire connection if it doesn’t work

**Comment by SomwareHR** [comment]
Happens to me, too. 
Conversations legacy 1.23.12
Same symptoms with both eJabber and/or Prosody as servers.
Works for some time after adding account and then for some reason stops.
After long time trying to reconnect - "Server not found" error shows and switches to "Temporarily disabled"
DNSSEC was not enabled in any of cases.

**Comment by licaon-kter** [comment]
@SomwareHR capture a logcat of these moments

**Comment by SomwareHR** [comment]
I uninstalled the server and will rebuild the system later.

> ... Why stick to old version

I would install even older one but I believe that's what was available to me at the time for that old machine - it already has more than enough for what I am using it.
I avoid "_Install new version of every software_" policy wherever I can for various reasons. Some of them are:

- new versions way too often cut off useful functions just to try and sell them later as an "extension"
- switching from "_just discovered security issue_" to "_not yet discovered security issue_" doesn't seem like a good reason to me, neither :) 
- there is rarely an option "_This version sucks; revert to previously installed one_"

I don't know if that's a case with Conversations. I believe it's not as developers seems to pay 
 a good attention. But regrettably I don't have the time to check every new version of every software before implementing.

**Comment by licaon-kter** [comment]
You do you... But you're missing out on 4 or more years of enhancements like calls and such.

That being said, not sure that version is supported so try to test with latest first and repro.
