### ISSUE TITLE
Requesting a new function

### ISSUE THREAD

**Issue by Barmarel** [iNPUTmice/Conversations#4307]
Please add the ability to set a pin code/password to enter the application.

**Comment by Barmarel** [comment]
> /close as duplicate #557 #2034 etc

Is it possible to add a function that if you enter one (main) pincode when logging into the application, one specific group of users and correspondence will be displayed, but if you enter another (hidden) pincode, another hidden group of users and correspondence will be displayed...?

**Comment by GithubUser452** [comment]
> /close as duplicate #557 #2034 etc

Those are more about encryption, what about just a simple graphical layer?

**Comment by licaon-kter** [comment]
How would that help with anything?

**Comment by GithubUser452** [comment]
> How would that help with anything?

Something l

**Comment by GithubUser452** [comment]
> How would that help with anything?

As an AppLock helps...

**Comment by GithubUser452** [comment]
> > /close as duplicate #557 #2034 etc
> 
> Is it possible to add a function that if you enter one (main) pincode when logging into the application, one specific group of users and correspondence will be displayed, but if you enter another (hidden) pincode, another hidden group of users and correspondence will be displayed...?

This is a great idea!
