### ISSUE TITLE
Chat list preview renders bold markup

### ISSUE THREAD

**Issue by cjaone** [iNPUTmice/Conversations#4311]
#### General information

* **Version:** 2.10.2.1+fcr
* **Android Version:**  Android 9 (stock)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Receive message (in a multi-user or personal chat) where the first words include bold font markup, i.e. `*test*`.
2. Read the message
3. Open the Conversations main page with the list of chats and have a look at the content preview.

#### Actual result

Usually unread messages are always rendered as bold in the content previews, and as soon as you read them and return to the chat list with the previews they will be displayed as normal text (not bold anymore).

But if the received message contained bold markup (`*test*` -> **test**) it is still displayed as bold.

This is confusing because it looks like there is an unread message (but there is none).

#### Expected result

Previews with bold markup are not displayed the same way as unread messages.

**Comment by iNPUTmice** [comment]
There is no 'correct' way to handle this. In fact when we introduced message styling we didn’t apply it to the preview for the exact reason you are describing. And then people complained about it not being styled (there is probably still an issue around for this).

However the title is not bold which should give enough of an indication.
