### ISSUE TITLE
Couldn't connect to account -- Stream Error

### ISSUE THREAD

**Issue by jmencak** [iNPUTmice/Conversations#4313]
Recent version of Conversations (after commit https://github.com/iNPUTmice/Conversations/commit/6bd552f6a32ca93826cb491f9b4bd757f9698227) are randomly disconnected from the server and A/V calls fail to be initiated.  Reverting the previously mentioned commit fixes the issues for me.

I've verified this on Google Pixel 5, stock Android 12 and Samsung S4 mini Lineage 16.0.

**Comment by licaon-kter** [comment]
Do you have any logs? Which server software?

**Comment by jmencak** [comment]
> Do you have any logs? Which server software?

ejabberd 21.01-2 on Debian 11.  I have the logs, but they contain too much private info.  This is what caught my eye:
```
conversations: user@my-server.mydomain: stream error <error xmlns="http://etherx.jabber.org/streams"><connection-timeout xmlns="urn:ietf:params:xml:ns:xmpp-
streams"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-streams">Idle connection</text></error>
```

**Comment by licaon-kter** [comment]
Put your (cleaned) ejabberd config on https://gist.github.com and paste the link

**Comment by jmencak** [comment]
Thank you for the revert, Daniel.
