### ISSUE TITLE
New message notifications do not work for groups on Fairphone4

### ISSUE THREAD

**Issue by pirofti** [iNPUTmice/Conversations#4316]
Hi,

First of all thank you for your efforts in making this great software!

I am encountering a problem with notifications for new messages in groups (conferences in xmpp-speak) on Conversations 2.10.2.1+fcr installed from F-droid on an Fairphone4 (FP4.FP3V.A.116.20220414) running Android 11. Private chat work, just groups are the problem. Tested on multiple servers and groups.

My server's users are able to reproduce this on other phones and Android versions, but I don't have their exact specifications. If needed I can gather some more setups where this is reproducable. I am running on prosody 0.12.

Any tips what to try or any other information that I can supply?

Thank you,
Paul Irofti

**Comment by pirofti** [comment]
All notifications are on. For everything. It's public channels. I can reproduce this with the prosody channel as well.

**Comment by licaon-kter** [comment]
If this happens to all groups then it's a device issue, or a settings one.

Pics of Android Notifications settings for Conversations?

**Comment by pirofti** [comment]
![Screenshot_20220429-003233](https://user-images.githubusercontent.com/1188967/165849360-44e20609-9119-414d-9238-e349fa5b6a3b.png)
![Screenshot_20220429-003201](https://user-images.githubusercontent.com/1188967/165849363-b9fafc1b-b107-49a4-a782-053f20c9b570.png)
![Screenshot_20220429-003144](https://user-images.githubusercontent.com/1188967/165849365-06e8b507-7288-46ea-bd8b-3b157fb9db19.png)

**Comment by licaon-kter** [comment]
You tested accounts on other servers too? Eg. Make a free account on `conversations.im` and join a group and test

**Comment by pirofti** [comment]
I have. But if you mentioned it, I created a new account as instructed and connected on the support channel there. Luckly daniel helped me realize that I have to modify the channel details and enable notifications there for all messages. So all is working, sorry about the noise.

On an unrelated note, @licaon-kter, I really like you avatar. It was my favorite childhood book. Was reprinted recently and I bought a new copy :)

**Comment by licaon-kter** [comment]
Mă bucur că îl recunoști ;)
