### ISSUE TITLE
Select Image does not open Gallery and instead opens files

### ISSUE THREAD

**Issue by Yoshi14502** [iNPUTmice/Conversations#4318]
Choosing Select Image in a chat leads me into my files instad of my gallery, just as select files would do. 

Xiaomi 11T Pro - Android 11

**Comment by licaon-kter** [comment]
It should open the Document view of files with a filter for images, not gallery. This is by design.

**Comment by Yoshi14502** [comment]
Thats the thing there is no filter for images or anything like that. It is just a normal fileviewer.

**Comment by licaon-kter** [comment]
Can you post a (censored) picture of what you see when you chose Files and what you see when you choose Image?

**Comment by Yoshi14502** [comment]
![1652621942896](https://user-images.githubusercontent.com/105558231/168475860-556e5c60-c2f3-48a6-b3d8-945023200301.jpg)
![1652621942904](https://user-images.githubusercontent.com/105558231/168475862-ed6f0d34-d006-472c-9f9e-0615f86bb2f5.jpg)

**Comment by licaon-kter** [comment]
That's awful, but not Conversations fault. Where you ever asked to choose an app to open with, when sharing?

Eg. Try to reset "open by default" properties of that File Manager app

**Comment by Yoshi14502** [comment]
Alright so I tried pretty much everything regarding that now. When I reset everything related and reinstall Conversations it does not ask me which programm to choose it just instantly sends me into the file manager. Does work fine on every other app, which is weird.

**Comment by licaon-kter** [comment]
Logcat via ADB? Grab the log when doing the action, maybe there's some useful info there.

**Comment by iNPUTmice** [comment]
From an app side there is no difference in the intent that starts a gallery vs an intent that starts a file chooser (only a pre selected type that that a file chooser can fulfill tool)
