### ISSUE TITLE
Support 3GPP video playback

### ISSUE THREAD

**Issue by singpolyma** [iNPUTmice/Conversations#4321]
Right now 3GPP is treated as audio-only even when it has video in it.

**Comment by licaon-kter** [comment]
So how does it decide ?

https://github.com/iNPUTmice/Conversations/blob/4a5e27130c000f8dbcdfde7e8b6ba6416cab039b/src/main/java/eu/siacs/conversations/utils/MimeUtils.java#L228

vs 

https://github.com/iNPUTmice/Conversations/blob/4a5e27130c000f8dbcdfde7e8b6ba6416cab039b/src/main/java/eu/siacs/conversations/utils/MimeUtils.java#L368

**Comment by singpolyma** [comment]
Not really a great solution, but for now  I have done this: https://git.singpolyma.net/cheogram-android/commit/082d7477788d617dd2f2d3ea64775aab6f865f12

**Comment by iNPUTmice** [comment]
Do you happen to have a 3gpp video test file I could use?

**Comment by singpolyma** [comment]
I used these: https://filesamples.com/formats/3gp
