### ISSUE TITLE
Compliance tester should specifically not attempt testing components which advertise the gateway category.

### ISSUE THREAD

**Issue by maranda** [iNPUTmice/Conversations#4325]
To test MUC features the tester needs to create a room else it'll fail 'em even if the tested features *are actually supported*, considering there isn't an actual disco feature to advertise *if* room creation is supported or unsupported, the tester should specifically ignore all components which also advertise in disco the gateway category. Otherwise the tester will lower the service score even if there's another MUC components which supports all features and allows room creation.

**Comment by iNPUTmice** [comment]
This is the bug tracker for the app

**Comment by maranda** [comment]
@iNPUTmice yes and there's no tracker for the tester -> https://github.com/iNPUTmice/caas
