### ISSUE TITLE
App disconnects when phone screen is off

### ISSUE THREAD

**Issue by solus-hq** [iNPUTmice/Conversations#4327]
Hello!

After updating my phone and switching to Conversations from F-Droid repo I can't resolve this issue when app disconnects when screen is off and instantly reconnects when it's back on.

Basic info:

Mobile: Galaxy S20FE
OS: Android 12
Conversations: latest from F-Droid

Turned off:

- Battery optimizations
- Adaptive battery
- Put unused apps to sleep

Network:

VPN connection is "Always On" via Mullvad wireguard, using WIFI

**Comment by licaon-kter** [comment]
https://dontkillmyapp.com didn't help?

**Comment by solus-hq** [comment]
Well, it seems that turning every battery optimization option helped with this issue.

Thanks again for doing this great job of making a robust XMPP client for android! 

Wish you could release one for macOS =)

**Comment by licaon-kter** [comment]
Snikket should work fine (and Siskin it's base, but with some settings). Join the support room (readme) for more tips.
