### ISSUE TITLE
Deletion of old omemo-keys

### ISSUE THREAD

**Issue by xundeenergie** [iNPUTmice/Conversations#4328]
I use xmpp from 2 smartphones and 2 laptops, and sometimes from a webclient (movim is cool stuff!!!)

In the last year i collected 70 omemo-keys on one and 74 on the other smartphone... not able to delete them. 

How comes, that there are so many omemo-keys?
So every time i logged in to movim, i got a new key.
Every time i tried conversations, i got a new key.
I tried gajim, gajim-dev, dino and other Linux-clients on fedora. For each installation a new key.
I changed to debian, installed gajim from distribution -> A new key.
I upgraded gajim to 1.4.0 from backports... but it's unusable buggy. 1.4.3 is today in unstable. Wait 2, 3 weeks till it is in backports hopefully? So... use another client in this time... -> Gajim from flatpak -> a new key. Or Dino? -> a new key. switch back, wehen 1.4.3 or higher is in backports? -> A new key. 
Reset my phone -> a new key.
Try another client on my phone -> A new key.

so many situations i get a new key... and they stuck in conversations like the back-side stuff of a dog on my shoes. 

Delete "other devices" in conversations deletes the other keys in the omemo-representation. it works on gajim. all other keys are gone... but in conversations... they stuck there as old farts in chief-positions... 

Please make it possible to delete old omemo-keys manually in conversations an delete them, if they are deleted in omemo-key-publishing on other phones...

**Comment by licaon-kter** [comment]
Read: https://github.com/iNPUTmice/Conversations/issues/4147#issuecomment-903078635

/close as duplicate #3253
