### ISSUE TITLE
bug: voice message get cut off

### ISSUE THREAD

**Issue by paskalito** [iNPUTmice/Conversations#4329]
Android 12
LineageOS 19
Conversations: 2.10.2.1+fcr
Device: Oneplus 6

If i record voice messages they sometimes (~50+%) get cut off at some random point.
The UI is looking perfectly normal. but the file that is sent is cut off.
if i find the file and play it locally it is also cut off - it seems dough that the metadate within it, is showing the correct time of the intended recording length.

I downgraded to Conversations 2.9.13 +fcr and the issue seems to be gone.

**Comment by paskalito** [comment]
Yes, bug is introduced in 2,10,0 and kept till current (2.10.2.1+fcr)

i would need to learn logcat first, and currently i have very limited resources.

**Comment by paskalito** [comment]
I lied !
It happened on 2.9.13+ as well.
Testing 2.9.10+ since some days..

**Comment by iNPUTmice** [comment]
Duplicate of  #4223
