### ISSUE TITLE
Cannot compile libwebrtc from source in macbook m1

### ISSUE THREAD

**Issue by mobDevKz** [iNPUTmice/Conversations#4330]
Command "./tools_webrtc/android/build_aar.py" shows error:

ERROR at //build/config/android/config.gni:318:5: Assertion failed.
    assert(false, "Need Android toolchain support for your build CPU arch.")
    ^-----
Need Android toolchain support for your build CPU arch.
See //build/config/sysroot.gni:34:5: whence it was imported.
    import("//build/config/android/config.gni")
    ^-----------------------------------------
See //build/config/linux/pkg_config.gni:5:1: whence it was imported.
import("//build/config/sysroot.gni")
^----------------------------------
See //BUILD.gn:24:1: whence it was imported.
import("//build/config/linux/pkg_config.gni")
^-------------------------------------------

**Comment by licaon-kter** [comment]
Download the .aar directly, see .github/workflow.yml file

/close as invalid, report this to webrtc instead

**Comment by mobDevKz** [comment]
Thank you, but where can I download aar from? In .github of Conversations project I only see 
-FUNDING.yml
-workflows
      android.yml

**Comment by licaon-kter** [comment]
Read .ym

**Comment by mobDevKz** [comment]
Thank you
