### ISSUE TITLE
Add a setting to always ask the user whether to compress a picture/video

### ISSUE THREAD

**Issue by STPKITT** [iNPUTmice/Conversations#4342]
I hate the current workflow when you're a user like I am who very often but not always sends pictures (or very seldom videos) uncompressed especially since you can't setup Conversations so that you're still able to send compressed media and at the same time be able to select a picture to sent uncompressed from inside an external app since that always goes through the Conversations picture upload chain.
Currently the user can only select between the options "Never", "Large images only" & "Always" and for videos it's "Medium (360p)", "High (720p)" & "Original (uncompressed).
So my feature request is to add an option to both of those which will always ask the user whether this time he/she wants to sent compressed or uncompressed.

**Comment by licaon-kter** [comment]
What's the workflow for 10 pictures?

**Comment by haansn08** [comment]
If I remember correctly, if you choose "Attach File > Choose file" it will always be uncompressed, even if you select media files.

**Comment by STPKITT** [comment]
@licaon-kter What do you mean? I don't get your question.

@haansn08 Yes of course, that's how I currently do it but it's very cumbersome to for example be in my Gallery app and decide to sent a I'm viewing since I then have to open Conversations, select the receiving contact, click "Attach File > Choose file" and I'm then shown an Android system filemanager view which at least in my case doesn't even remember my prefered viewing settings (thumbnails, sort by date, newest picture on top).

**Comment by licaon-kter** [comment]
You'll get asked for each picture? You'll be shown a preview and a size text?

**Comment by STPKITT** [comment]
In that situation it would probably be the best solution to ask just once for the whole batch since in that moment the connection speed will be the same for all pictures and the recipient will be the same.

**Comment by iNPUTmice** [comment]
I understand wanting to send uncompressed images from time to time. However I recommend you just go through the attach file options rather than share with Conversations in those circumstances.

A case by case setting will just make the UI unnecessarily complex.
