### ISSUE TITLE
Fdroid update

### ISSUE THREAD

**Issue by Screenshared** [iNPUTmice/Conversations#4346]
Hello, i would like to know why app version of playstore and repository is newer than fdroid one.
Are updates also published in fdroid?
Thank u.

**Comment by licaon-kter** [comment]
Read https://gitlab.com/fdroid/fdroiddata/-/issues/2064

I started an effort to integrate all the non-webrtc changes here: https://github.com/iNPUTmice/Conversations/pull/4310 

/close this
