### ISSUE TITLE
[Feature Request] Add a button to connect/disconnect profiles from the home

### ISSUE THREAD

**Issue by sbadux** [iNPUTmice/Conversations#4347]
Hello,
could you please consider to add a button to connect/disconnect all the profiles from the main screen?

I will love a single button that connect/disconnect ALL the profiles without need to open the "..." then go in the profiles settings and enable/disable them.

E.g: Connected
![Connected](https://user-images.githubusercontent.com/28478027/180300383-7dc3ecfe-0e8f-4300-8959-6a6fc2be84a2.png)

Disconnected
![Disconnected](https://user-images.githubusercontent.com/28478027/180300459-831df865-c6ae-43c0-a747-02599f1f0051.png)

Obviously this is useful for me but maybe it's useless for everyone else :-) Just consider the idea please

**Comment by iNPUTmice** [comment]
Unfortunately we can not add short cuts for every single action anyone might want to do some day.

**Comment by sbadux** [comment]
No problem. I know that this request could have been rejected, but I tried to ask :+1: 
Thanks for your hard work on the App
