### ISSUE TITLE
White flash on app opening

### ISSUE THREAD

**Issue by jaredreardon** [iNPUTmice/Conversations#4348]
See the video below. When opening the app after it has been fully closed, there is a white screen that flashes at first. I've seen other issues on here where this is marked as fixed but I still get it.

https://user-images.githubusercontent.com/67240033/181386722-1d0c7eb0-6f3d-4cce-9d68-5d1d2907eb7c.mp4

**Comment by licaon-kter** [comment]
Device? Android version? Conversations version?

**Comment by iNPUTmice** [comment]
This is because of the jump into the Start Conversation screen. It will go away once you have open chats.
