### ISSUE TITLE
Audio / Video call fails in starting from BLABBER to CONVERSATIONS

### ISSUE THREAD

**Issue by Samanbaia** [iNPUTmice/Conversations#4349]
Issue.

BLABBER version 3.0.8
CONVERSATIONS 2.10.2.1+FCR

Blabber tries to call CONVERSATIONS in video. CONVERSATIONS user answers, but fails to take to call. On the BLABBER side, it says CONVERSATOONS user is busy. here is the log:

nicolas@nicolas-Modern-15-A11M ~ $ adb -d logcat -v time -s conversations
* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -
--------- beginning of crash
--------- beginning of system
--------- beginning of kernel
--------- beginning of main
07-30 17:13:00.792 D/conversations( 5622): action: null
07-30 17:13:00.804 D/conversations( 5622): ConversationsOverviewFragment.onStart()
07-30 17:13:00.805 D/conversations( 5622): ConversationsOverviewFragment.onResume()
07-30 17:13:00.832 D/conversations( 5622): laiv.salocin@conversations.im send ping (action=ui,lowTimeout=false)
07-30 17:13:00.836 D/conversations( 5622): app switched into foreground
07-30 17:13:03.164 D/conversations( 5622): ConversationFragment.onAttach()
07-30 17:13:03.197 D/conversations( 5622): reInit(hasExtras=true)
07-30 17:13:03.197 D/conversations( 5622): trimming conversation
07-30 17:13:03.209 D/conversations( 5622): scrolledToBottomAndNoPending=true
07-30 17:13:03.209 D/conversations( 5622): jump to first unread message
07-30 17:13:03.210 D/conversations( 5622): ConversationsOverviewFragment.onPause()
07-30 17:13:03.210 D/conversations( 5622): ConversationsOverviewFragment.onDestroyView()
07-30 17:13:05.248 D/conversations( 5622): ConversationsOverviewFragment.onStart()
07-30 17:13:05.248 D/conversations( 5622): ConversationsOverviewFragment.onResume()
07-30 17:13:05.249 D/conversations( 5622): ConversationFragment.onDestroyView()
07-30 17:13:26.666 D/conversations( 5622): toggle forced foreground service after receiving event (action=ping)
07-30 17:13:26.692 D/conversations( 5622): ForegroundService: on
07-30 17:14:05.633 D/conversations( 5622): ConversationsOverviewFragment.onPause()
07-30 17:14:06.861 D/conversations( 5622): app switched into background
07-30 17:15:27.971 D/conversations( 5622): ConversationsOverviewFragment.onStart()
07-30 17:15:27.973 D/conversations( 5622): ConversationsOverviewFragment.onResume()
07-30 17:15:28.013 D/conversations( 5622): ConversationsOverviewFragment.onPause()
07-30 17:15:28.092 D/conversations( 5622): laiv.salocin@conversations.im send ping (action=ui,lowTimeout=false)
07-30 17:15:28.095 D/conversations( 5622): app switched into foreground
07-30 17:15:28.148 D/conversations( 5622): app switched into background
07-30 17:15:31.360 D/conversations( 5622): ConversationsOverviewFragment.onStart()
07-30 17:15:31.360 D/conversations( 5622): ConversationsOverviewFragment.onResume()
07-30 17:15:31.445 D/conversations( 5622): app switched into foreground
07-30 17:15:34.917 D/conversations( 5622): ConversationsOverviewFragment.onPause()
07-30 17:15:35.650 D/conversations( 5622): app switched into background
07-30 17:16:06.723 D/conversations( 5622): toggle forced foreground service after receiving event (action=ping)
07-30 17:16:06.737 D/conversations( 5622): ForegroundService: on
07-30 17:20:48.969 D/conversations( 5622): laiv.salocin@conversations.im: delivered message to JingleRtpConnection <propose xmlns="urn:xmpp:jingle-message:0" id="+nIP76h0Q84nN+pIJK9foA"><description media="audio" xmlns="urn:xmpp:jingle:apps:rtp:1"/><description media="video" xmlns="urn:xmpp:jingle:apps:rtp:1"/></propose>
07-30 17:20:48.975 D/conversations( 5622): laiv.salocin@conversations.im: received session proposal from yanis.vial@conversations.im/blabber.im[3.0.8].WC-u for [audio, video]
07-30 17:20:48.975 D/conversations( 5622): laiv.salocin@conversations.im: transitioned into PROPOSED
07-30 17:20:48.990 D/conversations( 5622): ForegroundService: on
07-30 17:20:48.990 D/conversations( 5622): laiv.salocin@conversations.im: received call from yanis.vial@conversations.im/blabber.im[3.0.8].WC-u. start ringing
07-30 17:20:49.130 D/conversations( 5622): laiv.salocin@conversations.im: ignore jingle message from self
07-30 17:20:49.487 D/conversations( 5622): app switched into foreground
07-30 17:20:54.597 D/conversations( 5622): laiv.salocin@conversations.im: transitioned into PROCEED
07-30 17:20:54.597 D/conversations( 5622): onJingleRtpConnectionUpdate(ACCEPTING_CALL)
07-30 17:20:54.605 D/conversations( 5622): ForegroundService: on
07-30 17:20:54.605 D/conversations( 5622): stop playing ring tone
07-30 17:20:54.618 D/conversations( 5622): stop vibration
07-30 17:20:54.678 D/conversations( 5622): laiv.salocin@conversations.im: delivered message to JingleRtpConnection <accept xmlns="urn:xmpp:jingle-message:0" id="+nIP76h0Q84nN+pIJK9foA"/>
07-30 17:20:54.678 D/conversations( 5622): laiv.salocin@conversations.im: unable to transition to accept because already in state=PROCEED
07-30 17:20:54.861 D/conversations( 5622): laiv.salocin@conversations.im: receive message error for proceed message
07-30 17:20:54.861 D/conversations( 5622): laiv.salocin@conversations.im: transitioned into TERMINATED_CONNECTIVITY_ERROR
07-30 17:20:54.861 D/conversations( 5622): onJingleRtpConnectionUpdate(CONNECTIVITY_ERROR)
07-30 17:20:54.861 D/conversations( 5622): end card reached
07-30 17:20:54.867 D/conversations( 5622): ForegroundService: on
07-30 17:20:54.868 D/conversations( 5622): laiv.salocin@conversations.im: transitioned into connectivity error
07-30 17:20:54.921 D/conversations( 5622): checking microphone availability took 323ms
07-30 17:21:10.065 D/conversations( 5622): toggle forced foreground service after receiving event (action=idle_ping)
07-30 17:21:10.072 D/conversations( 5622): ForegroundService: on
07-30 17:21:56.084 D/conversations( 5622): app switched into background
07-30 17:26:07.098 D/conversations( 5622): toggle forced foreground service after receiving event (action=ping)
07-30 17:26:07.125 D/conversations( 5622): ForegroundService: on
07-30 17:29:29.525 D/conversations( 5622): laiv.salocin@conversations.im send ping (action=ui,lowTimeout=false)
07-30 17:29:29.528 D/conversations( 5622): app switched into foreground
07-30 17:29:29.529 D/conversations( 5622): restored last state from intent extra
07-30 17:29:29.627 D/conversations( 5622): laiv.salocin@conversations.im received pubsub notification for node=eu.siacs.conversations.axolotl.bundles:10025
07-30 17:29:29.630 D/conversations( 5622): AxolotlService (laiv.salocin@conversations.im): Received PEP device list [760707828, 48154632, 631535805, 10025, 2086701194, 2131911913, 6284, 8798] update from laiv.salocin@conversations.im, processing... 
07-30 17:29:29.630 D/conversations( 5622): laiv.salocin@conversations.im: ignoring duplicate own device id list
07-30 17:29:29.833 D/conversations( 5622): app switched into background
07-30 17:29:29.909 D/conversations( 5622): app switched into foreground
07-30 17:29:29.909 D/conversations( 5622): restored last state from intent extra
07-30 17:29:31.173 D/conversations( 5622): app switched into background
07-30 17:29:31.662 D/conversations( 5622): app switched into foreground
07-30 17:29:31.662 D/conversations( 5622): restored last state from intent extra
07-30 17:29:33.040 D/conversations( 5622): app switched into background
07-30 17:29:34.541 D/conversations( 5622): ConversationsOverviewFragment.onDestroyView()
07-30 17:29:34.542 D/conversations( 5622): ConversationsOverviewFragment.onDestroy()
07-30 17:29:34.561 D/conversations( 5622): ignoring onTaskRemoved because foreground service is activated
07-30 17:29:36.161 D/conversations( 5622): action: null
07-30 17:29:36.168 D/conversations( 5622): ConversationsOverviewFragment.onStart()
07-30 17:29:36.169 D/conversations( 5622): ConversationsOverviewFragment.onResume()
07-30 17:29:36.208 D/conversations( 5622): app switched into foreground
07-30 17:29:38.610 D/conversations( 5622): ConversationsOverviewFragment.onPause()
07-30 17:29:39.165 D/conversations( 5622): app switched into background
07-30 17:30:20.021 D/conversations( 5622): toggle forced foreground service after receiving event (action=ping)
07-30 17:30:20.050 D/conversations( 5622): ForegroundService: on

same thing happens in audio call:

07-30 17:32:42.780 D/conversations( 5622): toggle forced foreground service after receiving event (action=idle_ping)
07-30 17:32:42.791 D/conversations( 5622): ForegroundService: on
07-30 17:32:55.078 D/conversations( 5622): laiv.salocin@conversations.im: delivered message to JingleRtpConnection <propose xmlns="urn:xmpp:jingle-message:0" id="Dph+tfN7fPb5bJReiGP8mQ"><description media="audio" xmlns="urn:xmpp:jingle:apps:rtp:1"/></propose>
07-30 17:32:55.080 D/conversations( 5622): laiv.salocin@conversations.im: received session proposal from yanis.vial@conversations.im/blabber.im[3.0.8].WC-u for [audio]
07-30 17:32:55.082 D/conversations( 5622): laiv.salocin@conversations.im: transitioned into PROPOSED
07-30 17:32:55.097 D/conversations( 5622): ForegroundService: on
07-30 17:32:55.098 D/conversations( 5622): laiv.salocin@conversations.im: received call from yanis.vial@conversations.im/blabber.im[3.0.8].WC-u. start ringing
07-30 17:32:55.163 D/conversations( 5622): laiv.salocin@conversations.im: ignore jingle message from self
07-30 17:32:55.489 D/conversations( 5622): app switched into foreground
07-30 17:32:57.640 D/conversations( 5622): acquiring proximity wake lock
07-30 17:32:57.642 D/conversations( 5622): laiv.salocin@conversations.im: transitioned into PROCEED
07-30 17:32:57.642 D/conversations( 5622): onJingleRtpConnectionUpdate(ACCEPTING_CALL)
07-30 17:32:57.653 D/conversations( 5622): ForegroundService: on
07-30 17:32:57.653 D/conversations( 5622): stop playing ring tone
07-30 17:32:57.665 D/conversations( 5622): stop vibration
07-30 17:32:57.727 D/conversations( 5622): laiv.salocin@conversations.im: delivered message to JingleRtpConnection <accept xmlns="urn:xmpp:jingle-message:0" id="Dph+tfN7fPb5bJReiGP8mQ"/>
07-30 17:32:57.727 D/conversations( 5622): laiv.salocin@conversations.im: unable to transition to accept because already in state=PROCEED
07-30 17:32:57.764 D/conversations( 5622): laiv.salocin@conversations.im: receive message error for proceed message
07-30 17:32:57.764 D/conversations( 5622): laiv.salocin@conversations.im: transitioned into TERMINATED_CONNECTIVITY_ERROR
07-30 17:32:57.764 D/conversations( 5622): onJingleRtpConnectionUpdate(CONNECTIVITY_ERROR)
07-30 17:32:57.764 D/conversations( 5622): end card reached
07-30 17:32:57.764 D/conversations( 5622): releasing proximity wake lock
07-30 17:32:57.770 D/conversations( 5622): ForegroundService: on
07-30 17:32:57.770 D/conversations( 5622): laiv.salocin@conversations.im: transitioned into connectivity error
07-30 17:32:57.903 D/conversations( 5622): checking microphone availability took 261ms

**Comment by iNPUTmice** [comment]
> 07-30 17:32:57.764 D/conversations( 5622): laiv.salocin@conversations.im: receive message error for proceed message

This means we are getting an error message from Blabber or from the server on behalf of the client.

**Comment by licaon-kter** [comment]
@kriztan ^^^

**Comment by kriztan** [comment]
Maybe an update to blabber 3.1.x should help...

**Comment by iNPUTmice** [comment]
At this point I don’t see any bugs in Conversations. We clearly see an error message coming back to us in the logs. The next version of Conversations will explicitly log that error message helping you identify the problem. But it is very unlikely to be bug in Conversations.

**Comment by Samanbaia** [comment]
Sorry to be late: I updated BLABBER to the ultimate available version (3.1.3): it seems it solves the problem, even if I met the problem once again.
