### ISSUE TITLE
Store all media files in app's private storage

### ISSUE THREAD

**Issue by scubajeff** [iNPUTmice/Conversations#4361]
For privacy sake, can Conversations save all media files, no matter sent or received, in it's own private storage, rather than public folder like Pictures, Movies, etc? People choose XMPP to avoid using public IM services, mostly because of privacy concern. And under quite a few circumstances, message exchanged in picture rather than text. Media files stored in public folders can be easily scanned and uploaded by Big brother Apps.

**Comment by licaon-kter** [comment]
This comes up a lot.

Easiest action would be to not run Big Brother Apps.

There's a toggle in code, when you build the app, to use internal storage, but it has its drawbacks, like unable to batch export files.

**Comment by iNPUTmice** [comment]
FWIW this is basically an "accepted feature request" for Conversations 3.0 - not necessarily because of the privacy implications but because Androids storage has changed drastically in the last years and storing files in private storage is what apps are supposed to do these days.

**Comment by licaon-kter** [comment]
As long as there are no drawbacks for the user (eg. Exporting limited to sharing one file at a time) this sounds good.

**Comment by canary5** [comment]
I have build to use internal storage only. But it still saving media in galery

**Comment by licaon-kter** [comment]
@canary5 how did you?

**Comment by canary5** [comment]
I have a build using internal storage only. When i have media files, they appear on galery app. Even i do clean private storage option, those media files still in galery.
Media files permission for Conversations is enabled

**Comment by anyuta1166** [comment]
> As long as there are no drawbacks for the user

There is a major drawback. When you delete an app or clear app data, files in private storage are deleted too. So you will lose all your files if you want to reinstall or reset an app.

**Comment by scubajeff** [comment]
> > As long as there are no drawbacks for the user
> 
> There is a major drawback. When you delete an app or clear app data, files in private storage are deleted too. So you will lose all your files if you want to reinstall or reset an app.

All the albums are synced with server. So the next time you install Lespas, they will be synced back to your phone, and thanks for the 'remote album' feature, it will take just a minute  to do that.
