### ISSUE TITLE
Feature request: tap avatar in overview to view contact details 

### ISSUE THREAD

**Issue by aabacchus** [iNPUTmice/Conversations#4362]
Issue #2180 asked this but got no response - perhaps no one saw it?

I often find myself wanting to view someone's details without reading their message, or I find it slower to have to open the chat then go to their details.

Clicking the icon/avatar in the inbox screen should open contact details; clicking the message preview on the rest of each line opens the chat.

**Comment by aabacchus** [comment]
The referenced issue was closed and I don't think I can reopen it.

**Comment by licaon-kter** [comment]
Closed doesn't mean gone or forgotten...

**Comment by aabacchus** [comment]
Ok!
