### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by marmistrz** [iNPUTmice/Conversations#4364]
In a [comment](https://github.com/iNPUTmice/Conversations/pull/4192#issuecomment-957515691) to my PR #4192, in October 2021, you wrote:
> If all goes well (if nothing super urgent security wise comes up) there won’t be any more changes made to Conversations 2.x

There are other pull requests that greatly improve UX issues, such as #4095,  #3857 that have been left unmerged and without feedback for months. On the other hand, Conversations still receives maintenance updates.

What is the project status? Is Conversations 3.x planned and under development, or is the project dead feature-wise? Is there any development branch for 3.x? (I can find none)

cc feature PR contributors: @dmitry-markin @emankced @SmsS4

**Comment by iNPUTmice** [comment]
Conversations 3.0 is still in the planning phase.

**Comment by licaon-kter** [comment]
Already funded apparently:
https://gultsch.social/@daniel/109381130050801061
