### ISSUE TITLE
(Feature request) Context-less audio player

### ISSUE THREAD

**Issue by hardBSDk** [iNPUTmice/Conversations#4373]
An internal audio player (like Telegram) where all the audio files from a conversation are put in a playlist with playback options and keeps playing outside of the chat screen (even out of the app).

Code suggestion:

https://github.com/DoubleSymmetry/react-native-track-player

https://github.com/jeancsanchez/JcPlayer

https://github.com/yusufcakmak/ExoPlayerSample

https://github.com/HamidrezaAmz/MagicalExoPlayer

![135987411-fd57d084-fd82-4448-8a6c-341999d575ed](https://user-images.githubusercontent.com/55782009/189330364-44b61768-6a41-4315-bdeb-63e9242b1013.jpg)

**Comment by iNPUTmice** [comment]
Conversations will not become a super app (or emacs)
