### ISSUE TITLE
(Improvement) Add settings button to action bar 

### ISSUE THREAD

**Issue by Millesimus** [iNPUTmice/Conversations#4382]
Idea: add a settings button (gear wheel icon) to the action bar in the ConversationsOverview (only in vertical mode, i.e. when there is only the overview but no chats open).

Reason: Sometimes new users seem to have a surprisingly hard time to find the settings, as they are hidden in the three-dots-menu. That's not a show stopper, but it's an avoidable nuisance. Adding the gear icon would be a clear visual indicator and hopefully make it a lot easier to find.

**Comment by licaon-kter** [comment]
I'd rather have search there, how often are settings changed?

**Comment by Millesimus** [comment]
Just today I had a chat with someone who had the same problem and had a (unnecessarily) hard time finding the settings. I don't think it matters so much how often people need it (I need it quite often, but that's just me, I think), it rather matters that they find it if they need it.

**Comment by licaon-kter** [comment]
It used to be easier to find since it was in the three dots menu in every chat, not just overview.

**Comment by iNPUTmice** [comment]
The overflow menu is a pretty common pattern used across many android apps. The 'Messages' apps from Google for example behaves exactly the same (also not showing the settings menu item in the chat screens).
If a user doesn’t know this they should probably just learn this or else they will have a hard time with all apps.
