### ISSUE TITLE
(Improvement) Open accounts overview by tapping on action bar

### ISSUE THREAD

**Issue by Millesimus** [iNPUTmice/Conversations#4383]
Idea: make it possible to not only open the accounts overview via the three-dots-menu, but also by tapping the app name (in the ConversationsOverview). By "accounts overview" I mean the list of all accounts one has set-up in Conversations.

Reasoning: Opening the three-dots-menu is an extra step that could be avoided. Also, tapping on the action bar while in a conversation opens the respective details, thus it would make sense to me if doing the same in the overview would open the accounts overview.

**Comment by licaon-kter** [comment]
Touch your avatar in any chat to open account settings, this is what you want?

**Comment by Millesimus** [comment]
No, I want to open the accounts overview, not the details of a single account.

**Comment by iNPUTmice** [comment]
We can’t just make every possible only one tab away or else the app would just be buttons.
We also have to consider the fact that there is limited room in the icon bar.
