### ISSUE TITLE
After restoring Backup, Messages from new Device are invisible for myself

### ISSUE THREAD

**Issue by cocker-cc** [iNPUTmice/Conversations#4386]
I followed your Guideline ["Migrating to a new device"](https://github.com/iNPUTmice/Conversations/blob/master/docs/user/migrating_to_new_device.md) not with the Goal to ultimatively migrate Conversations, but to use it on both Devices simultaneously.  

Everything went well so far, but one Problem exists: my new Messages sent from the new Device are invisible on all my other Devices.

On my new Device I had to go to "Settings/Advanced/Expert Settings/Delete OMEMO-Identities" , to fix it.

Would be great if the Guideline could enlighten this Subject more deeply.

**Comment by licaon-kter** [comment]
Not sure which part of "do not use this to run simultaneous" was not clear if you said you followed the text.
