### ISSUE TITLE
Changed paths for attachments

### ISSUE THREAD

**Issue by ubeno** [iNPUTmice/Conversations#4388]
On my phone (no SD card), it seems that there was a change on the folders for attachments sometime during the last couple of weeks. During that time I upgraded from 2.10.9 to 2.10.10, so maybe the upgrade could explain this.

Previously, attachments were stored in the internal storage folder as follows:

- Conversations/Media/Conversations Files (received recordings)
- Conversations/Media/Conversations Images
- Conversations/Media/Conversations Recordings (sent recordings)
- Conversations/Media/Conversations Videos

Now, attachments are still stored in the internal storage folder, but within separate parent folders:
- Download/Conversations (received and sent recordings)
- Movies/Conversations
- Pictures/Conversations

While I very much prefer having one parent folder "Conversations" for all attachments, I could live with it. On the other hand, storing recordings in the Download folder (which I only use for temporary files and try to keep empty) seems not the best choice to me.

**Comment by licaon-kter** [comment]
Yup, thank Google for that, apps are no longer allowed to store files where they want.

/close as invalid

**Comment by wsbfimbapb** [comment]
Thanks for the quick reply! That is too bad - any chance of moving recordings out of `Download` and to some audio related folder, e.g. `Music`?

Question regarding the transition: Currently, attachments created with the old version are still at the old locations. Can I move them to the new locations in such a way that they are still correctly shown in the chat history? If possible, I would like to avoid having two folder structures for all eternity.

**Comment by licaon-kter** [comment]
Nope,  as their paths in the database are tied to the old paths. :shrug:

**Comment by wsbfimbapb** [comment]
I was afraid that was going to be the case.

Any feedback regarding this:

> That is too bad - any chance of moving recordings out of `Download` and to some audio related folder, e.g. `Music`?

**Comment by wsbfimbapb** [comment]
Well, in most music players I know, one usually specifies the "library folder". Besides, `Music` seems to be the Android default place for audio files of any kind. For example, my system sound recorder app writes its files into `Music/Sound records`.

In my opinion, it is highly confusing that 
- files the user created him/herself (voice messages he/she recorded and sent over conversations) 
- or other files which have not been downloaded by a browser
are stored in the `Download` folder.

**Comment by licaon-kter** [comment]
Because once you update to 11/12/13 you (the app) loose access to the files?

**Comment by anyuta1166** [comment]
BTW, a friend of mine has Android 11 and an old version of Conversations which stores its files in Internal Storage/Conversations, and everything works fine. Will Conversations lose access to the files if he update Conversations to the latest version?

**Comment by licaon-kter** [comment]
No, they won't. Read abovep
