### ISSUE TITLE
Complete list of the meaning of all message icons / symbols

### ISSUE THREAD

**Issue by gitbq** [iNPUTmice/Conversations#4389]
Hi. Thanks for all the time and effort in developing this app.

I have looked everywhere, but can't seem to find anything. Especially to help when helping newbies it would be really helpful if there was a complete list of all the possible icons that appear next to messages and their meanings.

Something similar to this: threema.ch/en/faq/status_expl

Thanks again.

**Comment by licaon-kter** [comment]
https://gultsch.de/trust.html

**Comment by gitbq** [comment]
Thanks for the reply. Apologies, but I can't see the connection to explains the message notification symbol meanings?
Does such a detailed explanation of each symbol exist?

**Comment by gitbq** [comment]
Sorry, I see what you mean.... Thanks

**Comment by muello** [comment]
I still wonder if it's possible to improve the (linked) documentation. Suggestions:

- add the documentation to conversations.im somewhere, or possibly even to the app,
- separate the explanation of the icons from that of the trust system, such that readers confused about the icons can get a quick understanding of them first, and a hint on where to read further to understand the issues around trust, 
- the linked page only explains that messages received from blindly trusted devices are marked with a lock and those from verified devices with a shield; add an explanation of what those icons mean next to messages that the user has *sent* from one of their own devices, and explain why in some one-on-one chats, some messages sent by the user get locks and others icons,
- explain what the ticks mean

A minor note on the linked page: it took me a while to make sense of the first sentence; if I now understand correctly, then "any" is meant, not "every".
