### ISSUE TITLE
Media not recognised after restoring backup

### ISSUE THREAD

**Issue by Terrance** [iNPUTmice/Conversations#4396]
I've successfully restored a Conversations backup after resetting my device, however it can't see the past images I've sent or received in chats.  The media grid when I tap on a contact only shows thumbnails of videos (in `Conversations/Media/Conversations Videos`, which are playable), but not pictures (in `Conversations/Media/Conversations Images`).

Attempting to open a missing image results in something like:

> NoSuchFileException: content://eu.siacs.conversations.files/external/Conversations/Media/Conversations%20Media/\<uuid>.jpg
> FileNotFoundException: open failed: EACCES (Permission denied)

(This was with Material Files, but I assume no external apps can read these content URIs if they're scoped to the Conversations app?)

I note that newly-sent images are stored in `Pictures/Conversations` instead (I assume this path changed following Android permissions changes alongside the new backups location in `Downloads/Conversations`), but copying old media there doesn't work either.

Is there a way of fixing the paths of existing images so that they can be viewed in context from within chats?

**Comment by licaon-kter** [comment]
So you've restored the old files back in the old place, granted Storage permission to the app, even restarted the device (just in case) and still does not show them?

**Comment by Terrance** [comment]
Correct:

> restored the old files back in the old place

I've tried both `Conversations/Media/Conversations Images` where they used to be, and `Pictures/Conversations` where new images are stored.

> granted Storage permission to the app

It has access to media only (which I guess is the problem with the old path: `Conversations` in the storage root doesn't come under this?) -- I can't grant it any higher as presumably the app is not declaring wider storage permissions?

> even restarted the device

I've force-stopped the app between changes, and given it a reboot now but still no joy.

I realise I didn't mention above: this is on Android 12 (OnePlus Nord CE, OxygenOS 12.1).

**Comment by iNPUTmice** [comment]
Permission to the old paths are only granted to apps that are being upgraded not to apps that are re-installed. Thus Conversations simply doesn’t have access to the old files. There is no way to fix this.

**Comment by Terrance** [comment]
Would it be possible just to recognise existing files in the new location (i.e. match them up by UUID filename, assuming they're intended to be unique)?  That way users can move their files to the new location and they'll show up without any extra permissions.

**Comment by iNPUTmice** [comment]
> Would it be possible just to recognise existing files in the new location (i.e. match them up by UUID filename, assuming they're intended to be unique)? That way users can move their files to the new location and they'll show up without any extra permissions.

yes. but Conversations doesn’t support that.

**Comment by Terrance** [comment]
Might this issue stay open as a feature request for that then (to make media references path-agnostic, or otherwise offer a way of migrating references against legacy paths)?

I'm guessing this will affect anyone who started using the app before the permissions / path changes, as even if they create a backup post-changes, they'll still have their media on hard-coded paths that are only accessible on their current installation (the permissions to paths under the root `Conversations` are presumably grandfathered-in for existing installations, but can't be granted on a new one).

**Comment by er-st** [comment]
Were you able to restore new photos that were already stored in the new structure to the new directory structure on another device? Not even that works for me.

**Comment by licaon-kter** [comment]
@er-st Stuff in `Pictures/Conversations` ? That should just work...

**Comment by er-st** [comment]
Images are there but the app does not show them. Could this be a permissions problem?

**Comment by licaon-kter** [comment]
You can always check that, yes, see if ~~Storage~~Media Files and Audio Files (or whatever these are called these days in your Android version) is/are granted.

Try to also restart the app and/or device just to be sure.
