### ISSUE TITLE
Remove battery optimization notification


### ISSUE THREAD

**Issue by Erictheplague** [iNPUTmice/Conversations#4398]
Remove the battery optimization notification
It drains battery on most phones and battery notification is annoying to see 

Remove account connected notification
It's annoying and no one wants to see a notification except it's a notification from the bank 

![Screenshot_20221028-124640.png](https://user-images.githubusercontent.com/81354428/198581074-e1efbf7d-268f-4e65-a8b0-1299ddf0d16e.png)

**Comment by licaon-kter** [comment]
/close as invalid

This is a Google requirement.

The notification does not drain anything.

The notification (channel named Foreground service) can be toggled off.

More details in: https://github.com/iNPUTmice/Conversations/blob/master/README.md
