### ISSUE TITLE
Add warning about lack of TURN

### ISSUE THREAD

**Issue by gdt** [iNPUTmice/Conversations#4400]
When using an XMPP server that does not offer TURN, it would be nice for Conversations to give some kind of warning to the user.   Perhaps something in the phone/video call icons that indicates possible trouble, perhaps a dismissible message when making a call, maybe once, maybe once per app update, maybe once per app restart.

I realize that some calls may complete without TURN, and that if the other party is on a server with TURN then the call will very likely complete anyway, but particularly for people running their own servers this is non-obvious to debug.

**Comment by licaon-kter** [comment]
Did you read https://help.conversations.im/ yet?

**Comment by gdt** [comment]
I had looked at it before and just re-skimmed it.   It is very useful for server admins (and I have indeed set up working TURN by now, and verified that audio calls work).

My point is that a random user -- who is not expert in this -- when using a server that does not have TURN, does not (or did not, when I tried it), get useful feedback to be able to tell their server admin "hey: set up TURN", when the information that would lead to that is inside the app state.   I have seen people ask about "Can you use jmp.chat with the calyxinstitute server" and besides the OTR/OMEMO-required rule, I think it doesn't have TURN.

**Comment by gdt** [comment]
I'm hitting close on this one, as I think notifying about lack of arriving media data is useful regardless, and #4401 mentions TURN.   I should have realize that before starting to file, sorry for 2.
