### ISSUE TITLE
Add warning about lack of received media in calls

### ISSUE THREAD

**Issue by gdt** [iNPUTmice/Conversations#4401]
(I started with xmpp before Jingle/WebRTC/TURN, didn't pay too much attention, and while I updated by server over the years both new releases and migrating twice, I never dug into TURN.   Then a few years ago tried a voice call with Conversations.)

When making a voice call, without TURN there might be no working ways to exchange voice packets.  My memory is that this resulted in a call that appears to be answered (because Jingle signaling carried in xmpp works) but which has no audio (because ICE picked the best bet but it doesn't actually work).

It would be nice if there is some indication in a call that voice (and video, if a video call) data is arriving.   Or better when it is not: a red "no incoming audio data" could be displayed if the call is active and there has been no audio for 1s.   This could be extended to a quality indication, when there's more than a little loss.

This could also be a good place to display a "No TURN server." warning as in #4400, perhaps only in calls that are not receiving audio, on the theory that it only demands attention when useful.

**Comment by iNPUTmice** [comment]
> When making a voice call, without TURN there might be no working ways to exchange voice packets. My memory is that this resulted in a call that appears to be answered (because Jingle signaling carried in xmpp works) but which has no audio (because ICE picked the best bet but it doesn't actually work).

Your memory is either incorrect or you ran into a bug. The expected behaviour is that the call doesn’t connect. Hence the entire premise of this issue is flawed.
