### ISSUE TITLE
FR: Costum Value for "Accept files"

### ISSUE THREAD

**Issue by paskalito** [iNPUTmice/Conversations#4404]
Not sure about translation in German it is: Einstellungen > Dateien annehmen > Dateien automatisch annehmen, die kleiner sind als...

Every value predefined is either to little or too high for "some specific user".
So i thought, why don't add an Option "Custom" where everyone can choose their exact correct value

**Comment by iNPUTmice** [comment]
Thank you for your suggestion I'll keep that in mind.
