### ISSUE TITLE
Text box above omemo key to create personal note

### ISSUE THREAD

**Issue by MaxsimLionel** [iNPUTmice/Conversations#4407]
There could be a text box above each OMEMO fingerprint for individuals to write locally what OMEMO key of theirs is for which device of theirs. I imagine this text box does not need to be bigger than the first line of the fingerprint. 
This can be helpful when having many devices because I can note locally on my Android device which fingerprint is my Linux computer, my iOS phone, for example. 
For us organized folks ;)

**Comment by MaxsimLionel** [comment]
@licaon-kter again, only a duplicate because the last issues went "stale".

**Comment by licaon-kter** [comment]
Stale does not mean forgotten or anything else.

Duplicate mean duplicate though.

**Comment by MaxsimLionel** [comment]
Stale leads to close though. If it was not closed, I would have seen it as an issue before creating one.

**Comment by licaon-kter** [comment]
@MaxsimLionel you can see and search closed issues too, fyi
