### ISSUE TITLE
Delete account from server from Conversations

### ISSUE THREAD

**Issue by MaxsimLionel** [iNPUTmice/Conversations#4408]
Same functionality as was in Blabber.im. Gives the user the ability to delete their xmpp account from the server, not just removing the account from their device. Many people do not know how to delete an account from the server, and in many cases, the only way is to contact the server administrator. I assume that not all server implantations may support this feature, so if Conversations implemented this feature, it could include the notice "if possible".

**Comment by MaxsimLionel** [comment]
@licaon-kter why close as duplicate when it's only a duplicate because the last one went "stale"?

**Comment by licaon-kter** [comment]
Because the dev in aware of the feature request/issue so a new duplicate issue does not help in any way.

**Comment by MaxsimLionel** [comment]
@licaon-kter shouldn't one issue addressing it stay open?

**Comment by licaon-kter** [comment]
Open or Close is not up to us but up to the dev. Either when manually closed or via the dumb stale bot.
