### ISSUE TITLE
Simplify UI, remove ... in top right on contacts page

### ISSUE THREAD

**Issue by MaxsimLionel** [iNPUTmice/Conversations#4409]
I think it would simplify the UI of Conversations to move the "Hide Offline" option to the main chats page where the other menu is (the one that has the search messages tool). Right now there are two places where users can access "Manage Accounts" and "Settings" from. I think that can confuse users and they may then expect to see all the settings in both places, from the chat page, and the contact page. I recommend just consolidating those settings (along with the QR button) on the main page.

**Comment by licaon-kter** [comment]
Not sure, what's the gain here?

Eg. in the past the settings/account entries where available in all views

**Comment by iNPUTmice** [comment]
> I think it would simplify the UI of Conversations to move the "Hide Offline" option

That would be a different thing though. One would hide conversations one hides contacts. I don’t think we should hide open conversations with offline contacts.
