### ISSUE TITLE
Update in debug versions

### ISSUE THREAD

**Issue by HackM3nt3** [iNPUTmice/Conversations#4412]
If i built a debug version following the instructions in readme, changing app name and application id, Do i receive some kind of update of notifications in android 11x or above from google play, github or F-droid?. Thanks in advance......

**Comment by licaon-kter** [comment]
No, it won't match any of the other keys used to sign Play or F-Droid.

If you build you own... you are on your own ;)

Question, why build debug?

**Comment by HackM3nt3** [comment]
I want to make my own branch and delete all pgp encryption and openkeychain packages. Thanks buddy

**Comment by Nemris** [comment]
Possibly worth mentioning that both F-Droid and Aurora Store can show - but obviously not install - Conversations updates, but only if you keep the package name untouched.

**Comment by licaon-kter** [comment]
@HackM3nt3 why delete pgp? If there's a threat vector there I sure do hope you've contacted the dev.
