### ISSUE TITLE
I would like to help out with some Traditional Chinese translations 

### ISSUE THREAD

**Issue by amalgame21** [iNPUTmice/Conversations#4413]
I am just a normal user.
I find out that some of the important translation (In the messaging view) are missing, making the apps unusable for those do not know English like the elderly.

Below translation apply to zh-HK (Traditional Chinese). Not sure if zh-TW work the same way since I am not a Taiwanese, but probably understandable.
The translation may be unprofessional, but at least make the app usable for people do not know English.

```
Messaging:
incoming call - 來電
missed call - 未接來電
outgoing call - 打出電話
seconds - 秒
minutes - 分鐘
hours - 小時
days - 天

Messaging menu:
Video call - 視像通話
Audio call - 語音通話

Audio call:
Discovering devices - 探索裝置中
Ring - 電話響起
Connected - 已接通
End call - 終止通話

main app menu:
Invite to Conversations - 邀請到Conversations

setting:
Broadcast use - 廣播
Image Compression - 圖像壓縮
```

**Comment by iNPUTmice** [comment]
Hi,

translations are handled on Transifex. Can you sign up their and contribute them via Transifex? There should be a link in the readme.
