### ISSUE TITLE
Changing the icon logo!

### ISSUE THREAD

**Issue by HackM3nt3** [iNPUTmice/Conversations#4414]
Good day guys, i am making my own fork and i am trying of change the icon logo, but i always got multiple errors, what should i do the change it. 
Iam getting this error when i trying to build a debug version:
build/intermediates/merged-not-compiled-resources/conversationsFree/debug/drawable/abc_dialog_material_background.xml) in source-sets.

Is it possible to change the icon?, can you help me please?

Thank and sorry for my ignorance!

**Comment by licaon-kter** [comment]
Please don't make a new fork!!!111

Why?

**Comment by HackM3nt3** [comment]
Like i wrote you before, i will erase all pgp encryption!!!! thats why

**Comment by licaon-kter** [comment]
Yeah, but, why?

**Comment by iNPUTmice** [comment]
This sounds like something where you just have to run `./gradlew clean`; however this is a bug tracker not a support forum. For questions please use our group chat at `xmpp:conversations@conference.siacs.eu?join`.
