### ISSUE TITLE
Leaking private IPs (?)

### ISSUE THREAD

**Issue by mrusme** [iNPUTmice/Conversations#4415]
I was informed by one of my contacts that apparently Conversations would leak private IPs:

```xml
        <candidate type='direct' jid='user@xmpp.org/Conversations.XYZ' host='10.0.0.26' cid='696aa669-9669-69aa-aaa6-96aaa6969696' priority='8257538' port='60906'/>
           <candidate type='direct' jid='user@xmpp.org/Conversations.XYZ' host='10.2.0.2' cid='6a969a6a-969a-5a9a-6a96-6a96aaa69669' priority='8257539' port='5322'/>
```

I'm wondering if that's actually a Conversation thing or rather has something to do with the XMPP server? As these are private (VPN) IPs, it's not critical, yet I'd prefer the `host` part to not have these IPs listed.

**Comment by iNPUTmice** [comment]
Yes accepting file transfers (which happens automatically for contacts) as well as placing calls will leak your IP. You can enable Tor if you want to avoid this. (And/or disable that file transfers are accepted automatically).

The problem isn’t contained to the IP being transported on the wire but P2P file transfers and calls are essentially "connect to that $thing" and $thing will always know your IP.

**Comment by mrusme** [comment]
@iNPUTmice thank you for the super quick reply! Understood.
