### ISSUE TITLE
Usability improvement: allow seeing message in its context from the search results

### ISSUE THREAD

**Issue by aurabindo** [iNPUTmice/Conversations#4416]
When a user wants to go back to a previous message, they may not remember the exact message wordings to search for, but remember something else in context which they discussed. It help to locate the actual message they were searching for when we allow Conversations to open the message in the history where they can see rest of the messages from others, especially in an MUC. To clarify, here is an example:

1. User1 in MUC: Hey! Does anyone know about foo?
2. User2:  Hey User1, No, but I know about bar! 

Fast forward a few days 100s of messages in the group chat, User1 might not remember about bar, but remember that they asked about foo so that they can search "foo". However, User1 forgot about the thing "bar". User1 will only find it again if they can see their message in the context with other's responses where User2 mentioned bar.

**Comment by aurabindo** [comment]
@licaon-kter   Looks like the duplicate was added a tag "wont-fix", but without a reason. Do you know why ?

**Comment by licaon-kter** [comment]
The current db design makes this hard

In the future this will be a feature: https://gultsch.social/@daniel/109381130050801061

**Comment by aurabindo** [comment]
Great news! Thanks for the info!

**Comment by aurabindo** [comment]
I guess I'll keep this open for future tracking. Feel free to close otherwise.

**Comment by iNPUTmice** [comment]
> I guess I'll keep this open for future tracking. Feel free to close otherwise.
still duplicate
