### ISSUE TITLE
Provide Quicksy for iOS based on an existing iOS xmpp app

### ISSUE THREAD

**Issue by pravi** [iNPUTmice/Conversations#4419]
As per https://github.com/monal-im/Monal/issues/565 there was some discussion with Monal developers about it. Is this still being planned? Looks like Monal now has group omemo support.

For Prav.App we'd like to have an iOS version and having Quicksy for iOS will help in that goal. We are hoping to do a crowd funding campaign to get it done, if resources are a limitation.

**Comment by licaon-kter** [comment]
IIRC quicksy.im handles sms verification. Many things need to be coded :shrug:

**Comment by pravi** [comment]
@licaon-kter asking on the quicksy server issue tracker if the idea is good, then we can try to find people to write the code.

**Comment by iNPUTmice** [comment]
Hi @pravi 

Conversations, Quicksy and QuicksyServer are under a permissive open source license and you are free to use the code however you like.

I’m not a fan of what you are trying to do with *Prav.App* and I do not wish to engage with it in any way. There are plenty of rebranded variants of Conversations that do not provide anything to the XMPP ecosystem and only water down the Conversations brand.

As far as collaborations between Quicksy and Monal are concerned I think that's something Thilo and I can discuss in private.

Good luck with your future endeavors.
