### ISSUE TITLE
Gallery handling

### ISSUE THREAD

**Issue by GreenLunar** [iNPUTmice/Conversations#4420]
Send ~~multiple images~~ gallery inside a CBZ (ZIP) file.

### Motive
I find it best to mangae graphical and mixed (graphical and text) references within CBZ files.

### Text
A caption may be added as `caption.txt` (inside CBZ file) to be presented below the gallery.
Captions (caption per image) may be added as `image001.png.txt`.

### Notes
I'm not offering an XEP or something alike, these is a practice which would be useful to sender and receiver.
Even when receiver doesn't support this practice, user can open this file with a document viewer or archive manager.

**Comment by licaon-kter** [comment]
Not sure this is wanted app feature, won't your manga reader handle it?

**Comment by GreenLunar** [comment]
I'm using CBZ (actually, CBT and CB7) for documents, galleries and
categorizing graphical information.

Yes, it would.

Again, I'm introducing here a practice.

If the user selects more than an image, Conversations, by default, will
automatically archive the images into a CBZ archive.

The proprietary platforms provide galleries inside a visual baloon box
(as if it was a single messages) which indicates of a series of images
that are related to each other.

That practice, of the proprietary platforms, is complex, clumzy and
confusing.
Adding a CBZ Viewer inside Conversations will be easier and more
sensible than intervening with the Chat View, to both users and
developers.

I think CBZ not only will ease the process of sharing images in bulk,
but will expose users to a more managable and flexible manner to share
images and scanned documents.

**Comment by GreenLunar** [comment]
@Licaon_Kter I hope not. I've never thought that the grouped images
idea is good, and I've never liked it these whole years.

There are problems with the grouped images:

1) It's not functional, just fancy and distracting.

2) It requires to download/save images upon click (5 images = 5 clicks);
however, CBZ will allow user to download/save the entire gallery at once
or to browse the gallery/list (archive) and select items from it.

3) You can't forward the whole grouped images at once, only one by one.

4) You need to select the whole group using a secondary mode (perhaps
with a long-click) instead of just clicking and deleting it regularly.

5) The grouped images method will result in further distractions,
confusion and more clicks/taps from the user.

### Conversations

Conversations might overcome problems 2 and 3, but consider other
clients, they might not overcome this issue.

I firmly believe that using CBZ and parsing it using the client with a
ZIP library would be at most beneficial to everyone.

### Notes

- CBZ using a ZIP library and a basic reader UI, would save time to all
  XMPP clients.

- CBZ is also a better way to transfer data. One package by default!

- If you would provide me with both ways, grouped images and CBZ, I'll
  choose CBZ 99.999...999% of the times.

**Comment by licaon-kter** [comment]
1) that's like only your opinion
2) I guess it won't be like that
3) same
4) that's not bad
5) lol wut, you already have UX studies?

I understand CBZ is your favourite thing in the tech world, but c'mon :)

**Comment by GreenLunar** [comment]
I'm against grouped images.

Let's observe at the proprietary competitors.

Assuming both has enough money and resources to apply whatever feature
they desire.  It's only their "Think Tanks" that give the approval of a
feature.

### The Blue Phone vs. The Green Phone
Overtime, The Blue Phone has made "enhanced" emoticons (aka stickers) in
a form of well crafted and transparent graphic files in the WebP file
format.
Later those stickers were available as animations which took even
higher amount of battery power.

* I find these stickers very annoying, so I turned them off when I
could. I don't think stickers are useful and will only annoy users.
* Stickers are what made me to disconnect from both (Blue and Green),
  and continue with Email, SMS and XMPP.

Please note that it took **months** for The Green Phone to add that
feature to their platform (which has made that platform even more
inconvenient afterwards).

Hence, I assume that the "Think Tanks" of The Green Phone has
also believed that it was not a useful feature to begin with.

### Note
The stickers feature is more than a practice than a feature, as it's
only treating WebP file differently.

### XMPP
Adding a fancy feature when we can do it even better and easier to
apply, both for XMPP developers and users, would be good.

**Comment by GreenLunar** [comment]
> 5) lol wut, you already have UX studies?

It's from self observation.

> I understand CBZ is your favourite thing in the tech world, but c'mon

It's only takes to make the UI in a way that will make CBZ handling
simpler.

I'm an attorney, we use internally for scanned documents. I refer to
the larger firms in Israel.

CBZ is flexible, easier to manage and modify documents/galleries, and
it only requires a ZIP parser.

**Comment by iNPUTmice** [comment]
The UX suggestions you are making (save / forward entire gallery at once) are valid. The suggested technical solution (zip file) is not as it introduces more problems than it solves.

**Comment by GreenLunar** [comment]
@iNPUTmice  May I continue the argument here or at the Conversations XMPP groupchat?

**Comment by GreenLunar** [comment]
Gentlemen, while special display of images might be useful in the short term, it won't be like so in the long term.

**This is not a handheld program feature** I petition for, this is a feature which takes all XMPP clients in consideration.

Think of desktop cliens like Dino, Kaidan and Gajim, these programs let default desktop programs to handle media files.

What about console clients. such as Profanity MCabber and Irssi?

By applying this special multi-image display you are very likely to harm the experience of desktop users, as they might see a series of lines occuppying their chat screen for no good justification.

CBZ (ZIP) would be a good practice in the long term.
