### ISSUE TITLE
A/V Calls compatiblity with other application

### ISSUE THREAD

**Issue by ali-imanpour** [iNPUTmice/Conversations#4423]
Can this application  make A/V calls to Siskin IM iOS client? Are the protocols same?
If no, is there any iOS app compatible with this application?

**Comment by licaon-kter** [comment]
Yes, to Siskin, Snikket (a Siskin 6 fork), Movim, Dino, Beagle, etc.

But, keep in mind that Apple kills the app while not in foreground so your Siskin contact appears offline 99% of the time and you can't call them from Conversations. But once they open the app... it works :) 

/close as invalid

**Comment by ali-imanpour** [comment]
Thanks for your prompt answer!
