### ISSUE TITLE
 delivery failed on self channel

### ISSUE THREAD

**Issue by tareefdev** [iNPUTmice/Conversations#4425]
When I use the "Me" channel to save some messages, I get the "delivery failed" status below them, and the error message says, "DNS lookup failed: non-existing domain," tho I can see these messages on all clients I use. The channel is unencrypted.

**Comment by iNPUTmice** [comment]
What is a me channel?

**Comment by tareefdev** [comment]
When I click on the Start Conversation button, I can see a list of all my contacts, including one says "Me", clicking on this I can start a chat with myself. I thought this is a default 'feature'?

I checked the log on my server, it has the following message:

````
<0.17548.0>@ejabberd_s2s_out:process_closed/2:157 Failed to establish outbound s2s connection xmpp.tareef.me -> me: DNS lookup     
failed: non-existing domain; bouncing for 161 seconds 
````

**Comment by licaon-kter** [comment]
I think you've once added an XMPP address of `me`.

There's no "me feature", buuuut you can add yourself yes, you need to add your full XMPP address though.

/close as invalid

**Comment by tareefdev** [comment]
Well, that worked pretty well. As you said, it seems I missed the right config for that. Thanks!
