### ISSUE TITLE
android update 2.11.0 2022.12.05 is stuck in an endless resend and/or reconnect loop. 

### ISSUE THREAD

**Issue by 0and1c** [iNPUTmice/Conversations#4426]
using 2 different android devices, both just upgraded to 2.11.0, sending
to linux pidgin and to each other using omemo:

sending...
waiting...
sending...
waiting...
sending... 

after every loop all messages sent are resent in bulk, spamming the
recipient.  nonstop as above for 24 hours, the only way to stop is to
log out of the account in the app. It's seems like the app may be
disconnecting and reconnecting to jabber.org. could this be a
certificate issue?

**Comment by licaon-kter** [comment]
Might.

Other accounts on other servers behave the same?

**Comment by 0and1c** [comment]
I'll register a few and report back.

**Comment by licaon-kter** [comment]
Pidgin is not developed anymore, please switch to current clients, depending on platform, eg. Dino or Gajim etc

**Comment by 0and1c** [comment]
noted. but this can't be a pidgin issue. conversations between 2 android
devices using 2.11.0 on jabber.org accounts gets stuck in the loop as
well, 2.10 yesterday was working fine. updating to 2.11.0 started a
flame war between my cellphone and tablet.

**Comment by licaon-kter** [comment]
The server looks unmaintained: https://compliance.conversations.im/server/jabber.org/ :(

**Comment by 0and1c** [comment]
nice! thank you for the compliance tester link. closing the issue, will
move my accounts elsewhere. All the best...
