### ISSUE TITLE
Picture/Video/File transfer: "delivery failed"

### ISSUE THREAD

**Issue by SW-9000** [iNPUTmice/Conversations#4429]
**Description:**
Trying to send a picture / video / file immediately fails (_**delivery failed**_).
Selecting "show error message" on the failed transfer displays: _**not acceptable**_

**Log:**
`17:04:00.186 D/conversations( 5070): send file message`
`17:04:00.318 D/conversations( 5070): successfully connected to our own proxy65 candidate`
`17:04:00.318 D/conversations( 5070): xxx@jabber.ccc.de: remote announced support for JET`
`17:04:00.321 D/conversations( 5070): xxx@jabber.ccc.de: sending S5B offer with 5 candidates`
`17:04:00.790 D/conversations( 5070): xxx@jabber.ccc.de: suppressing failed delivery notification because conversation is open` 

**Systems:**
- Conversations 2.11.0+free: Pixel 5 / GrapheneOS / Android 13
- Conversations 2.11.0+playstore: Galaxy A30s / Android 11

**Comment by licaon-kter** [comment]
That server might be at fault, please choose one of those with 90-100% ratings from this list instead: https://compliance.conversations.im/old

To explain https://compliance.conversations.im/server/jabber.ccc.de/ see its missing XEP-0363: HTTP File Upload support.
 
Eg. To test, make 2 accounts on conversations.im and send files between them.

**Comment by SW-9000** [comment]
The server "jabber.ccc.de" never implemented XEP-0363, but picture / file / video transfer was successful all the time during the last years since I started using Conversations.

The failure appeared only after updating to Conversations v2.11.0...

**Comment by iNPUTmice** [comment]
Yes. That’s likely a regression. File transfer should obviously still work even if the server doesn’t support HTTP Upload.

**Comment by fl0bo** [comment]
@iNPUTmice thanks for quickly fixing this. I was about to file an issue but was in bad health.
Can confirm that using F-Droid version 2.10.10+free works well, but 2.11.0+free does not for p2p file transfers.
