### ISSUE TITLE
Where is the Localization Project?

### ISSUE THREAD

**Issue by sr093906** [iNPUTmice/Conversations#4431]
The page on transifex shows 404.

https://www.transifex.com/siacs/conversations/dashboard/

**Comment by iNPUTmice** [comment]
Translations are now handled on Weblate https://translate.codeberg.org/projects/converastions/

Stay tuned for a proper announcement in the coming days.

**Comment by licaon-kter** [comment]
Maybe it will move to https://hosted.weblate.org @inputmice

**Comment by licaon-kter** [comment]
@iNPUTmice there's a typo in your URL?
