### ISSUE TITLE
Feature request - Option to turn off notification on connection issues

### ISSUE THREAD

**Issue by tbjorheim** [iNPUTmice/Conversations#4441]
My family use Conversations on several devices and some also have a smartband which is set up to get notifications from Conversations.

This works fine, but it's kind of annoying for some family members to get a lot of notifications about connection issues, if you for example is not online.

Would it be possible to add an option to not get notifications about connection issues?

**Comment by licaon-kter** [comment]
Why don't they use the Notification settings for Conversations in Android Settings? 

Toggle off **just** the "connection issue" channel.

/close as invalid

**Comment by tbjorheim** [comment]
Thanks, that setting would hopefully do the trick. :)

I think the connection issues happens when cellular data is turned off and wifi is disconnected. And for some users it would be useful to get a notification that it's not possible to connect, but for others they do not care about this as long as it will connect again when they are back online. :)
