### ISSUE TITLE
Conversations no longer works with Android Auto

### ISSUE THREAD

**Issue by tjspann** [iNPUTmice/Conversations#4443]
A couple of weeks ago Conversations completely disappeared out of both my and my wife's Android Auto. I have a OnePlus 7T and my wife has a OnePlus 8T. I've factory reset my phone and the issue still persists. 

Issue: Conversations no longer appears as an app in Android Auto, I no longer get notifications for messages and the app does not show up under 'customize launcher' in Android Auto settings

Expected Outcome: Until recently Conversations was fully functional through Android Auto.

**Comment by tjspann** [comment]
I did search before posting this, my apologies if this is already known and I missed it.

**Comment by licaon-kter** [comment]
Notice: https://github.com/iNPUTmice/Conversations/pull/4436

That being said, yes, removed:  _Life of a Play dev_ https://codeberg.org/iNPUTmice/Conversations/commit/ed9318feacaedf062232811a7bb2704394b5c7b0

/close as invalid

**Comment by tjspann** [comment]
invalid, apparently

**Comment by iNPUTmice** [comment]
Android Auto support is back for now.

Review times on Google Play go 10x with Android Auto is enabled. (From hours to days) That’s really really annoying when you try to push bug fixes.

Anyway since 1.12.1 seems relatively stable I brought it back for. Review just passed.

**Comment by tjspann** [comment]
Sir it's really annoying having to pull over to get emergency messages from my family when Facebook Messenger and every other messaging service works just fine. You don't prefer my family use FB Messenger over your app, right?

Also around here Farmrail (the train company) lays on the horn everywhere they go. You literally can't miss em.

**Comment by tjspann** [comment]
Sir it's really annoying having to pull over to get messages from my family when Facebook Messenger and every other messaging service works just fine with Android Auto. I would think you wouldn't prefer my family use FB Messenger over your app, right?

Around here Farmrail (the train company) lays on the horn everywhere they go. They are hard to miss.
