### ISSUE TITLE
How to migrate/restore multiple accounts?

### ISSUE THREAD

**Issue by tve** [iNPUTmice/Conversations#4444]
I have multiple accounts, how can I migrate the chat data to a new phone?
I followed the migration how-to, it created multiple backup files, one per account. I moved the files to the new phone and followed the restore procedure. Works great for the first file, but how do I restore the others?

**Comment by licaon-kter** [comment]
Accounts - menu - Restore

**Comment by Avispa** [comment]
For reference -- always helpful for others -- where to find the document about backup strategy they were (assumingly) talking about:
[https://github.com/iNPUTmice/Conversations/blob/master/docs/user/migrating_to_new_device.md#3-import-the-backup-new-device](https://github.com/iNPUTmice/Conversations/blob/master/docs/user/migrating_to_new_device.md#3-import-the-backup-new-device)
