### ISSUE TITLE
Design proposal for Attach file icon

### ISSUE THREAD

**Issue by jcperil** [iNPUTmice/Conversations#4446]
![Attach file](https://user-images.githubusercontent.com/89805719/219943813-e4ce5a66-4737-46bb-a447-2f5a5a663f89.jpg)

Clicking the + icon will show us a sheet of all the actions available.

![Actions](https://user-images.githubusercontent.com/89805719/219943843-d39c9472-8c58-4e69-bbc3-76d25c696dae.jpg)

###### The interface is from [Simple SMS Messenger](https://github.com/SimpleMobileTools/Simple-SMS-Messenger).

**Comment by licaon-kter** [comment]
Pls post these on Codeberg as the Readme says.
