### ISSUE TITLE
Phone call to Siskin does ring late (at hangup)

### ISSUE THREAD

**Issue by apprenticius** [iNPUTmice/Conversations#4447]
For IQ-Stanzas server (at least ejabberd-server) does not send a push message. I think this is the way push is defined to work. But this means that the push notification of a call always arrives on hangup phone token. What is pretty annoying. Isn't it possible to send a "feature request" before calling. At least on ejabberd I can see push notifications for "feature requests". The advantage in my opinion would be that there doesn't pops up a message in the chat and I don't have to send always a message before calling to iPhone clients.

If it is a stupid idea or I understand something wrong, I beg your pardon.

**Comment by licaon-kter** [comment]
There's no push for phone calls.

Or none that's defined by a standard XEP yet.

Siskin stays disconnected 99% of the time (as Apple iOS kills it) so you can only call them when the app is opened in foreground.

Monal just entered in Beta with calls _(not yet compatible with Conversations or Siskin but soon)_ and they try to keep the connection open more so maybe it will be snappier with calls too.
Eg. Read more
https://eversten.net/en/blog/notification/ 

/close this as invalid

**Comment by apprenticius** [comment]
I know that there is no push for phone calls. This why I write that I always have to send a message before calling. And that's why I'm wondering if it wouldn't be possible to send always a "feature request" before the call process, hence as fare as I see on the server side this sends a push notification to the app server.

But if my idea is so silly, I feel sorry an close this thread...

**Comment by licaon-kter** [comment]
I'm not sure there's even a "push for feature request". What does that mean? Which XEP defines this?

**Comment by apprenticius** [comment]
My app server gets a notification if someone sends a XEP-30 request. I don't know if this follows the specifications of push, but I get a notification.
