### ISSUE TITLE
cant join conversations@conference.siacs.eu

### ISSUE THREAD

**Issue by ashjas** [iNPUTmice/Conversations#4448]
When i join conversations@conference.siacs.eu through conversations,
i am only a visitor, the text box says "you are not participating"

whats up with this group? i used to be able to participate before.

**Comment by licaon-kter** [comment]
The group is now moderated, after a wave a spam messages.

Ask for voice from a moderator/admin via private messages.

/close this

/PS: FYI development is elsewhere: https://github.com/iNPUTmice/Conversations/blob/redirect/README.md

**Comment by ashjas** [comment]
Thanks.
