### ISSUE TITLE
Notifications broken on latest version from fdroid

### ISSUE THREAD

**Issue by linucksrox** [iNPUTmice/Conversations#4450]
I upgraded to the latest version from fdroid today, 2.12.3+free and afterward i was getting no notifications. I checked the settings and found that the app had no notifications enabled (available).

![Screenshot_20230503-170613](https://user-images.githubusercontent.com/5169868/236051576-4decdba7-8736-478e-9aad-2da851a5b0b9.png)
![Screenshot_20230503-170631](https://user-images.githubusercontent.com/5169868/236051601-329a2417-8387-4581-9672-e2e9ecced80a.png)

**Comment by licaon-kter** [comment]
/close this

Already reported in the proper repo:  https://codeberg.org/iNPUTmice/Conversations/issues/47 and https://codeberg.org/iNPUTmice/Conversations/issues/48 

Also, fixed in 2.12.4
