### ISSUE TITLE
Hostname error

### ISSUE THREAD

**Issue by SaviorD22** [iNPUTmice/Conversations#4457]
I am using Openfire as my xmpp server, to open it to the public I use playit.gg which has worked with spark and some web clients, but when using Conversations app it doesn't work, but let me explain it.  Let's say I set up the same domain and hostname in Openfire (192.168.8.90) so in conversations I type user@192.168.8.90 then I type the password, since playit.gg gives me a custom domain and port that redirects to 192.168.8.90:5222 I had to enable "connection options" which gives me the option to put the hostname and port, here I put the hostname (the IP given by playit.gg) and the port (the port given by playit.gg) and it doesn't work.  Now if you ask, yes this has worked in spark, I'm able to put the playit.gg domain and then go to advanced and uncheck "get host and port automatically" to then put the playit.gg Ip and port.  After all that spark lets me access my Openfire account from outside, so my question is, why is conversations not finding the server with the playit.gg IP when in spark works and they are both the same thing.

Help is appreciated!

**Comment by licaon-kter** [comment]
Close this and keep the one on Codeberg
