### ISSUE TITLE
There is no icons for calls ?

### ISSUE THREAD

**Issue by C3PO987** [iNPUTmice/Conversations#4467]
Hi and thanks for your work,
I've been testing Conversation and installing it through F-droid. It's pretty good but... In my version, there is no icons for phone call  -_-
By the way when I call from another account on Dino to Conversation, it work well.
Any idea of why ?

Have a nice day

**Comment by licaon-kter** [comment]
You added each other as contacts? In contact details both presence checkboxes are checked? Same server?

**Comment by C3PO987** [comment]
I've tried with same server (conversation.im) and different client (dino and conversations), different server (conversation.im and jabber) and different client. I'll try with same server and same server. 
Thanks for the answer
