### ISSUE TITLE
No A/V calls

### ISSUE THREAD

**Issue by CarstenHa** [iNPUTmice/Conversations#4469]
Hi,

First of all, thanks for your great work.
Since the last update of Conversations, I've problems with A/V-calls.
I always get a message: "Anruf nicht gesendet, keine gültige Nummer eingegeben"
Any idea of why?

Greetings

Carsten

**Comment by iNPUTmice** [comment]
Please provide more details on what device and what Android version you are running.

**Comment by CarstenHa** [comment]
Samsung Galaxy A5
Android Version 8.0.0

**Comment by alkahan** [comment]
Hi,

I have the same problem. 
Phone: Moto G5
Android: 8.1.0

I can receive A/V call but cannot emit.

**Comment by licaon-kter** [comment]
2.14.1 is live in F-Droid, can you retest?

**Comment by CarstenHa** [comment]
Since the last update it works fantastic again. Thank you! I noticed one thing on video calls. I can't control the speaker (this is not so important to me, but perhaps you are interested). For audio calls it works perfect. Thank you so much for your help.

Greetings

Carsten

**Comment by alkahan** [comment]
fixed for me too. Thanks !
