### ISSUE TITLE
Account / Address book integration

### ISSUE THREAD

**Issue by rtreffer** [iNPUTmice/Conversations#46]
Hi *,

As said I've some code floating around to simplify account management and to integrate with the phones address book...

I'd specifically like to move in:
- Everything related to "Add Account" from the settings (https://github.com/rtreffer/AsmackService/tree/master/src/com/googlecode/asmack/sync)
- Everything needed to sync contacts and update the presence in the phone book (https://github.com/rtreffer/AsmackService/tree/master/src/com/googlecode/asmack/contacts)

Now the important questions:
- What users (jids) should be moved to the address book?
- Should/Can we keep groups alive?
- Should we auto-merge with existing users?
- Should we slowly query the jids for their info? Or should we be "aggressive"?
- Should we integrate with the account sync? This would be the perfect moment for a roaster fetch.

@iNPUTmice opinions?

Merging / integrating this could take a bit longer.

**Comment by sedrubal** [comment]
I'd like to see my conversation contacts in my address book, too and if conversations account would be integrated in android accounts simply because this would be more androidish. And I like conversations because of being androidish ;)

**Comment by allo-** [comment]
Is there in the current implementation now a function to switch sync off? Android 6 keeps asking me for access to the address book, even when i denied it (i'd like to avoid syncing contacts and JIDs, mostly for not mixing this lists together, as XMPP does a decent job at keeping a roster).

**Comment by iNPUTmice** [comment]
If you set the checkbox on never ask again android 6 won't ask you again.

**Comment by allo-** [comment]
And the Conversations message "please accept the next question" before?

**Comment by iNPUTmice** [comment]
That as well of course.

**Comment by allo-** [comment]
Ah, need to re-test. The last times i just declined without setting the checkmark and thought conversations will have some checkmark not to ask by itself. If setting "do not ask again" works for all messages, it's fine :).

**Comment by bktowett** [comment]
This is an excellent app. I am trying to integrate with my address book. That's what I want and I need to do. I have seen some part of code that enables this but I am yet to find an interface to activate it.

`
public void onPhoneContactsLoaded(final List<Bundle> phoneContacts) {
		if (mPhoneContactMergerThread != null) {
			mPhoneContactMergerThread.interrupt();
		}
		mPhoneContactMergerThread = new Thread(new Runnable() {
			@Override
			public void run() {
				Log.d(Config.LOGTAG, "start merging phone contacts with roster");
				for (Account account : accounts) {
					List<Contact> withSystemAccounts = account.getRoster().getWithSystemAccounts();
					for (Bundle phoneContact : phoneContacts) {
						if (Thread.interrupted()) {
							Log.d(Config.LOGTAG, "interrupted merging phone contacts");
							return;
						}
						Jid jid;
						try {
							jid = Jid.fromString(phoneContact.getString("jid"));
						} catch (final InvalidJidException e) {
							continue;
						}
						final Contact contact = account.getRoster().getContact(jid);
						String systemAccount = phoneContact.getInt("phoneid")
								+ "#"
								+ phoneContact.getString("lookup");
						contact.setSystemAccount(systemAccount);
						if (contact.setPhotoUri(phoneContact.getString("photouri"))) {
							getAvatarService().clear(contact);
						}
						contact.setSystemName(phoneContact.getString("displayname"));
						withSystemAccounts.remove(contact);
					}
					for (Contact contact : withSystemAccounts) {
						contact.setSystemAccount(null);
						contact.setSystemName(null);
						if (contact.setPhotoUri(null)) {
							getAvatarService().clear(contact);
						}
					}
				}
				Log.d(Config.LOGTAG, "finished merging phone contacts");
				updateAccountUi();
			}
		});
		mPhoneContactMergerThread.start();
	}`

**Comment by benediktg** [comment]
The code @bktowett has pasted can be found here: https://github.com/siacs/Conversations/blob/11666195398b8c673b47863ab07744c8926b54d0/src/main/java/eu/siacs/conversations/services/XmppConnectionService.java#L1229
(just as a side note)

**Comment by fanningert** [comment]
I am using the addressbook integration. But I have contacts with more then one JID. 
Here now the problem.
I add a contact with his skype jabber id (XMPP transport) to my roster and also with his real jabber-ID. Now the problem is, that I add this two JID to the contact of my android addressbook, but I am seeing only on entry in the contacts of conversations and not two entries.
In a other XMPP client application (pidgin), I see two entries on my roster.

**Comment by bktowett** [comment]
@fanningert how are you able to do address book integration? I have not been able to figure out yet.

**Comment by fanningert** [comment]
@bktowett Sorry for the late response. But I don't find a solution for this problem.

**Comment by muchweb** [comment]
Just noticed there was no 'Accounts' settings menu integration. IMO this should be separate issue.

For the address book, I wouldn't like Conversations to modify it in any way (by default). It is perfect what it's doing at the moment — read-only integration, to bring names&avatars to roster.

**Comment by fanningert** [comment]
Read only is not the problem. The problem is, what is when one account has two JIDs. Where can I selected the right JID for a conversation.

**Comment by muchweb** [comment]
@fanningert, what do you mean by 'contact has two JIDs'?

**Comment by fanningert** [comment]
@muchweb I have some contacts with two XMPP-IDs (name@domain1.org, name@domain2.org) in there contact details. (JID = Jabber Identifiers)

**Comment by BavarvaSajan** [comment]
hello 

using this integration if new contact added on XMPP server and that contact number already in my phone book than That contact is automatically seen in my conversations application contact?  

thanks

**Comment by licaon-kter** [comment]
@BavarvaSajan There is no number involved. That's not how it works...
