### ISSUE TITLE
Automatic OpenPGP public key sharing not working without restart

### ISSUE THREAD

**Issue by Draghtnod** [iNPUTmice/Conversations#559]
I got OpenPGP set up with my Conversations (0.7.3), my friend did not, i enable OpenPGP for the conversation with her and Conversations tells me that she has not set up OpenPGP yet and i shall tell her to do so. I did what i was told. She fought herself through the still much too complicated and non-self-explaining process (at least for usual users..) of the OpenKeychain (3.0.1) key generation. She restarts Conversations, selects her newly generated private key, enables OpenPGP in our conversation and with her first message, my public key gets automatically transferred to her and i receive the encrypted message from her. Everything fine on the Conversations side for now.

Now if i try to reply to that encrypted message, my Conversation still tells me that i don't have her public key, which is correct. But the automatic key transfer from her to me doesn't start. Disabling and reenabling OpenPGP for that conversation did not help either. I had to kill the app in the app manager and restart it, before the automatic key transfer started with the next message i sent her.

If this feature doesn't work instantly, the user might think they have to transfer the key manually, which happened in our case is a lot of hassle with all the bugs of OpenKeychain and did not work at all.

**Comment by blitz** [comment]
:+1:
