### ISSUE TITLE
Ability to edit tags (groups)

### ISSUE THREAD

**Issue by knoy** [iNPUTmice/Conversations#702]
Ability to change the currently read-only tags

**Comment by rigid** [comment]
:+1:  for editing tags/groups

**Comment by knoy** [comment]
I think this issue should be revisited . The ideas mentioned by @SamWhited all seem like good points. Often times users have hundreds of contacts and can't be micromanaged individually without using multiple accounts, which is cumbersome. Being able to add or edit groups opens the door to easier roster management for power users

**Comment by SamWhited** [comment]
> The ideas mentioned by @SamWhited all seem like good points. 

For the record, my comment wasn't meant as an argument that we *should* do this, just a way we *could* implement it.

**Comment by knoy** [comment]
Another point I want to make... the user search can already search by contact group.  This could be a really effective way for powerusers with hundreds of users to quickly sort through people.

**Comment by conrad-heimbold** [comment]
workaround: for editing contact tags / groups, you can use Xabber (open-source as well, see xabber.com). Tagging only needs to be done once, so afterwards; you can delete Xabber again. Urgency of this issue is therefore not that high, sorry.
