### ISSUE TITLE
Notification grace period

### ISSUE THREAD

**Issue by ghost** [iNPUTmice/Conversations#762]
Conversations is awesome, so thank you for all your hard work!

There's just one thing that frequently annoys me: when I'm not able to look at my phone (driving, for example) and someone starts a conversation with me. Sometimes the other party will type 10 or 20 lines in a few minutes, and Conversations will beep & buzz every single time.

Could we introduce some kind of (configurable?) grace period for notifications from the same conversation? For example: once a conversation triggers a notification, for 60 seconds any subsequent notifications from that conversation would be muted. If you do get a notification in that period, the grace period could automatically be extended a bit further to 90 seconds, and so on. As soon as you'd open Conversations, all grace periods would reset.

**Comment by hillbicks** [comment]
I second this. I vaguely remember a thread about increasing the time, although this was in relation to use with a desktop client. Not sure if this was ever implemented.

**Comment by felixc** [comment]
:+1: Even if I'm responding from a different client, e.g. on my desktop, my phone sits and buzzes like mad.

**Comment by Nebukadneza** [comment]
Hi,

i implemeted something similar in Yaxim for exactly that reason!

When some message comes in, to decide whether to beep or not, i’d do this:
Was there a (beeping) message from the same contact < X seconds ago? ⇒ no beep
Was there a message from myself from another resource (received own carbon) < Y sec ago? ⇒ no beep
Did the user clear the notification for some contact less than Z sec ago? ⇒ no beep
otherwise ⇒ beep

This helps in the scenario where a user is active on another (desktop) client, and doesn’t need the mobile to notify him, as well as helps with many-message-from-someone scenarios where you cannot pick up your mobile to check on it, but don’t want to be annoyed. Should you have been annoyed enough to pick up the mobile and clear the notification, you get a (possibly) even higher timeout until the next beep — perfect!

I would really like to see something like this in more clients, also Conversation!

Best Regards
- Dario

**Comment by wiseoldman95** [comment]
+1 !

**Comment by msjoberg** [comment]
I'm annoyed by this exact same thing! +1

**Comment by schiesbn** [comment]
Would be really good to have a solution for this issue. But I would propose a different solution than the one discussed here. My solution would be:

- Receive a notification for the first new message
- No notification for any follow-up message
- Only after I looked at the chat I should get again a notification if a new message pop up

I think one notification is enough to know that something happened in a group chat. So I don't think there is a need for a new notification even with a delay of X seconds.

**Comment by knoy** [comment]
This is actually a pretty cool idea. You can always disable notifications from people by long-pressing on their conversation and tapping "Disable notifications". However sometimes it can be too time consuming to do this or you have no prior idea you're going to get flooded with msgs.

**Comment by benediktg** [comment]
I think this feature request is solved by a feature called "Gnadenfrist" in German, isn't it?

**Comment by grafenhofer** [comment]
@benediktg: as far as I understand it, no. The "Gnadenfrist" period refers to silencing notifications for a certain time when another client (e.g. on a desktop computer) was active. My use case: I use empathy as a desktop xmpp client. I do not want to receive notifications in my phone (in my pocket), while I am chatting in empathy.

I am actually working on implementing the original proposal, i.e., silencing notifications for a certain period after a notification has been triggered as to remove notification bursts. The feature (a one line patch) works, but I am still figuring out (my first attempt of coding for Android) how to make it configurable via the preference settings. You can find a preliminary patch over here: https://share.grafenhofer.at/silence_period.patch

**Comment by licaon-kter** [comment]
@grafenhofer Any status updates?

**Comment by grafenhofer** [comment]
@licaon-kter This is the first time I touch Android code... The feature is implemented via a one-line patch and works. The problem I still have to solve is to make it configurable. I guess that I miss something trivial while implementing that which leads to crashes.

**Comment by Buntbart** [comment]
Now I am missing some messages...
The options are "Short", "Medium" and "Long" 
Would it be possible to add "None" again, please? I would prefer to be notified of every single message that comes in.

**Comment by SecTec** [comment]
Hi,
I think the grace time should be configurable in seconds by a number input field.

I have a second request for the same problem: I don't want a notifications sound as long my phone is unlocked, but I want a notification. I only want a notification with sound when the phone is locked.

Thx.

**Comment by iNPUTmice** [comment]
I think this is a social problem (people being annoying) that can’t and shouldn’t be solved with technology.
