### ISSUE TITLE
Invisibility

### ISSUE THREAD

**Issue by jkufner** [iNPUTmice/Conversations#880]
Now, whenever my phone is online it broadcasts to everyone "Hey I'm here!". This may have some privacy implications (partial tracking of user's location) or it may simply be inconvinient at the moment (using company account on holidays). Also this way Conversations will not override presence set by other clients, which may be desired when Conversations is used as secondary client.

From some point of view this may be similar to setting presence and status message, which was rejected many times already. However, invisibility have much wider impact.

Option to enable invisibility could be simple checkbox in account settings.

XEP-0126 (Invisibility) and XEP-186 (Invisible command) describe how to be invisible. It is mostly about sending presence

I believe many people may find this useful.

**Comment by languitar** [comment]
+1 I constantly get messages where people want to get in contact with me urgently just because conversations always advertises that I am online.

**Comment by d9h02f** [comment]
People should learn that 'online' ≠ 'paying attention'.

If you really don't want them to send you messages, leave your account offline. Doesn't that solve the problem anyway? Why would you even log in to a company account on holiday? I fail to see the possible benefits of invisibility.

**Comment by jkufner** [comment]
d9h02f wrote, on 27.6.2015 12:18:
> People should learn that 'online' ≠ 'paying attention'.

That would be nice, but that is not how many people work and you cannot
change that. User's visibility should be optional for the same reasons
as composing events are optional. You simply may not want to broadcast
to everyone that you are online, but you may still want to chat with
someone.

**Comment by d9h02f** [comment]
> You simply may not want to broadcast to everyone that you are online, but you may still want to chat with someone.
Which again begs the question why you want to talk to that person using an account you don't want to use for talking to anyone else. Add them to an account you do use, and disable the other account when you don't need/want it.

Also:
https://github.com/siacs/Conversations/issues/61#issuecomment-40460926

@iNPUTmice has stated several times that Conversations isn't trying to replicate desktop XMPP client functionality, but is, for better or worse, trying to provide a replacement for stuff like WhatsApp. If you want a more desktop-like experience, you can use other clients such as Xabber. (Although even Xabber doesn't have an option to hide your presence! Makes you wonder...)

**Comment by Natanji** [comment]
Whatsapp *does* allow you to hide your presence though. So with your argument, this should be implemented. 

Am 27. Juni 2015 15:34:25 MESZ, schrieb d9h02f <notifications@github.com>:
>> You simply may not want to broadcast to everyone that you are online,
>but you may still want to chat with someone.
>Which again begs the question why you want to talk to that person using
>an account you don't want to use for talking to anyone else. Add them
>to an account you do use, and disable the other account when you don't
>need/want it.
>
>Also:
>https://github.com/siacs/Conversations/issues/61#issuecomment-40460926
>
>@iNPUTmice has stated several times that Conversations isn't trying to
>replicate desktop XMPP client functionality, but is, for better or
>worse, trying to provide a replacement for stuff like WhatsApp. If you
>want a more desktop-like experience, you can use other clients such as
>Xabber. (Although even Xabber doesn't have an option to hide your
>presence! Makes you wonder...)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/880#issuecomment-116048668

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jkufner** [comment]
d9h02f wrote, on 27.6.2015 15:34:
> you can use other clients such as Xabber.

No. Xabber does not support stream management nor message archive
management, so it is useless. Conversations is currently the only usable
Jabber client.

**Comment by Natanji** [comment]
As I see it, this is still not implemented - and a feature that is available in WhatsApp, Telegram, etc.
So I'm commenting here so this doesn't get mistakenly auto-closed.

**Comment by iNPUTmice** [comment]
Two upvotes in 5 years. Doesn’t seem to be a much requested feature. I’m considering it feature creep.
