### ISSUE TITLE
Service discovery (XEP-0030) & Gateway interaction (XEP-0100)

### ISSUE THREAD

**Issue by jkufner** [iNPUTmice/Conversations#913]
XMPP Transports work fine as long as they are configured in another client. But if user wants to add some transport on the road with no access to another client, he is in trouble.

Proper transport support requires implementatin of service discovery to lookup available transports, user interface for server-defined dialogs and few actions on transport contact in roster to invoke the server-defined dialogs.

See [XEP-0100: Gateway Interaction](http://www.xmpp.org/extensions/xep-0100.html) and [XEP-0030: Service Discovery](http://xmpp.org/extensions/xep-0030.html).

**Comment by TameOfGroans** [comment]
service discovery is a must have

**Comment by rigid** [comment]
:+1:

**Comment by TomTheDragon** [comment]
Conversations is like the best XMPP client is found so far for Android and it's really fun to use. It would be just awesome if someone could add Service Discovery in some kind, because then we could replace things like this crappy Skype client without any problems ;)
