### ISSUE TITLE
Support for attention (XEP-0224) and/or some urgent notifications

### ISSUE THREAD

**Issue by neufeind** [iNPUTmice/Conversations#979]
http://xmpp.org/extensions/xep-0224.html

It might be good to be able to be able to turn on attention-notifications - either globally, for specific users or for a specific group. Since not many clients yet support it, maybe having rules for messages that require attention would a good idea as well (regex on certain fields maybe?), for the technically advanced users.

In some situations urgency might be desired to indicate even more forcefully - like for fault-monitoring-messages play a sound until the user actively silences the alarm (playing all long or starting every few minutes again or so).

**Comment by TameOfGroans** [comment]
Yes, I miss this from Xabber. It has keyword matches harkenning to irc allowing each match to fire a different notification sound.

**Comment by plsng** [comment]
Who would use this?

**Comment by neufeind** [comment]
@plsng: I'm not sure I understand the question right :-)
Regular usecases for me would be to get extra-quick attention in case of "urgent" messages (keywords mentioned, ...) and also for monitoring-messages delivered via XMPP.

**Comment by TameOfGroans** [comment]
the Xmpp Texting client Xabber offers this

 https://github.com/redsolution/xabber-android

-- the client previously mentioned. Attention is fantastically useful. It would be better if Light Flow could key to unique notifications. Light Flow overcomes annoyances in android.

**Comment by rnav** [comment]
This would be really good to have and one of the main things I'm missing in Conversations. My use case is similar to BBM's ping - to get the chat partner's immediate attention. It just boils down to a different notification option for a special 'ping' or 'buzz' or 'attention' message.

**Comment by BlauerHunger** [comment]
I already saw this feature in some other IM-Clients, and I liked it very much. 
The 'attention'-message could also be displayed as a red background for the conversation button in the conversations list.

**Comment by aelmahmoudy** [comment]
+1
